### ISSUE TITLE
[Add] : trapped water program by using DYNAMIC PROGRAMMING

### ISSUE THREAD

**Issue by kosuri-indu** [TheAlgorithms/Python#10026]
### Feature description

Trapped Water problem - using Dynamic Programming : 

![Screenshot 2023-10-07 at 21-10-47 Trapping Rainwater - https __www apnacollege in_path-player courseid alpha-batch-4 unit 64454bee464c180a3c0b664711Unit](https://github.com/TheAlgorithms/Python/assets/118645569/0cbe034f-66fb-4e0e-9742-6857ed5efa26)

![Screenshot 2023-10-07 at 21-19-24 Trapping rain water in javascript - LearnersBucket](https://github.com/TheAlgorithms/Python/assets/118645569/0eeac04d-b958-4919-9889-d470ec7e727a)

**Comment by anushkp1107** [comment]
@kosuri-indu I would like to work on this issue under hacktoberfest 2023. Kindly assign this to me.
