### ISSUE TITLE
Import block is un-sorted or un-formatted error

### ISSUE THREAD

**Issue by ojas-wani** [TheAlgorithms/Python#10050]
### What would you like to share?

I am getting an "**I001 Import block is un-sorted or un-formatted**" error at my function definition. 
This is my function.
def my_laplacian(ksize: int, src: np.ndarray) -> np.ndarray:

Can someone please help to resolve this error? I tried everything from my end but am getting the same error recursively.

**Comment by tianyizheng02** [comment]
Try running `ruff --fix .` locally in the command line. Does that fix the unsorted import block error?

**Comment by ojas-wani** [comment]
It worked. Thank you for the help

**Comment by KedwithGod** [comment]
Thanks the ruff --fix worked for me
