### ISSUE TITLE
Finding skewness and kurtosis for a distribution

### ISSUE THREAD

**Issue by UKJaagadhep** [TheAlgorithms/Python#10179]
### Feature description

I want to add a program to find skewness and kurtosis of a distribution of values. It can be useful in describing numerical data and in handling outliers.

**Comment by tianyizheng02** [comment]
Please read our contributing guidelines. If you wish to contribute this, please just open a PR. We don't assign issues in this repo.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
> 
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
