### ISSUE TITLE
Change Code to return tuple in dynamic_programming/subset_generation.py

### ISSUE THREAD

**Issue by AasheeshLikePanner** [TheAlgorithms/Python#10189]
### What would you like to share?

The file dynamic_programming/subset_generation.py codes printing the list, which is hard to add doctest in it. And make it cover lower 
## Changes
Change the code to return tuple so we can add doctests in it and make cover higher

**Comment by Batty-sk** [comment]
@AasheeshLikePanner can you assign this to me

**Comment by TheTahaYaseen** [comment]
i wannt try?

**Comment by TheRealSaiTama** [comment]
i am doing it

**Comment by Paulraj916** [comment]
can you assign this to me

**Comment by Gyan313** [comment]
is this issue closed @AasheeshLikePanner @TheRealSaiTama ?

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.

**Comment by AasheeshLikePanner** [comment]
@cclauss I created the pull request last week for this. But it still didn't get reviewed So I think creating a issue can help.
Can you please check  this #10191
