### ISSUE TITLE
Encryption and Decryption  in Python

### ISSUE THREAD

**Issue by joshiadarshx** [TheAlgorithms/Python#10212]
### Feature description

I propose creating an algorithm in Python that provides encryption and decryption functionalities for strings.
I found no such basic projects or programs here so I created an issue.
Maintainers, could you please assign it to me so you can review I can add it to your strings folder.
Also please while assigning add hacktoberfest label to it

**Comment by tianyizheng02** [comment]
Did you read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues)?
> **Do not** create an issue to contribute an algorithm. Please submit a pull request instead.

Also, we literally have an entire directory called `ciphers`.
