### ISSUE TITLE
Reducing Jupyter Notebooks' size

### ISSUE THREAD

**Issue by poyea** [TheAlgorithms/Python#1022]
One could also reduce them by translating them into `.py`. 

https://github.com/TheAlgorithms/Python/search?l=jupyter-notebook

**Comment by cclauss** [comment]
How much size are we reducing?  https://github.com/TheAlgorithms/Python/blob/master/other/Food%20wastage%20analysis%20from%201961-2013%20(FAO).ipynb is impressive as an __.ipynb__ file but would loose much of its story telling power as a __.py__ file?

**Comment by poyea** [comment]
By half? I don't know if this is possible, but some files are making the repository large in size.

**Comment by cclauss** [comment]
Would it make sense to create a new repo called https://github.com/TheAlgorithms/Jupyter like GitHub does with https://github.com/trending/Python and https://github.com/trending/Jupyter.

**Comment by chiazor** [comment]
Clearing the outputs created after the execution of a Jupiter Notebook's cell reduces the Notebook's size.
The file size can reduce by half.

**Comment by cclauss** [comment]
Is there an automated way clear the outputs from the command line?

GitHub no longer considers __TheAlgorithms/Python__ to be a __Python__ repo.  It is now considered tobe a __Jupyter__ repo (by size 65.8% vs. 34.2%) even though the repo currently only has 5 Jupyter files vs. 320 Python files.  This means that our repo will no longer be visible on GitHub's [trending Python repos](https://github.com/trending/python) which is one of the ways that we attract new contributors.  My sense is that if the size of the notebooks can not be reduced then we should create an alternative TheAlgorithms/Jupyter-Notebook that can take its place on https://github.com/trending/jupyter-notebook

![Screenshot 2019-07-21 at 17 43 00](https://user-images.githubusercontent.com/3709715/61593624-40d26680-abe2-11e9-84d4-7a1425d93d46.png)

**Comment by cclauss** [comment]
__ls -Fla $NB ; jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace $NB ; ls -Fla $NB__
```
./machine_learning/NaiveBayes                                            50,103 -->  4,217
./machine_learning/reuters_one_vs_rest_classifier                       154,557 --> 13,299 
./machine_learning/random_forest_classification/random_forest_classifier 46,123 -->  4,473
./machine_learning/random_forest_regression/random_forest_regression     16,886 -->  2,319
./neural_network/fully_connected_neural_network                          18,158 -->  5,143
```

**Comment by chiazor** [comment]
I agree with @cclauss creating a separate repo for notebooks is more suitable.

**Comment by QuantumNovice** [comment]
> 
> 
> **ls -Fla $NB ; jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace $NB ; ls -Fla $NB**
> 
> ```
> ./machine_learning/NaiveBayes                                            50,103 -->  4,217
> ./machine_learning/reuters_one_vs_rest_classifier                       154,557 --> 13,299 
> ./machine_learning/random_forest_classification/random_forest_classifier 46,123 -->  4,473
> ./machine_learning/random_forest_regression/random_forest_regression     16,886 -->  2,319
> ./neural_network/fully_connected_neural_network                          18,158 -->  5,143
> ```
> 
> I still think a separate repo for notebooks is more sustainable. Much of the storytelling power is in the output.

Creating a separate repository with sub-directory for each each languages supported by Jupyter is great.
