### ISSUE TITLE
Fix the LGTM issues

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#1024]
The LGTM service is run by Travis CI on all pull requests and it currently reports:
```
2 Errors
12 Warnings
10 Recommendations
```
https://lgtm.com/projects/g/TheAlgorithms/Python/alerts/?mode=list

Please try to fix ___just a few___ of these issues in a pull request.

For speed of review, please do not try to do them all.  Where possible add doctests as well.

**Comment by cclauss** [comment]
@epicalyx, @harshildarji, @rishu2403 Could one of you please consider fixes to unused variables in logistic_regression?  They might be false positives or they might be worth fixing.

**Comment by AmritK10** [comment]
I would like to work on the issue of unused variables in logistic_regression.

**Comment by cclauss** [comment]
Go for it!

**Comment by denis-trofimov** [comment]
Gonna handle an error in root/matrix/matrix_operation.py

**Comment by denis-trofimov** [comment]
> hello can someone help me solve this :

Hi @tchatec I guess you should create new issue. It is the wrong place to ask such question.
