### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by Chanchal-D** [TheAlgorithms/Python#10274]
### Feature description

Can I work on the documentation of the readme, as it needs to be updated in order to make it more interactive and help users to know more about the repo.

**Comment by airwakz** [comment]
i  am workin on this  right now

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.
