### ISSUE TITLE
Density-based spatial clustering of applications with noise(DBSCAN)

### ISSUE THREAD

**Issue by CHAFIQMohamed** [TheAlgorithms/Python#10318]
### Feature description

Adding DBSCAN Algorithm in the machine learning part

**Comment by tianyizheng02** [comment]
Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contribution): they explicitly state that you should not open new issues to add new algorithms.
> **Do not** create an issue to contribute an algorithm. Please submit a pull request instead.
