### ISSUE TITLE
Create a Python Bot that can send Email at scheduled time

### ISSUE THREAD

**Issue by Arcturus22** [TheAlgorithms/Python#10346]
### Feature description

@cclauss 
I'm creating this issue to create a Python Bot that can send Email automatically at the scheduled time specified by the user.
I want to contribute by adding code for this to the repository. Kindly assign me this issue.

**Comment by haxkd** [comment]
Please go through the (contributing.md)[contributing.md]

**Comment by haxkd** [comment]
go through the [contributing.md](contributing.md)

**Comment by Arcturus22** [comment]
> go through the [contributing.md](contributing.md)

I have a;ready read it.

**Comment by haxkd** [comment]
go through the [https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md](CONTRIBUTING.md) it should be an algorithm

**Comment by Arcturus22** [comment]
Ohh Alright, Sorry for the trouble. I will close my Pull Request.
