### ISSUE TITLE
missing_number algorithm dosen't work as intended (bit_manipulation/missing_number.py)

### ISSUE THREAD

**Issue by jamestitus299** [TheAlgorithms/Python#10357]
### Repository commit

d0c54acd75cedf14cff353869482a0487fea1697

### Python version (python --version)

Python 3.12.0

### Dependencies version (pip freeze)

setuptools==68.2.2
wheel==0.41.2

### Expected behavior

for array [1,3,4,5,6] the output should be 2

### Actual behavior

the output got is 4

**Comment by Manoj-Routhu** [comment]
i have resolved the but its failing in build and the code working fine on mine system.
