### ISSUE TITLE
Added some DSA PROBLEM Question

### ISSUE THREAD

**Issue by saurabhprasadsah** [TheAlgorithms/Python#10376]
### Feature description

Added DSA Question

**Comment by theinit01** [comment]
@saurabhprasadsah, What do you mean by this issue? Can you please elaborate?

**Comment by saurabhprasadsah** [comment]
@theinit01 add some DSA problem question.

**Comment by haxkd** [comment]
@saurabhprasadsah add algorithm only

**Comment by tianyizheng02** [comment]
??? I'm sorry, this issue makes no sense. _What_ DSA problem are you talking about? You didn't answer this even when other contributors asked.

**Comment by haxkd** [comment]
@tianyizheng02 he try to say, to add some DSA based problems in this repo.

**Comment by saurabhprasadsah** [comment]
@haxkd  ye correct add some DSA based problems in this repo.

**Comment by haxkd** [comment]
@saurabhprasadsah but this repo ia only for algorithma

**Comment by theinit01** [comment]
This issue is closed. Let it be
