### ISSUE TITLE
Hacktoberfest 2023

### ISSUE THREAD

**Issue by its-100rabh** [TheAlgorithms/Python#10383]
### What would you like to share?

I recently created a pull request where I modified comments in an existing algorithm. The pull request got mereged but it isn't reflected in my Hacktoberfest 2023 profile. I am new to this field so any kind of help would be appreciated.

**Comment by Tashuuuu** [comment]
It will reflect after a week as the Hacktoberfest's team also has to review it.

**Comment by its-100rabh** [comment]
Oh , thank you.
