### ISSUE TITLE
Top 100 contribur Picute in contributor section on readme.md file 

### ISSUE THREAD

**Issue by MuhammadNizamani** [TheAlgorithms/Python#10384]
### Feature description

I want to add top 100 contributor profile like added in following repo 
![contribor](https://github.com/TheAlgorithms/Python/assets/49721249/4c860866-46de-444b-9e2d-cab9e131e7ee)

**Comment by Joseph2001-braganza** [comment]
This should be in the Readme right ?
I can work on this issue.

**Comment by MuhammadNizamani** [comment]
@Joseph2001-braganza I am working on it sorry 😞

**Comment by B-a-b-u** [comment]
I am working on this

**Comment by MuhammadNizamani** [comment]
@B-a-b-u  I have done my work on it. I am just getting issue for creating PR

**Comment by haxkd** [comment]
@B-a-b-u create proper PR

**Comment by MuhammadNizamani** [comment]
@haxkd  I don't know why the bot keeps closing my PR!

**Comment by haxkd** [comment]
@MuhammadNizamani that PR is not valid

**Comment by AasheeshLikePanner** [comment]
I think it because you are not putting x perfectly you putting like this [x ] but you need to put like this [x]

**Comment by airwakz** [comment]
> @haxkd I don't know why the bot keeps closing my PR!

bruh uh need to check mark in the pr 
 thank me later if ur query is solved

**Comment by cclauss** [comment]
# [`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.
