### ISSUE TITLE
Implementing Dijkstra's Algorithm for Shortest Path. 

### ISSUE THREAD

**Issue by Srishti2703** [TheAlgorithms/Python#10493]
### What would you like to share?

This issue aims to implement Dijkstra's algorithm for finding the shortest path in a graph with weighted edges. Dijkstra's algorithm is a classic graph algorithm used in routing, network optimization, and various other applications.

### Additional information

The benefits of implementing this feature are as follows:
  Enhanced graph analysis capabilities: Users can apply Dijkstra's algorithm for solving problems related to 
   shortest paths in graphs.
  Improved codebase: The addition of this graph algorithm enhances the project's applicability.

**Comment by B-a-b-u** [comment]
I can work on this

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> Calculate the waiting time for processes to be completed in a specified duration.
