### ISSUE TITLE
Duplicate method (Newton–Raphson method)

### ISSUE THREAD

**Issue by obelisk0114** [TheAlgorithms/Python#1049]
The following 3 methods are the same. Maybe we can rename them and put them to the same directory.

https://github.com/TheAlgorithms/Python/blob/master/maths/newton_raphson.py
https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/newton_raphson_method.py
https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/newton_method.py

**Comment by QuantumNovice** [comment]
[This](https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/newton_method.py) should be removed as it asks the user for both f(x) as well as f'(x). It's very old C  style implementation of the algorithm.

On the other hand [this](https://github.com/TheAlgorithms/Python/blob/master/maths/newton_raphson.py) is way better implementation. Can somebody timeit both the algorithms to see which one is faster??
If the answer is not sympy. We need to add this to SymPy project as well.

**Comment by cclauss** [comment]
[__SymPy__ is already in __requirements.txt__](https://github.com/TheAlgorithms/Python/blob/master/requirements.txt#L10)

**Comment by obelisk0114** [comment]
I will remove [arithmetic_analysis/newton_method.py](https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/newton_method.py) and move the other 2 methods into [arithmetic_analysis](https://github.com/TheAlgorithms/Python/tree/master/arithmetic_analysis) folder if no one have other suggestions in a week.

**Comment by cclauss** [comment]
It would be cool to see [some tests](https://travis-ci.org/TheAlgorithms/Python/builds/563188763#L568) in __arithmetic_analysis__.

**Comment by cclauss** [comment]
Can this issue be closed?
