### ISSUE TITLE
Adding postfix_to_infix_conversion.py

### ISSUE THREAD

**Issue by bhorsujal** [TheAlgorithms/Python#10598]
### What would you like to share?

I would like to contribute in the stacks directory under data_structures by adding the Postfix to Infix conversion.

### Additional information

I would like to use stacks to implement Postfix to Infix conversion in Python.

**Comment by AasheeshLikePanner** [comment]
Hi, Just create a pull request which you want to change or contribute. Don't create Issue for this.

**Comment by AasheeshLikePanner** [comment]
Can you please close the issue now.

**Comment by AasheeshLikePanner** [comment]
Thanks
