### ISSUE TITLE
PR is not getting merged

### ISSUE THREAD

**Issue by ojas-wani** [TheAlgorithms/Python#10625]
### What would you like to share?

I opened a pull request last week. I passed all the tests but still, it is not merged. Can someone please review it and help me to get it merged? Also, If it needs any changes please suggest me.

https://github.com/TheAlgorithms/Python/pull/10045

**Comment by PoojanSmart** [comment]
Hi @ojas-wani, 
I am not a maintainer. But just to point out that your PR is also removing an algorithm file. `digital_image_processing/filters/laplacian_filter.py`
I am not sure you meant to remove it.
Just letting you know.

**Comment by ojas-wani** [comment]
I am also adding this file into different location.

**Comment by AasheeshLikePanner** [comment]
Can you close this issue now. You pr got merged
