### ISSUE TITLE
[feat] : Optimize Merge Sort Algorithm for Large Datasets

### ISSUE THREAD

**Issue by Parvezkhan0** [TheAlgorithms/Python#10677]
### Feature description

The current implementation of the Merge Sort algorithm performs efficiently for typical dataset sizes. However, it could benefit from optimizations to handle larger datasets more efficiently.

Tasks:

 

- [ ] Analyze the current Merge Sort implementation for potential performance bottlenecks.

- [ ]  Research and implement optimizations (e.g., reducing unnecessary memory allocations, improving cache locality).

- [ ]  Conduct benchmark tests on large datasets to validate the improvements.

**Comment by prithvihehe** [comment]
hey @Parvezkhan0 i would like to work on this issue

**Comment by tianyizheng02** [comment]
Did you read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues)?
> **Do not** create an issue to contribute an algorithm. Please submit a pull request instead.
