### ISSUE TITLE
[feat] : Implement Priority Queue using Binary Heap

### ISSUE THREAD

**Issue by Parvezkhan0** [TheAlgorithms/Python#10676]
### Feature description

We propose adding an implementation of a Priority Queue using a Binary Heap to enhance the data structures section. This will provide users with an efficient way to manage items with assigned priorities.

Tasks:

 

- [ ] Implement the Priority Queue class with necessary methods (insert, extract_min, etc.).

- [ ]  Write comprehensive test cases to ensure correctness and efficiency.

- [ ] Document the implementation, including time complexity analysis.

**Comment by tianyizheng02** [comment]
Did you read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues)?
> **Do not** create an issue to contribute an algorithm. Please submit a pull request instead.
