### ISSUE TITLE
Remove other/finding_primes.py

### ISSUE THREAD

**Issue by obelisk0114** [TheAlgorithms/Python#1070]
[other/finding_primes.py](https://github.com/TheAlgorithms/Python/blob/master/other/finding_primes.py) and [maths/sieve_of_eratosthenes.py](https://github.com/TheAlgorithms/Python/blob/master/maths/sieve_of_eratosthenes.py) are the same. Both of them implemented sieve of Eratosthenes. However, the latter's time complexity is better.

If it is accepted, #1026 can be closed.

**Comment by cclauss** [comment]
@brunohadlich @LizardWizzard Are you in agreement?

@obelisk0114 if you change:
> If it is accepted, #1026 can be closed.

To __fixes #1026__ then GitHub will autoclose 1026 when this PR lands.

**Comment by brunohadlich** [comment]
I agree.

**Comment by LizardWizzard** [comment]
I agree.

**Comment by cclauss** [comment]
@obelisk0114 Looks like everyone is in agreement.
