### ISSUE TITLE
DBSCAN algorithm

### ISSUE THREAD

**Issue by SimranLahrani842** [TheAlgorithms/Python#10767]
### Feature description

It is non supervised algorithm used in machine learning.It comes under clustering.

**Comment by tianyizheng02** [comment]
Do not open an issue to propose new algorithms. Read our contributing guidelines.

**Comment by SimranLahrani842** [comment]
> Do not open an issue to propose new algorithms. Read our contributing guidelines.

Should I directly open pull request for new algorithm?

**Comment by tianyizheng02** [comment]
**_Yes, it says so in the contributing guidelines._** I already told you to read it.
