### ISSUE TITLE
want to add multilevel queue implementation

### ISSUE THREAD

**Issue by KasunUdaraWaththeHewa** [TheAlgorithms/Python#10789]
### Feature description

I want to add multilevel queue implementation please assign me

**Comment by KasunUdaraWaththeHewa** [comment]
assign me please

**Comment by AasheeshLikePanner** [comment]
Hi, Don't create issue for this. Instead, create a pull request.

**Comment by tianyizheng02** [comment]
Do not open an issue to propose new algorithms. Read our contributing guidelines.
