### ISSUE TITLE
want to add regex like string matching algo

### ISSUE THREAD

**Issue by KasunUdaraWaththeHewa** [TheAlgorithms/Python#10794]
### Feature description

I want to add regex like string matching algo. please assign me

**Comment by KasunUdaraWaththeHewa** [comment]
assign me please

**Comment by AasheeshLikePanner** [comment]
Hi, Don't create issue for this. Instead, create a pull request.

**Comment by tianyizheng02** [comment]
Do not open an issue to propose new algorithms. Read our contributing guidelines.

Also, @KasunUdaraWaththeHewa, we don't assign issues in this repo. Just open a PR if you feel that you have something to contribute that we don't already have. Our contributing guidelines already say all of this.
