### ISSUE TITLE
Need review for #10725

### ISSUE THREAD

**Issue by Arunsiva003** [TheAlgorithms/Python#10815]
### Feature description

The PR needs to be revived....speed up the merge

**Comment by tianyizheng02** [comment]
**_Do not_** open issues to solicit code reviews.

**Comment by Arunsiva003** [comment]
> **_Do not_** open issues to solicit code reviews.

But it not been reviewed for almost 4 days...now made a PR #10830...atleast now make a review and proceed the merging
