### ISSUE TITLE
decimal to binary converter does not take floating values

### ISSUE THREAD

**Issue by Corruption13** [TheAlgorithms/Python#1083]
The conversions/decimal_to_binary.py script does not take in floating point values and instead only converts the whole number part of the value.

**Comment by Corruption13** [comment]
I have implemented the required changes in this pull request:

https://github.com/TheAlgorithms/Python/pull/1084

**Comment by cclauss** [comment]
Works as designed.  The current functionality mirrors the Python builtin [__bin()__](https://docs.python.org/3/library/functions.html#bin) which also does not accept floating point values.
