### ISSUE TITLE
Need more pytests

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#1085]
The following do not yet have any pytests:
* [x] boolean_algebra
* [x] digital_image_processing
* [x] divide_and_conquer
* [x] hashes
* [x] linear_algebra #1124
* [x] networking_flow #1126
* [x] traversals
* [ ] file_transfer_protocol  # __This might be difficult__
* [ ] machine_learning
* [ ] neural_network

For ease of review, please only modify one directory per pull request.

**Comment by mrvnmchm** [comment]
Added a few doctests for boolean_algebra #1097

**Comment by QuantumNovice** [comment]
Added pytests to sha1.py #1098

**Comment by QuantumNovice** [comment]
Added pytests to hashes/md5.py #1100

**Comment by mrvnmchm** [comment]
Added pytests for digital_image_processing #1111

**Comment by mrvnmchm** [comment]
Looking into slow tests from #1117 

<img width="977" alt="image" src="https://user-images.githubusercontent.com/11682032/63219708-d6abd380-c145-11e9-93ea-cc773fcd87c8.png">

**Comment by cclauss** [comment]
Thanks for this.  It is better to test than not to test.  Is it possible to accelerate the algorithms or test on smaller images while still covering all the same corner cases?  If not, we can live with the current runtimes.

**Comment by Naklecha** [comment]
Added  a few doctests for traverals https://github.com/TheAlgorithms/Python/pull/1149

**Comment by AngelGarcia20** [comment]
Hi! I hope I may post this message on the right place. I would like to obtain permission to fork the ciphers folders for learning purposes (all credits to the original author). Thanks!

**Comment by parthpandyappp** [comment]
@cclauss Hello!
I went through the issue and I don't know python but I know C++.
I'm interested to contribute here!
I was asking that we just have to implement pytest ? That's it?
how to implement pytest?
can I have some help?

**Comment by cclauss** [comment]
PyTest is automatically run by Travis CI on every pull request.  https://github.com/TheAlgorithms/Python/blob/master/.travis.yml#L13 Today, it is just running doctests but the coverage is quite impressive: https://travis-ci.org/TheAlgorithms/Python/builds/592517664#L610

Perhaps you and @cozek could see if there are other pytests that we need or perhaps our code coverage is solid enough and we can close this issue.  Or perhaps create a new issue of all Python files that are not currently tested.  That would create a liast of TODOs for Hacktoberfest contributors.

**Comment by cclauss** [comment]
There are currently still no __machine_learning__ or __neural_network__ doctests that are being detected by pytest.

**Comment by hash84** [comment]
Created test functions for Decision Tree mean Squared error method
https://github.com/TheAlgorithms/Python/pull/1374

**Comment by parthpandyappp** [comment]
@cclauss Can I please know the step by step process of how to do pytest for a particular python program?

**Comment by cclauss** [comment]
The easiest way is to add doctests in the docstrings of functions and methods like [here](https://github.com/TheAlgorithms/Python/blob/master/maths/abs.py#L4-L14).  These will be tested by Travis CI but you can also test them locally as discussed in CONTRIBUTING.md.

**Comment by janithwanni** [comment]
I'll take up the machine learning folder @cclauss

**Comment by cclauss** [comment]
Awesome...  Another great example with both doctests and type hints is https://github.com/TheAlgorithms/Python/blob/master/ciphers/shuffled_shift_cipher.py

**Comment by cclauss** [comment]
Pytest currently runs 373 on every pull request.
