### ISSUE TITLE
decimal_to_binary() should return identical values as bin()

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#1090]
https://github.com/TheAlgorithms/Python/blob/7b267e5e4f8ccb72dd58fcf0057642fd62a36bdf/conversions/decimal_to_binary.py#L4

Please change __decimal_to_binary()__ to return identical values as the Python builtin [__bin()__](https://docs.python.org/3/library/functions.html#bin).  With doctests to prove it please.

@PatOnTheBack @Corruption13

**Comment by syedwaleedhyder** [comment]
Give an example of a decimal number for which `decimal_to_binary(num)` is inconsistent.

**Comment by cclauss** [comment]
__0b__ is missing

**Comment by syedwaleedhyder** [comment]
I have created a pull request(#1093).
The new code can handle ZERO and negative numbers too.
