### ISSUE TITLE
Sync with Travis-CI

### ISSUE THREAD

**Issue by H-Darji** [TheAlgorithms/Python#11]
If you want previous merge to work, you need to sync this repository with Travis-CI.
I already had made request from my Travis-CI profile to this organization, you just need to grant it.

**Comment by dynamitechetan** [comment]
How do I grant it

**Comment by H-Darji** [comment]
Actually I also don't have any idea about it. May be you've received an email from travis.

**Comment by dynamitechetan** [comment]
I granted the access.  Now what?

**Comment by H-Darji** [comment]
I do have access to repository I created, but I need access right to access Python repo.
Take a look at below image:
![capture](https://cloud.githubusercontent.com/assets/14276147/17332366/2386a010-58ec-11e6-9a85-ad915ce77f98.JPG)

**Comment by H-Darji** [comment]
Owner of this repository needs to active repo for Travis-CI from **setting** -> **Webhook & services**. There must be travis service. open it, activate it and then click on update service button.

**Comment by dynamitechetan** [comment]
Check it my committing a file... I almost did everything they mentioned on their website

**Comment by H-Darji** [comment]
Done!
