### ISSUE TITLE
Adding Hexadecimal to Octal Conversion in Conversions

### ISSUE THREAD

**Issue by Abhishek-Rajput-81** [TheAlgorithms/Python#11029]
### Feature description

I would like to request the addition of a hexadecimal to octal conversion feature.
please assign this job to me
Thank you

**Comment by tianyizheng02** [comment]
Read our contributing guidelines: do not open issues to propose new algorithms. We also don't assign issues in this repo. If you want to contribute an algorithm, just open a PR.
