### ISSUE TITLE
empty, seemingly unused files

### ISSUE THREAD

**Issue by AlexDvorak** [TheAlgorithms/Python#1112]
The files in question are `16L'` and `Q'` and appear to be unrelated to [the PR](https://github.com/TheAlgorithms/Python/pull/1098/commits/a8b5c748c2cc162fcb69b86b4deeae3a66965c05) that added them

**Comment by cclauss** [comment]
@harshildarji @QuantumNovice Your thoughts?

**Comment by harshildarji** [comment]
@cclauss Positive, my bad! @AlexDvorak Thanks for pointing out!
