### ISSUE TITLE
Goldbach's conjecture

### ISSUE THREAD

**Issue by ABarpanda** [TheAlgorithms/Python#11128]
### Feature description

I wish to add a program that tests Goldbach's conjecture.

**Comment by zachtheyek** [comment]
@ABarpanda This seems interesting, could you be a bit more descriptive w.r.t. the "testing" part. How exactly would you approach Goldbach's conjecture without brute force computations?

**Comment by tianyizheng02** [comment]
As stated in the contributing guidelines, which OP hopefully read:
> _Do not_ create an issue to contribute an algorithm. Please submit a pull request instead.

If OP still wishes to contribute this algorithm (after clarifying its purpose, as @zachtheyek pointed out), they may do so in another PR.
