### ISSUE TITLE
file_transfer_protocol doesn't actually implement FTP

### ISSUE THREAD

**Issue by AlexDvorak** [TheAlgorithms/Python#1113]
It simply sends the contents of a single file over a TCP socket, with no support for browsing directories, or authentication. While this is a good demo of how to setup and use TCP sockets in Python, it is not really an implementation of FTP.

**Comment by cclauss** [comment]
What would be a better, less misleading title for these files?

**Comment by AlexDvorak** [comment]
send_data.py?

**Comment by cclauss** [comment]
send_file.py and receive_file.py ?
send_a_file.py and receive_a_file.py ?

Please consider submitting a PR.

**Comment by AlexDvorak** [comment]
sure, `send_file.py` and `receive_file.py` sounds good

**Comment by cclauss** [comment]
Should the directory name also be changed?

**Comment by AlexDvorak** [comment]
I wouldn't because I think that an actual implementation of FTP would make more sense with this simple sending and receiving a file over sockets.

**Comment by cclauss** [comment]
There are already open source implémentations of ftp.  Why not just rename the directory __file_transfer__ and it can contain just a few simple examples.

**Comment by AlexDvorak** [comment]
sure, does this look good? https://github.com/dlsyj/ftp

**Comment by cclauss** [comment]
We do _not_ need a full implementation of ftp in this repo.  Just some simple implémentations of how to transfer a file from one machine to another.
