### ISSUE TITLE
Find Biparate Matching Algorithms missing

### ISSUE THREAD

**Issue by madeyexz** [TheAlgorithms/Python#11140]
### Feature description

Find Biparate Matching Algorithms missing

**Comment by SarojArchana** [comment]
Can you review my PULL request

**Comment by GalvanAzmuth** [comment]
what is the purpose of biparate matching in real time application or is it an algorithm whose concept can be applied in any other application that can be created or can it be used to provide any kind of service.

**Comment by SarojArchana** [comment]
@madeyexz 
Can you review my PULL request

I have added the Biparate Matching Algorithm

**Comment by tianyizheng02** [comment]
Re-closing as not planned rather than completed since we make it very clear in the contributing guidelines not to open issues to contribute an algorithm:
> **Do not** create an issue to contribute an algorithm. Please submit a pull request instead.
