### ISSUE TITLE
Global variable should not using in class method

### ISSUE THREAD

**Issue by icecraft** [TheAlgorithms/Python#11232]
### Repository commit

9caf4784aada17dc75348f77cc8c356df503c0f3

### Python version (python --version)

python3.11

### Dependencies version (pip freeze)

#nop 

### Expected behavior

Hi, guys. I come across one global variable that used in class method. I think using instance attribute would be better !
```python
    def show_data(self):
        show_list = []
        for i in range(1, N + 1):  ==> should using self.N instead of N !
            show_list += [self.query(i, i)]
        print(show_list)
```
[source](https://github.com/TheAlgorithms/Python/blob/master/data_structures/binary_tree/segment_tree.py#L101)

### Actual behavior

```python
    def show_data(self):
        show_list = []
        for i in range(1, self.N + 1):  
            show_list += [self.query(i, i)]
        print(show_list)
```

**Comment by GantedaAravind** [comment]
Hi,
i am beginner to open source can you give the instructions to solve this problem.. can you work on this issue

**Comment by zakariatahiri** [comment]
hi i am beginner to open source too

**Comment by smruthi-sumanth** [comment]
Hello! Can I get the go ahead to start on fixing this issue?
