### ISSUE TITLE
attributeerror:'artistlist' object has no attribute 'remove'

### ISSUE THREAD

**Issue by aref9069** [TheAlgorithms/Python#11260]
### What would you like to share?

I am facing an issue while attempting to run a GUI for live image processing. In my code, I have defined the GUI's output frame and utilized the "add_artist" function (live plot in Matplotlib) to draw live lines on the frame. However, I've encountered a problem where, after running the code and obtaining some initial images, subsequent images are being cut off, preventing me from obtaining the complete set of images needed for my image processing tasks.

I am using:

<for each in self.Live_ax.lines: each.remove() >

to remove the previous image and but gives me this error:

(attributeerror:'artistlist' object has no attribute 'remove')

I am seeking assistance to identify the root cause of this issue and find a solution to ensure that all live images are captured. Any help would be appreciated :)

Tried to inexecutable the "for each in self.Live_ax.lines: each.remove()" with adding triple quotes but it seems that they are accumulating and causing unnecessary spaces with each iteration!

I am leaving the part of the code that I am working on here:

### Additional information

#Updates the graph to dsiplay the new graphical image of the current line
    def Update_Live_Graph(self, X_Data, Y_Data, X_est, Y_est):
        self.Live_Canvas.restore_region(self.Live_background)
        self.Live_ax.set_xlim(X_Data[0]-300,X_Data[0]+100)

  #plots theoretical plot
        if X_est is not None:
            if self.Live_X:
                self.Current_Lines_est = self.Live_ax.plot(X_est,(Y_est), color ='red',  linestyle='dashed')[0]
                self.Live_Figure.add_artist(self.Current_Lines_est)
                self.Live_Figure.draw_artist(self.Current_Lines_est)
            else:
                X_est =np.append(X_est[0]+300,X_est )
                Y_est =np.append(Y_est,Y_est[-1])
                self.Current_Lines_est = self.Live_ax.plot(X_est,(Y_est), color ='red',  linestyle='dashed')[0]
                self.Live_Figure.add_artist(self.Current_Lines_est)
                self.Live_Figure.draw_artist(self.Current_Lines_est)    

        #Draw the True line
        self.Current_Lines = self.Live_ax.plot(X_Data,(Y_Data), color ='blue')[0]
        #Draw the marker to highlight the last point
        self.Last_Point = self.Live_ax.plot(X_Data[0],(Y_Data[0]), color ='black', marker = '.', linewidth = 4, markersize = 10)[0]

        self.Live_Figure.add_artist(self.Current_Lines)
        self.Live_Figure.draw_artist(self.Current_Lines)
        self.Live_Figure.add_artist(self.Last_Point)
        self.Live_Figure.draw_artist(self.Last_Point)
        #Refresh the canvase
        self.Live_Canvas.blit(self.Live_ax.bbox)

        #Remove the lines from the image:
        try:
            self.Live_ax.lines.remove(self.Current_Lines_est)
            self.Current_Lines_est.remove()
        except:
            pass

        for each in self.Live_ax.lines: 
            each.remove()
        print(self.Live_ax.lines)
        self.Current_Lines.remove()
        self.Last_Point.remove()

**Comment by DrxcoDev** [comment]
Hello!! The issue you're facing stems from the fact that self.Live_ax.lines is a list of Line2D objects, and these objects do not have a remove() method. Instead, you can use the remove() function of the container, which is the axis itself (self.Live_ax in this case).


# Actualiza el gráfico para mostrar la nueva imagen gráfica de la línea actual
def Update_Live_Graph(self, X_Data, Y_Data, X_est, Y_est):
    self.Live_Canvas.restore_region(self.Live_background)
    self.Live_ax.set_xlim(X_Data[0] - 300, X_Data[0] + 100)

    # Plots gráfico teórico
    if X_est is not None:
        if self.Live_X:
            self.Current_Lines_est = self.Live_ax.plot(X_est, Y_est, color='red', linestyle='dashed')[0]
            self.Live_Figure.add_artist(self.Current_Lines_est)
            self.Live_Figure.draw_artist(self.Current_Lines_est)
        else:
            X_est = np.append(X_est[0] + 300, X_est)
            Y_est = np.append(Y_est, Y_est[-1])
            self.Current_Lines_est = self.Live_ax.plot(X_est, Y_est, color='red', linestyle='dashed')[0]
            self.Live_Figure.add_artist(self.Current_Lines_est)
            self.Live_Figure.draw_artist(self.Current_Lines_est)

    # Draw the True line
    self.Current_Lines = self.Live_ax.plot(X_Data, Y_Data, color='blue')[0]

    # Draw the marker to highlight the last point
    self.Last_Point = self.Live_ax.plot(X_Data[0], Y_Data[0], color='black', marker='.', linewidth=4, markersize=10)[0]

    self.Live_Figure.add_artist(self.Current_Lines)
    self.Live_Figure.draw_artist(self.Current_Lines)
    self.Live_Figure.add_artist(self.Last_Point)
    self.Live_Figure.draw_artist(self.Last_Point)

    # Refresh the canvas
    self.Live_Canvas.blit(self.Live_ax.bbox)

    # Remove the lines from the image
    try:
        self.Live_ax.lines.remove(self.Current_Lines_est)
        self.Live_ax.lines.remove(self.Current_Lines)
    except ValueError:
        pass

    self.Current_Lines_est.remove()
    self.Current_Lines.remove()
    self.Last_Point.remove()
