### ISSUE TITLE
Adding Financial algorithms in Python 

### ISSUE THREAD

**Issue by Akshat111111** [TheAlgorithms/Python#11304]
### Feature description

Adding the different machine learning algorithms of quantitative finance

**Comment by Akshat111111** [comment]
Kindly assign me this issue so that I can work on it

**Comment by krishjoshi7** [comment]
hello can you please let me know more about the issue and explain it in brief

**Comment by tianyizheng02** [comment]
Please read the contributing guidelines.
> **We do not assign issues in this repo** so please do not ask for permission to work on an issue.
>
> **Do not** create an issue to contribute an algorithm. Please submit a pull request instead.
