### ISSUE TITLE
Install github's "Stale bot" in the repository

### ISSUE THREAD

**Issue by QuantumNovice** [TheAlgorithms/Python#1134]
https://github.com/marketplace/stale
![image](https://user-images.githubusercontent.com/43876848/63150637-2fe7fb80-bfbc-11e9-8dbe-c87e4ff41e4f.png)

**Comment by cclauss** [comment]
I am usually not a fan of stalebot but for this repo currently with 150+ open PRs, it might not be a bad idea.

I would also be interested to see TheAlgorithms sign up for the GitHub Actions beta.  Doing so would enable us to replace our Travis setup.  https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

**Comment by cclauss** [comment]
No one has admin rights to this repo.
