### ISSUE TITLE
 Implementation of the Knapsack Problem Solver

### ISSUE THREAD

**Issue by MFRADJ** [TheAlgorithms/Python#11401]
### Feature description

**_Description_**
I propose the addition of a new feature to solve the Knapsack Problem, a fundamental challenge in combinatorial optimization. This problem involves selecting items with specific weights and values to maximize the total value without exceeding the weight capacity of the knapsack. It has applications in resource allocation, logistics, finance, and more.

**Suggested Implementation**
The solver could be implemented using Python, and I recommend starting with a dynamic programming approach for the 0/1 Knapsack Problem. Future enhancements might include other variations like the Bounded and Unbounded Knapsack Problems.

Educational Value: Great for demonstrating algorithm efficiency and optimization techniques.
Utility: Can be used as a utility for other features within the project that may require optimization capabilities.
Community Engagement: Offers a well-defined problem that could help new contributors get involved with the project through clear, manageable goals.

**Requirements**
A function to accept arrays/lists of weights, values, and the maximum capacity of the knapsack.
An algorithm to compute the maximum value that can be carried in the knapsack without exceeding the weight limit.
Unit tests to ensure the functionality works correctly under various scenarios.

**Possible Extensions**
Adding support for fractional items (for the fractional knapsack problem).
Implementing different algorithms for comparison, such as a greedy approach, branch and bound, or genetic algorithms.
I believe this feature would be a valuable addition to the project and look forward to the community's feedback and ideas on this proposal.

[Example_Knapsack Problem.pdf](https://github.com/TheAlgorithms/Python/files/15287324/Example_Knapsack.Problem.pdf)

**Comment by tianyizheng02** [comment]
We literally have a `knapsack/` directory just for solutions to the knapsack problem. Please look over the repo contents before you open an issue.

Also, if you want to contribute an algorithm, just open a PR. There's no need to open an issue, as there is no "issue".
