### ISSUE TITLE
use subrocess,check_output 'utf-8' codec can't decode byte 0xd3 in position 79: invalid continuation byte error

### ISSUE THREAD

**Issue by xiezhipeng-git** [TheAlgorithms/Python#11413]
### Repository commit

tags/v3.10.10:aad5f6a

### Python version (python --version)

python3.10.10

### Dependencies version (pip freeze)

absl-py==1.4.0
accelerate==0.29.2
addict==2.4.0
aiofiles==23.2.1
aiohttp==3.8.4
aiosignal==1.3.1
albumentations==1.3.0
ale-py==0.8.1
alembic==1.13.1
aliyun-python-sdk-core==2.15.1
aliyun-python-sdk-kms==2.16.2
altair==5.3.0
annotated-types==0.6.0
anyio==4.3.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.2.1
async-lru==2.0.4
async-timeout==4.0.2
atari-py==0.2.9
atomicwrites==1.4.1
attrs==22.2.0
Babel==2.14.0
backcall==0.2.0
backoff==2.2.1
beautifulsoup4==4.12.3
bitsandbytes==0.43.1
black==23.1.0
bleach==6.1.0
Box2D==2.3.2
Box2D-kengz==2.3.3
box2d-py==2.3.5
cachetools==5.3.0
certifi==2024.2.2
cffi==1.15.1
chardet==5.2.0
charset-normalizer==2.1.1
click==8.1.3
cloudpickle==2.2.1
colorama==0.4.6
colorlog==6.7.0
comm==0.1.3
concurrent-log-handler==0.9.20
contourpy==1.0.7
crafter==1.8.1
crcmod==1.7
cryptography==42.0.5
cycler==0.11.0
Cython==0.29.33
datasets==2.18.0
debugpy==1.8.1
decorator==4.4.2
defusedxml==0.7.1
Deprecated==1.2.14
dill==0.3.6
distlib==0.3.6
distro==1.9.0
dm-control==1.0.14
dm-env==1.6
dm-tree==0.1.8
dnspython==2.6.1
docstring_parser==0.16
einops==0.6.1
environs==9.5.0
et-xmlfile==1.1.0
exceptiongroup==1.1.3
executing==1.2.0
Farama-Notifications==0.0.4
fastapi==0.110.2
fasteners==0.18
fastjsonschema==2.19.1
ffmpy==0.3.2
filelock==3.9.0
fire==0.5.0
fonttools==4.39.2
fqdn==1.5.1
frozenlist==1.3.3
fsspec==2023.10.0
gast==0.5.4
glcontext==2.3.7
glfw==1.12.0
google-auth==2.16.2
google-auth-oauthlib==0.4.6
gradio==4.31.4
gradio_client==0.16.4
greenlet==3.0.3
grpcio==1.51.3
gym==0.26.2
gym-notices==0.0.8
gym-super-mario-bros==7.4.0
gym3==0.3.3
gymnasium==0.28.1
h11==0.14.0
hf_transfer==0.1.6
httpcore==1.0.5
httpx==0.27.0
huggingface==0.0.1
huggingface-hub==0.23.0
idna==3.4
imageio==2.26.1
imageio-ffmpeg==0.3.0
importlib-resources==5.12.0
importlib_metadata==7.1.0
iniconfig==2.0.0
intel-openmp==2021.4.0
ipykernel==6.29.4
ipython==8.16.0
ipywidgets==8.1.2
isoduration==20.11.0
jax-jumpy==1.0.0
jedi==0.19.1
Jinja2==3.1.2
jmespath==0.10.0
joblib==1.3.2
json5==0.9.25
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.1.0
jupyter_core==5.3.0
jupyter_server==2.14.0
jupyter_server_terminals==0.5.3
jupyterlab==4.1.6
jupyterlab_pygments==0.3.0
jupyterlab_server==2.26.0
jupyterlab_widgets==3.0.10
kaggle==1.6.12
keyboard==0.13.5
kiwisolver==1.4.4
labmaze==1.0.6
lazy_loader==0.2
libaio==0.9.1
-e git+https://github.com/hiyouga/LLaMA-Factory.gi
t@2a67457e3944d5e528286cb7203857c13078c484#egg=lla
mafactory
llmtuner==0.7.0
loguru==0.6.0
lxml==4.9.3
lz4==4.3.2
Mako==1.3.3
Markdown==3.4.1
markdown-it-py==3.0.0
MarkupSafe==2.1.2
marshmallow==3.20.1
matplotlib==3.7.1
matplotlib-inline==0.1.6
mdurl==0.1.2
memory-maze==1.0.3
metrics==0.3.3
minio==7.1.17
mistune==3.0.2
mkl==2021.4.0
mlagents-envs==0.28.0
modelscope==1.14.0
moderngl==5.8.1
MouseInfo==0.1.3
moviepy==1.0.3
mpmath==1.2.1
msgpack==1.0.5
mujoco==2.3.7
mujoco-py==2.1.2.14
multidict==6.0.4
multiprocess==0.70.14
mypy-extensions==1.0.0
nbclient==0.10.0
nbconvert==7.16.3
nbformat==5.10.4
nes-py==8.2.1
nest-asyncio==1.5.6
networkx==3.0rc1
notebook==7.1.3
notebook_shim==0.2.4
numpy==1.26.4
oauthlib==3.2.2
openai==1.23.6
opencv-python==4.7.0.72
opencv-python-headless==4.7.0.72
openpyxl==3.1.2
opensimplex==0.4.5
optuna==3.6.1
orjson==3.10.1
oss2==2.18.4
overrides==7.7.0
packaging==23.0
pandas==2.2.2
pandocfilters==1.5.1
parso==0.8.3
pathlib2==2.3.7.post1
pathspec==0.5.5
peft==0.10.0
pettingzoo==1.23.1
pickleshare==0.7.5
Pillow==9.3.0
pip==24.0
platformdirs==4.2.1
pluggy==1.0.0
portalocker==2.7.0
procgen==0.10.7
proglog==0.1.10
prometheus_client==0.20.0
prompt-toolkit==3.0.38
protobuf==3.20.3
psutil==5.9.4
pure-eval==0.2.2
py==1.11.0
pyarrow==16.0.0
pyarrow-hotfix==0.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAutoGUI==0.9.54
pybind11==2.11.1
pybind11-stubgen==2.2.2
pycolab==1.2
pycparser==2.21
# Editable install with no version control (pycraw
lers==1.1.6)
-e d:\my\work\llm\download\pycrawlers-1.1.6
pycryptodome==3.20.0
pydantic==2.5.0
pydantic_core==2.14.1
pydub==0.25.1
pygambit==16.2.0
pygame==2.1.0
PyGetWindow==0.0.9
pygifsicle==1.0.7
pyglet==1.5.21
Pygments==2.18.0
pymilvus==2.3.2
pymongo==4.7.2
PyMsgBox==1.0.9
pynput==1.7.6
PyOpenGL==3.1.6
pyparsing==3.0.9
pyperclip==1.8.2
PyQt5==5.15.10
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
PyRect==0.2.0
pyrsistent==0.19.3
PyScreeze==0.1.30
PySoundFile==0.9.0.post1
pytest==7.0.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.9
python-slugify==8.0.4
pytweening==1.2.0
pytz==2022.7.1
PyWavelets==1.4.1
pywin32==305
pywinpty==2.0.13
PyYAML==6.0
pyzmq==25.0.2
qtconsole==5.5.1
QtPy==2.4.1
qudida==0.0.4
ray==2.6.0
referencing==0.34.0
regex==2023.3.22
requests==2.31.0
requests-oauthlib==1.3.1
responses==0.18.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.1
rpds-py==0.18.0
rsa==4.9
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
ruff==0.4.2
safetensors==0.4.3
scikit-image==0.20.0
scikit-learn==1.2.2
scipy==1.10.1
seaborn==0.12.2
semantic-version==2.10.0
Send2Trash==1.8.3
sentencepiece==0.2.0
setuptools==69.5.1
sh==2.0.3
shellingham==1.5.4
shtab==1.7.1
simplejson==3.19.2
six==1.16.0
slxpy==1.6.0
sniffio==1.3.1
sortedcontainers==2.4.0
soupsieve==2.5
SQLAlchemy==2.0.29
sse-starlette==2.1.0
stable-baselines3==2.2.1
stack-data==0.6.2
starlette==0.37.2
support-developer==1.0.5
swig==4.1.1
sympy==1.12
tbb==2021.11.0
tensorboard==2.12.0
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
termcolor==2.2.0
terminado==0.18.1
text-unidecode==1.3
threadpoolctl==3.1.0
tifffile==2023.4.12
timm==0.6.13
tinycss2==1.2.1
tokenizers==0.19.1
tomli==2.0.1
tomlkit==0.12.0
toolz==0.12.1
torch==2.3.0+cu121
torchaudio==2.3.0+cu121
torchvision==0.18.0+cu121
tornado==6.2
tqdm==4.66.4
traitlets==5.9.0
transformers==4.40.2
trl==0.8.6
typer==0.12.3
types-python-dateutil==2.9.0.20240316
typing_extensions==4.11.0
tyro==0.8.3
tzdata==2024.1
ujson==5.8.0
uri-template==1.3.0
urllib3==2.2.1
uvicorn==0.29.0
vec-noise==1.1.4
virtualenv==20.21.0
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
websockets==11.0.3
Werkzeug==2.2.3
wheel==0.40.0
widgetsnbextension==4.0.10
win32-setctime==1.1.0
windows-curses==2.3.2
wrapt==1.16.0
xformers==0.0.26.post1
xxhash==3.2.0
yapf==0.40.2
yarl==1.8.2
zipp==3.15.0

### Expected behavior

https://github.com/microsoft/vscode/issues/210957
It is vscode error or Python error

### Actual behavior

see https://github.com/microsoft/vscode/issues/210957

**Comment by tianyizheng02** [comment]
Closing because this has nothing to do with the Python Algorithms repo. The issues tab of this repo is not a general Python help forum.

**Comment by xiezhipeng-git** [comment]
Oh no, I submitted it in the wrong place
