### ISSUE TITLE
Need to migrate to NumPy 2.0.

### ISSUE THREAD

**Issue by its-100rabh** [TheAlgorithms/Python#11480]
### Feature description

Need to migrate to NumPy 2.0 as ruff tests are failing or need to change test configurations

Below is the error raised by ruff check
graphs/multi_heuristic_astar.py:82:12: NPY201 np.chararray will be removed in NumPy 2.0. Use numpy.char.chararray instead.
![Screenshot (743)](https://github.com/TheAlgorithms/Python/assets/98408932/1dfd5eca-d0c5-46d6-bdaf-80d21f07260c)

**Comment by XtriX203** [comment]
Hello there,
From what I checked in **graphs/multi_heuristic_astar.py** it uses **numpy.char.chararray** and works well,
so either the broblem has already been resolved or you should update your repo.
<img width="1279" alt="Screenshot 2024-07-12 135855" src="https://github.com/user-attachments/assets/d747482d-6127-4d2f-9c7f-b7724f3a176b">

**Comment by its-100rabh** [comment]
Yes, you are right.
The latest commit to the repository has solved this error.
My pull request has passed the review as well.
We can close this issue.
