### ISSUE TITLE
Where can I find these algorithms questions?

### ISSUE THREAD

**Issue by RockLeeStudio** [TheAlgorithms/Python#1151]
Where can I find these algorithms questions?

**Comment by cclauss** [comment]
I do not understand this issue.
Our index of algorithms is https://github.com/TheAlgorithms/Python/blob/master/DIRECTORY.md

**Comment by RockLeeStudio** [comment]
for example : bisection. 
What is bisection? Where can I find the bisection description.

**Comment by cclauss** [comment]
https://en.m.wikipedia.org/wiki/Bisection_method

**Comment by cclauss** [comment]
What might be supercool would be a dict that links __algorithm_name__ to __wiki_article_name__.  If we had that then our __scripts/build_directory_md.py__ could autogenerate a DIRECTORY.md that linked the two.
