### ISSUE TITLE
Harah

### ISSUE THREAD

**Issue by Harsh240-raj** [TheAlgorithms/Python#11533]
### Feature description

Here's a simple example of a Python code using the Turtle library to draw 

import turtle

# Set up the screen
screen = turtle.Screen()
screen.bgcolor("white")

# Create a new turtle object
my_turtle = turtle.Turtle()
my_turtle.speed(0)  # Fastest speed

# Function to draw a square
def draw_square(color):
    my_turtle.fillcolor(color)
    my_turtle.begin_fill()
    for _ in range(4):
        my_turtle.forward(50)
        my_turtle.right(90)
    my_turtle.end_fill()

# Draw the chessboard
for row in range(8):
    for col in range(8):
        my_turtle.penup()
        my_turtle.goto(col * 50, row * 50)
        my_turtle.pendown()
        if (row + col) % 2 == 0:
            draw_square("gray")
        else:
            draw_square("white")

**Comment by tianyizheng02** [comment]
Not sure what this has to do with this repo
