### ISSUE TITLE
Unresponsive PRs and issues

### ISSUE THREAD

**Issue by harshildarji** [TheAlgorithms/Python#1155]
To ~@cclauss~ @AnupKumarPanwar @poyea

---
Hey all,
At this moment, we have over **150 PRs**. Some of these are requested changes by the reviewers, but there is no response from the PR makers after that. Some PRs are months old which now may cause conflicts with current implementations if merged.
**Therefore, I plan to close such PRs which have no response from people who made it or is months old which might break an existing implementation.**
But before doing so, I would like to know what other members think about this.
Thank you.

Best regards,
Harshil Darji

**Comment by cclauss** [comment]
My sense is that we should implement #1134.  It is better if it is done with GitHub's tool rather than doing it manually.

**Comment by QuantumNovice** [comment]
One of the reason why #1134 should be accepted.

**Comment by harshildarji** [comment]
@cclauss I agree. Doing so manually is tedious and it is also not my intention considering the number of open PRs. But we have to do this ASAP so we can focus only on PRs which are important and close the ones which are unnecessary and unresponsive.

**Comment by cclauss** [comment]
https://github.com/marketplace/stale

**Comment by harshildarji** [comment]
I've sent the request to install stale. Once it has been installed I'll send PR with stale.yml file to work with it.

**Comment by r0hit-gupta** [comment]
@harshildarji I have approved the request. Please go forward.

**Comment by harshildarji** [comment]
@r0hit-gupta Hey, Thanks for approving this. It's installed but since I do not have permission to configure it, you'll have to do it as an owner.
Visit [configure stale](https://github.com/apps/stale/installations/new) to configure it to work with Python repo.
Thank you.

**Comment by cclauss** [comment]
I do not have the rights to turn this on but __it should be turned on__.

**Comment by harshildarji** [comment]
@cclauss I think so. I also do not have rights for that!

**Comment by chttrjeankr** [comment]
I think using GitHub actions to check stale issues and PRs can be done now, since GitHub Actions is open for public.
Searched a bit and created this [gist](https://gist.github.com/chttrjeankr/420e9b7b5bafffeb3faa8b997e1e26d5) which I think will be apt for TheAlgorithms/Python repository, but I am unable to understand how exactly can I implement this. Can I please have some help to implement this into the repository? :pray:

**Comment by cclauss** [comment]
https://github.com/marketplace/stale is all we need.  It is free from GitHub.  Someone with Admin privileges just needs to turn in on.

**Comment by chttrjeankr** [comment]
I was suggesting we use [this](https://github.com/marketplace/actions/close-stale-issues)
