### ISSUE TITLE
Common errors used in python 

### ISSUE THREAD

**Issue by Phyhoncoder13** [TheAlgorithms/Python#11586]
### What would you like to share?

IOError
Raised when an I/O operation fails for an I/O-related reason, e.g., "file not found".

ImportError:
Raised when an important statement fails to find the module definition 

IndexError:
Raised when  a sequence index is out of range

KeyError:
Raised when a dictionary key is not found 

NameError:
Raised when a local or global name is not found 

TypeError
Raised when an operation or function is applied to an object of inappropriate type

For a complete list of all errors go to https://docs.python.org/3/library/expectations.html.

**Comment by Anjani87** [comment]
WHAT IS TO BE FIX IN THIS?

**Comment by Phyhoncoder13** [comment]
> WHAT IS TO BE FIX IN THIS?
> 

What do you mean

**Comment by eeshan15** [comment]
Hi Author can you tell how to take part in Hacktoberfest ?? I am new to this thing

**Comment by Phyhoncoder13** [comment]
> Hi Author can you tell how to take part in Hacktoberfest ?? I am new to this thing
> 

I'm new also and I put this on because it was in a book I've got that's teaching me python

**Comment by jatingarg36** [comment]
> Hi Author can you tell how to take part in Hacktoberfest ?? I am new to this thing

Hi, @eeshan15! To take part in Hackoberfest, you will need to work on any open-source git repository that either has the topic “**hacktoberfest**", or has the “**hacktoberfest-accepted**” label on the issue. 
The PR/MR will only be considered if its created btw 1st oct and 31st oct.
For further details you can check out [HacktoberFest 2024](https://hacktoberfest.com/participation/)

**Comment by tianyizheng02** [comment]
This issue doesn't seem to be related to this repo at all, so I'm closing this. Please read our contributing guidelines if you wish to contribute for Hacktoberfest.
