### ISSUE TITLE
Please like my code 

### ISSUE THREAD

**Issue by Phyhoncoder13** [TheAlgorithms/Python#11585]
userInput = input('Enter 1 or 2: ')
if userInput == "1":
    print ("Hello world")
    print ("I love Python")
elif userInput == "2":
    print ("python rocks")
    print ("How are you?")
else:
    print ("you did not enter a valid number")

**Comment by Phyhoncoder13** [comment]
Ima python beginner and I struggled to make this please like

**Comment by tianyizheng02** [comment]
Sorry, but I don't see how this is related to this repo at all.
