### ISSUE TITLE
Implementation of AES, DES and Blowfish Symmetric Cryptographic Algorithms in Ciphers Section

### ISSUE THREAD

**Issue by tkgowtham** [TheAlgorithms/Python#11593]
### Feature description

I would like to implement AES, DES and Blowfish algorithm from scratch in Python and upload it to ciphers folder. If you are ok with it, please assign me to the work and I will code it and create a pull requests for these algorithms.

**Comment by tianyizheng02** [comment]
Like I wrote on your previous issue, we don't assign issues in this repo, and please make sure that your contribution is your own original work and implements an algorithm from scratch.

**Comment by tkgowtham** [comment]
Ok, I will create a PR. And coming to the point of original work, I implemented the DBSCAN algorithm as part of ML class assignment is college and AES, DES and Blowfish as part of my Cryptography class assignment. I know there is nothing for me to prove that it is my original work, so I will create the PR, you can check for plagiarism and if you find it is copied from any other internet source, then decline my PR. Thanks !
