### ISSUE TITLE
Fixed and optimised capitalize.py , check_anagrams.py , back_propagation_neural_network.py.  please label me for HacktoberFest Accepted

### ISSUE THREAD

**Issue by Soyvor** [TheAlgorithms/Python#11595]
### Feature description

Please Label me for HacktoberFest accepted

Consistent naming conventions: The code uses both camelCase and underscore notation for variable names. To maintain consistency, I've used underscore notation throughout the code.
Type hints and docstrings: Added type hints and docstrings to improve code readability and understandability.
Simplified layer initialization: Simplified the layer initialization process by removing unnecessary variables and using more concise code.
Improved forward and backward propagation: Simplified the forward and backward propagation processes by reducing the number of intermediate variables and using more efficient matrix operations.
Removed unnecessary variables: Removed unnecessary variables and computations to improve code efficiency.
Improved plotting: Improved the plotting function to use more efficient and concise code.

**Comment by tianyizheng02** [comment]
I'm not sure why you opened this issue. If you'd like to contribute to this repo for Hacktoberfest, simply read CONTRIBUTING.md and submit a PR.
