### ISSUE TITLE
Implement Bucket Sort Algorithm in Python with Detailed Explanation

### ISSUE THREAD

**Issue by Gyanthakur** [TheAlgorithms/Python#11598]
### What would you like to share?

Bucket Sort is a comparison-based sorting algorithm that distributes elements into several 'buckets,' each representing a specific range of values. The elements within each bucket are sorted individually, either using another sorting algorithm or recursively applying Bucket Sort, and then combined to form the sorted array

**Comment by tianyizheng02** [comment]
1. Please do not open issues to suggest new algorithms. We do not assign issues in this repo. As stated in the contributing guidelines,
    > Do not create an issue to contribute an algorithm. Please submit a pull request instead.
    
2. Secondly, we already have an implementation of bucket sort in [`sorts/bucket_sort.py`](https://github.com/TheAlgorithms/Python/blob/0177ae1cd596f4f3c0ee7490666d74504deb0298/sorts/bucket_sort.py). If you wish to contribute an algorithm, please at least check to make sure that it hasn't already been implemented.

**Comment by Gyanthakur** [comment]
ok thankyou
