### ISSUE TITLE
Implementation of DBSCAN Algorithm in Machine Learning

### ISSUE THREAD

**Issue by tkgowtham** [TheAlgorithms/Python#11592]
### Feature description

Can we implement Density-based spatial clustering of applications with noise (DBSCAN) Machine learning model ? 
I have the code ready with me, if yes, I can immediately create a pull request by uploading the code for it.

**Comment by tianyizheng02** [comment]
1. We do not assign or approve issues in this repo. If you wish to contribute, please just open a PR.
2. > I have the code ready with me
  
    This sounds suspicious, not gonna lie. Please make sure that whatever you plan to contribute is your own work (i.e., not copied from elsewhere) and implements an algorithm from scratch.
