### ISSUE TITLE
Adding Graph Algorithm: Strongly Connected Components.

### ISSUE THREAD

**Issue by coffee-loves-code-2003** [TheAlgorithms/Python#11677]
### Feature description

Can i pull request for adding the graph section for Strongly Connected Components both in naive and optimized approach.

**Comment by tianyizheng02** [comment]
Please read our contributing guidelines before you open an issue or PR:
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.

Also, if you wish to contribute this algorithm, please make sure that it doesn't already exist in this repo.
