### ISSUE TITLE
Add AES Algorithm

### ISSUE THREAD

**Issue by unniznd** [TheAlgorithms/Python#11702]
### Feature description

Implement AES 128 Algorithm

**Comment by tianyizheng02** [comment]
As stated in our contributing guidelines,
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.

If you wish to contribute this algorithm, you're welcome to open a PR. Just make sure that you implement the algorithm yourself (i.e., do not just import an AES function from a library).
