### ISSUE TITLE
build_directory_md.py is not working correctly

### ISSUE THREAD

**Issue by jai-dewani** [TheAlgorithms/Python#1171]
The script should start all the headings with ##
but it is starting every line a *

**Comment by cclauss** [comment]
Both ## and * are valid markdown.

**Comment by jai-dewani** [comment]
But ## should be used for emphasizing the folders

**Comment by jai-dewani** [comment]
Fixed the bug #1161

**Comment by cclauss** [comment]
I like ## more because it create a link to a specific set of algorithms: __digital-image-processing__
https://github.com/TheAlgorithms/Python/blob/master/DIRECTORY.md#digital-image-processing

**Comment by jai-dewani** [comment]
Yes I am supporting the same point, the problem is that script when run is marking the folders with * instead of #
