### ISSUE TITLE
Add A* Searching Algorithm

### ISSUE THREAD

**Issue by UdaySharmaGitHub** [TheAlgorithms/Python#11732]
### Feature description

- Adding A* Searching Algorithm which much faster and more efficient than the other algorithms Graph Searching Algorithms.
- Assign me this issue under Hacktoberfest and Hacktoberfest2024.

**Comment by tianyizheng02** [comment]
1. We already have _multiple_ implementations of A* in our repo: https://github.com/search?q=repo%3ATheAlgorithms%2FPython%20a_star&type=code

    If you wish to contribute an algorithm to our repo, kindly do some due diligence first and check the codebase to make sure that your algorithm hasn't already been implemented.
2. We do not assign issues in this repo. This is made clear in our contributing guidelines (read if you haven't already):
    > If you are interested in resolving an open issue, simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
    >
    > Do not create an issue to contribute an algorithm. Please submit a pull request instead.
