### ISSUE TITLE
simple question about dijkstra.py 

### ISSUE THREAD

**Issue by rayjan0114** [TheAlgorithms/Python#1173]
Thanks for the great work!
I am just a starter of graph here
Thanks in advance if anyone responses
What is the code below for?
https://github.com/TheAlgorithms/Python/blob/a41a14f9d89b665178f08535f128ba14652ce449/graphs/dijkstra.py#L52-L53
Since we already have the code below to prevent from traveling twice, so I am so confused.
https://github.com/TheAlgorithms/Python/blob/a41a14f9d89b665178f08535f128ba14652ce449/graphs/dijkstra.py#L58-L59
Thanks!

**Comment by dragoFireup** [comment]
I'll try to explain this as simple as I can.
The first condition:
`if u in visited:` checks if the node which is popped from the heap is visited or not. 
and the second condition:
`if v in visited:` checks if the node to which the current node is connected to is visited or not.

Answering to your question to that why is `if u in visited:` condition required if `if v in visited:` is already present.
Sometimes different nodes might be connected to a single node x and all the other nodes will enter node x with its cost in the heap. For example, 2 nodes A and B are connected to C and A and B are visited before C. So both A and B add C into the heap as C has not yet been visited and now C is added twice into the heap. To check C again, the condition `if u in visited:` is added.

If you have any more questions feel free to ask and if someone finds any discrepancies please do tell and/or any better way to explain this.

**Comment by rayjan0114** [comment]
Thank you so much!
