### ISSUE TITLE
Want to add Sorted Linked List to Data Structires

### ISSUE THREAD

**Issue by mjk22071998** [TheAlgorithms/Python#11768]
### Feature description

I want to add sorted linked list to the repo under data structures. I have opened a pull request #11607 Please review

**Comment by AnuragSingh0000** [comment]
@mjk22071998 Is this issue completed? If not I would like to add it. Please respond.

**Comment by mjk22071998** [comment]
Yes this is complete

**Comment by roshankraveendrababu** [comment]
@mjk22071998 please assign this issue to me if it is in open. please respond

**Comment by mjk22071998** [comment]
I do not have permissions to assign this issue to anyone

**Comment by roshankraveendrababu** [comment]
> I do not have permissions to assign this issue to anyone

so whom should i ask for assignation ..

**Comment by mjk22071998** [comment]
Whoever is maintaining the repo

**Comment by onhgomat** [comment]
Can  I try this  can you give me this opportunity I want it

**Comment by onhgomat** [comment]
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class SortedLinkedList:
    def __init__(self):
        self.head = None

    def insert(self, data):
        if not self.head or data < self.head.data:
            new_node = Node(data)
            new_node.next = self.head
            self.head = new_node
        else:
            current = self.head
            while current.next and data > current.next.data:
                current = current.next
            new_node = Node(data)
            new_node.next = current.next
            current.next = new_node

    def print_list(self):
        current = self.head
        while current:
            print(current.data, end=" ")
            current = current.next
        print()

**Comment by mjk22071998** [comment]
Guys Guys Guys calm down, I opened the issue after I opened a pull request you can see #11607. The purpose of opening the issue is to get attention of maintainers to review the pull request

**Comment by onhgomat** [comment]
Sorry sir I want to contribute to this issue
