### ISSUE TITLE
Faster matrix multiplication for square matrices

### ISSUE THREAD

**Issue by dragoFireup** [TheAlgorithms/Python#1176]
It is not exactly an issue but sort of like a proposal. In matrix multiplication wouldn't it be better if Strassen's Method is applied only for square matrices for faster matrix multiplication? If it seems like a good idea I would like to work on it.

**Comment by cclauss** [comment]
I am a huge believer in benchmarks.  Would you be willing to set up some side-by-side comparisons with https://docs.python.org/3/library/timeit.html or similar?  Also compare against the builtin @ operator https://www.python.org/dev/peps/pep-0465/

**Comment by dragoFireup** [comment]
Hey! Sorry for the late reply.
I wrote the code for Strassen's Algorithm. There are some things I would like to mention.
1) It works only on matrices of the size of power of 2 as in every function call the size gets reduced to half.
2) By Master's method, its time complexity is O(N^2.8) (For some reason it ain't working very fast on my computer). But I would still say that it is a really good algorithm for the divide and conquer method and If it is fine with you I would like to submit a PR for it.

**Comment by HarsheetKakar** [comment]
strassen's algorithm is frowned upon for some reasons
1. it takes up a lot of call stack memory
2. its constants are very big, it is fast only on paper
3. it takes a lot of time to code

and u dont need it to be in 2's powers it can be anything, you can just convert it into a suitable matrix by introducing null values in rest of the structure

**Comment by dragoFireup** [comment]
Thanks @HarsheetKakar for clearing some things. I didn't think of padding the matrix to suit the requirements.
So, I guess that Strassen's is not good enough and rather not use it. I'll close this issue now.
