### ISSUE TITLE
want to add Depth First Search and Breadth First Search

### ISSUE THREAD

**Issue by EfrataAron** [TheAlgorithms/Python#11793]
### Feature description

Depth First Search and Breadth First Search algorithms.

**Comment by AHuzail** [comment]
if not completed, I would like to work on this.

**Comment by EfrataAron** [comment]
Actually, I started on it and its almost done.  Sent from Mail for Windows From: Ahmad Huzail KhanSent: Sunday, 6 October 2024 00:49To: TheAlgorithms/PythonCc: Efrata Aron; AuthorSubject: Re: [TheAlgorithms/Python] want to add Depth First Search and Breadth First Search (Issue #11793) if not completed, I would like to work on this.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by simin75simin** [comment]
I believe you shouldn't open an issue to contribute an algorithm. Please read the docs [here](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#:~:text=Do%20not%20create%20an%20issue%20to%20contribute%20an%20algorithm.%20Please%20submit%20a%20pull%20request%20instead.)

**Comment by EfrataAron** [comment]
okay.
