### ISSUE TITLE
Add Dijkstra's shortest path algorithm in the graph section 

### ISSUE THREAD

**Issue by shivam-tripathi** [TheAlgorithms/Python#118]
Being one of the most common algorithm in the Graph set, it should be implemented.

**Comment by shivam-tripathi** [comment]
I would like to take it up, if no one else is looking into it :)

**Comment by sachinarora707** [comment]
Yes. Go ahead,

**Comment by shivam-tripathi** [comment]
@sachinarora707 Thank you :) Will start work on it!

**Comment by SteadBytes** [comment]
@shivam-tripathi Hey, are you still working on this? If not I'd like to give it a go :) Thanks!

**Comment by shivam-tripathi** [comment]
I think the [commit](https://github.com/TheAlgorithms/Python/commit/4d4b0ff31a88d13e42021687b8a0cd3e5db09d78) solves this, we can close this issue.
