### ISSUE TITLE
Reversort is missing 

### ISSUE THREAD

**Issue by Dhineshkumarprakasam** [TheAlgorithms/Python#11800]
### Feature description

 I noticed that the repository includes a variety of sorting algorithms, but it currently does not have an implementation for a Reverse Selection Sort Algorithm, where subarrays are reversed to progressively sort the array. This is a unique variation of the traditional selection sort algorithm and can be an interesting addition to the collection.

**Comment by vikassahu1** [comment]
Kindly assign me this work under hacktoberfest label.

**Comment by Nandinig24** [comment]
Please assign the task to me
