### ISSUE TITLE
Adding Matrix Exponentiation

### ISSUE THREAD

**Issue by anirudnits** [TheAlgorithms/Python#1180]
I was just browsing through  the algorithms and data structures but couldn't find Matrix Exponentiation, which is useful for solving linear recurrences in logarithmic time. So, is this something you guys think should be added? If yes then I can work on it and submit a PR. Thanks

**Comment by cclauss** [comment]
👍 Go for it!

**Comment by anirudnits** [comment]
sure

**Comment by cclauss** [comment]
Please show us side-by-sige benchmarks (using [timeit](https://docs.python.org/3.7/library/timeit.html) or similar) of the two methods running on the same square matrices so we can see the performance.

**Comment by anirudnits** [comment]
Initially I thought of using the simple problem of finding the nth element of fibonacci series in O(logn) using Matrix Exponentiation as the base example to use because this is the most common problem in competitive programing sites to introduce matrix exponentiation. So, do you think this problem is enough or do I go for some more general linear recurrence?

**Comment by anirudnits** [comment]
Initially I thought of using the simple problem of finding the nth element of fibonacci series in O(logn) using Matrix Exponentiation as the base example to use because this is the most common problem in competitive programing sites to introduce matrix exponentiation. So, do you think this problem is enough or do I go for some more general linear recurrence?

**Comment by anirudnits** [comment]
@cclauss I used the example of finding the nth element in the Fibonacci series in O(logn) to demonstrate Matrix Exponentiation. For performance evaluation, I compared the simple linear method of finding the nth element with the same using Matrix Exponentiation for random numbers in range of 10**4. Is anything else you would like me to add? otherwise I will submit the PR. Thanks

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/issues/1180#issuecomment-531466471

**Comment by anirudnits** [comment]
Submitted the PR, please have a look.
