### ISSUE TITLE
2 Graph folders

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/Python#119]
There are 2 separate folder of Graph
1. Graph
2. Data Structures - > Graph

Merge them and keep the second one

**Comment by CaptainAshis** [comment]
Hi Anup ,May be I'm asking a really stupid question but I have a doubt . You want this folder thing to be done in github right ? Or is it in some location in your computer drive . Just wanted some clarification .

**Comment by dynamitechetan** [comment]
in the python repository, there is a graph folder and another folder called Data Structures - > Graph. 
You need to merge them. 
Clone this repo move the content of the folders and send a PR.

**Comment by iharsh234** [comment]
@AnupKumarPanwar  #120 is merged, can you please close this :)

**Comment by AnupKumarPanwar** [comment]
The "data_structures/Graph/" still not properly merged.
There are 2 copies of same algo :-

Breadth_First_Search.py
Deep_First_Search.py

P01_BreadthFirstSearch.py
P02_DepthFirstSearch.py

**Comment by iharsh234** [comment]
@AnupKumarPanwar  so do we suppose to delete both?
```
P01_BreadthFirstSearch.py
P02_DepthFirstSearch.py
```

**Comment by shivam-tripathi** [comment]
As the folder have been merged, I think this issue can be closed now. Any comments?

**Comment by lierluis** [comment]
It seems like `Breadth_First_Search.py` and `Deep_First_Search.py` have some syntax issues.
`P01_BreadthFirstSearch.py` and `P02_DepthFirstSearch.py` can run and are documented.
Which two should be deleted? How would you like these programs to be merged?
