### ISSUE TITLE
Feature adding : Enhancement 

### ISSUE THREAD

**Issue by soniya-malviy** [TheAlgorithms/Python#12002]
### Feature description

Currently website is looking simple to enhance user experience i want enhance styling and add my contribution for better experience.
Please assign me this issue i want to contribute.

**Comment by tianyizheng02** [comment]
This repo does not maintain the website for The Algorithms. If you want to contribute to the website, please refer to the repo for the website and be more specific to the maintainers there about what changes you'd like to propose.
