### ISSUE TITLE
Kruskal's Algo in Graphs Folder

### ISSUE THREAD

**Issue by vaishvi2811** [TheAlgorithms/Python#12020]
### Feature description

The repository's Graph folder can be expanded to include popular greedy graph algorithm, Kruskal's Algorithm. 
I'm participating in Hacktober fest, please assign this to me.

**Comment by Smriti-Prajapati** [comment]
Hey I am participating in Hactoferbest , could you please assign this issue to me.

**Comment by Smriti-Prajapati** [comment]
I updated the code , check it and if it's correct , please merge it so that
my tasks can be completed.

**Comment by tianyizheng02** [comment]
We already have multiple implementations of Kruskal's algorithm: https://github.com/search?q=repo%3ATheAlgorithms%2FPython%20kruskal&type=code

Also, please do not create issues to propose new algorithms. This has already been said in our contributing guidelines, which you have hopefully already read:
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.

In this case, it's not a new algorithm, but in any case contributors should do their own due diligence to confirm that their proposed algorithms haven't already been implemented.
