### ISSUE TITLE
add quicksort under divide and conquer

### ISSUE THREAD

**Issue by OmMahajan29** [TheAlgorithms/Python#12046]
### Feature description

would like to add quicksort algo under divide and conquer

**Comment by riku-d** [comment]
can this be assigned to me

**Comment by tianyizheng02** [comment]
We already have multiple implementations of quick sort in this repo. We do not want duplicate implementations of existing algorithms. Furthermore, **_please read our contributing guidelines._** We do not assign issues in this repo, and contributors should not create issues to suggest new algorithms.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
>Do not create an issue to contribute an algorithm. Please submit a pull request instead.
