### ISSUE TITLE
python program car and boats classes 

### ISSUE THREAD

**Issue by NimraAslamkhan** [TheAlgorithms/Python#12115]
### Feature description

This problem involves creating two classes (Car and Boat) that return a formatted string based on the vehicle's speed. This solution includes the implementation of constructors and string representations.

**Comment by NimraAslamkhan** [comment]
I’m excited to request to be assigned  the issue for implementing the Car and Boat classes! 🚗⛵ With my Python expertise and strong grasp of object-oriented design, I’m confident I can deliver effective solutions.

**Comment by tianyizheng02** [comment]
Sorry, but I don't see how such an implementation suits our repo. While it serves as a demonstration of OOP, we wouldn't really consider it an "algorithm" as we've specified in our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
