### ISSUE TITLE
A request to add a palindrome checker 

### ISSUE THREAD

**Issue by sarveshsrinath** [TheAlgorithms/Python#12165]
### Feature description

# Palindrome Checker
A code specifically written to check if a phrase, word or an integer is a palindrome.
I have written this code using string slicing which returns a boolean value.

**Comment by tianyizheng02** [comment]
We already have multiple algorithm files that checks for palindromes, including an implementation that uses string slicing:
https://github.com/search?q=repo%3ATheAlgorithms%2FPython%20palindrome&type=code

We do not want duplicate algorithms, so please do the due diligence of checking the codebase for existing implementations before opening an issue.

Furthermore, we do not open issues for algorithm suggestions, nor do we assign issues. This was explicitly stated in the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md), which you should've already read:
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
