### ISSUE TITLE
Adding Kadane's algothirm to array in data_structures folder

### ISSUE THREAD

**Issue by Siddhart2004** [TheAlgorithms/Python#12224]
### Description
Kadane’s algorithm is a popular algorithm used to find the **maximum sum of a contiguous subarray** in an array with a time complexity of ``O(n)``. It efficiently handles both positive and negative numbers, making it an essential part of algorithmic problem-solving.
This algorithm can be a valuable addition to the project’s library under the **"array"** section, improving resources for learners and contributors.

I would like to work on this.

**Comment by tianyizheng02** [comment]
We already have an implementation of Kadane's algorithm in [`dynamic_programming/max_subarray_sum.py`](https://github.com/TheAlgorithms/Python/blob/b5c8fbf2e8254b53056b741aacce3842736ba177/dynamic_programming/max_subarray_sum.py). We do not want duplicate algorithms in our repo. If you wish to contribute an algorithm, please check the codebase first to see if it's already been implemented.

Furthermore, do not open issues to suggest algorithms, and do not ask to be assigned to an issue. This was made clear in our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md), which you should've already read:
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
