### ISSUE TITLE
[enhancement] : Introducing Gabow’s Algorithm (**GRAPH**) & Commentz-Walter Algorithm  (**STRING SEARCHING**)

### ISSUE THREAD

**Issue by Rudrajiii** [TheAlgorithms/Python#12297]
### Context

Hello @darkstar  @bit-man @spazm @horstjens and @Cjkjvfnby   I was going through some underrated algo's in this website and randomly searched about this 2 algorithms mentioned in title but it was not there :( so i thought i can help you by adding this 2 interesting algo's , Here is the brief about this 2 algorithm 

## Gabow’s Algorithm :
**To find all the strongly connected components in a directed graph with a time complexity of 
O(V+E). Used in circuit analysis and dependency resolution.**

## Commentz-Walter Algorithm :
**This is basically a multi-pattern matching algorithm that combines the `Aho-Corasick` and `Boyer-Moore` algorithms. It’s effective when searching for multiple patterns in a text and Used in network intrusion detection and anti-virus software.**

**Comment by Param1304** [comment]
Can I take this issue ?
