### ISSUE TITLE
Warning sign after completing installation of all the requirements

### ISSUE THREAD

**Issue by kangaroo-eating-carrots** [TheAlgorithms/Python#12346]
### What would you like to share?

Python version: Python 3.11.5

Hi, I would like to raise an issue which is related to the warning sign after installing all the requirements. 

I see the warning sign while I have installed them. 
![warning](https://github.com/user-attachments/assets/9b4b34cb-3525-4f34-8606-5b99aec077d9)

Please refer to the below images which shows the installation of the packages.
![fake-useragent](https://github.com/user-attachments/assets/4728afdd-f5d6-4449-800e-6629c199f6d5)
![sphinx-pyproject](https://github.com/user-attachments/assets/faeb0977-be4e-4727-ac4e-0001313cc8a7)

The problems are fixed when changing the names.
- from fake_useragent to fake-useragent
- from sphinx_pyproject to sphinx-pyproject

However, before making a PR, I would like to check whether this problem is from the setting of my PC or the problem can arise in other PCs.

Thank you for reviewing the issue in advance.

**Comment by 27371123** [comment]
Software Installation Context
 
- Missing Dependencies Warning:
- Description: Even if you think you've installed all the stated requirements, sometimes there could be additional hidden or secondary dependencies that weren't accounted for. For example, a program might require a specific version of a graphics library that wasn't properly installed along with the main components. You might see an error message like "ModuleNotFoundError: No module named 'xyz'" where 'xyz' is one of those missing dependencies.
- Solution: Check the software's documentation for a list of all possible dependencies and make sure they are installed in the correct versions. You can often use package managers (like pip for Python, apt-get for Debian-based Linux systems, etc.) to install the missing ones.
- Configuration File Warning:
- Description: The software might rely on a properly configured settings file. If the installation process didn't set up the default configuration correctly or if it can't find the configuration file in the expected location, you could get a warning like "Configuration file not found. Using default settings which may not be optimal." For instance, a web server application might need certain settings about ports, IP addresses, and access permissions in its configuration file.
- Solution: Locate the sample configuration file provided by the software (usually in the installation directory or available on the official website). Edit it according to your needs and place it in the correct location where the software expects to find it.
-

**Comment by sanks011** [comment]
@kangaroo-eating-carrots Please take a look at the merge request
