### ISSUE TITLE
Update CONTRIBUTING.md Regarding Validate filenames Fail

### ISSUE THREAD

**Issue by kangaroo-eating-carrots** [TheAlgorithms/Python#12352]
### Feature description

I believe it will be helpful if a solution is updated regarding the test failure of Validate files names which the project participants who are using Windows may experience when trying to commit. 

![image](https://github.com/user-attachments/assets/3e5d622b-659a-4bf0-83bb-b44b66e2cded)

There was an issue regarding this problem (#8736), I easily fixed it with the comment from jlhuhn (using 'mklink' command).
 
![image](https://github.com/user-attachments/assets/f8cc7cf8-2532-4883-a271-a56c92a7f414)

I appreciated his comment, but it believe it will be much better **if the solution is added to CONTRIBUTING.md in 'Pre-commit plugin' section** as participants can notice this problem after using 'pre-commit run --all-files --show-diff-on-failure'.

Thank you.

**Comment by edlerd** [comment]
I will send a PR for this shortly.

**Comment by kangaroo-eating-carrots** [comment]
This issue is resolved by #12371
