### ISSUE TITLE
500: INTERNAL_SERVER_ERROR While opening Python algorithms in The Algorithms Website

### ISSUE THREAD

**Issue by D-ENCODER** [TheAlgorithms/Python#12381]
### What would you like to share?

![image](https://github.com/user-attachments/assets/4d75a8d8-c581-470c-9e8d-24b2d8ec56cb)

I am facing this issue since a week or so. Please do the needful.

**Comment by tianyizheng02** [comment]
This GH repo is only responsible for maintaining the Python algorithms themselves, not the website for The Algorithms. I'd like to redirect you to the repo https://github.com/TheAlgorithms/website instead, I believe they'd be more likely to be able to handle your issue.
