### ISSUE TITLE
[Fix] Remove inaccessible URL in computer_vision/README.md Line 11

### ISSUE THREAD

**Issue by setbit123** [TheAlgorithms/Python#12382]
### Repository commit

10aa789c3e4531558526e2e964673d537a09e249

### Python version (python --version)

not important

### Dependencies version (pip freeze)

not important

### Expected behavior

Remove inaccessible URL.

### Actual behavior

There is a inaccessible URL in line 11.

**Comment by setbit123** [comment]
Additionally, I have attempted to search for the article using a similar title in DataRobot but did not retrieve any information, therefore, I personally believe that it would be more feasible to delete this URL instead of modifying it.

**Comment by setbit123** [comment]
@TheAlgorithms/python_maintainers You reviews, please.

**Comment by 27371123** [comment]
To remove an inaccessible URL on line 11 of the computer_vision/README.md file, you'll need to follow these general steps depending on your operating system and the text editor you're using:
Windows
Open the computer_vision folder in File Explorer.
Right-click on the README.md file and select "Open with" and then choose a text editor like Notepad++, Visual Studio Code, etc. (If Notepad++ is not installed, you may need to download and install it first).
In the text editor, navigate to line 11.
Delete the entire URL text on that line. Make sure you only remove the URL and not any other relevant text that might be around it and is still needed.
Once you've made the deletion, go to the "File" menu in the text editor and select "Save" to save the changes to the README.md file.
macOS
Open the Terminal application.
Navigate to the directory where the computer_vision folder is located using commands like cd. For example, if the folder is on your Desktop, you might type cd ~/Desktop/computer_vision.
Once in the correct directory, type open README.md which will open the file in the default text editor (usually TextEdit). If you prefer to use another text editor like Visual Studio Code, you can install it and then type the appropriate command to open the file in that editor (e.g., code README.md if you have VS Code installed and added to your path).
In the text editor, find line 11 and delete the URL.
Save the file. In TextEdit, you can go to the "File" menu and select "Save". In other text editors like VS Code, you can use the shortcut like Command + S (on macOS) to save the changes.

**Comment by setbit123** [comment]
I have completed this task and submitted a PR, but it has been a long time since anyone has responded to that PR.

#12383
