### ISSUE TITLE
strings/split.py is incorrect

### ISSUE THREAD

**Issue by Kaaserne** [TheAlgorithms/Python#12403]
### Repository commit

9316e7c0147a84b9b549094a5b8c70f95a0cd3a1

### Python version (python --version)

n/a

### Dependencies version (pip freeze)

n/a

### Expected behavior

```python
s = ";abbb;;c;"
split(s, ';') == s.split(';')
# ['', 'abbb', '', 'c', ''] == ['', 'abbb', '', 'c', '']
```

### Actual behavior

```python
s = ";abbb;;c;"
split(s, ';') == s.split(';')
# ['', 'abbb', '', 'c'] != ['', 'abbb', '', 'c', '']
```

**Comment by sanks011** [comment]
@Kaaserne Please take a look at the merge requests

**Comment by Kaaserne** [comment]
Looks good
