### ISSUE TITLE
https://the-algorithms.com/language/python throwing Code: INTERNAL_UNEXPECTED_ERROR

### ISSUE THREAD

**Issue by gopalmani** [TheAlgorithms/Python#12475]
### Repository commit

N/A

### Python version (python --version)

N/A

### Dependencies version (pip freeze)

N/A

### Expected behavior

Webpage should open for algorithms implemented in python.

### Actual behavior

curl : 
`curl 'https://the-algorithms.com/language/python' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8' \
  -H 'accept-language: en-GB,en;q=0.8' \
  -H 'cache-control: max-age=0' \
  -H 'priority: u=0, i' \
  -H 'referer: https://the-algorithms.com/' \
  -H 'sec-ch-ua: "Brave";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-user: ?1' \
  -H 'sec-gpc: 1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'`
  Throwing 500 error, Trace ID : bom1::pgk7b-1735242843075-a7af390d0c66

**Comment by tianyizheng02** [comment]
I'm experiencing the 500 error as well. Unfortunately, this GH repo is only responsible for maintaining the Python algorithms themselves, not the website for The Algorithms. I'd like to redirect you to the repo https://github.com/TheAlgorithms/website instead, I believe they'd be more likely to be able to handle the issue.
