### ISSUE TITLE
No successful Travis builds in the last 3 months

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#125]
https://travis-ci.org/TheAlgorithms/Python/builds

**Comment by shabbir4791** [comment]
I would like to take this up

**Comment by cclauss** [comment]
@harshildarji Instead of removing .travis.yml (as has been done), can we put it back and fix the errors?  I and (I believe) @shabbir4791 would be willing to work on this.

**Comment by harshildarji** [comment]
@shabbir4791 @cclauss I am sure things are in place now. I am working on errors that are causing builds to fail.

**Comment by cclauss** [comment]
Unfortunately [flake8](http://flake8.readthedocs.io) tests currently fail on both Python 2 and Python 3:
---
flake8 testing of https://github.com/TheAlgorithms/Python on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./data_structures/LinkedList/singly_LinkedList.py:14:13: F821 undefined name 'insert_tail'
            insert_tail(Head.next, data)
            ^
./data_structures/Trie/Trie.py:15:32: E999 SyntaxError: invalid syntax
    def insert_many(self, words: [str]):
                               ^
./dynamic_programming/fastfibonacci.py:10:16: E999 SyntaxError: invalid syntax
def fibonacci(n: int):
               ^
2     E999 SyntaxError: invalid syntax
1     F821 undefined name 'insert_tail'
```
--
flake8 testing of https://github.com/TheAlgorithms/Python on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./File_Transfer_Protocol/ftp_client_server.py:11:28: E999 SyntaxError: invalid syntax
print 'Server listening....'
                           ^
./Project Euler/Problem 29/solution.py:30:28: E999 SyntaxError: invalid syntax
    print "Number of terms ", len(collectPowers)
                           ^
./data_structures/LinkedList/singly_LinkedList.py:14:13: F821 undefined name 'insert_tail'
            insert_tail(Head.next, data)
            ^
./dynamic_programming/abbreviation.py:29:14: E999 SyntaxError: invalid syntax
    print abbr("daBcd", "ABC") # expect True
             ^
./machine_learning/scoring_functions.py:73:13: E999 SyntaxError: invalid syntax
    print str(numerator)
            ^
4     E999 SyntaxError: invalid syntax
1     F821 undefined name 'insert_tail'
```

**Comment by cclauss** [comment]
[flake8](http://flake8.readthedocs.io) tests with --select=E901,E999,F821,F822,F823 currently pass on both Python 2 and Python 3!!  Nice work.
