### ISSUE TITLE
add python program that surfs the web.

### ISSUE THREAD

**Issue by archu5** [TheAlgorithms/Python#1317]

**Comment by Kunal614** [comment]
It is showing merging is block

**Comment by cclauss** [comment]
Travis CI tests need to be passing.  See CONTRIBUTING.md for details.

**Comment by Kunal614** [comment]
didn't get , can you help.

**Comment by mohanish2504** [comment]
Hi,

I am a beginner in open source contribution, I will like to contribute! please consider the following reply.
There are 3 Libraries in python already which can help in surfing the web:
 1.Selenium Web Driver
 2.Scrappy
 3.Beautiful soup
It will still great if you can provide some explanations on kind of surfing you want to perform.

**Comment by onlinejudge95** [comment]
@mohanish2504 we currently have some `web crawling` programs in [web_programming](https://github.com/TheAlgorithms/Python/tree/master/web_programming) directory.

If you are interested, do check them and raise a PR if you want to add any new program or propose a new feature in the currently listed ones.

For more information about how to contribute to this repo please read the [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md)
