### ISSUE TITLE
Need to update README.md of project_euler

### ISSUE THREAD

**Issue by aritrartira** [TheAlgorithms/Python#1340]
The README.md of project_euler hasn't been updated it seems. The problem statements for most problems haven't been provided.

**Comment by cozek** [comment]
Perhaps you can help by updating it.
I don't think its autogenerated.

**Comment by aritrartira** [comment]
I’d be glad to, as soon as I have time on my hands.

**Comment by kshivi99** [comment]
@aritrartira I will do it. Maybe by evening today.

**Comment by cclauss** [comment]
Is there some external page that we can link out to that is to canonical source of problem descriptions.  It seems like a lot of busy-work could be eliminated that way.

**Comment by kshivi99** [comment]
Hi @cclauss here is the description of all 650+ problems in Eular in a single page.

[https://projecteuler.net/show=all](url)

**Comment by kshivi99** [comment]
I think we should remove all the problem descriptions from readme and just put this link over there.
Would look cleaner.

**Comment by cclauss** [comment]
Awesome.  Agreed.  Can you please create a pull request for that?

**Comment by kshivi99** [comment]
will do..

**Comment by kshivi99** [comment]
@cclauss created the pull request. Let me know if its sufficient :)
