### ISSUE TITLE
Is Recursion Example included in Bactracking and Dynamic Programming?

### ISSUE THREAD

**Issue by Prathamesh404** [TheAlgorithms/Python#1357]
Is there a need of creating a new folder with Recursion labelled.

**Comment by edoardottt** [comment]
Right. :)

**Comment by onlinejudge95** [comment]
`master` branch contains a recursive implementation of [minimax](https://github.com/TheAlgorithms/Python/blob/master/backtracking/minimax.py) in **backtracking** directory.

If you feel like implementing a recursive version of other problems in **backtracking** or **dynamic_programming** directory, i suggest you create a sub-directory named **recursive** within the above mentioned directories and move the iterative versions in a sub directory named **iterative**

@harshildarji , @cclauss what are your views about the same?

**Comment by cclauss** [comment]
I am not a fan of a top level directory for recursion.  I would suggest that you use the existing directory structure and if you must, use the filename (like xyz_recursion.py) to highlight the use of this programming technique.

**Comment by cclauss** [comment]
I am also, not a fan of nesting of directories.  Users spend too much time digging and that leaves less time for reading/using.
