### ISSUE TITLE
Give more details about Problem Statement.

### ISSUE THREAD

**Issue by sanjaypradeep** [TheAlgorithms/Python#1365]
https://github.com/TheAlgorithms/Python/blob/b190c8f629d1fb8371fb9ea434d986a843b2ecab/data_structures/stacks/next_greater_element.py#L1

**Comment by jai-dewani** [comment]
Please look at this PR and let me know if any more changes are required.

**Comment by sanjaypradeep** [comment]
Hi @jai-dewani Thanks for your reply, if you see the PR, I can understand this is a kinda puzzle you solved. Much appreciated, but the other way, Adding one or two lines of explaining about the puzzle really helps in people who visit the code.

**Comment by jai-dewani** [comment]
I am sorry but I haven't added this piece of code, I just saw the code and understood what the problem statement might have been and explained the same with the 1 line comment already present in it, the problem statement is pretty obvious. I don't know if this was a part of a puzzle
