### ISSUE TITLE
decimal_to_octal return

### ISSUE THREAD

**Issue by afeiguo** [TheAlgorithms/Python#1368]
the return code is wrong for big number, e.g.:

`print("{0:g}".format(float(1000000001.0)))`

the return is **1e+09**, not **'1000000001'**

**Comment by afeiguo** [comment]
> the return code is wrong for big number, e.g.:
> 
> print("{0:g}".format(float(1000000001.0)))
> 
> the return is 1e+09, not '1000000001'

coding should change:   return "{0:g}".format(float(octal))           =>
                return  str(int(octal))

**Comment by blaxii** [comment]
You know you could justt do 
`def decimal_to_octal(num):
    """Convert a Decimal Number to an Octal Number."""
    calcul = ""
    while num > 0:
        reste = num % 8
        num = num // 8
        calcul = str(reste) + calcul
    return int(calcul)`

**Comment by blaxii** [comment]
If you want you can do:

> def decimal_to_octal(num):

    """Convert a Decimal Number to an Octal Number."""
    calcul = ""
    while num > 0:
        rest = num % 8
        num = num // 8
        calcul = str(rest) + calcul
    return int(calcul)

As I see your code is too complex for the program you want to do.

**Comment by cclauss** [comment]
num, rest = divmod(num, 8)

**Comment by onlinejudge95** [comment]
The issue has been fixed here https://github.com/TheAlgorithms/Python/pull/1482. Hence closing the issue.
