### ISSUE TITLE
Long-short term memory

### ISSUE THREAD

**Issue by saskakarsi** [TheAlgorithms/Python#1380]
Hey everyone,

I'd like to look into implementing LSTM in this library, so probably in the neural_network directory. I've got a [repo](https://github.com/saskakarsi/lstm) I'd like to use as a base, and it's under the same license - does anyone how this works? Should I include my little copyright in there since the MIT license says it needs to be present (the other stuff required is already found in the license of TheAlgorithms/Python)? (EDIT: I.e. can I do a new version that's free of my copyright or is self-plagiarism still plagiarism or how does this stuff actually work?)

Does this make sense? Other than implementing a properly working gradient checker and refactoring my code to a single file to comply with the folder structure, is there anything I need to do? Where should I add my tests (I see some of the other folders already have a tests directory, should neural networks have one as well)? I also have some pre-written explanatory stuff for it (Algorithms-Explanation), although I definitely don't think I can calculate the time complexity of this thing...

**Comment by onlinejudge95** [comment]
HI @saskakarsi,

`if PR.is_not_raised():`
Have a look at [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) as a checklist. 
As of now, there is support for `doctest`, though I am unable to find any file under `neural_network` dir to pass along as a starting example.
