### ISSUE TITLE
Wrong name for a vector class method

### ISSUE THREAD

**Issue by tirthajyoti** [TheAlgorithms/Python#1388]
A method of the `Vector` class is wrongly named, perhaps.

[Here is the code.](https://github.com/TheAlgorithms/Python/blob/master/linear_algebra/src/lib.py#L91)

Should be euclidLength instead of eulidLength. The **'c'** is missing.

**Comment by cclauss** [comment]
I agree.

**Comment by Iqrar99** [comment]
fixed on my PR here #1392 @tirthajyoti @cclauss
