### ISSUE TITLE
`Head` and `temp` names should change

### ISSUE THREAD

**Issue by tirthajyoti** [TheAlgorithms/Python#1397]
Hi,

In your [Linked List implementation](https://github.com/TheAlgorithms/Python/blob/master/data_structures/linked_list/singly_linked_list.py), I think `temp` is wrongly spelled as `tamp`. The code works but for readability purpose all `tamp` should be replaced by `temp`.

Also, I find it strange to name the `head` with a capital `Head`. Generally, capitalization in Python is saved for Class names, not class attributes or methods. If you think the code should be more *Pythonic*, please consider changing all `Head` to `head` in the class attributes for Linked List.

**Comment by cclauss** [comment]
Agreed.  Can you please submit a pull request that fixes these issues and adds doctests?
