### ISSUE TITLE
Longest Increasing Subsequence - in O(NlogN) #DynamicProgramming  

### ISSUE THREAD

**Issue by aravindiiitb** [TheAlgorithms/Python#145]
I would like to add Dynamic programming code for LIS with complexity of O(NlogN)

**Comment by PrajwalRavi** [comment]
Hey, I would like to work on this. Please confirm.

**Comment by aravindiiitb** [comment]
Hi Prajwal,

Appreciate your interest in adding O(nlogn) method for LIS.

But I've already implemented it and sent a pull request to the owner. 

Thanks,
Aravind
