### ISSUE TITLE
DIRECTORY.md not being updated by TravisCI

### ISSUE THREAD

**Issue by chttrjeankr** [TheAlgorithms/Python#1460]
- [x] .travis.yml isn't updating DIRECTORY.md automatically as it should
- [x] scripts/build_directory_md.py needs can have some minor changes too.  #1461

**Comment by cclauss** [comment]
If you can make Travis CI write back to the incomming pull request, that would be cool.  Writing back to `master` might put Travis into an infinite loop.  @jneeven is doing some magic in lgeiger/black-action#2 but that is based on GitHub Actions, not Travis CI.

**Comment by mrvnmchm** [comment]
A fix for the DIRECTORY.md, can't get Travis CI to push back to the initiating PR. #1542

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/.github/workflows/autoblack.yml Is writing changes back to a PR.  GitHub Actions Beta ends in two weeks and then it will go live,

**Comment by mrvnmchm** [comment]
Nice! That looks very close to the same changes I was making to the travis.yml. When the GH Actions is released I'll make the updates. Thanks @cclauss

**Comment by cclauss** [comment]
See if they will let you into the beta... https://github.com/features/actions

**Comment by poyea** [comment]
@cclauss @mrvnmchm GitHub Actions is now available for all public repositories.

**Comment by cclauss** [comment]
#1569

**Comment by mrvnmchm** [comment]
Should I make any changes to #1549, or do I just need another peer review?

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/pull/1570/checks?check_run_id=303560970#step:4:550

**Comment by cclauss** [comment]
Writing back to a PR is NOT allowed in GitHub Actions.  See the other workflow to see how to use __push__ instead.

**Comment by chttrjeankr** [comment]
Can this issue now be considered resolved then?

**Comment by cclauss** [comment]
This should remain open until #1572 lands.
