### ISSUE TITLE
Keyword Cyphers can be added

### ISSUE THREAD

**Issue by arjun1299** [TheAlgorithms/Python#1492]
Cyphers like 
- [x] Porta Cypher #1550 
- [x] Simple Keyword
- [ ] Transpose cypher
- [x] Mixed Keyword Cypher #1492

can be added to cyphers

**Comment by trendhometex** [comment]
i had the same `<a href="https://trendhometex.com/">issue </a>`

**Comment by onlinejudge95** [comment]
2 items from this issue are pending, what are our thoughts about the same?
Are we implementing them? If not let's close this issue since the PR has already been merged
