### ISSUE TITLE
Implementing Circular Linked List

### ISSUE THREAD

**Issue by onlinejudge95** [TheAlgorithms/Python#1579]
I was going through this repository and found out that most of the **Data Structures** are still there but there was no implementation of a **Circular Linked List**. I wrote an implementation for the same while studying DS and would like to add it to this repo. There are many applications of a **Circular Linked List** namely

1. Managing computer resources.
2. A slight variation (*Doubly Circular Linked List*) is used in an advanced Data Structure namely **Fibonacci Heap**, which can be used for **Priority Queue** implementation.

I will raise a PR for the same.

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/data_structures/queue/circular_queue.py submitted by @Himan10 would be a good model to follow for type hints and doctests which are also discusses in CONTRIBUTING.md.

**Comment by onlinejudge95** [comment]
@cclauss can you add me to the contributed list so that I can do a merge across branch rather than a merge across forks

**Comment by onlinejudge95** [comment]
This is safe to close
