### ISSUE TITLE
Open LGTM alerts

### ISSUE THREAD

**Issue by onlinejudge95** [TheAlgorithms/Python#1586]
As of now, LGTM analysis has the following counts
```
2 Errors
9 Warnings
10 Recommendations
```
Is there any plan to lower the count as much as possible because I can see certain issues that can be solved. Moreover, can we have a strict policy for any incoming changes to make sure that the LGTM dashboard stays as clean as possible?
Willing to contribute to this effort.

**Comment by cclauss** [comment]
I think we should shut off LGTM.  It has tons of false reports and is super slow!!

**Comment by onlinejudge95** [comment]
+1 on super-slow.

We can use certain other python tools for code quality if you want, namely
- `pylint`
- `vulture`
etc.

**Comment by cclauss** [comment]
I know them well... My sense is we are linting enough already.  Where we need to focus is on accepting or rejecting our PRs and clearing our issues.

**Comment by onlinejudge95** [comment]
Anyways I can help you guys in clearing your issues, and PRs
