### ISSUE TITLE
Add Linear Discriminant Analysis

### ISSUE THREAD

**Issue by EverLookNeverSee** [TheAlgorithms/Python#1591]
Hi 
I would like to add linear discriminant analysis algorithm (implement from scratch) into machine learning directory.

**Comment by cclauss** [comment]
Go for it.

**Comment by cclauss** [comment]
A GitHub trick for pull requests that fix issues... If you put the text __Fixes #1592__ in the commit message of the pull request then when the PR gets merged, GitHub will autoclose the issue.
