### ISSUE TITLE
Type Error in linear_discriminant_analysis.py

### ISSUE THREAD

**Issue by EverLookNeverSee** [TheAlgorithms/Python#1601]
There is a type error in this following code:
`pre_indexes = predict_y_values(x, actual_means, variance, probabilities)`
the 'probabilities' parameter must be a list object , but is a generator object.
generated error is as follows:
`TypeError: 'generator' object is not subscriptable`

**Comment by cclauss** [comment]
My bad.  Sorry about that.

**Comment by EverLookNeverSee** [comment]
no problem
@cclauss

**Comment by cclauss** [comment]
Now you know why I love to see [__doctests__](https://docs.python.org/3/library/doctest.html).  It would be great to see __linear_discriminant_analysis.py__ in our test list
https://travis-ci.com/TheAlgorithms/Python/builds/138595890#L429

**Comment by EverLookNeverSee** [comment]
@cclauss , I will do it as soon as possible
