### ISSUE TITLE
Implementing async functionality from scratch

### ISSUE THREAD

**Issue by onlinejudge95** [TheAlgorithms/Python#1604]
I had a chance to attend PyCon India 2019 where David Beazley, gave a [workshop](https://www.youtube.com/watch?v=Y4Gt3Xjd7G8) on the same topic. Since the topic is not of my own so I wanted to ask the community whether I can raise a PR for the same. The uber idea is to use Python's Standard Library to implement `async` functionality. It can have some variants also like using **Pub-Sub Pattern**. Do share your thoughts about the same.

**Comment by onlinejudge95** [comment]
Guys, any thoughts about the same

**Comment by cclauss** [comment]
We could create an __asyncio__ directory for algorithms built on top of Python's __asyncio__ module or that attempt to replicate that functionality from scratch.

**Comment by onlinejudge95** [comment]
Would be able to review a PR for the same

**Comment by onlinejudge95** [comment]
Hi Team, I would be working on this really soon. Had to deposit my previous system due to job change.
