### ISSUE TITLE
Adding tests directory into machine learning(using pytest)

### ISSUE THREAD

**Issue by EverLookNeverSee** [TheAlgorithms/Python#1607]
Hi @cclauss , I would like to write tests into linear_discriminant_analysis functions using doctest, but doctest have not enough options and features to do this correctly ; therefore i decided to use pytest instead. we need to add a tests directory and write tests into it.
what is your opinion?!

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/strings/rabin_karp.py uses a doctest to _bootstrap_ a normal unittest.  Will that technique work for your purposes?

**Comment by EverLookNeverSee** [comment]
I don't think so, one of the problems is that i can not handle multiple line generated list (expected output) in interpreter mode in docstring as follows :
for example:
`>>> gaussian_distribution(5, 1, 20)`

[6.288184753155463, 6.4494456086997705, 5.066335808938262, 4.235456349028368, 
 3.9078267848958586, 5.031334516831717, 3.977896829989127, 3.56317055489747, 
 5.199311976483754, 5.133374604658605, 5.546468300338232, 4.086029056264687, 
 5.005005283626573, 4.935258239627312, 3.494170998739258, 5.537997178661033, 
 5.320711100998849, 7.3891120432406865, 5.202969177309964, 4.855297691835079]

**Comment by cclauss** [comment]
__>>> gaussian_distribution(5, 1, 20)  # doctest: +NORMALIZE_WHITESPACE__

We already do this a lot...
https://github.com/TheAlgorithms/Python/search?q=NORMALIZE_WHITESPACE

**Comment by EverLookNeverSee** [comment]
I didn't know this option, Thank you very much.

**Comment by EverLookNeverSee** [comment]
When i wrote a doctest into <predict_y_values> function , i got print keyword output as expected value instead of function return value.
Should i remove line below from that function?
`print("Generated Discriminants: \n", results)`
I require your assistance, @cclauss
