### ISSUE TITLE
We are lacking some algorithms from simulations

### ISSUE THREAD

**Issue by Vasuji** [TheAlgorithms/Python#1613]
There are some interesting algorithms in simulation from Physics, Chemistry, and Engineering especially regarding Monte Carlo simulation: Heat Bath algorithm, Metro-Police algorithm, Markov Chain Monte Carlo, etc.

**Comment by onlinejudge95** [comment]
PR is always welcome :)
Do go through [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) before pushing your changes.

**Comment by rakadkh** [comment]
Hi 👋,
I would love to contribute to this session, can you give some advices or tips on how can I do such?

**Comment by rakadkh** [comment]
> There are some interesting algorithms in simulation from Physics, Chemistry, and Engineering especially regarding Monte Carlo simulation: Heat Bath algorithm, Metro-Police algorithm, Markov Chain Monte Carlo, etc.

Hi 👋,
I would love to contribute to this session, can you give some advices or tips on how can I do such?

**Comment by onlinejudge95** [comment]
@rakadkh here are some simple steps.

1. Fork this repo.
2. Before adding your code make sure you have gone through [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md)
2. Add your code.
3. Make sure your code is passing all checks provided in our [.travis.yml](https://github.com/TheAlgorithms/Python/blob/master/.travis.yml) file.
4. Once you have pushed your changes to your fork and are ready to merge, please raise a Pull Request.
5. Maintainers will provide additional review on your changes.
6. Once approved your PR will be merged to `master` and you can pat on your back 🤩

**Comment by FatAnorexic** [comment]
Time to write an algorithm or two.

**Comment by cschuerc** [comment]
I would like to contribute a Monte Carlo algorithm for the approximation of PI (see [here](https://www.geeksforgeeks.org/estimating-value-pi-using-monte-carlo/)). Of course, I would implement my own version. Is this okay?

**Comment by cclauss** [comment]
Go for it.  https://github.com/TheAlgorithms/Python/issues/1613#issuecomment-565829640

**Comment by naviji** [comment]
I'll make a program calculating the probability of a particular sum of the throw of two dice using simulation.

**Comment by naviji** [comment]
I made it.
https://github.com/TheAlgorithms/Python/pull/1759

**Comment by danmurphy1217** [comment]
> There are some interesting algorithms in simulation from Physics, Chemistry, and Engineering especially regarding Monte Carlo simulation: Heat Bath algorithm, Metro-Police algorithm, Markov Chain Monte Carlo, etc.

Hi Dibakar, I'm happy to help with the heat bath or Markov Chain algorithm  if it is still not done. Let me know!

**Comment by BokuAM** [comment]
This looks like an interesting field to work in.

**Comment by cclauss** [comment]
Changing the name of this issue because we now have [Monte Carlo](https://github.com/TheAlgorithms/Python/search?q=monte&unscoped_q=monte) algorithms but could use _other_ simulation algorithms.

**Comment by Aditya231** [comment]
> There are some interesting algorithms in simulation from Physics, Chemistry, and Engineering especially regarding Monte Carlo simulation: Heat Bath algorithm, Metro-Police algorithm, Markov Chain Monte Carlo, etc.
 
Show some

**Comment by bbowles98** [comment]
I was thinking of contributing a Monte Carlo algorithm to simulate the game of craps, would this be ok?

**Comment by cclauss** [comment]
Would the algorithm be different than the others that already exist?  https://github.com/TheAlgorithms/Python/issues/1613#issuecomment-605327601

**Comment by bbowles98** [comment]
The algorithm wouldn't be much different, just used under a different scenario than calculating pi. Are there any algorithms in particular you are looking for?

**Comment by Vasuji** [comment]
Thank you so much everybody for the great contributions.

**Comment by 8Dion8** [comment]
Would a simulation of a one-dimensional cellular automata that takes a ruleset as input and outputs the image of some number of generations from one single pixel be ok?
https://mathworld.wolfram.com/ElementaryCellularAutomaton.html

**Comment by cclauss** [comment]
@8Dion8 Please use https://github.com/TheAlgorithms/Python/tree/master/cellular_automata

**Comment by eclint** [comment]
Hello_good people, Please  i need help on submiting my cs50 psets. How to go about it will be appreciated .

**Comment by fabrizzioalco** [comment]
Which one is left to make it?

**Comment by ZadeAbhishek** [comment]
Any Algo left for to solve let me know ??

**Comment by ZadeAbhishek** [comment]
Any Algo left ?? to solve let me know .

**Comment by onlinejudge95** [comment]
> Hello_good people, Please i need help on submiting my cs50 psets. How to go about it will be appreciated .

@eclint this repo has no relation with CS:50, although you can use this as a source of algorithms, but please note that no one here is going to solve your homework
