### ISSUE TITLE
Implementing Simulated Annealing and Hill Climbing

### ISSUE THREAD

**Issue by fk03983** [TheAlgorithms/Python#1640]
Hello, 

I was looking through the algorithms, and could not find any optimization algorithm, can I go ahead and implement Simulated Annealing and Hill Climbing algorithms? I plan to do this for mathematical functions for now but with a general interface. 

Let me know what you guys think of this.

**Comment by cclauss** [comment]
Two separate algorithms in two separate pull requests?  I will be very interested to Re tans understand.  Please have doctests and type hints on all key functions as discussed in CONTRIBUTING.md.
