### ISSUE TITLE
32.48 * 100 = 3247.9999999999995 ????

### ISSUE THREAD

**Issue by Pengfei-Gao** [TheAlgorithms/Python#1644]
Are you kidding me?

![image](https://user-images.githubusercontent.com/16488309/71408971-ebabec80-267a-11ea-961e-e7f95fe970e6.png)

**Comment by cclauss** [comment]
https://docs.python.org/3/tutorial/floatingpoint.html

**Comment by Pengfei-Gao** [comment]
Even so, it's not scientific. Other programming languages don't have this problem. It's definitely a bug!!

**Comment by cclauss** [comment]
Please open an issue on https://github.com/python/cpython
