### ISSUE TITLE
Find The Possible Number of BST from Key.

### ISSUE THREAD

**Issue by MadyDixit** [TheAlgorithms/Python#1661]
Hey! Can we Add Function That Calculate the Number of Possible BST from Given Keys.

>> Function : noBST(n Key Value)
>> Return : x : Integer That is the number of total Possible Binary Search Tree.

Is it Interesting!?

**Comment by cclauss** [comment]
If it has doctests, type hints, black formatting (https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) then it would be good to review.

**Comment by MadyDixit** [comment]
Thank you!! Hope It will Helpful in Future!

**Comment by cclauss** [comment]
Try __python3 -m doctest -v your_version.py__ and __python3 -m doctest -v the_merged_version.py__ to see the doctests in action.
