### ISSUE TITLE
Hey!!! Adding Different Approach

### ISSUE THREAD

**Issue by MadyDixit** [TheAlgorithms/Python#1668]
Hi...
I have Saw your Dynamic Programming Directory in Your Repo, It is Quite Exciting:: But I want Contribute a Different Approach in Longest Common Sub Sequence using Dynamic Approach (Using **Top-Down Approach _(Memoization)_** Instead of the **Bottom UP Approach _(Tabulation)_**).

Hope! it is Quite Interesting::??

**Comment by cclauss** [comment]
The Capital Letters Drive Me A Bit NuTs!

Sure. I am ok with multiple implementations of the same algorithm under two conditions:
1. All implementations should be in the same file and tested against the same data.
2. There are [timeit](https://docs.python.org/3/library/timeit.html) (or similar) benchmarks to compare the performance of the implementations

Python has a memoization function:
https://docs.python.org/3.8/library/functools.html?highlight=lru#functools.lru_cache

**Comment by onlinejudge95** [comment]
I would like to see an implementation using Standard Library of Python as mentioned by @cclauss. I think it would help people understand how mature the library is.
