### ISSUE TITLE
Recursive insertion sort

### ISSUE THREAD

**Issue by shrabian** [TheAlgorithms/Python#1678]
Hey,

I'm new to github and thought this repo would be a good opportunity to get familiar and contribute a simple algorithm. I noticed the sorts folder is lacking a recursive implementation of the insertion sort. Is it OK if I add one?

**Comment by onlinejudge95** [comment]
By any means go ahead, Do have a look at CONTRIBUTING.md, and reach out in case of any further queries. happy coding :)

**Comment by amalujose25** [comment]
okay

**Comment by zcypython** [comment]
Hope you have a fun code:)

**Comment by shrabian** [comment]
Hey,
I've already implemented this algorithm and it has been merged into master. Sorry for not closing this sooner.
