### ISSUE TITLE
Update Pull Request Template

### ISSUE THREAD

**Issue by Kazaf123** [TheAlgorithms/Python#1681]
It is hard to understand the pull reuqest when I meet some pull requests that only have code, so I think updating a Pull Request Template will make them more readable. Such as:
######Description

######Check List

######My PR Type is:

Thank you!!

**Comment by onlinejudge95** [comment]
In the meanwhile, raise the PR. We can discuss about the requirements there.

**Comment by mihaimaruseac** [comment]
Seems to be spam
![VCA6DzWKgeZ](https://user-images.githubusercontent.com/323199/72463619-84202300-3788-11ea-9d4b-08ac8683f524.png)

**Comment by poyea** [comment]
It's unclear what you mean by "PR type". As long as one describes his/her PR, say is a code change or a doc change to a specific file, everyone would know and understand. I'd close this as this recommendation is not quite suitable here.
