### ISSUE TITLE
Providing additional algorithms

### ISSUE THREAD

**Issue by shrabian** [TheAlgorithms/Python#1688]
Hello,

I wanted to add my own implementation of an algorithm that approximates the length of a curve and one which approximates the area under a curve (where the curve is defined by a function).

If that's alright, could you also please indicate which folder I should push to.

Thanks!

**Comment by poyea** [comment]
You can put it under the `math/` directory. Thank you in advance! Feel free to reference this issue when you create the PR.

**Comment by cclauss** [comment]
Please read CONTRIBUTING.md _before_ contributing.  ;-)

**Comment by cclauss** [comment]
Closed in #1692
