### ISSUE TITLE
Augment Binary Search algorithm

### ISSUE THREAD

**Issue by cschuerc** [TheAlgorithms/Python#1703]
Binary search for an item is already implemented [here](https://github.com/TheAlgorithms/Python/blob/9eb50cc223f7a8da8d7299bf4db8e4d3313b8bff/searches/binary_search.py). I would like to augment it by a binary search to "find the first element in a sorted list that is >= a given item" as this is also a frequent task to do. I am interested in your opinion on this.

**Comment by Scopula** [comment]
I do agree that is it a useful variant of binary search.

bisect docs has some example of how to achieve this with the bisect module (see: find_le and find_ge).
https://docs.python.org/3/library/bisect.html

**Comment by cclauss** [comment]
Sounds useful.  Should we implement the full API of the bisect module?
```
bisect.bisect_left(a, x, lo=0, hi=len(a))
bisect.bisect_right(a, x, lo=0, hi=len(a))
bisect.bisect(a, x, lo=0, hi=len(a))
bisect.insort_left(a, x, lo=0, hi=len(a))
bisect.insort_right(a, x, lo=0, hi=len(a))
bisect.insort(a, x, lo=0, hi=len(a))
```
