### ISSUE TITLE
CPU Scheduling Algorithms

### ISSUE THREAD

**Issue by Ale3androsS** [TheAlgorithms/Python#1709]
Can I submit CPU Scheduling algorithms such as SJF, FCFS, Round-Robin etc.. in a new folder called 'cpu-scheduling'?

**Comment by cclauss** [comment]
Let's not limit to CPUs.  What about...
```
scheduling
    first_come_first_served.py
    round_robin.py
    shortest_job_first.py
    ...
```

**Comment by Ale3androsS** [comment]
I justs added the FCFS algorithm. If you have any changes in mind I would be glad to add them before accepting the PR.
