### ISSUE TITLE
Linking Issues with PRs

### ISSUE THREAD

**Issue by onlinejudge95** [TheAlgorithms/Python#1716]
How about linking an Issue to a PR wherever possible, so that both can be closed together i.e. we do not have zombie issues still open which have their PR merged or vice-versa?

**Comment by cclauss** [comment]
In the PRs, just put the text:
```
fixes: #9999999 
```
and GitHub will autoclave the issue when the PR is closed.

**Comment by onlinejudge95** [comment]
Exactly, i was hoping if we could enforce this in the **CONTRIBUTING.md**
