### ISSUE TITLE
Contribution of an algorithm FP-Graphminer 

### ISSUE THREAD

**Issue by siva1098** [TheAlgorithms/Python#1729]
I'd like to contribute under the topic graphs by adding new algorithm "FP-graphminer", an implementation of a research paper. 
It is a Frequent Pattern Graph Mining algorithm, that compactly represents a set of network graphs as a Frequent Pattern Graph (or FP-Graph). 
This graph can be used to efficiently mine frequent subgraphs including maximal frequent subgraphs and maximum common subgraphs.

Sample Application: clustering the customers based on the items purchased.

**Comment by cclauss** [comment]
Please use the filename `graph/frequent_pattern_graph_miner.py`

**Comment by siva1098** [comment]
can you please re-open this issue?
I'm working on this right now and I'm on my final stage of completion.
