### ISSUE TITLE
Fixing failing check in master

### ISSUE THREAD

**Issue by onlinejudge95** [TheAlgorithms/Python#1741]
Hi Team,

Our `master` branch is failing in pipeline. I am raising a PR for the same. I will list the file names that are failing the changes in the same issue.

**Comment by onlinejudge95** [comment]
@cclauss have we dropped support for `flake8`. I see it is pip installed in `codespell.yml` but it is not used in the same or any other GitHub action?

**Comment by cclauss** [comment]
I wonder if we should drop Travis CI and move all our tests to GitHub Actions.  Thoughts?

**Comment by onlinejudge95** [comment]
+1 for only GitHub Actions backed pipelines
