### ISSUE TITLE
LGTM Alert regarding hash and eq

### ISSUE THREAD

**Issue by onlinejudge95** [TheAlgorithms/Python#1743]
We currently have a [LGTM alert](https://lgtm.com/projects/g/TheAlgorithms/Python/snapshot/7ce05b0fc309fc5a35d637d707edafc2333c96e9/files/searches/hill_climbing.py?sort=name&dir=ASC&mode=heatmap#x2978473143457f06:1). The class defines a `__hash__` method without defining an `__eq__` method. 

According to Python [docs](https://docs.python.org/3/reference/datamodel.html#object.__hash__)

> If a class does not define an __eq__() method it should not define a __hash__() operation either; if it defines __eq__() but not __hash__(), its instances will not be usable as items in hashable collections.

Should we go ahead with a PR for the same?

**Comment by cclauss** [comment]
Is there documentation or an issue on the LGTM community that explains _why_ this rule exists.  I have never heard of it before.

**Comment by cclauss** [comment]
Yes.  Please submit a PR.

**Comment by onlinejudge95** [comment]
Also, I could see certain other issues that are legit.
Should I raise PR for similar types of issues clubbed together, rather than each going on a separate PR. What do you suggest?
