### ISSUE TITLE
Who gets the money that is donated to TheAlgorithms?

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#1747]

**Comment by poyea** [comment]
I guess it's the creator(s) who get it. I vote to close the sponsor option as the work here is a collaborative effort.

**Comment by cmgfz** [comment]
not only the collaborator but the creator(s).

**Comment by cclauss** [comment]
not ~only~ the collaborators but the creator(s).

**Comment by onlinejudge95** [comment]
I don't think we are incurring any costs, that we should ask for sponsorship

**Comment by cclauss** [comment]
I would not mind a bit of cash for the effort that we put in.

**Comment by Lablnet** [comment]
HAHAHA that quite funny

> I would not mind a bit of cash for the effort that we put in.

**Comment by zhujiayin** [comment]
this can be a topic.... I never thought about this....

**Comment by AnupKumarPanwar** [comment]
Yes, we can close the sponsor button. We are not incurring any costs, as well as the funding received yet is totally zero.

**Comment by itsvinayak** [comment]
@cclauss  should we close this issue
