### ISSUE TITLE
Add a LSTM neural network?

### ISSUE THREAD

**Issue by Tejaswgupta** [TheAlgorithms/Python#1770]
Adding a LSTM neural net to predict stock prices to neural network category would help the beneficial.

**Comment by onlinejudge95** [comment]
If you are working on a PR. make sure to link it to this issue

**Comment by iamlatin** [comment]
Dear government can I get my $3 3 million Grant From TSA government and from the fleet government and from other government agencies I’m a victim of sex trafficking on my phone I got pictures to prove it

**Comment by iamlatin** [comment]
Government can I do surveys for money can I do bitcoin for money

**Comment by iamlatin** [comment]
freecoinhunt.com It’s broken fix it

**Comment by iamlatin** [comment]
btmManager.com no activato

**Comment by iamlatin** [comment]
btc Manager.com Needs activation

**Comment by iamlatin** [comment]
I’ll pay a person bitcoin to active to activate it

**Comment by iamlatin** [comment]
You gotta activate it 1st to get to you got activated 1st to be paid

**Comment by jeffin07** [comment]
Is this issue still open ? I would like to work on it

**Comment by cclauss** [comment]
Go for it.
