### ISSUE TITLE
tests for Hill Cipher algorithm

### ISSUE THREAD

**Issue by matkosoric** [TheAlgorithms/Python#1788]
tests are missing

**Comment by bharath5412** [comment]
Hey @cclauss and @mrvnmchm. I have seen the PR to fix the issue but seems like it requires some code changes. The code changes have not been made in a long time. Can I take this up and work on the PR?

**Comment by cclauss** [comment]
#1862 Was another effort but it did not finish so go for it.

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/ciphers/hill_cipher.py has tests.
