### ISSUE TITLE
author and mail info

### ISSUE THREAD

**Issue by matkosoric** [TheAlgorithms/Python#1789]
Original creator of algorithm should be mentioned in docstring, but does it also apply for the person who added python implementation to this repo? Shouldn't git history be enough? If so, contribution guidelines have to contain this point, including the policy about mentioning personal mails and github profiles.

**Comment by cclauss** [comment]
I do not believe that our contribution process should _mandate_ that contributors disclose Personal Data.  If a contributor wants to share then it is OK but there should be no requirement.
