### ISSUE TITLE
SSD object detection algorithm

### ISSUE THREAD

**Issue by siddharthjain1611** [TheAlgorithms/Python#1791]
It has come to my notice that SSD object Detection algorithm is missing, I'd love to add it community allows.

**Comment by cclauss** [comment]
Solid State Disk??

**Comment by siddharthjain1611** [comment]
Single Shot MultiBox Detector. You can find more about it [here](uhttps://medium.com/@smallfishbigsea/understand-ssd-and-implement-your-own-caa3232cd6adrl)
