### ISSUE TITLE
Differentiation of ML algorithms

### ISSUE THREAD

**Issue by siddharthjain1611** [TheAlgorithms/Python#1793]
There is a need to segregate the algorithms into Regression, Classification and Clustering.

**Comment by sandyuser404** [comment]
Import numpy 
Import pandas
Import matplotlib. Pyplot as plt
Import seabon
Data=pd.DataFrame('files. Csv') 
Data. Head()
Sns.pairplot(data)
From sklearn. Model_selection import train_test_split
Xtrain, xtest, ytrain, ytest=train_test_split(x,y,test_size=0.28)
From sklearn.linear_model import linear regression 
Ir=linearregresion()
Ir=ir.predict(xtrain,ytrain)
Plt.scatter(xtrain,ytrain)
Plt.plot(xtrain,ir.predict(xtrain),color=red)
Plot. Show()
