### ISSUE TITLE
Tests for string module

### ISSUE THREAD

**Issue by HarsheetKakar** [TheAlgorithms/Python#1794]
There are no tests for string module.

I would like to work on it.

**Comment by cclauss** [comment]
Travis CI test >500 files on every pull request including 7 in the strings directory.
https://travis-ci.com/github/TheAlgorithms/Python/builds/152796098#L738

**Comment by HarsheetKakar** [comment]
I dont fully understand that, but ok

**Comment by cclauss** [comment]
[This](https://github.com/TheAlgorithms/Python/blob/master/strings/aho-corasick.py#L66-L68) is a [Python doctest](https://docs.python.org/3/library/doctest.html) as discussed in [CONTRIBUTING.md](blob/master/CONTRIBUTING.md) that is run by [pytest](https://docs.pytest.org) in our [Travis CI test configuration](https://github.com/TheAlgorithms/Python/blob/master/.travis.yml#L13).

**Comment by HarsheetKakar** [comment]
Oh ok, i wasn't checking int he right place, sorry to bother.

**Comment by cclauss** [comment]
There are untested algorithms so it would be great if you want to add tests.

**Comment by HarsheetKakar** [comment]
> There are untested algorithms so it would be great if you want to add tests.

sure will look into it
