### ISSUE TITLE
Adding bidirectional dijkstra to graphs

### ISSUE THREAD

**Issue by armingh2000** [TheAlgorithms/Python#1805]
There are 3 implementations of Dijkstra in graphs dir, but none is bidirectional.
I can implement the algorithm if it's needed.
+: Is it worth to change each directory's files, so that all inputs of classes and functions are in a specific format which is accepted by all other related functions and methods?

**Comment by cclauss** [comment]
Please feel free to submit PRs without waiting for permission.  It is easier for review Python code then English prose.  Normalizing the function call parameter only makes sense if you are going to create performance benchmarks so we can have an bake-off.
