### ISSUE TITLE
implementation of computer vision algorithm in python  

### ISSUE THREAD

**Issue by hritik5102** [TheAlgorithms/Python#1809]
I want to work on this issue, please assign it to me.

**Comment by cclauss** [comment]
You do not need to request permission... just submit pull requests.

**Comment by jeffin07** [comment]
@cclauss Can you please give some examples of cv algorithms that you expecting ?

**Comment by cclauss** [comment]
License plate recognition
Is there a tree in this picture?
How many trees are in this picture?
Is there a willow tree in this picture?
What is the species of the tree in the picture?
What are the species of all the trees in the picture?

**Comment by cclauss** [comment]
All talk.  No action.  :-(

**Comment by AyyESS1** [comment]
excuse me I'm have some other focuses in other things these days.So, I had
stopped my activity in git-hub .

Le dim. 31 mai 2020 à 10:44, Christian Clauss <notifications@github.com> a
écrit :
