### ISSUE TITLE
Any thoughts on adding Quantum Algorithms? 

### ISSUE THREAD

**Issue by Vasuji** [TheAlgorithms/Python#1831]
This could include a very large family and could go beyond the scope of the current plan. Introducing some basic quantum algorithms could be helpful for beginners. There are currently, gate based QC (e.g., IBM, Google, Rigetti) and Quantum annealers ( DWave). Am I missing others, topological or quantum optics based QC? The image below shows where is QC going in the future? 
![img](https://github.com/q4quanta/Qinfo/blob/master/qc.jpg?raw=true)
Image Courtesy: [Quantum Computing, Progress and Prospects](https://www.nap.edu/catalog/25196/quantum-computing-progress-and-prospects)

**Comment by hackercyclops12** [comment]
I think that's a great plan!

**Comment by cclauss** [comment]
Go for it!!!  If it becomes a monster, then we could create a separate repo but it is best to get started.

**Comment by hackercyclops12** [comment]
Ideas?

https://en.m.wikipedia.org/wiki/Shor%27s_algorithm

https://en.m.wikipedia.org/wiki/Grover%27s_algorithm

https://en.m.wikipedia.org/wiki/Quantum_Fourier_transform

https://en.m.wikipedia.org/wiki/Topological_quantum_field_theory

**Comment by hackercyclops12** [comment]
I would also find this interesting to look into:

https://research.google/teams/applied-science/quantum/

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/tree/master/quantum is open for business...

**Comment by cclauss** [comment]
All talk, no action.  :-(

**Comment by cclauss** [comment]
@Vasuji @hackercyclops12 How do we get some quantum algorithms?!?

**Comment by hackercyclops12** [comment]
I'm not shure

 quantum computing is often used for medical sciences or predicting natural recurrences such as weather and how that relates to agriculture 

A recent one is climate change around the globe and how it is affecting certain parts of country's 

Most likely you would need a quantum computer to check the "quantum algorithim" after it is written 

In short I have no idea where we will get some algorithoms from as they are developed for private enterprises 
(However you might be able to find some basic ones with some research)

**Comment by cclauss** [comment]
[Above](https://github.com/TheAlgorithms/Python/issues/1831#issuecomment-610228671) you mentioned four quantum algorithms:
* Shor's algorithm
* Grover's algorithm
* Quantum Fourier transform
* Topological quantum field theory

Could we start with one of those?

**Comment by Vasuji** [comment]
Dear all, here are some resources:

1.  https://qiskit.org/textbook/preface.html
2. http://docs.rigetti.com/en/stable/exercises.html
3. https://cirq.readthedocs.io/en/stable/examples.html
4. https://strawberryfields.readthedocs.io/en/stable/
5.
https://docs.ocean.dwavesys.com/projects/dwave-networkx/en/latest/intro.html
6. https://docs.ocean.dwavesys.com/en/stable/
7. https://openfermion.readthedocs.io/en/latest/openfermion.html

**Comment by hackercyclops12** [comment]
Sure! lets choose one to start 
@cclauss & @Vasuji which one do you want to start with?
