### ISSUE TITLE
Ideas For Quantum Algorithms  

### ISSUE THREAD

**Issue by hackercyclops12** [TheAlgorithms/Python#1843]
Further Ideas & examples

https://research.google/pubs/?area=data-management&area=data-mining-and-modeling&area=general-science

**Comment by hackercyclops12** [comment]
Started at: https://github.com/TheAlgorithms/Python/issues/1831

**Comment by cclauss** [comment]
Moved to #1831 — We don’t need two issues for the same topic.

**Comment by hackercyclops12** [comment]
OK sorry
