### ISSUE TITLE
pyd nested call error

### ISSUE THREAD

**Issue by huang229** [TheAlgorithms/Python#1846]
I used C++ to customize a cross function, and then successfully compiled it to cross.pyd. Now I call it in a.py file, then compile it into exe executable file, run exe result is normal. But if I call this cross.pyd nested and compile the project into an exe executable file, when I run exe, I will report that I can't find the cross function. Why?        In addition, there is no problem in compiling. pyd file nested calls of Python's third-party libraries into exe executable files.

**Comment by cclauss** [comment]
It is easier to debug Python code than English prose...
* Do you have a repo that contains the C++ and Python files with build instructions?

**Comment by huang229** [comment]
Hello, thank you very much for your reply. But I don't quite understand.
That's true:
Use the pybind11 tool to compile cross.cpp to cross.pyd. The generated cross.pyd is automatically placed in the site packages directory of Python.

Now I import the cross function in the tmp.py script. Then use the Cython tool to compile tmp.py as tmp.pyd, which also generates tmp. c as an intermediate file.

Then I'm writing a test. py script, in which I import the functions in tmp. pdy.

Finally, use the pyinstaller - F test.py command to compile test.py to generate the test.exe executable. No exception is thrown during compilation. However, when running test.exe, it reported that the function in cross.pyd could not be found.

**Comment by huang229** [comment]
@cclauss

**Comment by cclauss** [comment]
Please create a new repo at https://github.com/huang229?tab=repositories that contains:
* cross.cpp
* tmp.py
* test.py
* build.sh -- Which contains the steps that that you describe above
* README.md -- Which explains what success would be and where you are stuck

**Comment by huang229** [comment]
@cclauss Thank you very much for your attention. I have just solved this problem.

**Comment by cclauss** [comment]
Please close this issue.
