### ISSUE TITLE
im2col function has a issue

### ISSUE THREAD

**Issue by thewq** [TheAlgorithms/Python#1847]
````
def im2col(image, block_size):
    rows, cols = image.shape
    dst_height = cols - block_size[1] + 1
    dst_width = rows - block_size[0] + 1
    image_array = zeros((dst_height * dst_width, block_size[1] * block_size[0]))
    row = 0
    for i in range(0, dst_height):
        for j in range(0, dst_width):
            window = ravel(image[i : i + block_size[0], j : j + block_size[1]])
            image_array[row, :] = window
            row += 1
    return image_array`
```
**### #There should be:
    for i in range(0, dst_width):
        for j in range(0, dst_height):**

**Comment by Togrul2001** [comment]
> ````
> def im2col(image, block_size):
>     rows, cols = image.shape
>     dst_height = cols - block_size[1] + 1
>     dst_width = rows - block_size[0] + 1
>     image_array = zeros((dst_height * dst_width, block_size[1] * block_size[0]))
>     row = 0
>     for i in range(0, dst_height):
>         for j in range(0, dst_width):
>             window = ravel(image[i : i + block_size[0], j : j + block_size[1]])
>             image_array[row, :] = window
>             row += 1
>     return image_array`
> ```
> **### #There should be:
>     for i in range(0, dst_width):
>         for j in range(0, dst_height):**
>

**Comment by itsvinayak** [comment]
> ```
> def im2col(image, block_size):
>     rows, cols = image.shape
>     dst_height = cols - block_size[1] + 1
>     dst_width = rows - block_size[0] + 1
>     image_array = zeros((dst_height * dst_width, block_size[1] * block_size[0]))
>     row = 0
>     for i in range(0, dst_height):
>         for j in range(0, dst_width):
>             window = ravel(image[i : i + block_size[0], j : j + block_size[1]])
>             image_array[row, :] = window
>             row += 1
>     return image_array`
> ```
> **### #There should be:
>     for i in range(0, dst_width):
>         for j in range(0, dst_height):**
> ```

@thewq  please explain the issue, provide some details

**Comment by cclauss** [comment]
What is the outer loop and what is the inner loop? height / width or width / height?

**Comment by ken437** [comment]
Is there a situation where this function gives an incorrect result or crashes?

**Comment by EkanshMangal** [comment]
is issue still open??
