### ISSUE TITLE
Need a GitHub Action to autoclose empty issues

### ISSUE THREAD

**Issue by freedom22-cyber** [TheAlgorithms/Python#1901]
It seems like daily a new GitHub user opens an issue on this repo that has no content.
This ___needlessly interrupts the attention___ of each of the 4700+ people who _watch_ this repo.

It would be helpful if we had a GitHub Action that autoclosed these empty issues to ease the life of project maintainers -- @cclauss

**Comment by mateuszz0000** [comment]
Perhaps it would be helpful:
https://github.com/roots/issue-closer-action

**Comment by itsvinayak** [comment]
> Perhaps it would be helpful:
> https://github.com/roots/issue-closer-action

@mateuszz0000 with this we can add "guidelines for an opening issue" which must be included with every issue, maybe a Checklist which tells more about the issue.
something same a **PR** one

**Comment by cclauss** [comment]
We do not need a template for issues...  This should just be free-form to not stifle open thinking.  PRs on the other hand need to demonstrate compliance so the template is quite useful.

**Comment by poyea** [comment]
> Perhaps it would be helpful:
> https://github.com/roots/issue-closer-action

We may make a requirement on the number of words in an issue as well. It'd be possible with `{,}` quantifiers.

**Comment by NLe1** [comment]
Seems like a good idea, are this still open and looking for help?
