### ISSUE TITLE
Warnings generated by test_matrix_operation.py

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#1917]
`Python/matrix/tests/test_matrix_operation.py` mentions [@pytest.mark.mat_ops](https://github.com/TheAlgorithms/Python/blob/master/matrix/tests/test_matrix_operation.py#L31) numerous times which is [generating a lot of warnings](https://travis-ci.com/github/TheAlgorithms/Python/builds/162930523#L1058) every time Travis CI does a build.  @StephenGemin, @WilliamHYZhang can you please investigate how to fix the code to suppress these warnings?

**Comment by WilliamHYZhang** [comment]
Most likely it is due `@pytest.mark.mat_ops` being an invalid marker, can we remove @cclauss?

**Comment by cclauss** [comment]
Please give that a try.
