### ISSUE TITLE
Same name for an attribute and a function

### ISSUE THREAD

**Issue by mrcloma** [TheAlgorithms/Python#1926]
Hi, I'm new to programming and I'm not sure if it's a problem, but the code(
Python/data_structures/queue/queue_on_list.py) have the same name for an attribute and a function.
```
class Queue:
    def __init__(self):
        self.entries = []
        self.length = 0
        self.front = 0

    def front(self):
        return self.entries[0]
```
When executed it gives me the error:
TypeError: 'int' object is not callable

**Comment by cclauss** [comment]
You are correct.  It is an anti-pattern to have the same name for both an attribute and a method of the same class.

**Comment by vipulrai91** [comment]
@cclauss  , can I work on this ?
