### ISSUE TITLE
Getting error in renaming the columns

### ISSUE THREAD

**Issue by Aditya222002** [TheAlgorithms/Python#1933]
I am getting error in renaming the columns
------------------------------------------------------------------
CODE:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
url="C:/Users/Lenovo/Desktop/Edited_car1.csv"
car=pd.read_csv(url)
drive_wheels_count=car["drive-wheels"].value_counts()
drive_wheels_count.rename(columns={'drive-wheels':'value_count'},inplace=True)

ERROR:
-----------------------------------------------------------------------
 runfile('C:/Users/Lenovo/.spyder-py3/untitled0.py', wdir='C:/Users/Lenovo/.spyder-py3')
Traceback (most recent call last):

  File "C:\Users\Lenovo\.spyder-py3\untitled0.py", line 7, in <module>
    drive_wheels_count.rename(columns={'drive-wheels':'value_count'},inplace=True)

TypeError: rename() got an unexpected keyword argument 'columns'

SCREENSHOTS:
--------------------------------------------------------------------------
[
![image](https://user-images.githubusercontent.com/64554000/80911088-a480e700-8d51-11ea-88b1-d51b5a57d222.png)
](url)

**Comment by poyea** [comment]
Please your issue in [spyder](https://github.com/spyder-ide/spyder) or [pandas](https://github.com/pandas-dev/pandas).
