### ISSUE TITLE
Make Discord Server for TheAlgorithms/Python or TheAlgorithms in general

### ISSUE THREAD

**Issue by QuantumNovice** [TheAlgorithms/Python#1965]
Many devs prefer to use discord these days.

**Comment by hackercyclops12** [comment]
Great idea! I believe we need to talk to the Developers first
[https://github.com/orgs/TheAlgorithms/people](url)

**Comment by cclauss** [comment]
I question the need for a "chat room" for TheAlgorithms.  We don’t need long, nuanced discussions to create a collection of disconnected algorithms.  There are no architectural questions to wrestle with beyond continuous integration testing which I believe is better handled in GitHub issues and pull requests.  The traffic on Gitter is not informative and is mostly from folks who are too lazy to read CONTRIBUTING.md.  My sense is that we are better served by recording our needs, questions, and concerns in GitHub issues. Separating our discussions from our code repo means that there are now more places to look and read to understand the changing mission of the community and there are no permanent links between the discussions and our code.  I find the best conversations are in issues opened to describe why an existing algorithm is incorrect or not optimized.  Those discussions are directly linked to the original pull request and can be linked to future pull requests to test, benchmark, and remedy those algorithms.  All those links are lost when those conversations are happening outside our repo.

Gamers use Discord.  Developers use Slack...  it is more programmable.

**Comment by QuantumNovice** [comment]
Now that you mention it. I remember what people do in chat rooms. It's not a great idea, I just wanted to explore it anyway. Slack would do as well. Having channels for, build status, warnings would be helpful. 
Another thing I am looking forward to, is assigning custom roles to contributors so when a particular test fails, users with expertise in that algorithms are pinged.

**Comment by Panquesito7** [comment]
If someone's still interested, we've built a Discord community server last month; and it's growing more and more. [Join now!](https://discord.gg/c7MnfGFGa6)
