### ISSUE TITLE
Merge sort is improperly implemented

### ISSUE THREAD

**Issue by brayo-pip** [TheAlgorithms/Python#1970]
Specifically the merge sort is improperly implemented. Merge sort should sort recursively but the code simply sorts two lists then merges them.

**Comment by ahmedelgohary** [comment]
It is called recursively [here](https://github.com/TheAlgorithms/Python/blob/7f04e5cd3499c07f07ae94437b706254edb7ba39/sorts/merge_sort.py#L46):

```python
return merge(merge_sort(collection[:mid]), merge_sort(collection[mid:]))
```
