### ISSUE TITLE
Some graphs ideas

### ISSUE THREAD

**Issue by guilyx** [TheAlgorithms/Python#1994]
Hey everyone,

Do you reckon PRs implementing the following graph searches would be welcome ?

- [x] Bidirectional A*
- [x] Greedy Best-First
- [ ] Bidirectional BFS

If so, do you think a bidirectional search should be either **two different searches looking for its counterpart's tail** or **two different searches looking for its counterpart's head**.

Thanks!

**Comment by cclauss** [comment]
Please do not wait for permission.  Just submit pull requests for review.  Thanks.

**Comment by shubhamsah** [comment]
This issue should be closed.

**Comment by cclauss** [comment]
The issue can remain open until pull requests close it.

**Comment by NLe1** [comment]
@guilyx I can help with bidirectional BFS if you need some help!

**Comment by guilyx** [comment]
@NLe1  sure !
@cclauss since there's probably going to be one PR per algorithm implanted you can close it now I guess ?

**Comment by cclauss** [comment]
I would expect that this issue would be closed when all boxes above are checked.  ✔️ currently none of them are.  https://github.com/TheAlgorithms/Python/tree/master/graphs
