### ISSUE TITLE
Mergesort Update Variable Names

### ISSUE THREAD

**Issue by ken437** [TheAlgorithms/Python#2023]
I was looking over the mergesort.py file in the divide_and_conquer directory when I saw that all of the variable names are a single letter and there is not much documentation. Does anyone know enough about this file to improve the variable names and make the code more understandable?

**Comment by avitomar12** [comment]
Can I improve the file?

**Comment by cclauss** [comment]
No need to wait for permission.  Just go for it.  Pull requests will be reviewed.

Only our competitors think that we should wait.

**Comment by aditya-190** [comment]
Can I Modify the Variables to Clarify There Meanings ?

**Comment by Robinson-Arivan** [comment]
What I can do

**Comment by poyea** [comment]
Hello folks @Robinson-Arivan @aditya-190 @avitomar12, welcome to the community and before you contribute, please read our [CONTRIBUTION.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md). It resolves most of the doubts you may have! You can go to the file and see if there's a problem as OP has noted. If you want to take the issue, remember to notify our community here as well to avoid conflicts.

**Comment by EkanshMangal** [comment]
Hello, I have understand the issue.
Can I solve it?

**Comment by EkanshMangal** [comment]
I have opened PR 
https://github.com/TheAlgorithms/Python/pull/2032
I am a beginner in Open Source Contribution Platform . @poyea  Please let me know, is it correct or not.
Thanks!
