### ISSUE TITLE
Formatting issues not getting caught in TravisCI

### ISSUE THREAD

**Issue by onlinejudge95** [TheAlgorithms/Python#2050]
It has come into the observation that files that are not `black` compliant are still passing the Travis CI build. Due to which our master has failing checks. Can we do something about it?

Reference https://github.com/TheAlgorithms/Python/pull/2041

**Comment by cclauss** [comment]
See the _second_ commit on https://github.com/TheAlgorithms/Python/pull/2051

The GitHub Action autoblack (not Travis CI) autoformats our code.  It only runs when a maintainer (with the commit bit) creates a PR.  This approach gives us eventual compliance with psf/black without having to teach every first-time contributor what psf/black is and how to use it.
