### ISSUE TITLE
Can we move the tests to the bottom of each file?

### ISSUE THREAD

**Issue by 0scarDev** [TheAlgorithms/Python#2069]
It really impedes comprehension when you have blocks like the one below:

    def __len__(self) -> int:
        """
        Dunder method to return length of the CircularLinkedList
        >>> cll = CircularLinkedList()
        >>> len(cll)
        0
        >>> cll.append(1)
        >>> len(cll)
        1
        >>> cll.prepend(0)
        >>> len(cll)
        2
        >>> cll.delete_front()
        >>> len(cll)
        1
        >>> cll.delete_rear()
        >>> len(cll)
        0
        """
        return self.length

**Comment by cclauss** [comment]
I (and the [Python standard library](https://docs.python.org/3/library/doctest.html)) disagree.  You read...
1. The function signature with parameters names and types and return types.
2. The doctests which shows how the function is called successfully and how it fails.
3. The implementation which you may try to optimize as long as the tests continue to pass.
