### ISSUE TITLE
Trigonometric functions

### ISSUE THREAD

**Issue by beqakd** [TheAlgorithms/Python#2074]
Hey, i was not able to find some Trigonometric functions in math folder. If not mistaken can i contribute it?

**Comment by cclauss** [comment]
See #2000 — I will work on that PR in next 24 hours.

**Comment by beqakd** [comment]
can i asaing it to myself?

**Comment by cclauss** [comment]
#2000 will not land with failing tests so please go ahead and fix it or write you own version with similar tests.
