### ISSUE TITLE
should to treated specially when first insert a tail node 

### ISSUE THREAD

**Issue by johnzhaoxiao** [TheAlgorithms/Python#2112]
https://github.com/TheAlgorithms/Python/blob/20b21e5ec9d4ed28ede8bd67d4b5bc924454d4ac/data_structures/linked_list/doubly_linked_list.py#L36

**Comment by zky001** [comment]
> https://github.com/TheAlgorithms/Python/blob/20b21e5ec9d4ed28ede8bd67d4b5bc924454d4ac/data_structures/linked_list/doubly_linked_list.py#L36

I think  it's not necessary to treated specially when first insert a tail node.

**Comment by cclauss** [comment]
#2052 says that we need tests before we need other modifications.
