### ISSUE TITLE
Addition of maximum non-adjacent sum algorithm

### ISSUE THREAD

**Issue by ruppysuppy** [TheAlgorithms/Python#2129]
I would like to add on the maximum non-adjacent sum algorithm in [dynamic programming](https://github.com/TheAlgorithms/Python/tree/master/dynamic_programming) section. Can I work on it?

**Comment by cclauss** [comment]
Go for it.  No need to open issues.  Just create a pull request and it will be evaluated on it merits.

**Comment by ruppysuppy** [comment]
@cclauss could you please help? The pull request is failing the build as there is some issues with [ciphers/affine_cipher.py](https://github.com/TheAlgorithms/Python/blob/master/ciphers/affine_cipher.py#L16). I went through the Travis CI logs. The 3rd doctest is failing for that file is failing.
