### ISSUE TITLE
Hierarchical Clustering Addition

### ISSUE THREAD

**Issue by BassCoder2808** [TheAlgorithms/Python#2165]
I would like to add add code for Hierarchical Clustering which I found out is missing/not available in machine_learning folder.
If the solution already exist I would request someone to add the relevant files under the machine_learning folder.
If the solution does not exits I would like to work on it.
https://github.com/TheAlgorithms/Python/tree/master/machine_learning

**Comment by deadshotsb** [comment]
@BassCoder2808  You can go ahead, we will help you if required.

**Comment by BassCoder2808** [comment]
Thanks, I have started working on it.
