### ISSUE TITLE
K-th smallest Element in BST

### ISSUE THREAD

**Issue by jay24rajput** [TheAlgorithms/Python#2172]
## Problem Statement
Adding a function to the [BST](https://github.com/TheAlgorithms/Python/blob/master/data_structures/binary_tree/binary_search_tree.py) to find the kth-smallest element in the entire binary search tree. If possible I would also like to extend it to find the kth-largest element in the BST.

## Motivation
This problem was asked in [Leetcode Challenge](https://leetcode.com/explore/challenge/card/may-leetcoding-challenge/536/week-3-may-15th-may-21st/3335/). I thought that this will be a good addition( if not absolutely necessary) to the BST functions.

**Comment by jay24rajput** [comment]
@cclauss thoughts?

**Comment by gaushikmr** [comment]
@jay24rajput Can u assign me to work on this.

**Comment by jay24rajput** [comment]
@gaushikmr I was kind of hoping to work on it myself once @cclauss or any other mentor approves the functions

**Comment by gaushikmr** [comment]
@jay24rajput Is there any other issues in which I can help you.I am familiar with C,C++ and python languages

**Comment by cclauss** [comment]
Please do not open issues to ask permission or be assigned.  Those are both alien concepts in this repo.  ___We review pull requests.___  If you have a good idea then implement it and submit a pull request.  If you both submit pull requests on the same algorithm, we might pick one and close the other.  Or more likely we might ask you to work together to create a unified pull request that takes the strengths of each request.

_Only our competitors think that we should wait..._

**Comment by jay24rajput** [comment]
Thanks for the reply! I will issue a PR soon

**Comment by cclauss** [comment]
It would also help readers if you could provide a use case.
When and why would I want to find the k-th smallest element in a binary search tree.

**Comment by gaushikmr** [comment]
@jay24rajput R u working on this issue.if not I can work on it

**Comment by jay24rajput** [comment]
@gaushikmr Please go ahead :+1:

**Comment by gaushikmr** [comment]
@jay24rajput OK

**Comment by SiddhantBobde** [comment]
Can I work on this issue?

**Comment by cclauss** [comment]
PLEASE do not ask permission to work on a problem.  This repo does not reserve tasks or give permission.  If you see something that should be fixed then please submit a pull request and it will be evaluated on its merits.  Having two developers submit alternative solutions to a problem is better than having developers waiting for permission to start working.
