### ISSUE TITLE
The descriptive part in the algorithms. 

### ISSUE THREAD

**Issue by KMx404** [TheAlgorithms/Python#2176]
For someone who came here to learn some stuff, Maybe some descriptive parts with well documented code shall help us the noobies learn more.

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Algorithms-Explanation

**Comment by cclauss** [comment]
@KMx404 I am not sure what the _action/ask/todo_ is from this issue.  There are three things that you might do to help us...
1. List _specific alogrithms_ in this issue that you have found difficult to understand.
2. Open new issues on _specific alogrithms_ or directories that you are having trouble with.
3. Open pull requests on _specific alogrithms_ or directories to demonstrate your understanding.

The best way to learn it to teach.  Help us to document where you are having trouble so it will be easier for future learners.

**Comment by KMx404** [comment]
@cclauss I will.
