### ISSUE TITLE
Add Normalization and Standardization Algorithms?

### ISSUE THREAD

**Issue by danmurphy1217** [TheAlgorithms/Python#2189]
I don't see any algorithms for normalization and standardization yet. Could I Implement them in the Machine Learning folder? Or in a sub-folder within Machine Learning for Data Transformations?

**Comment by cclauss** [comment]
The submission is only going to be a few functions then put them in a single machine_learning/data_transformations.py file.  Only create a subdirectory if you add a lot of files.  Flatter directory structures facilitate discovery.
