### ISSUE TITLE
Python 2 or Python 3 or both?

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#219]
Is the code in this repo designed to run on Python 2 or on Python 3 or on both?

**Comment by christianbender** [comment]
@cclauss  I would say more python 2. My last contribute was of basis of python 2.

**Comment by cclauss** [comment]
python2 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
python3 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics

Show some code is Python 2 only and other code is Python 3 only.
