### ISSUE TITLE
maths/number_of_digits.py is naive!

### ISSUE THREAD

**Issue by vasugamdha** [TheAlgorithms/Python#2220]
<code>[maths/number_of_digits.py](https://github.com/TheAlgorithms/Python/blob/master/maths/number_of_digits.py)</code> has a naive method. The suggested method has a time complexity of O(n). We can count number of digits of a number in O(1).

**Comment by cclauss** [comment]
Can we put both algorithms into the same file and add a benchmark that _proves_ that the theory that the proposed algorithm is noticeably faster than the current algorithm?

**Comment by vasugamdha** [comment]
@cclauss Yes! I have proposed the algorithm that is noticeably faster as <code>num_digits_fast()</code> in the #2221 
Please review it. Thanks.
