### ISSUE TITLE
Csv file

### ISSUE THREAD

**Issue by Mist-16** [TheAlgorithms/Python#2239]
How do I read a csv file and use it in a if function

**Comment by fhlasek** [comment]
@Mist-16 can you please share a bit more context? Where do you intend to use CSV files?
There's a library for reading csv files or you can just read it as a regular file and split the lines by the comma (unless you care about escaping)
https://docs.python.org/3/library/csv.html

**Comment by Mist-16** [comment]
Like I want to use the csv to store usernames and password, I can write the 
Csv file but I need to read it and use it in a if function you know to find the password and username for the user

**Comment by cclauss** [comment]
Please use https://stackoverflow.com for these kind of questions.
