### ISSUE TITLE
Word frequency

### ISSUE THREAD

**Issue by Yeswanth-Chippada** [TheAlgorithms/Python#2240]
def word_count(str):
    counts = dict()
    words = str.split()

    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1

    return counts

print( word_count('the quick brown fox jumps over the lazy dog.'))

**Comment by cclauss** [comment]
`str` is a basic datatype in Python so it is not an appropriate variable name.

https://docs.python.org/3.8/library/collections.html#collections.Counter makes these algorirms trivial in Python.
