### ISSUE TITLE
maths/least_common_multiple very inefficient

### ISSUE THREAD

**Issue by fhlasek** [TheAlgorithms/Python#2268]
The time complexity of the [least common multiple implementation](https://github.com/TheAlgorithms/Python/blob/master/maths/least_common_multiple.py) is O(max(A, B)) where A and B are the function parameters.

Much more efficient implementation uses the [formula with the greatest common divisor](https://en.wikipedia.org/wiki/Least_common_multiple#Using_the_greatest_common_divisor) which is already [implemented efficiently](https://github.com/TheAlgorithms/Python/blob/master/maths/greatest_common_divisor.py) in this repo.

**Comment by cclauss** [comment]
Without a [benchmark](https://github.com/TheAlgorithms/Python/search?q=timeit), this seems to be a theoretical supposition with no executable proof.
