### ISSUE TITLE
Need contributor access to the repository

### ISSUE THREAD

**Issue by kanthuc** [TheAlgorithms/Python#2292]
I would like to work on issue #2128, adding static type checking. I started with basic_binary_tree.py but am unable to publish my branch. This is the error I recieved.

> c:\github\algo\Python\data_structures\binary_tree>git push --set-upstream origin basic_binary_tree.py-static-type-checking
remote: Permission to TheAlgorithms/Python.git denied to kanthuc.
fatal: unable to access 'https://github.com/TheAlgorithms/Python.git/': The requested URL returned error: 403

Could I please have access so I can publish my branch and create a PR, thank you

**Comment by cclauss** [comment]
Push to ___your own fork___ of this repo which should be at https://github.com/kanthuc/Python to create a pull request to this repo.  As noted in the comments of #2128, the file `.travis.yml` already runs `mypy` on all pull requests.

**Comment by kanthuc** [comment]
thank you!
