### ISSUE TITLE
Provision to add ipython and jupyter notebook code

### ISSUE THREAD

**Issue by Arnav0400** [TheAlgorithms/Python#2299]
I am trying to implement auto-encoder but the whole point of that algorithm is visualizations. Adding Jupyter-Notebook support will easily help to visualize matplotlib figures. Please confirm if jupyter notebook support will be added or not. Thanks in advance..

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Jupyter is waiting for your pull request.

We don't take Jupyter files in this repo because then GitHub views it as a Jupyter repo, not a Python repo.

**Comment by Arnav0400** [comment]
Thank you. I just missed that repo.
