### ISSUE TITLE
Dead link 

### ISSUE THREAD

**Issue by auto-blue** [TheAlgorithms/Python#2373]
MIT License in the CONTRIBUTING.md seems to be a dead link (https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contributor)

> [MIT License](https://github.com/TheAlgorithms/Python/blob/master/License)

**Comment by cclauss** [comment]
It should be LICENSE.md

**Comment by muskanvk** [comment]
Hey I fixed it and Raised a PR. #2378
