### ISSUE TITLE
Python crawler keeps crawling the content of the first page repeatedly

### ISSUE THREAD

**Issue by Q-yh-ouo** [TheAlgorithms/Python#2379]
`import requests
import urllib
from lxml import html
#需要爬数据的网址
j=0
    #!s-p3
for k in range(1,20):
    url='https://www.duitang.com/search/?kw=%E6%AD%A3%E5%A4%AA&type=feed'+'#!s-p'+str(k)
    page=requests.Session().get(url)
    tree=html.fromstring(page.text)
    result=tree.xpath('//a[@class="a"]//img/@src') #获取需要的数据
    for i in result:
        urllib.request.urlretrieve(i,'C://Users//FangJZ//Desktop//duitan//'+(str(j))+'.jpg')
        j=j+1
print('true')`

**Comment by HarshilShrivastava** [comment]
can you format it that would be great
