### ISSUE TITLE
Using as interaper 

### ISSUE THREAD

**Issue by yuvalmas** [TheAlgorithms/Python#2391]
Is there a way to update my python to be up to date with the GitHub? I don't mind doing occasional manual updates I just want to be able to work with some of the functions in it. I want to be able to use them without having to import anything

**Comment by cclauss** [comment]
Is this question about your current version of Python (`python3 --version`) or is this a question about the code in this repo?

**Comment by yuvalmas** [comment]
@cclauss I would like to add the functions in this repo into my default python so I don't have to import anything
