### ISSUE TITLE
LCA problem

### ISSUE THREAD

**Issue by vardhanshah** [TheAlgorithms/Python#240]
Hey, Can i include code for  Lowest Common Ancestor algorithm for Directed Acyclic Graph (algorithm is based upon LCA  problem to RMQ(Range Minimum Query) problem reduction (solving RMQ problem via sparse table), which has time complexity per query O(1) and memory complexity of O(N.log N) ?

**Comment by harshildarji** [comment]
@vardhanshah Your contribution to this repository is welcomed.
