### ISSUE TITLE
Pillow: PIL DeprecationWarnings in pytest output

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#2402]
https://travis-ci.com/github/TheAlgorithms/Python/builds/182944036#L895 seems similar to #2284

**Comment by HarshilShrivastava** [comment]
Can you downgrade the version

**Comment by cclauss** [comment]
Can you fix the code so that it no longer uses the deprecated syntax?

**Comment by DmytroLitvinov** [comment]
Hi @cclauss ,

I have provided https://github.com/TheAlgorithms/Python/pull/2678. Would be nice if you can check because you fixed a similar issue.

**Comment by dhruvmanila** [comment]
#2678 Fixes this issue.
