### ISSUE TITLE
README.md - Quicksort average case performance

### ISSUE THREAD

**Issue by antfitch** [TheAlgorithms/Python#245]
Readme says average case performance for quicksort is 0(n^2), but elsewhere, this is O(n log n). 
https://en.wikipedia.org/wiki/Quicksort

Is this a bug in the docs? Or is average case performance for the version of quicksort in this repo actually O(n^2)?

**Comment by harshildarji** [comment]
I hope that screenshot below will clear your doubts:

![capture](https://user-images.githubusercontent.com/14276147/35549008-40c87a34-05a9-11e8-85ee-345ec8415b1c.PNG)

If you have any improved script for **QuickSort**, Your contribution is welcomed.

**Comment by antfitch** [comment]
Hello harshildarji, my comment was for average case, not best case. Average case is usually O(n log n) not O(n^2) for this alg.

**Comment by harshildarji** [comment]
@antfitch My bad, I’ll check and correct it within next 24 hours (or you can just do a PR with the corrections, I’ll immediately merge it).

**Comment by antfitch** [comment]
No worries and cool. I added a PR.

**Comment by harshildarji** [comment]
@antfitch Done!
