### ISSUE TITLE
Python 

### ISSUE THREAD

**Issue by eksam03** [TheAlgorithms/Python#2485]
#2484

**Comment by cclauss** [comment]
#1901

**Comment by cclauss** [comment]
@eksam03 Where did you get the idea to open an empty issue with no content?

**Comment by eksam03** [comment]
Sorry I didn't mean it. 
I'm newbie here

**Comment by cclauss** [comment]
Understood.  No problems.  But was there a website or a blog or some other place that suggested the idea to you?  We get a ton of these empty issues and I am wondering if there is some common source to them.
