### ISSUE TITLE
Unable to be create branches

### ISSUE THREAD

**Issue by xcodz-dot** [TheAlgorithms/Python#2490]
I am trying to initiate pull request but i am not able to make a branch
I am new to github, any idea for updating my files on this repository

**Comment by cclauss** [comment]
Are you using git on the command-line or the GitHub web UI?

**Comment by xcodz-dot** [comment]
web ui

**Comment by xcodz-dot** [comment]
web UI

**Comment by xcodz-dot** [comment]
Please help me, I have algorithm for 3d vector point to 2d vector point

**Comment by cclauss** [comment]
Add file... Create new file...
![Screenshot 2020-09-26 at 19 20 14](https://user-images.githubusercontent.com/3709715/94346532-88961e80-002d-11eb-8524-28ae1178cca9.png)

**Comment by xcodz-dot** [comment]
thanks
