### ISSUE TITLE
I want to borrow some modules from this place into my project. What are the T&C?

### ISSUE THREAD

**Issue by xcodz-dot** [TheAlgorithms/Python#2504]
Please tell the guidelines i should follow before i borrow anything. [My project](https://github.com/xcodz-dot/denver) is MIT Licensed and is Open Source.

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/LICENSE.md are the ONLY terms and conditions.

**Comment by xcodz-dot** [comment]
ok
