### ISSUE TITLE
Hacktoberfest 2020 - Implement Python algorithms or data structures, fix existing ones and more!

### ISSUE THREAD

**Issue by poyea** [TheAlgorithms/Python#2510]
The annual [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is around the corner! Register on [Hacktoberfest's website](https://hacktoberfest.digitalocean.com/) and open 4 pull requests during October 2020 to receive the swags (if you're the first 70,000 participants)!

In our Python repository, there are currently several open issues:
* [ ] #2128
* [ ] #1901

What's more, you can also **fix an existing bugs, improve any documentation** and **provide better implementations** for [certain algorithms](https://github.com/TheAlgorithms/Python/blob/master/DIRECTORY.md)! Feel free to inform the community by **filling an issue** and start hacking! If you're new to contributing code, please read our [Contribution Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) for an overall understanding and ask questions on the internet - Google, StackOverflow or our Gitter.

[TheAlgorithms](https://github.com/TheAlgorithms) has repositories in other programming languages, so find your language and start coding there!

### What you can do to participate
1. Read our [Contribution Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md)
2. Comment below or open an issue (for big ideas you may want the community to know) on your new implementations, fixes or functionalities
3. Start hacking!
4. Open a pull request for your contribution
5. Label your pull requests with `hacktoberfest`
6. Wait until your pull requests get reviewed or merged! In the meantime, you can review someone else's pull requests too

### Useful links
* Our [Gitter](https://gitter.im/TheAlgorithms) channel
* The [Contribution Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) of TheAlgorithms/Python
* Our [Code of Conduct](https://github.com/TheAlgorithms/.github/blob/master/CODE_OF_CONDUCT.md)
* The [Directory](https://github.com/TheAlgorithms/Python/blob/master/DIRECTORY.md) of TheAlgorithms/Python

### Remarks
* Please observe Hacktoberfest's rules, terms and FAQ. If a pull request is marked `invalid` or `spam` it would not be counted and the person may be disqualified for the swags.
* Hacktoberfest 2020 is an event presented by DigitalOcean, Intel and DEV.

### Hacktoberfest's update
> PRs count if:
> Submitted in a repo with the hacktoberfest topic AND
> during the month of October AND (
>   The PR is merged OR
>   The PR is labelled as hacktoberfest-accepted by a maintainer OR
>   The PR has been approved
> )
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by cclauss** [comment]
PSA: I am checking out for the month of Hactoberfest.  I have some important work that I must attend to so I will stop contributing to this repo for the next 30 days.  I would encourage maintainers to stick with the rules that have gotten us this far: be friendly, insist on best coding practices including all that is in CONTRIBUTING.md (functions, type hints, doctests, etc.)

If you see PRs that are useless or show that the contributor has not read CONTRIBUTING.md please mark those PRs with the `invalid` label and close them.  (Hacktoberfest organizers look for the `invalid` label.) Do the same for any contributor who is disrespectful.  If we consistently demonstrate that we have high standards and no tolerance for disrespect then the spamers will go elsewhere.

See you again in November.

**Comment by poyea** [comment]
Please observer that, from now on, a PR has to be marked `hacktoberfest-accepted`, approved or merged in order to be counted towards the event. For maintainers, please add the labels `hacktoberfest-accepted` to PRs that are NOT spams, even if you can't review those PRs at the moment. As usual, we label spams as `invalid`.

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by DmytroLitvinov** [comment]
Hi @poyea ,
Mark please issue #2402 as resolved in the first message of that issue.

**Comment by poyea** [comment]
Sure.

**Comment by thevirtualbuddy** [comment]
Hi @poyea & other maintainers,
I am interested to contribute one of my projects to this repository. 
The project is a simple CLI application (python based) which has the following functionalities:
1. Encrypt and encode data in an image.
2. Decode and decrypt data from an image.

It uses Caesar cipher (encryption & decryption) and Image Steganography(encoding & decoding).

Can I contribute it to this repository?

**Comment by poyea** [comment]
Yes. You may also see if there's any related implementation in [`ciphers`](https://github.com/TheAlgorithms/Python/tree/master/ciphers).

**Comment by thevirtualbuddy** [comment]
Thank you for the quick response. 
It has caesar cipher #1958 but it doesn't have image steganography combined with it. 
So, should I work on the existing code or work fresh?

**Comment by poyea** [comment]
You may add a new one, as the current one works with strings, unless you can modify it make it compatible with images or matrices.

**Comment by thevirtualbuddy** [comment]
Thank you @poyea 
I will add a new folder as Image Steganography.

**Comment by cclauss** [comment]
Please create a new directory only if there are going to be multiple Python files in it.  If it is just a single Python file then please find and existing directory to put it in.  We do not want to force visitors to click into and out of tons of directories to find something of interest.

**Comment by poyea** [comment]
Yes, add a folder if you have images related to that, but in general, we want to avoid this.

**Comment by thevirtualbuddy** [comment]
I am a bit confused here now :'). 
If I should add it in [Ciphers](https://github.com/TheAlgorithms/Python/tree/master/ciphers) as  caesar_ciphers_with_steganography or create a new folder?

**Comment by cclauss** [comment]
How many Python files will your proposed new folder contain?

**Comment by thevirtualbuddy** [comment]
@cclauss I can combine all the files in a single file. Right now, I have the files divided as caesar.py, steganography.py and driver.py

**Comment by cclauss** [comment]
Cool.  Then do it whichever way that you think best.  Thanks.

**Comment by MonarchChakri** [comment]
Hi @cclauss / @poyea 
Added file_utils.py under others and created a PR https://github.com/TheAlgorithms/Python/pull/2735
A utility files helpful for all common file IO.
Please review and merge.

**Comment by dickyw71** [comment]
Hi @poyea & other maintainers,

I have a fix for issue #1901 and I would like to submit.

My YAML Workflow file auto-closes empty issues. 
The file-path name is `.github/workflows/auto_close_empty_issues.yml`.

The workflow checks whether a new issue body is empty and if so it uses the [close-issue](https://github.com/marketplace/actions/close-issue) action to auto-close the issue and send a notification email to the repo owner/maintainers. 
 
I have tested the Workflow works as expected in my own [repo](https://github.com/dickyw71/gh-actions).

Is is ok for me to raise a PR?

**Comment by prakhargurunani** [comment]
Hey @cclauss @poyea Can i add some chemical conversitions to `/conversions` as a part of hacktoberfest ?

**Comment by breezko** [comment]
I’ve added #2782

**Comment by dhruvmanila** [comment]
As mentioned, please include ***for Hacktoberfest*** or something like that in your ***description*** to signal us that this PR is for Hacktoberfest otherwise we wouldn't know that you participated or not.

**Comment by dhruvmanila** [comment]
@poyea Should we add #2786 and #2695 to Hacktoberfest?

**Comment by prakhargurunani** [comment]
@dhruvmanila yeah....for hacktober fest....I am making a PR for `conversions`

**Comment by ChiragBolakani** [comment]
Hey @poyea and other maintainers,
    I would like to contribute to the web_programming folder with a webscraper which will allow users to scrape presentations and then download them.

**Comment by gupta-niharika** [comment]
Hey I'd like to work on one of the issues. I'm a first timer

**Comment by poyea** [comment]
> Hey @cclauss @poyea Can i add some chemical conversitions to `/conversions` as a part of hacktoberfest ?

We'd love to see that.

**Comment by mandloiaditi** [comment]
Hi, I would like to implement  DSW algorithm to balance binary search tree. May I take up this task and add the implementation to data_structures/binary_tree folder ?

**Comment by prakhargurunani** [comment]
I have created a PR https://github.com/TheAlgorithms/Python/pull/2944 @cclauss @poyea . I have added `molecular_chemistry` algorithm in `/conversions`.

**Comment by mvhb** [comment]
Hi, can you guys take a look at #2779?
Thanks in advance

**Comment by Satyamkumarai** [comment]
Hi @poyea 
I'd like to contribute to `Python/maths/factors.py ` as part of hactoberfest
I have implemented  a fast prime no Generator function 
Can i Create a PR?

**Comment by bryophyllum1** [comment]
HI @poyea, I want to contribute some algorithms during the hacktober, can you assign me, please?

**Comment by verdantfire** [comment]
I want to add the implementations of Operating Systems scheduling algorithms. Should I add features upon the basic algorithm structure written by @cclauss (to maintain consistency) or use my own?

**Comment by SimonLammer** [comment]
I've opened the PR #2916, is there anything I still have to do moving forward?

**Comment by pikachu28** [comment]
Hi, I would like to work on the implementation of the Recurrent Neural Network From Scratch by python. May I implement this and create a pull request ?

**Comment by radadiyamohit81** [comment]
Hello @poyea, I would like to contribute to your repository that I have build one `Deep Neural Network` (Research Work) for greater accuracy .
Can I contribute it to this repository?

**Comment by KmrAnish04** [comment]
Hello @poyea, I am beginner to this programming and open source world and I have not much knowledge about DS/Algo but I want to contribute to this repository. So I have some python3.7 scripting program, can I add my program to "other" directory of this repository. I will be thankful by contributing to this repository.
Regards,
Anish

**Comment by TheSussex** [comment]
Hi @poyea I'd like to add a Number Guess python algorithm to the repository, can I go ahead?

**Comment by Ed1123** [comment]
Hi, this'd be my first PR to a public repo so I'd like to keep it very small (very). I'm starting by improving the documentation for this two algorithms ([newton_method.py](https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/newton_method.py) and [newton_raphson.py](https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/newton_raphson.py)).

I know it is a small contribution and know that it may not count towards Hacktoberfest. If you have any feedback on how to make it count I'm all ~~ears~~ eyes. 😄
If there is no way it can count it'd ok. It will serve me to get familiarized with how Github and PR's work (I'm following this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) by DigitalOcean for that).

**Comment by cybov** [comment]
I opened a PR #3192 and only Travis CI passed. I've read the log for codespell and pre-commit and still no luck. 
Help please.

**Comment by sumitmohite0501** [comment]
Divide and Conqrer added #3202. all chechpoint pass

**Comment by Ed1123** [comment]
> Hi, this'd be my first PR to a public repo so I'd like to keep it very small (very). I'm starting by improving the documentation for this two algorithms ([newton_method.py](https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/newton_method.py) and [newton_raphson.py](https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/newton_raphson.py)).
> 
> I know it is a small contribution and know that it may not count towards Hacktoberfest. If you have any feedback on how to make it count I'm all ~ears~ eyes. 😄
> If there is no way it can count it'd ok. It will serve me to get familiarized with how Github and PR's work (I'm following this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) by DigitalOcean for that).

Hi @poyea, I came across with an implementation of the [secand method](https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/secant_method.py) in which many improvements can be done. Should I just modify that file or add a new algorithm?

**Comment by KaLiMaLi555** [comment]
Hi, I wanted to add a implementation for a Data-structure called KD-Tree. It has various uses like multi-dimensional partitioning and searching. Is it a nice idea? If so where should I add it?

**Comment by dark00infinity** [comment]
solution of euler problem38 added #3452 . all checkpoint pass

**Comment by shabab477** [comment]
Can anyone look into [3468](https://github.com/TheAlgorithms/Python/pull/3468)? Thanks! 😄

**Comment by cybov** [comment]
Can someone pls look into my PR #3420

**Comment by shabab477** [comment]
@cclauss, @poyea could you look into [3468](https://github.com/TheAlgorithms/Python/pull/3468)

**Comment by skhurana852** [comment]
Hi, I would like to add implementation for Banker's Algorithm which is a deadlock detection algorithm that uses 2d arrays. Can I contribute?

**Comment by cclauss** [comment]
@skhurana852 https://github.com/TheAlgorithms/Python/search?q=Banker

**Comment by BasilVictor** [comment]
@poyea or any of the other project maintainers, I have created a program and have created a PR, but there has been no response of any sort 😔
Can someone review #3512 and give any feedback if any, so that even I can contribute here.

**Comment by cclauss** [comment]
@BasilVictor There are 460+ open PRs on this repo and before Hacktoberfest started there were 30.  All maintainers are snowed under with the silliness of Hacktoberfest on a set of tasks that we do for no remuneration.

Is your algorithm (#3512) really differentiated from / better than [all the other distance algorithms in this repo](https://github.com/TheAlgorithms/Python/search?q=distance)?  You have checked the box `I have read CONTRIBUTING.md.` but your submission contains no type hints, no doctests, a function name that is not in snake_case, and no URL to a source describing the algorithm.

**Comment by GGn0** [comment]
Hello maintainers!
I think there might be a problem with the PR #3110
One of the two Travis CI checks seems to be still in progress (for over 16 days!)
but clicking the details shows that the build passed after 19 minutes [here's a link to the build](https://travis-ci.com/github/TheAlgorithms/Python/builds/189058683)

**Comment by SOUMEE2000** [comment]
Hello @cclauss. This is my first time contributing to anything. So basically, I submitted three PR s that are for the c language directory. A stupid question, but can they be thought of as participating for hactoberfest?

**Comment by shabab477** [comment]
@dhruvmanila could you look into #2510

**Comment by shabab477** [comment]
@dhruvmanila @cclauss, @poyea could you look into [3468](https://github.com/TheAlgorithms/Python/pull/3468). Thanks!

**Comment by cclauss** [comment]
@shabab477 https://github.com/TheAlgorithms/Python/issues/2510#issuecomment-701540969

**Comment by sonechca** [comment]
I would like to create a web crawler to find jobs at StackOverFlow :)

**Comment by cclauss** [comment]
Just do it!

**Comment by shabab477** [comment]
@sonechca would definitely use the script

**Comment by cclauss** [comment]
We started with 30 open PRs and ended with 521.

**Comment by shabab477** [comment]
Thank you, all the maintainers of this project for showing patience while participating in this event. Love you all <3
