### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by irokafetzaki** [TheAlgorithms/Python#256]
Hello, 

My name is Iro Kafetzaki and I'm studying in the third year at the Athens University of Economics and Business in the Department of Management Science and Technology.  In terms of a lesson called Software Engineering in Practise and as I'm interested in algorithms that can be used for operational research I would like to ask you if I can contribute to your project in the "searches" folder and contribute tabu search for a Traveling Salesman Problem -TSP written in python.

Thank you in advance.

**Comment by harshildarji** [comment]
Hello @irokafetzaki,
This is an open source repository and any one can contribute in this repository. All your contributions are highly welcomed.
Thank you.
