### ISSUE TITLE
math/extended_euclidean_algorithm cannot properly handle negative numbers

### ISSUE THREAD

**Issue by pikulet** [TheAlgorithms/Python#2630]
![image](https://user-images.githubusercontent.com/24848927/94875997-fbb5ef80-0488-11eb-8010-e46e1bd56201.png)

Think there is a mistake in the algorithm implemented.
By definition, gcd (a,b) = gcd (a,-b) = gcd (-a,b) = gcd (-a,-b)

So for a = 1, b = 4, the gcd is 1.

eqn1: 0(4) + 1(1) = 1 (correct)
eqn2: 0(4) + 1(-1) = -1 (sign incorrect)
eqn3: -1(1) +  1(-4) = -5 (sign and value incorrect)
eqn4: 1(-1) + 0(-4) = -1 (sign incorrect)

**Comment by dhruvmanila** [comment]
Hey, thank you for pointing this out. It also seems that the Euclidean algorithm for GCD is not able to handle negative numbers as well:

```console
$ python greatest_common_divisor.py
Enter two integers separated by comma (,): -3,9
greatest_common_divisor(-3, 9) = -3
By iterative gcd(-3, 9) = 3

$ python greatest_common_divisor.py
Enter two integers separated by comma (,): 3,-9
greatest_common_divisor(3, -9) = 3
By iterative gcd(3, -9) = -3

$ python greatest_common_divisor.py
Enter two integers separated by comma (,): -3,-9
greatest_common_divisor(-3, -9) = -3
By iterative gcd(-3, -9) = -3

$ python greatest_common_divisor.py
Enter two integers separated by comma (,): 3,9
greatest_common_divisor(3, 9) = 3
By iterative gcd(3, 9) = 3
```
Can you make two ***separate*** PRs to correct the algorithms?

**Comment by Mianto** [comment]
Hey, I am Siddhant Shaw. I would like to work on this issue.
