### ISSUE TITLE
Issue related to addition. 

### ISSUE THREAD

**Issue by CodeWithPython57** [TheAlgorithms/Python#2661]
In the Maths folder there is add. py file.  So that is used for addition of two numbers. You must have to implement it and use it in a way so that user can enter N number and get the addition. Also you have to use try/except just because if someone uses string.

**Comment by MANYAJAIN195** [comment]
I would like to work on this issue.

**Comment by Kush1101** [comment]
It's a very trivial problem and there is no need for another algorithm for this. We can simply make recursive calls to the add function to add n numbers. Please bring forward some genuine ideas/implementations to contribute.
