### ISSUE TITLE
Add games folder

### ISSUE THREAD

**Issue by Sreehith128** [TheAlgorithms/Python#2673]
I want to add  simple games made using pygame api.

**Comment by Sreehith128** [comment]
Pygame is python module where we can make simple games which were build in old phones.This adds a new folder which enhances this repo.

**Comment by Pranathi6767** [comment]
Hello! I will be delighted to help u in any way. I have developed a snakegame which runs from the command line.  Using pygame module. It would be great if i can collaborate.

**Comment by NicholasACTran** [comment]
Making simple games does not seem like it would fit in this repo's goal

**Comment by dnga8** [comment]
Would be cool to have a game like Tapper with a Hacktoberfest theme!

**Comment by xcodz-dot** [comment]
Well I think this repository is for algorithms not the complete product

**Comment by mrmaxguns** [comment]
An algorithm produces side-effects in rare cases. You can implement algorithms used in games, but I don't think implementing a game would fit the definition of "algorithm".

**Comment by dhruvmanila** [comment]
As mentioned in the previous comments, a game wouldn't fit in this repository. The algorithm used to implement some functionality might be, but not the entire module. If you want to submit an algorithm, please go through the Contributing guidelines and open a pull request for it. 

Closing this issue.
