### ISSUE TITLE
Add more solutions to Project Euler problems

### ISSUE THREAD

**Issue by aceking007** [TheAlgorithms/Python#2695]
Project Euler has about 700 problems, but the current repository hosts solutions for only about 60-70 problems.   
I'm willing to work on the issue and also if someone wants to help they can join in.  
We can create guidelines on how many minimum solutions a PR should have to prevent spammy PRs with just one or two easy solutions. (open to discussion)

**Comment by dhruvmanila** [comment]
As of now, we are only accepting PRs with one algorithm in it as it is easier to review one file at a time.
Feel free to open PR for whichever problem you have solved provided the answer is correct.

Anyone reading this can join and open PRs as well. We accept multiple solutions to a problem as everyone has their own approach to problem-solving but it should be their own and unique compared to other solutions. 

**NOTE:** Please give us time to review as there are so many to go through. If possible submit one PR at a time and when that is merged provided it passes all the automatic tests, you can submit another PR.

***One step at a time***

**Comment by RGarg2002** [comment]
Where can I get the problems from?

**Comment by berry-thawson** [comment]
https://projecteuler.net/
Hope this helps

**Comment by RGarg2002** [comment]
Thanks it helped🙂

**Comment by hbarovertwo** [comment]
I would love to join and contribute. Project Euler was always fun to me back in college :)

**Comment by berry-thawson** [comment]
Hi,
When there is a program for which input is presented as a file, how should the input be coded?
Should it be hardcoded in the file or should it be reading from a file relative to the directory?

**Comment by dhruvmanila** [comment]
@berry-thawson Please refer to [problem_54#L367-L369](https://github.com/TheAlgorithms/Python/blob/master/project_euler/problem_54/sol1.py#L367-L369)

```python
import os  # with other imports
...

def solution():
    script_dir = os.path.abspath(os.path.dirname(__file__))
    <file_name_without_extension> = os.path.join(script_dir, "<file_name>")
    with open(<file_name_without_extension> , "r") as file_hand:
        # ... your code ...
```

- Instead of `<file_name>` add the name of the file you want to import.
- Instead of `<file_name_without_extension>` add the variable name which is descriptive. If possible choose the name as the file name but without the extension.
- Then using `with` do whatever you want to do with the contents of the file.

I hope this explains your doubt. If you still have any problem, don't hesitate to ask.

**Comment by berry-thawson** [comment]
Thanks @dhruvmanila 
This is helpful

**Comment by appsx13** [comment]
Hi, can we add solution to any problem?

**Comment by Hyftar** [comment]
Hi, I added two PR to add solutions to new problems: #3018 and #3016

**Comment by manthan2501** [comment]
I am good at maths and would like to contribute in this. kindly assign me this work.

**Comment by Hyftar** [comment]
> 
> 
> I am good at mathematics and would like to contribute in this. kindly assign me this work.

Hi @manthan2501, you can start by solving problems that aren't yet in this repository on https://projecteuler.net/archives. You don't need to be assigned to this issue to contribute.

**Comment by pedabraham** [comment]
I would like to add a readme to each problem already solved, well I already made it in my local repository, but should I do a PR for every problem or one PR for all the problems?

**Comment by dhruvmanila** [comment]
Please don't submit PRs for the solutions which already exist in the repository. This issue is meant to increase the number of solved problems and not to increase the number of solutions in a problem. 

Open ***ONLY*** one PR at a time and when that is merged, open another one.

**Comment by flick-23** [comment]
I want to submit my solutions. How do i submit ?

**Comment by shubhranshubhoi78** [comment]
I'm a keen Euler solver.please let me help in providing efficient solutions to the problems.

**Comment by unbeatable01** [comment]
I would like to contribute.

**Comment by maanpatel2492** [comment]
@aceking007 In these issue
we have to give a solution to the project Euler problem right?

**Comment by deepanshuoct12** [comment]
hey I also want to join,please can u let me know how many problems we need to solve?and in which language?

**Comment by aceking007** [comment]
> @aceking007 In these issue
> we have to give a solution to the project Euler problem right?

@maanpatel2492  Yes. Any project Euler problem that doesn't have a solution yet in the repo.  
Please refrain from submitting solutions for previously solved problems and adhere to the recommended guidelines.

**Comment by aceking007** [comment]
@deepanshuoct12 Submit a PR containing the solution to **one unsolved** project Euler problem. The language is Python.

**Comment by AkshitAggarwal** [comment]
Doesn't the Project Euler website specifically say not to post solutions to the problems publicly?

**Comment by aceking007** [comment]
According to the FAQs, it seems that Project Euler has directly denied everyone to publish the answers to the questions freely.

>**I learned so much solving problem XXX so is it okay to publish my solution elsewhere?**
It appears that you have answered your own question. There is nothing quite like that "Aha!" moment when you finally beat a problem which you have been working on for some time. It is often through the best of intentions in wishing to share our insights so that others can enjoy that moment too. Sadly, however, that will not be the case for your readers. Real learning is an active process and seeing how it is done is a long way from experiencing that epiphany of discovery. Please do not deny others what you have so richly valued yourself.

But ...
1. They've got no ownership over your solution. They can make a gentle request that, in the spirit of Project Euler, you will not ruin the challenge for others, but that's all they can do--make a gentle request. In the end, the code is yours, and what I do with it is your decision.
2. The point of the rule is to prevent the challenge from being ruined for others. If Project Euler questions (and solutions) remain clearly marked as such, the challenge can only be ruined for someone who does not care about the challenge in the first place--someone who deliberately clicks a link knowing it contains a Project Euler solution.
3. The answers are already out there. Don't believe me? Google "Project Euler answers". Moreover, Project Euler knows the answers are out there. As such, they have this disclaimer:

>**DISCLAIMER**
>The popularity of Project Euler has increased tremendously over the years since its inception through the concerted effort of numerous people.
>Members have generally taken pride in showing their achievements. The obvious place to do so is the forum that is set up for each problem. However the increasing popularity has also been attracting people with a different agenda. With so many internet sites publishing answers for the PE problems instead of using the forum on this site, some people now seem to take pride in gathering and submitting those answers for whatever reason.
>It is humanly impossible for Project Euler, or indeed any member, to reliably differentiate those people from members that have solved the problems under their own steam. The ranking lists on Project Euler should be interpreted for what they are: an indication of the number of correct answers submitted by the member in question and validated by our answer checker. Individual members themselves know best what they have achieved on their own. Laying too much stress on competition might spoil the fun of problem solving which is one of the purposes of Project Euler. Also, any claim from a member about his own achievement cannot be supported as trustworthy by Project Euler. If critical, other means from third parties would be required to verify such claims.
>Providing quality problems for entertainment and educational purposes will continue to be the main goal of Project Euler, regardless of the intentions of a minority of the members.

They also have the following FAQ put up on their site:

>**I solved it by using a search engine, does that matter?**
Making use of the internet to research a problem is to be encouraged as there could be hidden treasures of mathematics to be discovered beneath the surface of many of these problems. However, there is a fine line between researching ideas and using the answer you found on another website. If you photocopy a crossword solution then what have you achieved?

Thus, Project Euler is not an official competition and you won't get anything because of participating (except the "joy" of solving a problem by yourself and the **"Eureka"** moment. It does post some guidelines regarding the questions and how to discuss the answers. But if you post the solutions, explicitly marking what question it belongs to, you don't interfere with the spirit of the whole endeavor, as only people who are interested in *"cheating"* would open that link before solving a question. It's more of a moral code that you should stick with.

**Comment by heyyviv** [comment]
Error: Process completed with exit code 1.
how to get rid of this error

**Comment by frextrite** [comment]
Hey, could you please tell if I should create an issue before working on a problem (so that other contributors know which problem I'm currently working on and there is no clash) or should I go ahead without creating an issue? (I'm planning to submit it over the weekend)

**Comment by dhruvmanila** [comment]
@frextrite You can open a draft PR with an empty file in the project directory, but only if you're submitting a problem that doesn't exist in this repository.

**Comment by subnut** [comment]
@dhruvmanila What do you have to say about this ...
![Screenshot_2020-10-16 Problem 3 - Project Euler](https://user-images.githubusercontent.com/56714626/96277701-3cb61400-0ff2-11eb-99f0-7f3ae6df0a10.png)

**Comment by alins1r** [comment]
hi sir can i make a fork to working on solution of PE problem no.38 i know how should i solve it right now and i want to be part of this hacktoberfest i solve it with on for loop and one while loop

**Comment by Ed1123** [comment]
Working on [problem 84](https://projecteuler.net/problem=84), please consider choosing another. It is almost done, but I have to wait my other PR to be merge (1 PR at a time). ☺️

**Comment by dhruvmanila** [comment]
I'm closing this issue due to the following reasons:
- There have been a lot of spam pull request.
- Pull request where the user didn't bother to read the guidelines provided.
- Duplications where multiple pull request submits solutions to the same problem.
- Submission for the problems which already exist in this repository. 

Thank you for your contributions!
