### ISSUE TITLE
Fix crawler for Instagram

### ISSUE THREAD

**Issue by DmytroLitvinov** [TheAlgorithms/Python#2699]
When running test locally, it throws next error:
> FAILED web_programming/instagram_crawler.py::web_programming.instagram_crawler.test_instagram_user

If we check [Instagram of the user GitHub](https://www.instagram.com/github/), we will see that the link is `https://github.com/readme/wes-mckinney`. Seems like GitHub user changed his link after [the latest CI build](https://travis-ci.com/github/TheAlgorithms/Python/jobs/394543248).

**Comment by dhruvmanila** [comment]
Hey, @DmytroLitvinov thanks for pointing this out. Can you show us the exact output of the error?

**Comment by DmytroLitvinov** [comment]
Currently I am not at PC. I will provide the output in ~1 day.

**Comment by DmytroLitvinov** [comment]
Hi @dhruvmanila ,

Seems like [GitHub](https://www.instagram.com/github/) changed back to URL "https://github.com/readme". No reason seems to merge this PR.

**Comment by dhruvmanila** [comment]
Alright, then please close this issue and your PR as well.
