### ISSUE TITLE
Adding Reinforcement Machine Learning models

### ISSUE THREAD

**Issue by anushka0301** [TheAlgorithms/Python#2701]
I didn't found any Reinforcement Machine Learning models in the machine learning folder. I would like to contribute to the same and add the UCB and the Thompson Sampling algorithms.

**Comment by dhruvmanila** [comment]
This sounds interesting! Please read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) and open ***separate*** PR for both algorithms.
