### ISSUE TITLE
server.py : Error

### ISSUE THREAD

**Issue by christianbender** [TheAlgorithms/Python#288]
See the file [here](https://github.com/TheAlgorithms/Python/blob/master/server.py)

> Traceback (most recent call last):
  File "/home/christian/Programmierung/GitHub/Python/server.py", line 29, in <module>
    t.bind()
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: bind() takes exactly one argument (0 given)

The error above occures by python 2 and python 3.

**Comment by harshildarji** [comment]
**bind()** takes address as the argument. 
For example:
```python
HOST = 'localhost'
PORT = 1994
# socket initialization task goes here
socket.bind((HOST, PORT))
```

**Comment by christianbender** [comment]
@harshildarji super!
