### ISSUE TITLE
[Web Programming] Can I add files?

### ISSUE THREAD

**Issue by anaghkanungo7** [TheAlgorithms/Python#2915]
Hi There!

I would like to contribute to expanding the Web Programming section of this repository. I have a couple of Python projects in mind which use free API services to fetch data. They are useful programs like the ones already in the directory. 

So, can I contribute to the web programming directory? I just wanted to ask for permission since I could not find a clear answer for this in the Contributing.md file.

Thanks!

**Comment by dhruvmanila** [comment]
Sure. Why not! 
- Make sure to read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) before opening a PR.
- Include type hints and tests (`doctest` or `pytest` or `unittest`)
- Format the code with `black` and `isort`
- Check it with `flake8`, `mypy`

P.S. If you don't want to use the formatter and linters mentioned above, you can use `pre-commit` as it is enabled for this repository.
