### ISSUE TITLE
[Hacktoberfest] Need some quantum algorithms!

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#2923]
https://github.com/TheAlgorithms/Python/tree/master/quantum has no algorithms!

**Comment by PranavMurali** [comment]
what kind of algorithms are you expecting? @cclauss

**Comment by Elrashidy-Ahmed** [comment]
I am a physics major and I would love to give it a shot. I think a quantum random number generator would be a place to start. The  QRNG@ANU JSON API is fairly straight forward to deal with. https://qrng.anu.edu.au/contact/api-documentation/ 
I will try to get that done within a week or so. 

Also, converting the code here to functions and classes is a nice idea.
https://qiskit.org/textbook/preface.html

Qiskit is probably the best place to start implementing quantum algorithms. I have jotted a few ideas that combine quantum computing and deep learning and look forward to seeing how far things will go.

**Comment by MrIceman** [comment]
Quantum has algorithms, they just don't exist yet... or maybe they do? :-)

**Comment by prakhargurunani** [comment]
@cclauss I have added Breast Cancer detection algorithm https://github.com/TheAlgorithms/Python/pull/2983.

**Comment by abhishekjiitr** [comment]
Started with just a bare-minimum quantum circuit PR for starters, can anyone take a look?
https://github.com/TheAlgorithms/Python/pull/3173

Looking to add code samples of increasing difficulty in future! :clinking_glasses:

**Comment by beardedasianlad** [comment]
I'm going to attempt to tackle Deutsch-Jozsa Algorithm with qiskit this week.
