### ISSUE TITLE
[Not Needed] Multiple implementation for stale bot

### ISSUE THREAD

**Issue by Gau02** [TheAlgorithms/Python#2969]
I could see multiple implementation of stale bot 🤖. Do we really require both implementations? 🤔 

1. https://github.com/TheAlgorithms/Python/blob/master/.github/stale.yml
2. https://github.com/TheAlgorithms/Python/blob/master/.github/workflows/stale.yml

P.S. looks like workflow automation is more active than stale bot.

**Comment by dhruvmanila** [comment]
Hi, sorry for being so late. You're correct. https://github.com/probot/stale-action
Stale action has been deprecated for the new workflow which we also have. So, if you want you can open a PR removing the old `.github/stale.yml` file.
