### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [TheAlgorithms/Python#297]
Greetings @TheAlgorithms ,

I'm a Graphic Designer interested in collaborating 
with this project by delivering a _free_ logo proposal
if this is something that interest this project, let me know

Cheers!
-Luigi.

**Comment by dynamitechetan** [comment]
Sure @LuigiBaute. You can create some designs and post them in the issue. We are excited to see your work 🙌🏻.

**Comment by LuigiBaute** [comment]
![logotipo python 2018](https://user-images.githubusercontent.com/36426974/40211158-f79318b6-5a16-11e8-8d84-f04af4cc6b02.jpg)
this is my proposal

**Comment by yesIamHasi** [comment]
I like the 1st and 4th.

**Comment by LuigiBaute** [comment]
Oh thank you, I'm really glad you like'd em @dynamitechetan @yesIamHasi 

 but which one of these are you going to use in this project?

 so I'll submit a pull request with the logo and I'll give you all the logo monochromatics in a google drive link for any future updates :+1:

**Comment by LuigiBaute** [comment]
Hello again @dynamitechetan did you like this logo? 
I can come up with something new if you think that this one doesn't fit well for the project :+1: 
I'd like to know what you tought about these ones! thanks.

**Comment by dynamitechetan** [comment]
Hi. We liked your designs but we cannot set icons for individual repositories. We have a icon for a organisation. This icon is specific for the Python Repo. Can you please make some icon for the Organisation i.e The Algorithms.

**Comment by LuigiBaute** [comment]
Ok! I understand, I'll try to follow the same style I used on this logo and see what I came up with. 
Thanks @dynamitechetan

**Comment by LuigiBaute** [comment]
Hey @dynamitechetan  
This is what I came up with
I hope you like it!!
Any suggestions?
I'd like to know what you think about it.


![logotipo python 2018](https://user-images.githubusercontent.com/36426974/40572608-5cd046a0-607e-11e8-9c24-4c72adac83f6.png)

**Comment by harshildarji** [comment]
Hello @LuigiBaute,
I appreciate your work brother. One mistake is, you wrote **The Algorithm** instead of **The Algorithms**. The noun, **Algorithm** should be **plural** in this context. And I think logo will look better without name in it (_this is just my suggestion_). By the way, the last decision is of @dynamitechetan.
Thank you.

Best regards,
Harshil Darji

**Comment by LuigiBaute** [comment]
Hello @dynamitechetan  @harshildarji  what do you think of this ones?
hope you like it 
![logotipo python3 2018](https://user-images.githubusercontent.com/36426974/40581205-56d69626-6120-11e8-86ba-5009bf329ffc.png)
![logotipo python 2018 1](https://user-images.githubusercontent.com/36426974/40581206-5d3964f8-6120-11e8-9b0d-7f8af42b9682.png)

**Comment by LuigiBaute** [comment]
Hello @harshildarji ,

Don't worry I'll delete the name,
where can I make the pull request?

**Comment by harshildarji** [comment]
Hello @LuigiBaute,
One cannot change the logo of the organization by merging a pull request. Only owners have the rights to do it, which in this case, are @dynamitechetan, @AnupKumarPanwar, @r0hit-gupta and @sachinarora707! You can send logo to them (_or to anyone of them_), and they can manually change it from settings.
Thank you.

Best regards, Harshil Darji

**Comment by LuigiBaute** [comment]
Hello! @r0hit-gupta  ,

by the same color, you mean the dark gray color of the book as an square icon? 

I'm really glad you liked the logo :+1:

**Comment by r0hit-gupta** [comment]
@LuigiBaute yes. That is what I meant exactly.

**Comment by LuigiBaute** [comment]
Ok @r0hit-gupta

I'll make the update and tag you when ready :)

**Comment by LuigiBaute** [comment]
![4 1](https://user-images.githubusercontent.com/36426974/40591130-51fccd78-61d9-11e8-9823-c64fdd52e8be.png)
 
@r0hit-gupta

**Comment by r0hit-gupta** [comment]
Great work @LuigiBaute. I have updated the logo. 🎊

**Comment by harshildarji** [comment]
Hello @LuigiBaute @r0hit-gupta,
As logo is updated and there is nothing else to discuss at this point, I am closing this issue now. If there is anything remaining to work on, we will surely reopen it!
By the way, thank you @LuigiBaute for providing us a new logo ;)
Thank you.

Best regards,
Harshil Darji

**Comment by LuigiBaute** [comment]
Sure @harshildarji ,

here is the [google drive](https://drive.google.com/drive/folders/1sUJ1U5z94c8f-pHaVCMuJ2uHeMJ6VKuv?usp=sharing) links with all the necessary versions of the logo if you ever need it to update, 
and thanks for letting me a part of this project
@r0hit-gupta @dynamitechetan 

Best Regards.
