### ISSUE TITLE
The taste of selection_sort and merge_sort is not good.

### ISSUE THREAD

**Issue by yesIamHasi** [TheAlgorithms/Python#299]
All the sorting algorithms are implemented in Python using C++ thinking which makes the code execution time too high.
The current selection sort algorithm is 65% slower, merge_sort algorithm is 10^4 times slower.
Here's timeit result.
![screenshot from 2018-05-19 18-15-11](https://user-images.githubusercontent.com/28681929/40268971-0b390986-5b91-11e8-9cb6-5a2d2abe28c6.png)
[Here](https://github.com/yesIamHasi/EngineeringAlgorithms/blob/master/selection_sort.py) is a better taste of selection sort.
[Here](https://github.com/yesIamHasi/EngineeringAlgorithms/blob/master/merge_sort.py) is a better taste of merge sort.
Tell me what you think about it?
Should I add it to TheAlgorithms/Python/sorts ?

**Comment by harshildarji** [comment]
@yesIamHasi We have reviewed your [merge short](https://github.com/TheAlgorithms/Python/pull/301) commit and we are on our way to merge it. Your are welcomed to submit the pull request of selection sort too.

Best regards,
Harshil Darji
