### ISSUE TITLE
Should we implement CODEOWNERS for the directories of this repo?

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#3011]
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners

Maintainers could volunteer to be assigned to all new PRs for particular folders in the repo this would mean that a maintainer would have 5 or 10 pull requests to review in topic areas that they are interested in instead of wading thru the current 224 open PRs.

**Comment by dhruvmanila** [comment]
This would be extremely useful but there's some caveats:
- We have over dozens of directories (around 40)
- If a maintainer is responsible for 5 directories, we need over 8 of them. This is assuming that we will divide it by 5, if it is less, then more number of maintainers will be required.
- I might be wrong but I don't think we have that many active maintainers.

**Comment by cclauss** [comment]
Is it possible to start with a partial implementation?  Just a few directories are assigned to just a few maintainers and the other directories have no owners? I would be interested to be assigned:
* .github
* ciphers
* conversions
* data_structures
* others
* strings
* web_programming

**Comment by dhruvmanila** [comment]
Yeah that would be fine. I haven't actually looked at all the directories to decide for myself, but to start I will take the entire `project_euler` directory. I am also interested in Machine Learning and Neural Networks. 

I will create a PR for this but before that can you take a look at #2973 ?
