### ISSUE TITLE
Fetch You Tube Comments

### ISSUE THREAD

**Issue by pikachu28** [TheAlgorithms/Python#3022]
Fetching You tube comments for a particular video and adding the file in web_programming directory

**Comment by pikachu28** [comment]
Do we have get assigned for issues we created. If yes, pls assign this issue to me : )

**Comment by dhruvmanila** [comment]
This is not an issue. If the algorithm isn't present then you can open a PR for it assuming that you read CONTRIBUTING.md and passed all our automated testing ***BEFORE*** opening the PR.
