### ISSUE TITLE
Markov Model Algorithms

### ISSUE THREAD

**Issue by NicholasACTran** [TheAlgorithms/Python#3027]
Would there be interest in adding algorithms that relate to Markov models, e.g. Viterbi's Algorithm, Metropolis-Hastings, Hamiltonian Monte Carlo, etc.? I looked and couldn't find any implementations of these types of algorithms.

**Comment by dhruvmanila** [comment]
Sure, why not? 
- Read CONTRIBUTING.md
- Make sure all our automated tests are passing ***BEFORE*** opening the PR
- Open the PR for one algorithm at a time
