### ISSUE TITLE
A new data structure proposal 

### ISSUE THREAD

**Issue by kaynaat007** [TheAlgorithms/Python#303]
Greetings @TheAlgorithms ,

I wish to contribute to this project by proposing to add a new data structure called Binary Indexed Tree. 
How can i start ? 
Any suggestions ?

regards,
Nikhil.

**Comment by harshildarji** [comment]
Hello @kaynaat007,
Fork this repository (_if you haven't forked it yet_), Clone it and Commit your (_working_) files in your forked repository and then simply make a PR!
Also, I am sure [this](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) will help you.
Thank you.

Best regards,
Harshil Darji
