### ISSUE TITLE
Add scoring functions for binary classification tasks

### ISSUE THREAD

**Issue by 0Zeta** [TheAlgorithms/Python#3038]
- Precision (https://en.wikipedia.org/wiki/Precision_and_recall#Definition_(classification_context))
- Recall (https://en.wikipedia.org/wiki/Precision_and_recall#Definition_(classification_context))
- F1 (https://en.wikipedia.org/wiki/F1_score#Formulation)

**Comment by dhruvmanila** [comment]
Open a PR if you want to submit an algorithm, not create an issue.
