### ISSUE TITLE
Parallel / distributed implementations of algorithms ♾️

### ISSUE THREAD

**Issue by zhe-thoughts** [TheAlgorithms/Python#3095]
Background: I am from the Ray team (https://github.com/ray-project/ray) and Ray's goal is make parallel / distributed Python as easy as with a simple process. So I was very excited to find this repo, which is a goldmine of good challenges 😉 Because, well, algorithms should be fast

I will start to implement some algorithms here in parallel / distributed manner. But if you are interested please write your suggestions on this thread (as for which algorithms you think I should try). 

I'll maintain a list of implemented algorithms with live edits:

1. Distributed quick sort: #3100

**Comment by zhe-thoughts** [comment]
Implemented distributed Quick Sort #3100

**Comment by rangira** [comment]
I can do parallel dfs and bfs

**Comment by zhe-thoughts** [comment]
@rangira Yes please!

**Comment by xcodz-dot** [comment]
hello, I was thinking to simplify the process much more by simply making a script which can easily find packages and package them into a single package and then make 2 types of PyPI distributions. sdist (Source Distribution), bdist_wheel (The Python Wheel Distribution). This process would not require any new branch or repository.
