### ISSUE TITLE
Pull request closed without a given reason

### ISSUE THREAD

**Issue by ronnydw** [TheAlgorithms/Python#3096]
My pull request #3071 was closed without a given reason.
I don’t mind it being closed without merging but I would like to learn why.
After all learning is the main purpose of this repo, no?

**Comment by dhruvmanila** [comment]
The reason was given as the label `invalid`, as it was an extremely minor change which was not needed.

**Comment by ronnydw** [comment]
Ok, fine for me, but take into account:
1. replacing list comprehension by generator expression is not always an "extremely" minor change, see https://www.python.org/dev/peps/pep-0289/. I could have reported a bug that the algorithm does not work on low-memory machines when n is large (Out of memory exception).
2. If this was not clear I would at least expected a request/comment to clarify instead of closing the pull request without further notice
3. where can we find an explanation of the label #invalid?

I would propose the following **process improvement**:
Create a **guideline for administrators**
- every update should be encouraged, how little it the improvement might be. Stimulating learning is the main goal of this repo.
- before merging or rejecting a pull request 2 admins have to approve (especially for admins who are new to the project)
- every rejection should be accompanied by a comment explaining why the pull request was rejected
- in case of doubt write a comment for the author and ask for further clarification
