### ISSUE TITLE
Redundant parameters in SegmentTree

### ISSUE THREAD

**Issue by AnshulMalik** [TheAlgorithms/Python#310]
[here](https://github.com/TheAlgorithms/Python/blob/master/data_structures/Binary%20Tree/SegmentTree.py) `st.query(1, 1, N, ...)` the first three parameters are unnecessary. We are using class but not taking advantage of it.

The same thing is with other classes as well.

**Comment by harshildarji** [comment]
Hello @AnshulMalik,
It would be really great if you can submit a pull request to update the current scripts.
Thank you.

Best regards,
Harshil Darji

**Comment by AnshulMalik** [comment]
But this is a valid issue isn't it? So I think it should be open until resolved.

**Comment by harshildarji** [comment]
Hello @AnshulMalik,
Actually, I was in hurry, and so instead of **Comment**, I clicked on **Close**. Thank you for pointing it out and sorry for my mistake.

Best regards,
Harshil Darji
