### ISSUE TITLE
Hello @poyea, I would like to contribute to your repository that I have build one `Deep Neural Network` (Research Work) for greater accuracy .

### ISSUE THREAD

**Issue by radadiyamohit81** [TheAlgorithms/Python#3119]
Hello @poyea, I would like to contribute to your repository that I have build one `Deep Neural Network` (Research Work) for greater accuracy .
Can I contribute it to this repository?

_Originally posted by @radadiyamohit81 in https://github.com/TheAlgorithms/Python/issue_comments/705944946_

**Comment by dhruvmanila** [comment]
Please open a pull request to submit an algorithm instead of an issue.
