### ISSUE TITLE
Use consistent directories and file naming

### ISSUE THREAD

**Issue by AnshulMalik** [TheAlgorithms/Python#315]
Currently, the directories and files don't follow a convention, some are `snake_case`, some `PascalCase`. We should stick to a convention.

**Comment by elpaxoudis** [comment]
Greetings, I was going to start the same idea in a personal project but then I stumbled upon this one. So, I was thinking maybe I could contribute to this one instead.

I have never contributed to an open source project before. However, I could easily try this issue as my first. What do you think?

By the way I think that an all lower case convention is a suitable one if we consider them as [modules/packages](https://www.python.org/dev/peps/pep-0008/#package-and-module-names).

**Comment by AnshulMalik** [comment]
Hey @elpaxoudis, Nice to have you here, you can definitely start with this one. And we can go ahead with snake case, as this is the standard.

**Comment by elpaxoudis** [comment]
Nice! Thanks @AnshulMalik for letting me work on this. Just one final question. Should I change the source .py files into `snake_case` too?

**Comment by AnshulMalik** [comment]
Yep @elpaxoudis

**Comment by cclauss** [comment]
Fixed in #993 and to be enforced in our Travis CI testing with #1005
