### ISSUE TITLE
Add Expression Tree in Binary Tree

### ISSUE THREAD

**Issue by jindalsachin** [TheAlgorithms/Python#3150]
**Description**
The expression tree is a type of  binary tree in which each internal node corresponds to the operator and each leaf node corresponds to the operand .
I would like to add Expression Tree in data_strucutre -> Binary Tree

**Comment by jindalsachin** [comment]
Please assign me this issue

**Comment by dhruvmanila** [comment]
Please open a pull request to submit an algorithm instead of an issue.
