### ISSUE TITLE
Readmes in each project euler problem.

### ISSUE THREAD

**Issue by pedabraham** [TheAlgorithms/Python#3157]
Hi @dhruvmanila  I would like to add a readme with the description of the problem to each problem already solved, well I already did it in my local repository, but should I do a PR for every problem or one PR for all the problems?

_Originally posted by @pedabraham in https://github.com/TheAlgorithms/Python/issues/2695#issuecomment-706398360_

**Comment by dhruvmanila** [comment]
Thank you for thinking about it but this is not needed as the problem description will always be present in the module-level docstring.

**Comment by pedabraham** [comment]
I get it, I thought that someone who is a foreigner to the problem and project Euler might want to check the problem before give it a try, anyway I already did a scrip which takes the problem from the project Euler web site and makes a readme.md, I will close the issue but if you change your mind in the future please let me know.
