### ISSUE TITLE
Fix needed for Project Euler problem 234 sol1.py

### ISSUE THREAD

**Issue by dhruvmanila** [TheAlgorithms/Python#3163]
### Problem:

According to the [problem description](https://projecteuler.net/problem=234), the input value for the function `solution()` should be `999966663333`. Now, if we follow the control flow of the problem we see that there's going to be a loop that will have `999966663333` many iterations and for each iteration [this line](https://github.com/TheAlgorithms/Python/blob/master/project_euler/problem_234/sol1.py#L43) asks the user for input. As mentioned in CONTRIBUTING.md, we cannot ask for input and this solution will be asking for the input for `999966663333` times.

```python
for x in range(n):  # n = 999966663333 according to the problem description
    l = [i for i in input().split()]  # noqa: E741
```

### Proposed solution:

1. Remove the current solution and implement a new one.
2. Take a look at the current solution and fix it.

The second solution is highly unlikely as I am not able to deduce what is actually going on in the function and why do we even need to ask for the input. If anyone can figure it out, they can submit a PR for this.

***I propose the first solution.***

Once the issue is fixed, we can start running this [script](https://github.com/TheAlgorithms/Python/blob/master/project_euler/validate_solutions.py) which checks for all answers to Project Euler problems.

**Comment by Harivind** [comment]
Hi @dhruvmanila, can I take up the issue?

**Comment by dhruvmanila** [comment]
@fpringle Can you take a look at this? Thanks if you do.

**Comment by Hyftar** [comment]
Hi, I will attempt to implement a new solution for this problem.
