### ISSUE TITLE
May I add Elgamal security system algorithm to “cipher” directory?

### ISSUE THREAD

**Issue by psyas** [TheAlgorithms/Python#317]
Hello world! I’m Sang Young Park, a student studying cryptography at South Korea
By the way, may I add The Elgamal security system code using python to this awsome project?

Best regards, Sang Young

**Comment by psyas** [comment]
Elgamal security system is similar to RSA algorithm, however it is based on discrete logarithm problem!

**Comment by harshildarji** [comment]
Hello @psyas,
As you already noticed that this is an open organization where everyone can contribute their ideas and algorithms, You're also welcomed to add the work you've done.
Thank you.

Best regards,
Harshil Darji
