### ISSUE TITLE
Add Generate Parentheses in backtracking section

### ISSUE THREAD

**Issue by rajapuranam** [TheAlgorithms/Python#3178]
Hi, I want add Generate Parentheses solution in backtracking section. 
Can you please assign me this issue?

**Comment by morenocl** [comment]
Please, assign this to me

**Comment by xcodz-dot** [comment]
well hello @morenocl, it seems that @rajapuranam asked to be assigned first

Also, you do not need to ask to be assigned, this repository does not require you all to do that, simply make a pull request. All the discussions are made there. **All the best** 👍

**Comment by dhruvmanila** [comment]
As mentioned in https://github.com/TheAlgorithms/Python/issues/3178#issuecomment-708319171
