### ISSUE TITLE
Python PyPI distribution for this repository so others can use it as a requirement

### ISSUE THREAD

**Issue by xcodz-dot** [TheAlgorithms/Python#3239]
We can make a simple setup.py file which packs the distribution into one package

I am working on a custom setup.py script for the same

My custom setup.py script will
* search for all package directory under root
* copy them to a new directory named python_algorithms
* make a standard source distribution (All requirements will be read from *requirements.txt*)
* cleanup

After all you will find the distribution under `./dist/` which will contain the file which can later be uploaded to [PyPI](https://pypi.org/).

**Comment by dhruvmanila** [comment]
This is a good idea but not appropriate for this repository. What we really want is automation for a lot of things. If you can try that, it would be more beneficial. Please mention what type of automation you want to build, if any.

**Comment by xcodz-dot** [comment]
Ok, thanks for the explanation, I will try automating new things soon 😄
