### ISSUE TITLE
Pathfinding algorithms

### ISSUE THREAD

**Issue by Rolv-Apneseth** [TheAlgorithms/Python#3260]
Hi, just wondering if adding some pathfinding algorithms implemented in python would be something I could contribute to this project? I have experience with these as I have built a pathfinding algorithm visualiser using pygame (repo here: https://github.com/Rolv-Apneseth/pathfind-visualiser)

**Comment by NumberPiOso** [comment]
Nice repo!

This kind of algorithms, like **A\*** and **Greedy** algorithms are included in searches section.

I suppose they would belong there.

**Comment by Rolv-Apneseth** [comment]
Ok, so should I do it as a grid of nodes which is printed to the console or it returns a path or what is best

**Comment by Rolv-Apneseth** [comment]
Or just an int of the shortest path length?
