### ISSUE TITLE
Browser Automation and web scrapping using selenium web driver in web_programming.

### ISSUE THREAD

**Issue by Kamesh-Mishra** [TheAlgorithms/Python#3326]
Problem Statement:
    Write a Python code to Scrap data from ICC Ranking's 
    page and get the ranking table for ODI's (Men). 
    Create a DataFrame using pandas to store the information.
  Hint: 
    https://www.icc-cricket.com/rankings/mens/team-rankings/odi

**Comment by Kamesh-Mishra** [comment]
I would like to work on this issue , can you please assign me !!

**Comment by mateuszz0000** [comment]
Go ahead!

**Comment by Kamesh-Mishra** [comment]
@mateuszz0000 need your help,, in my code O have two three files one is .py file which is my code second is requirements.text and this is .exe file which is webdriver.exe to run this file.   

here i detailed you about my code hope you will solve this issue. 
thanks
