### ISSUE TITLE
Python code that reverses the vowels in the given string

### ISSUE THREAD

**Issue by Jainesh18** [TheAlgorithms/Python#3362]
For example given a  string "hello programming" the code will reverse the vowels in the given string and will display "hilla progrommeng"

**Comment by sandeep3136** [comment]
assign to me

**Comment by aniketprasadgit** [comment]
I am interested in doing this assignment. Please assign to me if possible.

**Comment by gauravdatt2000** [comment]
please assign me i am interested

**Comment by YashJain2** [comment]
I want to work on this algorithm in python please assign me if possible

**Comment by spartaabhishek** [comment]
I would like to do it

**Comment by ishaanj2000** [comment]
pls assign it to me

**Comment by sudheer-kumar-kapalavai** [comment]
https://github.com/TheAlgorithms/Python/pull/3431 This has passed all the test cases. @Jainesh18 please approve

**Comment by nehalabhasetwar** [comment]
I would like to solve it , plz assign it to me

**Comment by Arushi04** [comment]
Is this still open? If yes, I would like to work on it.

**Comment by xcodz-dot** [comment]
this does not seems to be a useful algorithm at all and the work needed to this easy but you guys can still consider it.

Here is my very small version of it:

```python
def reverse_vowels(statement: str) -> str:
    character_list = list(statement)
    character_list.reverse()
    vowels_sequence = []
    for index in range(len(character_list)):
        if character_list[index].lower() in "aeiou":
            vowels_sequence.append(character_list[index].lower())
    character_list.reverse()
    for index in range(len(character_list)):
        if character_list[index].lower() in "aeiou":
            character_list[index] = vowels_sequence[0] if character_list[index].islower() else vowels_sequence[index].upper()
            vowels_sequence.pop(0)
    return ''.join(character_list)
```

**Comment by Sanchayan-Bhowal** [comment]
May I work on this issue

**Comment by dhruvmanila** [comment]
This doesn't seem like an issue. If you want to contribute an algorithm then please read through the Contributing guidelines and open a pull request for it.

Closing this.
