### ISSUE TITLE
Merge sort best & average case O(n)?

### ISSUE THREAD

**Issue by sfdye** [TheAlgorithms/Python#340]
https://github.com/TheAlgorithms/Python/blob/master/README.md#merge
Shouldn't it be O(n log n).

The Java repo is correct though:
https://github.com/TheAlgorithms/Java#merge

**Comment by pandyamarut** [comment]
it's O(n log n ) only.

**Comment by sumitkumar22299** [comment]
Yes! It should be O(n*log(n)) for every case i.e. best case, average case, worst case.

**Comment by hasangokdag** [comment]
Are you pointing out that there should be a "*" between n and log(n)?
like O(n log(n)) vs O(n*log(n))?

In readme file Merge, Quick and Shell is also using one space as multiplication instead of "*". Thats why I also used it that way in the PR.

**Comment by sfdye** [comment]
@hasangokdag No. In the master, best & average are `O(n)` which are simply incorrect and misleading.

**Comment by piyush-kgp** [comment]
Hi @sfdye ,  @hasangokdag  has corrected precisely what you are saying in his commit. Look at his commit: https://github.com/TheAlgorithms/Python/pull/342/commits/ce3e6787f4df7fa198881b1dfa80c58a5c7afbb5 
But his PR is still open, please be patient and let the repo owners merge his PR.

**Comment by sfdye** [comment]
@piyush-kgp Yeah I am aware of the PR. It should get high priority as this simple typo could fail someone's interview.

**Comment by piyush-kgp** [comment]
Yes. you are right. Just noticed that this thread is 9 days old. Apologies.

**Comment by AnshulMalik** [comment]
Thanks @hasangokdag

**Comment by sfdye** [comment]
Finally this is merged. Cheers 👍
