### ISSUE TITLE
Minor improvements to prime_check.py

### ISSUE THREAD

**Issue by Rolv-Apneseth** [TheAlgorithms/Python#3453]
Not necessary so feel free to close if you don't want it, but I made some minor improvements to prime_check.py by shortening it a bit and fixing some of the comments/docstring

**Comment by Bhaswati-Saha** [comment]
I would like to contribute. So please assigned it to me.

**Comment by Rolv-Apneseth** [comment]
I made the pull request already but if you know how to solve the issue I'm having with one of the checks that would be great
