### ISSUE TITLE
Create algorithm to rename all files with the given extension with random numbers in a folder

### ISSUE THREAD

**Issue by pedrosv20** [TheAlgorithms/Python#3532]
**DESCRIPTION** 
This is usefull when you want to create tests and train datasets and want to get the files in a random order.

**LANGUAGE**
Python

**Framework Used**
Glob

**Comment by neelthakker22** [comment]
I want this and know this, but I am not getting the random order naming thing. If you could please explain?

**Comment by pedrosv20** [comment]
Think that you have 20 frames of 2 different videos and want to randomly separate them to test if your image recognition algorithm works. Now imagine having 5000 frames from several different films, the random to rename them helps when accessing them to test the algorithm for example to be as random as possible

**Comment by neelthakker22** [comment]
ok, so naming could be with random numbers instead of sequence?

**Comment by pedrosv20** [comment]
yeah, in my first think i thought to do only random but i can make in sequence too

**Comment by neelthakker22** [comment]
okay, can you please assign it to me? I will try as this is my first try on Github and I don't know much about it.

**Comment by pedrosv20** [comment]
Sorry im confused right now. I thought that creating the issue here I would have to wait for someone to approve for me to code this.

**Comment by pedrosv20** [comment]
Sorry my friend, in this repo to add some code we need to just open it in the pull requests section.
