### ISSUE TITLE
Where can we add file functions ?

### ISSUE THREAD

**Issue by neelthakker22** [TheAlgorithms/Python#3562]
I am new to this, so please if someone would guide me where can I upload file functions python file?

**Comment by xcodz-dot** [comment]
Ok please clarify me,

Do you want me to tell you how to contribute a few functions which are in a file??

**Comment by xcodz-dot** [comment]
@dhruvmanila, how about closing this

**Comment by xcodz-dot** [comment]
Shall we close it? @cclauss

**Comment by cclauss** [comment]
@dhruvmanila It looks like you and @neelthakker22 are in the same state so I will let you decide.

**Comment by dhruvmanila** [comment]
@neelthakker22 What do you mean by file functions? What type of algorithm are you trying to submit? If you can be a bit more detailed, it would really help. Thanks if you do.

**Comment by xcodz-dot** [comment]
He asked this on 19 October, and does not seem to response

**Comment by xcodz-dot** [comment]
It about a month now

**Comment by xcodz-dot** [comment]
I think we will let it become stale or you might close it

**Comment by dhruvmanila** [comment]
Please feel free to reopen this issue if you feel it was not solved. Closing this for now.
