### ISSUE TITLE
Adding Weddles_rule method for integration

### ISSUE THREAD

**Issue by Suvadip-Universe** [TheAlgorithms/Python#3565]
Actually I am a beginner in Github. 
May I add this computing method?

**Comment by dhruvmanila** [comment]
Sure, why not!
If you want to submit an algorithm, please open a pull request for it ***after*** reading the [Contributing Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).

Closing this as it doesn't seem like an issue.
