### ISSUE TITLE
Hacktoberfest flooded this repository with pull requests

### ISSUE THREAD

**Issue by xcodz-dot** [TheAlgorithms/Python#3609]
If possible can we all please focus on pull request and close the unnecessary ones

**Comment by xcodz-dot** [comment]
dear maintainers, if possible please check this issue out.

 @cclauss @dhruvmanila

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/issues/2510#issuecomment-701540969

We should have a GitHub Action that autocloses PRs that do not have tests.

Criteria:
1. Search Python code for "`>>> `" and
2. Search Python filenames for test_*.py or *_test.py
    * https://docs.pytest.org/en/stable/goodpractices.html#conventions-for-python-test-discovery

If both of those tests fail then the Action shoul autoclose the PR with a note pointing the contributor to CONTRIBUTING.md.

**Comment by xcodz-dot** [comment]
Oh. I did not know that. Bye! Have a great day ahead.

**Comment by dhruvmanila** [comment]
Sorry I've been a bit busy, lot of things going on. This seems like a good idea, I will get onto it. One more thing we should do is use labels extensively. This will give a short summary of what is happening in a given PR and it will become the first point of contact between a maintainer and a user.

- [ ] Script for auto-closing PR which do not contain tests (any other conditions where auto-closing a PR would help?)
- [ ] Auto-label PRs?: tests are failing (I have already written a script for this using PyGithub library), merge-conflicts (search auto label merge conflicts) ...,
- [ ] Write a note for maintainers about the importance of labels
- [ ] IDEA for Project Euler PRs: As we don't want to be flooded with PRs for beginner level problems, I restricted to not submit problems that exist in this repository. Users still do that so make a script which will close them.

**Comment by cclauss** [comment]
> any other conditions where auto-closing a PR

No annotations (type hints).  I believe that this would require `inspect` or `ast`.

**Comment by xcodz-dot** [comment]
Auto-labelling is a good idea, i am not good at workflows but i will try out that part.

**Comment by xcodz-dot** [comment]
I was also thinking about this #3239, Any suggestions?

**Comment by poyea** [comment]
I see 10 open implementations for Problem 50 of Project Euler.

My opinion is for `hacktoberfest-accepted`, we may make it a bit lenient. I'm not sure if closing PRs with `hacktoberfest-accepted` tagged sounds logical or not.

**Comment by xcodz-dot** [comment]
hactoberfest counts any valid pull request so we do not need to specially mark them with labels, we only need to mark them when they are invalid

**Comment by poyea** [comment]
@xcodz-dot There're some updates this year: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by xcodz-dot** [comment]
Ok, thanks for letting me know. I logged into hactoberfest on 1st October and the article was released on 3rd October

**Comment by ronnydw** [comment]
> [#2510 (comment)](https://github.com/TheAlgorithms/Python/issues/2510#issuecomment-701540969)
> 
> We should have a GitHub Action that autocloses PRs that do not have tests.
> 
> Criteria:
> 
> 1. Search Python code for "`>>> `" and
> 2. Search Python filenames for test_*.py or *_test.py
>    
>    * https://docs.pytest.org/en/stable/goodpractices.html#conventions-for-python-test-discovery
> 
> If both of those tests fail then the Action should autoclose the PR with a note pointing the contributor to CONTRIBUTING.md.

Please also include unittest and perhaps pytest. doctest are not the most beautiful way to add test code: http://www.rohitschauhan.com/index.php/2018/07/05/python-relative-benefits-of-pytest-unittest-nose-and-doctest/#:~:text=Pytest%20provides%20essentially%20the%20same,very%20easy%20to%20do%20so.

**Comment by cclauss** [comment]
They are included in 2. above.  Our automated testing uses pytest, not nose or unittest.  Tests that follow pytest discovery rules will ensure that the PR is not autoclosed.

Doctests are not pretty but they are more simple for first-time contributors to understand.

**Comment by xcodz-dot** [comment]
https://github.com/actions/stale 
I found this, anyone who can implement it for PRs?

**Comment by dhruvmanila** [comment]
This has already been implemented but the number of days before an issue becomes stale is 30 so it takes time to see the difference.

**Comment by xcodz-dot** [comment]
You are right but we need a action for PR (stale is implemented for issues only), #3707.

**Comment by dhruvmanila** [comment]
Um, no. https://github.com/TheAlgorithms/Python/blob/master/.github/workflows/stale.yml
It is implemented both for PR and issues.

**Comment by xcodz-dot** [comment]
Whoops! thanks for letting me know. 😄

**Comment by xcodz-dot** [comment]
Please close these PRs
#3741 #3737 (they are duplicates of #3743) Those three PR's are made by the same person @agpeshal

**Comment by NumberPiOso** [comment]
Is there any way we can help you with the pull requests ?

**Comment by cclauss** [comment]
Anyone can review any pull request on any repo on GitHub.  Look at PRs that have passing tests and then near the top of the pull request click `Files changed` and read thru the changes...  Are they clear?  Are they an improvement?  Are there tests?  Do those tests cover a sensable set of cases (large numbers, small numbers, zero, integers, floating-point numbers, strings, empty strings, lists, tuples, dicts, etc.)?  Are there type hints on all function parameters and return values?  When you have had a good read through the changes, click the `Review changes` button at the upper right and call 'em like you see 'em.  Positive reviews will give maintainers confidence that you have read through the contribution and believe that it would help to improve the repo.  Other comments can help the contributor to improve their work so that it is easier for visitors to read and easier for maintainers to review.  Thx!

**Comment by kakashi215** [comment]
@xcodz-dot Please help me with my PR #3706 
Its been 8 days, pending for review.
Am i missing on something?

**Comment by cclauss** [comment]
Hacktoberfest 2020 stats: started with 30 open PRs, ended with 521.

**Comment by kakashi215** [comment]
> Hacktoberfest 2020 stats: started with 30 open PRs, ended with 521.

I'd love to help up clear out the load of work!!

**Comment by xcodz-dot** [comment]
Try suggesting changes, review PRs, mention maintainers (not me) if it is good to go. Thanks.

**Comment by kakashi215** [comment]
> Try suggesting changes, review PRs, mention maintainers (not me) if it is good to go. Thanks.

On it.

**Comment by mrmaxguns** [comment]
What is to be done to the pull requests whose authors have not followed the contribution guidelines and/or the code has invalid syntax?

**Comment by xcodz-dot** [comment]
@mrmaxguns, you can suggest changes, write messages regarding their checklist

**Comment by dhruvmanila** [comment]
Some stats regarding the Hacktoberfest: 🔢 

- Total PRs opened: 1,208 [Current: 472 open]
- Total PRs closed: 736
  - Total PRs merged: 165
  - Total PRs closed and unmerged: 571
  - This means 77% PRs closed were spam 😮 
- Total PRs labelled `invalid`: 198 (Most of them weren't even labelled)

**Comment by mrmaxguns** [comment]
This is troubling considering the contribution guidelines are very detailed.

**Comment by cclauss** [comment]
Oh, I do not agree.  I think our high standards is what led to a lot of these PRs being considered spam.  I see a ton of repos who take in any code without running any tests without requiring doctests, type hints, no plagerism.  Those repos are useless but a ton of folks get free tee-shirts.  I am really happy that we have high standards and that we do not dumb down our approach for Hacktoberfest.

**Comment by mrmaxguns** [comment]
I agree. What I meant to say was that people should pay attention to the contribution guidelines before submitting a pull request so that it is easier for people to give them feedback.

**Comment by cclauss** [comment]
In a perfect world...

**Comment by dhruvmanila** [comment]
That is why we are trying to set up a bot in this repository so that the bot takes care of the lower-level stuff for us to focus on the actual algorithm. :)

**Comment by prashantdoshi28** [comment]
Hi all, I have a question regarding PRs. 

Do we follow rule of 1 concept per PR sort of thing here or is it ok if a PR has multiple unrelated codes ? 

If we don't allow such PRs, do we have any flag to mark them so maintainers can reject those straight away? 

Thanks :)

**Comment by dhruvmanila** [comment]
We have a label `Multiple Algorithms Not Allowed` in black :)

**Comment by prashantdoshi28** [comment]
Another question, may sound dumb, but is there any documentation of labels we use, for example,

```
Multiple Algorithms Not Allowed : PR should be limited to single functionality only, multiple unrelated code in a PR not allowed.
```

Thanks :)

**Comment by dhruvmanila** [comment]
Only members can add or update the labels. Thanks for the suggestion!

**Comment by xcodz-dot** [comment]
According to the rate of PR Reviews, I think this might take upto 130 days to bring back numbers to near 10.

**Comment by cclauss** [comment]
Yeah but at least we will be prepared for the next Hacktoberfest.

**Comment by xcodz-dot** [comment]
Possibly, If any of you guys could suggest them an idea

https://github.com/TheAlgorithms/Java/issues/1929

**Comment by xcodz-dot** [comment]
I am sure that pull requests are getting closed beacause of stale rather than our reviews. Although that's good :smile:

**Comment by xcodz-dot** [comment]
time to close this

**Comment by cclauss** [comment]
Yes.  At least until 02 Oct. 2021.
