### ISSUE TITLE
obj.__dict__ return one not expect result

### ISSUE THREAD

**Issue by yangjnMapBox** [TheAlgorithms/Python#3633]
![image](https://user-images.githubusercontent.com/44802474/96821519-9e470a00-145a-11eb-91ee-1e124b64e6bb.png)

**Comment by Snimer** [comment]
Remove the last commas from line 7 and 8.  You will get str.

**Comment by yangjnMapBox** [comment]
great!thanks,snimer.

**Comment by Snimer** [comment]
This is because.
When we assign a variable with comma. like this
var = "Meassge", "Hello"
now var becomes a tuple. It is feature in python. 
When you don't assign the second value. It still consider it as a tuple but without Second part.
