### ISSUE TITLE
Quick sort algorithm

### ISSUE THREAD

**Issue by shreyasd302** [TheAlgorithms/Python#3646]
Implementing Quick sort algorithm in python to sort given array.

**Comment by shreyasd302** [comment]
Can I work on this please?

**Comment by xcodz-dot** [comment]
yeah sure, You do not need ask for that just link a pull request to it. 😄

**Comment by spamegg1** [comment]
@shreyasd302 Quick sort is already present in the repository: https://github.com/TheAlgorithms/Python/tree/master/sorts

**Comment by xcodz-dot** [comment]
@spamegg1 is right, forgot to see that. Better luck next time @shreyasd302

**Comment by dhruvmanila** [comment]
Closing this as it doesn't seem like an issue. The algorithm is already present as mentioned in the previous comment. If you want to submit another algorithm, please open a pull request for it ***after*** reading the [Contributing Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
