### ISSUE TITLE
Concurrency: concurrent logger

### ISSUE THREAD

**Issue by srafi1** [TheAlgorithms/Python#3655]
Is this project open to concurrent/parallel algorithms? I'd like to implement concurrent logging as a simple concurrency algorithm and other algorithms that can be solved differently when concurrency is invlolved (ex: Floyd-Warshall).

**Comment by dhruvmanila** [comment]
Sure, why not! If you want to submit an algorithm, please open a pull request for it ***after*** reading the [Contributing Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) first.

Closing this as it doesn't seem like an issue.
