### ISSUE TITLE
Greedy Algorithm for Egyptian Fraction

### ISSUE THREAD

**Issue by shreyasd302** [TheAlgorithms/Python#3673]
Every positive fraction can be represented as sum of unique unit fractions.
Egyptian Fraction Representation of 2/3 is 1/2 + 1/6.

**Comment by sonechca** [comment]
I would like to create this algorithm, Can I Join in this issue?

**Comment by prantoran** [comment]
Can you assign this issue to me?

**Comment by dhruvmanila** [comment]
Closing this as it doesn't seem like an issue. If you want to submit an algorithm, please open a pull request for it ***after*** reading the [Contributing Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) first.
