### ISSUE TITLE
HACKTOBERFEST - Add Solution to Project Euler Question 64.

### ISSUE THREAD

**Issue by kakashi215** [TheAlgorithms/Python#3705]
[Project Euler - 64](https://projecteuler.net/problem=64)

I have solved the problem and want to add my solution to the repository.

Happy Coding!

**Comment by fatihhelvaci** [comment]
https://github.com/TheAlgorithms/Python/pull/3744#issue-509644033

**Comment by kakashi215** [comment]
@Kush1101 
@cclauss 
@dhruvmanila 
Could we complete this issue please?
I have linked a PR that needs review.
Requesting you to help with that.

Happy Coding!

**Comment by dhruvmanila** [comment]
Closing this as it doesn't seem like an issue. If you want to submit an algorithm, please open a pull request for it ***after*** reading the [Contributing Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) first.
