### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by dynamitechetan** [TheAlgorithms/Python#374]
Many new algorithms were added. The readme file can be updated with those new algorithms.
https://github.com/TheAlgorithms/Python/blob/master/README.md

**Comment by harshildarji** [comment]
Hello @klymenkoo,
Your contributions to improving **Readme** is highly welcomed.
Thank you.

**Comment by Gekk0r** [comment]
Hello :),

I would like to add description for these:

- pankace
- gnome
- tree
- cycle

**Comment by AnupKumarPanwar** [comment]
We don't want a single README file having all the algorithms. Create individual readme files for every algorithm in [this repo](https://github.com/TheAlgorithms/Algorithms-Explanation/). See the [sample readme.md file](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/README.md) and try to keep the same format as far as possible.

**Comment by Gekk0r** [comment]
Ok, sorry for the misunderstanding!
Added heap sort.md in the other repo :)

**Comment by klymenkoo** [comment]
> We don't want a single README file having all the algorithms. Create individual readme files for every algorithm in [this repo](https://github.com/TheAlgorithms/Algorithms-Explanation/). See the [sample readme.md file](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/README.md) and try to keep the same format as far as possible.

@AnupKumarPanwar it seems to be another big issue as it means restructuring the whole project.

**Comment by JRaiden16** [comment]
So... Where I put the README files of the algorithms I added to the project?

**Comment by AlexDvorak** [comment]
I could split up the main readme into smaller readmes for each subfolder. and i could make the main readme link to each of those. is that fine or are there other concerns?

**Comment by RobbyB97** [comment]
If you look at Pull request #488 I fixed the README entirely. Everything is formatted properly now.

**Comment by emmafritx** [comment]
.

**Comment by EternalLearner42** [comment]
Greetings. Can this still be considered open? I have some ideas on improving the README (adding images to some of the algorithms, fixing typos, ...) and would like to know if I am free to go.

**Comment by wizzup** [comment]
I think each directory should contain a separate README file so when browsing the repo on github it will render the README as directory summary instead of list of files.

**Comment by JRaiden16** [comment]
I'm agree with that

El vie., 24 de may. de 2019 05:25, Wisut Hantanong <notifications@github.com<mailto:notifications@github.com>> escribió:

I think each directory should contain a separate README file so when browsing the repo on github it will render the README as directory summary instead of list of files.
