### ISSUE TITLE
No logistic Regression and SVM in machine learning directory

### ISSUE THREAD

**Issue by deadskull7** [TheAlgorithms/Python#378]
Is the logistic regression as well as SVM model is missing in machine learning directory or I am referring to wrong directory. If its so...? 
I would like to take this issue and wanted to make the models from scratch if allowed by mentor.

**Comment by zhqu1148980644** [comment]
#508

**Comment by zhqu1148980644** [comment]
![smo](https://user-images.githubusercontent.com/29366130/47628349-22b66900-db70-11e8-9bd9-b4d91053e8eb.png)
