### ISSUE TITLE
the upper function of the string module exists a spelling error

### ISSUE THREAD

**Issue by jiaxw32** [TheAlgorithms/Python#3807]
line 16 of the comment:

`if it is a capital letter it is getting shift by 32 which makes it a capital case letter`

here the `capital letter` should be `lower letter`

**Comment by gourang843** [comment]
> line 16 of the comment:
> 
> `if it is a capital letter it is getting shift by 32 which makes it a capital case letter`
> 
> here the `capital letter` should be `lower letter`

i did not understand your problem, tell me in easy way..

**Comment by sethusankar** [comment]
instead of this 

if it is a capital letter it is getting shift by 32 which makes it a capital case letter

can we have this

if it is a lower letter it is getting shift by 32 which makes it a capital case letter
