### ISSUE TITLE
Conversion: Integer to Roman Numeral

### ISSUE THREAD

**Issue by rikkashb** [TheAlgorithms/Python#3810]
If given an integer, its equivalent roman numeral should be returned.

**Example: 1**
Input: 50
Output: L
**Example: 2**
Input: 84
Output: LXXXIV

**Comment by rikkashb** [comment]
@poyea Could you assign this to me?

**Comment by thedivyanshuyadav** [comment]
@rikkashb  Hey I want to fix this issue. Can I ?

**Comment by gourang843** [comment]
hello my self gourang agrawal.
this problem is like pretty simple but still it have some troubles that make you stuck.
but for me i already made this type of program so i will definitly done this problem if you assign me.
thank you..

**Comment by Chandanitian** [comment]
@rikkashb Hey I want to fix this issue. i will definitly solve  this problem if you assign me.

**Comment by dhruvmanila** [comment]
Closing this as it doesn't seem like an issue. If you want to submit an algorithm, please open a pull request for it ***after*** reading the [Contributing Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) first.
