### ISSUE TITLE
Coding problem

### ISSUE THREAD

**Issue by coolman6** [TheAlgorithms/Python#3868]
Hello you all. I'm having trouble trying to figure out this coding assignment for python. Does anyone know a correct solution for this?

1. Write function repeatEnd that takes a String and an int n, and returns a string
made of n repetitions of the last n characters of the string. For example
repeatEnd("Hello", 3) should return "llollollo"
repeatEnd("Hello", 2) should return "lolo"
repeatEnd("Hello", 1) → "o"
If n is not between 0 and the length of the string return the empty string “”.

2. A "triple" in a string is a character appearing three times in a row. Write a function called
countTriple that takes a string as an argument and returns the count of the number of
triples it in. Note that triples may overlap. Here are some examples to demonstrate:
countTriple("abcXXXabc") should return 1
countTriple("xxxabyyyycd") should 3 because xxx yyy and yyy
countTriple("a") should return 0

3. Write tester fuctions for each function above

4. Write header comments for each function above.

**Comment by dhruvmanila** [comment]
I don't think that this is the correct place to ask for doubts. Please don't spam issues.

Closing this issue.
