### ISSUE TITLE
Weight Conversion

### ISSUE THREAD

**Issue by AnubhavSolanki** [TheAlgorithms/Python#3888]
As there is no weight conversion algorithm till now so I like to add one.

**Comment by erdum** [comment]
Yes i would be very nice to have, i will also contribute in

**Comment by xcodz-dot** [comment]
any progress? or this might end up as stale issue

**Comment by AnubhavSolanki** [comment]
i have created it but it's my first open source contribution i don't how to do it
Can you guide me?

**Comment by AnubhavSolanki** [comment]
@xcodz-dot  @erdum

**Comment by xcodz-dot** [comment]
* OK, First of all make a fork of this repo
* clone it locally
* make changes to local copy (add files)
* run these commands in order:
  * `pip install pre-commit`
  * `pre-commit run -a` It might show you it failed, but do not worry (It did not actually fail)
* commit and push the changes to your fork repo from local copy
* go to pull request sections of your fork
* click on a new PR button
* start your PR

**Comment by xcodz-dot** [comment]
You can do google searches for more info (that is the way how i learnt github)

**Comment by AnubhavSolanki** [comment]
can u check my PR @xcodz-dot 
https://github.com/TheAlgorithms/Python/pull/3964
I don't know what's wrong with it?

**Comment by erdum** [comment]
i also recently made my first contribution  
please make sure your code is neat because this is most important

**Comment by xcodz-dot** [comment]
Hello, there is a very simple command set which is:
* `pip install pre-commit`
* `pre-commit run -a` at root of local copy of repo

This doesn't require much hard work to format codes

**Comment by dhruvmanila** [comment]
This issue got closed with #3964
