### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dahalabiskar** [TheAlgorithms/Python#3899]
Here is error could not open requirements file how can i solve this error in anaconda
pip install -r requirements.txt

**Comment by dhruvmanila** [comment]
Please be more specific regarding the problem you are facing.

**Comment by hrshit998** [comment]
anaconda uses many modules for processing different tasks. in your "requirements.txt" file there are modules which needs to build wheel, and in building wheels it needs a stable internet connection. in anaconda there are problems that occurs when we install different modules at a same time. so the main solution is to install those modules in a specific environment OR one by one in that same environment that you are using.

**Comment by Tamoghna15** [comment]
please install modules one by one on a specific environment.
