### ISSUE TITLE
Reenable files when TensorFlow supports the current Python

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#3946]
As discussed in #3926, the following files do not have `.py` extensions because [TensorFlow does not yet support the current Python](https://github.com/tensorflow/tensorflow/issues/44485).
* dynamic_programming/k_means_clustering_tensorflow.py_tf
* machine_learning/lstm/lstm_prediction.py_tf
* neural_network/gan.py_tf
* neural_network/input_data.py_tf

TODO: Restore the `.py` file extensions and ensure our tests pass when TensorFlow supports the current Python.

**Comment by Joe-Sin7h** [comment]
I understood the issue , Could please me to this issue @cclauss

**Comment by cclauss** [comment]
We do not assign issues.  We review pull requests.

**Comment by Joe-Sin7h** [comment]
hello @cclauss 
tensorflow 2 as for now doesn't support Python 3.9.
so I'll change them once tensorflow 2 is compatible with python 3.9.

**Comment by cclauss** [comment]
This repo does not assign issues.  We review pull requests.

**Comment by thewittystranger** [comment]
@cclauss  Sir, m new to open source and i want to start. I want to contribute in your organization. Please guide me how to start

**Comment by mailinh19** [comment]
Thanks for your sharing!
https://trexrun.co

**Comment by surbhinahta1211** [comment]
Hi,
Model progress can be saved during and after training. This means a model can resume where it left off and avoid long training times. Saving also means you can share your model and others can recreate your work. When publishing research models and techniques, most machine learning practitioners share:

code to create the model, and
the trained weights, or parameters, for the model
Sharing this data helps others understand how the model works and try it themselves with new data.

Regards - [Python training in pune.](https://www.sevenmentor.com/best-python-classes-in-pune.php)

**Comment by surbhinahta1211** [comment]
I am also facing the same issue related to [python](https://www.sevenmentor.com/best-python-classes-in-pune.php). thanks for your advice.

**Comment by embattle16** [comment]
hey i am new to git hub. can you direct me how shll i work on this issue?

**Comment by cclauss** [comment]
Yes.  Scroll to the top of this page and click the link __TensorFlow does not yet support the current Python.__. Once that issue is fixed then this issue can be worked on.

**Comment by hammyofmha** [comment]
https://gist.github.com/tmelz/76e655a3d8f2878fc9a4#file-pre-commit-sh

**Comment by todlove** [comment]
203.144.144.201
https://github.com/rajkumardusad/Tool-X/discussions/217#discussion-2356639

**Comment by todlove** [comment]
https://github.com/rajkumardusad/Tool-X/discussions/217#discussion-2356639

**Comment by azizadiab** [comment]
Hello World

**Comment by cclauss** [comment]
The TensorFlow 2.5 release candidate is our so we should be able to fix this issue soon...
https://github.com/tensorflow/tensorflow/releases

**Comment by Hansenwuwuwu** [comment]
so cool

**Comment by f0xxx1** [comment]
@cclauss I've renamed the files in a branch which then can be just tested and It will be ready to be merged whenever TF releases the support for py3.9, can I get a permissions to push the branch? 

I followed the Contribution Guidelines, the only thing that I am unsure is the branch name which is `rename-files-to-support-tensorflow-3946` I think it should be fine?

**Comment by cclauss** [comment]
We are getting close because TensorFlow 2.6 release candidate 2 is available…
https://github.com/tensorflow/tensorflow/releases

**Comment by cclauss** [comment]
Python 3.11 is finally supported.  https://github.com/tensorflow/tensorflow/releases
@tianyizheng02 or @MaximSmolskiy Interested?
https://github.com/search?q=repo%3ATheAlgorithms%2FPython%20tensorflow&type=code
