### ISSUE TITLE
Error in Algorithm

### ISSUE THREAD

**Issue by maldz3** [TheAlgorithms/Python#3953]
I found an error in one of the algorithms, fixed it, and tried to make a pull request.  However I already have a previous pr open so I'm unable to make another one.  Should i just wait, or close my earlier one?  

Also I noticed your conversation about rejecting prs without doctests which makes sense.  In this case, the error I've fixed is in a file that I think needs quite a few more changes, and it doesn't yet have doctests included.  However, I wanted my first pr for this file to be just a simple fixing of the error.  Adding doctests will unfortunately be a little more complicated since the original code writer added a lot of print statements within the functions.

**Comment by xcodz-dot** [comment]
Make a branch of your fork, update your new branch from this repo, make changes, create PR from that branch

**Comment by xcodz-dot** [comment]
You can reopen your second PR after your first work is done, please wait until then.

**Comment by maldz3** [comment]
Thanks will do!

**Comment by cclauss** [comment]
Closed in #3874
