### ISSUE TITLE
conversions speedup

### ISSUE THREAD

**Issue by Ksengine** [TheAlgorithms/Python#3954]
## binary_to_demical.py
we can simply convert binary to demical
```python
int("      1010100    ", 2)
```
## decimal_to_binary.py
```python
>>> bin(500)
'0b111110100'
>>> bin(500)[2:]
'111110100'
```

**Comment by xcodz-dot** [comment]
Well @Ksengine , most of us know those methods but the thing here is that we want to really show the internal working (algorithms). As you might have read in readme.md or in contributing.md, the algorithms here are for educational purpose only

**Comment by Ksengine** [comment]
> Well @Ksengine , most of us know those methods but the thing here is that we want to really show the internal working (algorithms). As you might have read in readme.md or in contributing.md, the algorithms here are for educational purpose only

ok, Thanks.
