### ISSUE TITLE
data_structures/linked_list: Add __str__() function

### ISSUE THREAD

**Issue by arif599** [TheAlgorithms/Python#3960]
Background: I just started learning Data Structures and Algorithms, while comparing my implementation of the Linked List class. I think adding a __str__() function to __init__.py can help users see the values inside the Linked List and also see where the numbers are pointing to.

Example output: 5 --> 14 --> 85 --> 20

If this is allowed, please assign this issue to me, I would like me to make this change. Thanks!

**Comment by xcodz-dot** [comment]
Great, You can start without asking, We will check the PR soon
