### ISSUE TITLE
PRs are getting stale and closed

### ISSUE THREAD

**Issue by xcodz-dot** [TheAlgorithms/Python#3968]
Many Pull Request with some important code are getting stale. Any idea of we could pause this process for a few moments until we are able to get our numbers down.

**Comment by cclauss** [comment]
I think we are intentionally trying to be a bit brutal in our post-Hacktoberfest cleanup.  We are being far less brutal than Hacktoberfest was itself. If there are good PRs then [review them](https://github.com/TheAlgorithms/Python/issues/3609#issuecomment-719628053) and provide you approval of them _before_ asking others to review them.  I am more inclined to review PRs that have already been reviewed by and approved others.

**Comment by dhruvmanila** [comment]
If you find any pull request which contains important or good code, you can just put a simple comment and the bot will un-stale the PR. 

I am thinking to let `algorithms-keeper` run the parser if a PR is `reopened`, that way it will detect all the missing requirements, label, and comment on the PR. What do you say @xcodz-dot? After adding this functionality, if we find some good PR which has been stale, we can close and reopen it to let the bot take care of the lower level stuff and we can focus on the actual review :)

**Comment by cclauss** [comment]
> let algorithms-keeper run the parser if a PR is reopened

👍

**Comment by dhruvmanila** [comment]
I've seen those types of activation, let me see what I can do.

**Comment by xcodz-dot** [comment]
Great then

**Comment by xcodz-dot** [comment]
> If you find any pull request which contains important or good code, you can just put a simple comment and the bot will un-stale the PR.
> 
> I am thinking to let `algorithms-keeper` run the parser if a PR is `reopened`, that way it will detect all the missing requirements, label, and comment on the PR. What do you say @xcodz-dot? After adding this functionality, if we find some good PR which has been stale, we can close and reopen it to let the bot take care of the lower level stuff and we can focus on the actual review :)

This is really good idea to implement that bot in old PR (which are trying to run themselves on Travis), simplifies process very easily

**Comment by dhruvmanila** [comment]
I am sorry I don't quite understand what you mean here. Can you clarify?
> bot in old PR ?
> which are trying to run themselves on Travis ?

**Comment by xcodz-dot** [comment]
I found out many PR which are opened before the bot was implemented are on Travis or am I misunderstood?

**Comment by dhruvmanila** [comment]
That doesn't matter; when you close and reopen a PR, tests will be triggered with the new configuration.

**Comment by xcodz-dot** [comment]
Great, that's what I meant to say

**Comment by dhruvmanila** [comment]
@cclauss It seems that a GitHub app cannot be mentioned, but the good news is that the bot can listen for comment events. After each comment is posted, the bot will parse the body and look for (regex?) patterns like the one you mentioned, and we can configure commands for the bot like: `@bot rerun` (algorithms-keeper is too long to type) or just `\rerun`

**Comment by dhruvmanila** [comment]
I suppose this issue can be closed? @xcodz-dot

**Comment by xcodz-dot** [comment]
Great
