### ISSUE TITLE
Is there anyone create kotlin version of this?

### ISSUE THREAD

**Issue by mochadwi** [TheAlgorithms/Python#3985]
TheAlgorithms/Python repo is way more contains a lot of DSA samples, kotlin version in https://github.com/bmaslakov/kotlin-algorithm-club doesn't active (no active commit less than a year)

**Comment by dhruvmanila** [comment]
The mentioned repository is not part of TheAlgorithms organization. This is the repository that is part of this organization: https://github.com/TheAlgorithms/Kotlin and if you want to submit an algorithm related to the Kotlin language, please feel free to open a PR on that repository.
