### ISSUE TITLE
A basic code that analyzes the overall color of the screen and sync RGB keyboard to it.

### ISSUE THREAD

**Issue by korum123** [TheAlgorithms/Python#3991]
Hey dear programmers, I was thinking of something and I tought that i could get some help here.

I bought a new laptop which includes a RGB keyboard that you can change the colors but it does not support advanced RGB settings because the Aura does not support Asus TUF models. So I only can use 4 modes, a constant color, changing rainbow, breathing, flashing. I searched for some advanced rgb settings but nah there isnt anything.

So I taught I need to make my own program to do what I want and let me tell you what I want as described in title.

A program that it will analyze the overall color of the screen (like orange when burning something or dark blue when its night) and change my keyboards color to that color using the color code that he gained before.

I cant describe you the first part but the program needs to find the R G B code of the overall color and enter the code to the Asus' RGB program every 0.2 seconds.

I don't know anything about programming (the basics with the python) but thay code seemed easy to me so i want you to help me with where should i start, which programming language i need to use, or is it too advanced i need to stop right know.

I just hope it is so easy that you would fine some codes or just write it right away but probably this is not how programming works. But I am already thankful for your helps.

**Comment by xcodz-dot** [comment]
Hello, it might be possible in Python, with some extra modules (proggrams), and if talked about proggraming yourself, then i think you might need a year and lots of experience to get to the level.

I myself used to code 4 hours a day just as a hobby.

Please provide links, system info, and also open a new repo and mention me there. Also your keyboard manufacturer must provides an api to connect to your keyboard

@korum123 possibly please close it from here
