### ISSUE TITLE
Catalan numbers into list?

### ISSUE THREAD

**Issue by EliKanevski** [TheAlgorithms/Python#4012]
Hey, how do I make a program that calculates the Catalan number of n and place the list of numbers into a list?
Thank you very much in advance!

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/data_structures/binary_tree/number_of_possible_binary_trees.py#L42 + #2527

**Comment by EliKanevski** [comment]
Thank you,
Do you have the code to do it without using factorials?

**Comment by EliKanevski** [comment]
Here's what I did, it works. Is there a better way?

```def Catalan_tuple(n):
    if n < 1:
        n = 1
    c = [1]
    for i in range(n-1):
        list_Catalan = 0
        for x in range(i+1):

            list_Catalan += c[x] * c[i - x]
        c.append(list_Catalan)
    return tuple(c)
n = int(input('Please enter a length for n: '))
print(Catalan_tuple(n))```
