### ISSUE TITLE
Polygon perimeter calculator 

### ISSUE THREAD

**Issue by EliKanevski** [TheAlgorithms/Python#4013]
For some reason when i assign a list to x this works perfectly fine, but when i take a list input i get an error. Does anyone know why?
Thank you.
```import math
print('*** QUESTION 4 ***')
def perimeter(points):
    d = 0
    len_points = len(points)
    if len(points) < 3:
        return 0
    for i in range(len_points):
        d += math.sqrt((points[i-1][0] - points[i][0])**2 + ((points[i-1][1] - points[i][1])**2))
    return d
x = list(input('please enter a list'))
print(type(x))
print(perimeter(x))```

**Comment by JayeshGChandan** [comment]
This will create a list of strings. I think you have to map it with the type.
e.g., x = list(map(type, input.split()))

**Comment by shashwat-code** [comment]
In python 3 when we take input it's type is string so firstly you have to typecast it into integer.
x= list(map(int,input().split("")))
something like this..

**Comment by EliKanevski** [comment]
@shashwat-code I tried what you said, i first got an empty separator error, so i put an blank space there, then got an "invalid literal for int() with base 10: 'input...' " error message. 
I tried give the input in a list and in just parentheses.  (0,4),(3,3),(4,0),....
Also tried the same just with opening and closing square brackets, and got the same result. 
Do you think it would work if I make an empty list in my function, and then append or concatanate the input to the list?
Thanks a lot. I appreciate your help!

**Comment by EliKanevski** [comment]
@JayeshGChandan I tried your code, it just returns the type to x and it remains a string.
Thank you for your help!

**Comment by JayeshGChandan** [comment]
My pleasure :)

**Comment by shashwat-code** [comment]
Ok so you want to take input something like this:
[[2,3],[4,5],[6,7]]
**Code**
x= list(map(int,input().split(" ")))
y=[]
for i in range(0,len(x),2):
    y.append([x[i],x[i+1]])
print(y)

**Input:**
1 2 3 4 5 6 7 8 9 0

**Output**
[ [1, 2 ], [3, 4 ], [5, 6 ], [7, 8 ], [ 9, 0 ] ]

I think so that works for you

**Comment by vitor592** [comment]
Galera sou novo por aqui estou entrando nesse mundo agora começando a estudar em Python !

**Comment by xcodz-dot** [comment]
Guys the final input code for you is:
```python
while True:
    r = False
    x = input("please enter a list:").split(" ")
    for item in x:
        if not item.isnumeric():
            print("please enter a valid list separated by ' '")
            r = True
    if r:
        continue
    x = map(int, x)
    break
```

The above code is resistant to all faulty input or errors
😄

**Comment by xcodz-dot** [comment]
Final code
```python
print('*** QUESTION 4 ***')
def perimeter(points):
    d = 0
    len_points = len(points)
    if len(points) < 3:
        return 0
    for i in range(len_points):
        d += math.sqrt((points[i-1][0] - points[i][0])**2 + ((points[i-1][1] - points[i][1])**2))
    return d
while True:
    r = False
    x = input("please enter a list:").split(" ")
    for item in x:
        if not item.isnumeric():
            print("please enter a valid list separated by ' '")
            r = True
    if r:
        continue
    x = map(int, x)
    if len(x) % 2 != 0:
        print("the amount of provided numbers are odd and this cannot form pairs")
        continue
    y = x
    x = []
    for p1, p2 in zip(y[0:len(y)//2], y[len(y)//2:len(y)]):
        x.append([p1, p2])
    break
print(perimeter(x))
```

**Comment by EliKanevski** [comment]
Thank you very much everyone for the help! Much appreciated!
