### ISSUE TITLE
Greedy Algorithm section

### ISSUE THREAD

**Issue by ajeetjaiswal02** [TheAlgorithms/Python#4026]
I think we have to make a Greedy Algorithms section to because in my opinion its the first Algorithm comes in mind after seeing a question
I am more then happy to create the section and contribute toward it 😀

**Comment by xcodz-dot** [comment]
well, just a question

After getting a algorithm ready you can have a filename for example `greedy_string_search.py` (this is just example)
Which if not greedy algoithms can go to other section such as search and also people might not be knowing there is a greedy algorithm for that until they visit it in that specific section. Also people usually come with a topic such as `cipher` and `search` for which they might not bother looking in greedy section.

Also will the above situation will be OK? (If not please specify how with a well explained example)

 (Also you might be knowing that `greedy algorithms` section was removed recently)

**Comment by ajeetjaiswal02** [comment]
ok thx for clarifying
