### ISSUE TITLE
tabu_search not working

### ISSUE THREAD

**Issue by hananaq** [TheAlgorithms/Python#4034]
hello, im trying to run you tabu_search.py code, but it's not working and keep giving my error

 for k in dict_of_neighbours[visiting]:
KeyError: ''

the error is not even written, so i couldn't debug it, i was wondering if you could help me out running it

**Comment by xcodz-dot** [comment]
could you please send the full traceback here

**Comment by xcodz-dot** [comment]
and please specify where in which directory can i find tabu_search.py

**Comment by hananaq** [comment]
Python/searches/tabu_search.py / 


Traceback (most recent call last):
  File "tsp.py", line 280, in <module>
    main(parser.parse_args())
  File "tsp.py", line 245, in main
    args.File, dict_of_neighbours
  File "tsp.py", line 92, in generate_first_solution
    for k in dict_of_neighbours[visiting]:
KeyError: ''

**Comment by xcodz-dot** [comment]
what files did you use as input?

**Comment by hananaq** [comment]
i didnt notice there was an input file, i thought the second parameter is an output file, excuse me im new to Python

**Comment by xcodz-dot** [comment]
There is no output file option and only input file option.
try: `python tabu_search.py --help` if on windows else `python3 tabu_search.py --help`

**Comment by hananaq** [comment]
thanks alot, i found the input file in the repo, and the script is now running perfectly,

**Comment by xcodz-dot** [comment]
your welcome, you can check the docstring in the code top to check how it works
please close this issue for now. :smile:
