### ISSUE TITLE
Need help to write Algorithm for copying text from one program and pasting it to another program

### ISSUE THREAD

**Issue by AltNeo** [TheAlgorithms/Python#4039]
![IMG_20201216_212300.jpg](https://user-images.githubusercontent.com/71923855/102374059-e6ac1f80-3fe6-11eb-95c8-7c4a40bc62f2.jpg)
(Pardon the handwriting)
This is a basic step procedure I chalked out
Any suggestion to help any bullet point will help
I m a student who just started learning about python and what it can do
Even a direction to the required libraries to import 
Or any other approach that can be more efficient will help a lot
Thanks

**Comment by xcodz-dot** [comment]
Mouse Clicking might not be the most effective way (this is hard)

 but you can achieve this very simply if you know the file path, also it might a better way to describe it more precisely (rather than how to do, please tell what to do)

😄 All the best though for Python

**Comment by AltNeo** [comment]
I want to copy my online meeting link from whatsapp web and paste it to a chat in Microsoft teams
The link changes everyday and I want to learn about automation

**Comment by xcodz-dot** [comment]
you might want to look at these links (I am not having any experience with microsoft teams):
* https://github.com/rveachkc/pymsteams (**Python API for Microsoft Teams**)
* https://www.twilio.com/docs/whatsapp/quickstart/python (**Python API for WhatsApp**)

**Comment by MiClaire** [comment]
hi,
If you want to write a algorithm to copy and paste like or text Python's Clipboard module might help.
[Clipboard](https://pypi.org/project/clipboard/)
Using it is really easy and might also help in handling copying and pasting text.

**Comment by xcodz-dot** [comment]
The data which is copy and pasted is not in Python and is Copied Pasted outside the actual program between whatsapp and MicrosoftTeams. So clipboard is likly not to help

**Comment by MiClaire** [comment]
Can you Explain it a little more what He is trying to achieve. Please?

**Comment by xcodz-dot** [comment]
He is trying to copy meeting links from WhatsApp and paste them in Microsoft Teams

**Comment by MiClaire** [comment]
okay.
I have Rough Idea that this can possibly be automated using twilio and pymsteams APIs mentioned above.

- send the link [that you want to paste in MSteams] to twilio account.
- Use the twilio API to extract that Text from the JSON file.
- Send that text using pymsteams module.

**Comment by Jayanth-Kalgikar** [comment]
> The data which is copy and pasted is not in Python and is Copied Pasted outside the actual program between whatsapp and MicrosoftTeams. So clipboard is likly not to help

Yea! Clipboard might not help.

**Comment by handsomelz** [comment]
https://user-images.githubusercontent.com/59047137/108807857-4b37bc00-75e0-11eb-8978-77c969ad064f.mp4

**Comment by dhruvmanila** [comment]
Hi, this does not seem like an issue related to TheAlgorithms/Python repository. Please do the related discussion on our [Gitter](https://gitter.im/TheAlgorithms) channel. Thank you for your cooperation.
