### ISSUE TITLE
[mypy] Need help to fix all `mypy` errors in the codebase

### ISSUE THREAD

**Issue by dhruvmanila** [TheAlgorithms/Python#4052]
# Just one left to fix...
https://github.com/TheAlgorithms/Python/blob/master/mypy.ini#L5
* [ ] other/least_recently_used.py
* [x] other/lfu_cache.py #5755
* [x] other/lru_cache.py #5755

---

__UPDATE:__ Our GitHub Actions now run `mypy --ignore-missing-imports` excluding those directories that fail that test.
* https://github.com/TheAlgorithms/Python/blob/master/mypy.ini#L5

Currently, we are not running `mypy` in our regular CI tests as there are a lot of errors in the entire codebase, which needs to be fixed. This won't be a one-person job, so we are asking for help from you. I cannot paste the entire message in here as there are around 600 of them, so here's just a gist of it:

```console
$ mypy --ignore-missing-imports .
strings/word_occurrence.py:17: error: Need type annotation for 'occurrence'
strings/min_cost_string_conversion.py:36: error: No overload variant of "__setitem__" of "list" matches argument types "int", "str"
strings/min_cost_string_conversion.py:36: note: Possible overload variants:
strings/min_cost_string_conversion.py:36: note:     def __setitem__(self, int, int) -> None
strings/min_cost_string_conversion.py:36: note:     def __setitem__(self, slice, Iterable[int]) -> None
strings/min_cost_string_conversion.py:40: error: No overload variant of "__setitem__" of "list" matches argument types "int", "str"
strings/min_cost_string_conversion.py:40: note: Possible overload variants:
strings/min_cost_string_conversion.py:40: note:     def __setitem__(self, int, int) -> None
strings/min_cost_string_conversion.py:40: note:     def __setitem__(self, slice, Iterable[int]) -> None
...
backtracking/n_queens_math.py:109: error: List comprehension has incompatible type List[str]; expected List[int]
backtracking/n_queens_math.py:110: error: Argument 1 to "append" of "list" has incompatible type "List[int]"; expected "List[str]"
backtracking/n_queens_math.py:149: error: Need type annotation for 'boards' (hint: "boards: List[<type>] = ...")
backtracking/minimax.py:15: error: "list" is not subscriptable, use "typing.List" instead
backtracking/knight_tour.py:6: error: "tuple" is not subscriptable, use "typing.Tuple" instead
backtracking/knight_tour.py:6: error: "list" is not subscriptable, use "typing.List" instead
...
```

# Guidelines to follow:

- Please make sure you read the [Contributing Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) first.
- Please submit a fix for a maximum of 3 files at a time (1 file is also acceptable).
- As we are not running `mypy` in our CI tests, the user who is submitting a pull request should run it on their local machine and ensure there are no errors in their submission.
- Please ensure your pull request title contains the word `mypy` in it. If possible use this template for your pull request title:
```
[mypy] Fix type annotations for <filenames>
```

### Which errors to fix?

Please follow the below steps to produce all the errors in this library:
- Fork this repository if you haven't already.
- Clone the forked repository on your local machine using the command:

```
git clone --depth 1 https://github.com/TheAlgorithms/Python.git
```
Then you need to install all the necessary requirements:
```
cd python/
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
python -m pip install mypy
```
Then run either of the two commands:
- `mypy --ignore-missing-imports .` -> To produce all the error messages for the entire codebase.
- `mypy --ignore-missing-imports <filepath1> <filepath2> ...` -> To produce error messages for the mentioned file.

### How to fix the errors?

- Make a separate branch for your fix with the command: 
```
git checkout -b mypy-fix
```
- Make changes to the selected files.
- Push it to your forked copy and open a pull request with the appropriate title as mentioned above.

### Focus on one directory at a time:

```
.
├── [x] arithmetic_analysis
├── [x] backtracking
├── [x] bit_manipulation
├── [x] blockchain
├── [x] boolean_algebra
├── [x] cellular_automata
├── [x] ciphers
├── [x] compression
├── [x] computer_vision
├── [x] conversions
├── [ ] data_structures
├── [x] digital_image_processing
├── [x] divide_and_conquer
├── [ ] dynamic_programming
├── [x] electronics
├── [x] file_transfer
├── [x] fractals
├── [x] fuzzy_logic
├── [x] genetic_algorithm
├── [x] geodesy
├── [x] graphics
├── [ ] graphs
├── [x] hashes
├── [x] knapsack
├── [x] linear_algebra
├── [x] machine_learning
├── [ ] maths
├── [ ] matrix
├── [x] networking_flow
├── [x] neural_network
├── [ ] other
├── [ ] project_euler
├── [x] quantum
├── [x] scheduling
├── [x] scripts
├── [ ] searches
├── [x] sorts
├── [ ] strings
└── [x] web_programming
```

### Pre-requisites:
- You should be familiar with `mypy`: https://mypy.readthedocs.io
- You should be familiar with Python type hints: https://docs.python.org/3/library/typing.html

**Comment by ManuKashyap01** [comment]
@dhruvmanila I am beginner programmer in python. Is there any help I can do regarding this?

**Comment by sky3760000** [comment]
wrking

**Comment by dhruvmanila** [comment]
# Update:

With the latest update for `mypy` http://mypy-lang.org/, it supports [PEP 585](https://www.python.org/dev/peps/pep-0585/) which lets us use `list[int]` instead of `List[int]`. We always run on the latest Python version so we will adopt the built in generic types instead of importing it from the `typing` module.

**Comment by cclauss** [comment]
I updated the list above to reflect the directories that pass in #4274.  As contributors fix directories, please add them to `.github/workflows/mypy.yml` so that we do not have regressions.

**Comment by ayushigoyal2840** [comment]
So, here's the crux of the issue: mypy does not try type-checking every single module you've imported. Instead, it only attempts to type-check modules that have explicitly opted-in to the typing ecosystem.

Modules can opt-in to the typing ecosystem via two key mechanisms:

Add type hints or stubs to their code, and include a file named py.typed within the package they distribute to PyPi (or any other package repository). The presence of this marker makes the package PEP-561-aware. The mypy docs also have more info about PEP-561-aware packages.
Alternatively, add stubs to typeshed, the repository of type hints for the standard library and select 3rd party libraries.
The aws_xray_sdk package has done neither of these things, so will be ignored by mypy.

**Comment by cclauss** [comment]
@ayushigoyal2840 The next step is to [remove the `exclude` statement](https://github.com/TheAlgorithms/Python/blob/master/mypy.ini#L5) while keeping the tests green.  Once that is done, we can look into the missing imports.

**Comment by ikobangs** [comment]
Great work team

**Comment by cclauss** [comment]
@ikobangs There is [still work to do](https://github.com/TheAlgorithms/Python/blob/master/mypy.ini#L5) so please consider attacking one of the directories:
* [ ] data_structures #4362 
* [ ]  dynamic_programming #4332
* [ ]  graphs
* [ ]  maths #4362 #4358
* [ ]  matrix
* [ ]  other
* [ ]  project_euler
* [ ]  searches #4323 #4352
* [ ]  strings

**Comment by ikobangs** [comment]
Where to start

**Comment by PraneshRajendraKumar** [comment]
I'm a beginner in Python, is there any help I can do?

**Comment by PraneshRajendraKumar** [comment]
I'm a beginner in Python, is there any help I can do?

**Comment by AminVerve14** [comment]
That u think can be better because I don't remember how to use all the
Algoritma ..u know old man so much thing forget so hope u just do a better
way than this

**Comment by ManjunathBharadwaj01** [comment]
Hello... Can I help with any of the issues here? ..i want to learn the ways ...so i also might need some guidance

**Comment by murari2401** [comment]
Hello .. Can I help with any issues here? Like if someone assigns me some work I would be grateful to work on that

**Comment by cclauss** [comment]
No one assigns work.  We just review pull requests so please go ahead.

**Comment by AminVerve14** [comment]
Now how to solve it

**Comment by murari2401** [comment]
@AminVerve14 Read all the instructions given in the guidelines of this issue, you will get to know

**Comment by pikulet** [comment]
I have done fixes for the entire proj euler repo

will slowly open the requests as they are approved (don't wanna change more than 1 problem / commit as that is messy)

**Comment by Alireza-Rahimi-3000** [comment]
its amazing project

**Comment by marcelozarate** [comment]
I believe there are no remaining meaningful fixes to do, as the left ones are adressed by this

> # Update:
> With the latest update for `mypy` http://mypy-lang.org/, it supports [PEP 585](https://www.python.org/dev/peps/pep-0585/) which lets us use `list[int]` instead of `List[int]`. We always run on the latest Python version so we will adopt the built in generic types instead of importing it from the `typing` module.

**Comment by cclauss** [comment]
Please add `from __future__ import annotations` and use `list`, not `List`.

**Comment by cclauss** [comment]
I would be willing to live with mypy fixes on a directory-by-directory basis.

I doubt that we need to go all the way to `—strict`.  Having type hints for all function parameters and return types is super helpful but we do not want mypy wound up so tight that beginning developers cannot contribute.

**Comment by cclauss** [comment]
#5608 Can anyone explain why the __exclude__ in `mypy.ini` does not work?!?

**Comment by cclauss** [comment]
What remains???  https://github.com/TheAlgorithms/Python/blob/master/mypy.ini#L5

* [ ] graphs/boruvka.py
* [ ] graphs/breadth_first_search.py
* [ ] graphs/breadth_first_search_2.py
* [ ] graphs/check_cycle.py
* [ ] graphs/finding_bridges.py
* [ ] graphs/greedy_min_vertex_cover.py
* [ ] graphs/random_graph_generator.py
* [ ] matrix_operation.py
* [ ] other/least_recently_used.py
* [ ] other/lfu_cache.py
* [ ] other/lru_cache.py
* [ ] searches/simulated_annealing.py
* [ ] searches/ternary_search.py

**Comment by cclauss** [comment]
# Just three left to fix...
https://github.com/TheAlgorithms/Python/blob/master/mypy.ini#L5
* [ ] other/least_recently_used.py
* [ ] other/lfu_cache.py
* [ ] other/lru_cache.py
