### ISSUE TITLE
Open text file in a separate file not in the terminal.

### ISSUE THREAD

**Issue by ritikag06** [TheAlgorithms/Python#4067]
f= open("face.txt", mode= "wt", encoding= "utf-8")
f.writelines([' ______ \n/      \ \n|  0 0 | \n|   *  |\n\   v  /\n ------ '])

f.close()

g= open("face.txt", "r")
print(g.read())

^^ That is my code and I am trying to open "face.txt" in a separate file but it keeps printing in the terminal. I am using Visual 
Studio Code and I have python 3.9.0. Please help with some solutions. Thanks!

**Comment by Aniket-kumar404** [comment]
> 
> 
> f= open("face.txt", mode= "wt", encoding= "utf-8")
> f.writelines([' ______ \n/ \ \n| 0 0 | \n| * |\n\ v /\n ------ '])
> 
> f.close()
> 
> g= open("face.txt", "r")
> print(g.read())
> 
> ^^ That is my code and I am trying to open "face.txt" in a separate file but it keeps printing in the terminal. I am using Visual
> Studio Code and I have python 3.9.0. Please help with some solutions. Thanks!

u want to open a seprate file in other dailog box rather printing in terminal its quite easy just do following things:
import os
os.system("face.txt")
that's it

**Comment by ritikag06** [comment]
import os

f= open("face.txt", mode= "wt", encoding= "utf-8")
f.writelines([' ______ \n/      \ \n|  0 0 | \n|   *  |\n\   v  /\n ------ '])

f.close()

os.system("face.txt")


#g= open(os"face.txt", "r")
#print(g.read())

sh: face.txt: command not found 

^^it gives this command not found error when I used the text above...

**Comment by Aniket-kumar404** [comment]
hey  just run 
import os
os.open('face.txt')

that's it ,it will open your file content text  in notepad  . there is no such 
command like u used in last few lines... run only two line code if u want to open text file even the file and module is not in the same directory just pass the path of the file in between/......................... os.open(path_of_your_file)......

**Comment by xcodz-dot** [comment]
just to add on, the user here seems to be not using windows. :smile:

**Comment by H1Y1B8S1** [comment]
> > f= open("face.txt", mode= "wt", encoding= "utf-8")
> > f.writelines([' ______ \n/ \ \n| 0 0 | \n| * |\n\ v /\n ------ '])
> > f.close()
> > g= open("face.txt", "r")
> > print(g.read())
> > ^^ That is my code and I am trying to open "face.txt" in a separate file but it keeps printing in the terminal. I am using Visual
> > Studio Code and I have python 3.9.0. Please help with some solutions. Thanks!
> 
> u want to open a seprate file in other dailog box rather printing in terminal its quite easy just do following things:
> import os
> os.system("face.txt")
> that's it

its working perfectly in pycharm with opening in separate window.
