### ISSUE TITLE
Help me, how to do this

### ISSUE THREAD

**Issue by SyaziqHaizat** [TheAlgorithms/Python#4096]
![programming](https://user-images.githubusercontent.com/76934605/103506879-c90d0000-4e98-11eb-9f46-3000af7dd168.jpg)

**Comment by SyaziqHaizat** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/76934605/103507753-d7f4b200-4e9a-11eb-8cd9-e759416e5f56.jpg)

**Comment by vacom13** [comment]
How can I help?

**Comment by sudhakar6295** [comment]
Nationality not included in receipt .Do i need to include

**Comment by sudhakar6295** [comment]
I have completed this.
How to submit my code

**Comment by vacom13** [comment]
You need to create a pull request I think. Just check on that once.

**Comment by sudhakar6295** [comment]
Actually I am new to Git hub
Kindly help me out here

**Comment by vacom13** [comment]
Well that is the thing. I myself am trying to figure it out. M a newbie too XD. 

 So maybe first you need to fork this rep if you haven't already. Then you can add files to that rep and then in the forked rep itself, you can select the pull requests tab. It will compare the changes between your repository and the original. 

Then it will state the changes and then you can create a pull request. Then you need to specify what its for.

 Maybe just read a little on how to make good pull requests in the documentation. I don't want to guide you wrong. 

If you come across something useful, maybe help me out as well!

**Comment by Chaitanya-Varma-Sykam** [comment]
> I have completed this.
> How to submit my code

You can push ur code to this repository i think

**Comment by vacom13** [comment]
I think that requires access to the rep.

**Comment by SyaziqHaizat** [comment]
You know how to do this? can you share the code

**Comment by sudhakar6295** [comment]
please find the below code 





# -*- coding: utf-8 -*-
"""
Created on Thu Jan  7 06:35:29 2021

@author: SUDHAKAR
"""

def calculate_fee(category,nationality):
      if category.lower() == 'student':
          if nationality == 'L':
            return 600
          if nationality =='I':
            return 230
      if category.lower() == 'participant':
          if nationality == 'L':
            return 600
          if nationality =='I':
            return 230
def calculate_accomodation(no_of_days,nationality):
    if nationality == 'L':
        return 120*no_of_days
    if nationality == 'I':
        return (120/4.20)*no_of_days
def display(participant_name,category,accomodation,nationality,fee,accomodation_fee):
    print("   International Conference on Computational Science and   ")
    print("                     Technology (ICCST)")
    print("   -----------------------------------------------------   ")
    print("Name                         : "+ participant_name)
    print("Categoty                     : "+ category)
    print("Accommodation (Y/N)          : "+ accomodation.upper())
    if nationality.upper() == 'L':
      c = '(RM) '
    if nationality.upper() == 'I':
      c = '(USD)'
    print("Conference Fee  "+c+'        : '+ str(round(fee,2)))
    print("Accommodation Fee  "+c+'     : '+ str(round(accomodation_fee,2)))
    print("Total Fee  "+c+'             : '+ str(round(accomodation_fee+fee,2)))
    
    
    
    
participant_name = input("Enter Partcipant Name :")
category = input("Enter category as Participant/Student :")
nationality = input("Enter nationality as L/I :")
accomodation = input("Accommodation (Y/N) :")
if accomodation.upper() == 'Y':
    no_of_days = int(input("Number of days :"))
    accomodation_fee = calculate_accomodation(no_of_days,nationality.upper())
else:
    accomodation_fee = 0
fee = calculate_fee(category,nationality.upper())
display(participant_name,category,accomodation,nationality,fee,accomodation_fee
        )

**Comment by sudhakar6295** [comment]
Kindly assign the issue to my name
So that i can upload the code

**Comment by SyaziqHaizat** [comment]
Thank you for helping me really appreciate it.
