### ISSUE TITLE
matplotlib: plot a face using circles

### ISSUE THREAD

**Issue by ritikag06** [TheAlgorithms/Python#4098]
import matplotlib.pyplot as plt

radius=float(30)
circle=plt.Circle((15,30),radius, facecolor= 'white', edgecolor='black',linestyle='solid',linewidth='2.2')
plt.gca().add_patch(circle)
plt.plot()
plt.title('Circle')
plt.show()
Circle(float(radius))

I have made a circle using the code above but I am trying to make another one for the eye inside of this one but it is not showing up if I duplicate this code and change it to be smaller. How can I fix this?

**Comment by MiClaire** [comment]
Well 
- I want to know What is objective that you are trying to achieve by using matplotlib to create faces using Circles. 
- if you are new to python or matplotlib library try to learn how make plots like graphs, scatterplots and stuff, this will actually help you learning the new stuff.

**Comment by ritikag06** [comment]
> Well
> 
> * I want to know What is objective that you are trying to achieve by using matplotlib to create faces using Circles.
> * if you are new to python or matplotlib library try to learn how make plots like graphs, scatterplots and stuff, this will actually help you learning the new stuff.


I am learning python through small projects like plotting faces.

**Comment by MiClaire** [comment]
Actually, I have Never tried making Circles idea seem weird but result Looks funny.
```
# already imported matplotlib
figure, axes = plt.subplots() 
c_face = plt.Circle( (0.5, 0.5 ), 0.3 , fill = False )
c_eye_1 = plt.Circle( (0.4, 0.6 ), 0.1 , fill = False ) 
c_eye_2 = plt.Circle( (0.6, 0.4 ), 0.1 , fill = False )
c_mouth = plt.Circle( (0.4, 0.4 ), 0.05 , fill = False )

axes.set_aspect( 1 ) 
axes.add_artist(c_face) 
axes.add_artist(c_eye_1)
axes.add_artist(c_eye_2)
axes.add_artist(c_mouth)
plt.title( 'Circle Face' ) 
plt.show() 
```
Here you go. 
Try something Else.
Have Fun learning Python.
