### ISSUE TITLE
Please help with this:

### ISSUE THREAD

**Issue by ritikag06** [TheAlgorithms/Python#4114]
```
facesize=10
radius=5

for line in range(facesize):
    rightshift= ""
    for shift in range(5):
        print(" ")
    print("-")
```

Please help on how I can fix this. I am trying to make something like this:
```
            -
          -   -
        -       -
      -           -
    -               -  
      -           -
        -       -
          -   -
            -
```

**Comment by ForeverZlink** [comment]
Hello, i have a solution, but its without bonds of repeater.


Here is.


print(f'{"-":^20}')
print(f'{"-   -":^20}')
print(f'{"-       -":^20}')
print(f'{"-           -":^20}')
print(f'{"-               -":^20}')
print(f'{"-           -":^20}')
print(f'{"-       -":^20}')
print(f'{"-   -":^20}')
print(f'{"-":^20}')

**Comment by ForeverZlink** [comment]
I found a solution, but its without bonds of repeater.




print(f'{"-":^20}')
print(f'{"-----":^20}')
print(f'{"---------":^20}')
print(f'{"-------------":^20}')
print(f'{"---------------":^20}')
print(f'{"-------------":^20}')
print(f'{"---------":^20}')
print(f'{"-----":^20}')
print(f'{"-":^20}')

**Comment by monovon** [comment]
```
d = {1:"          -          ", 
     2:"        -   -        ",
     3:"      -       -      ",
     4:"    -           -    ",
     5:"  -               -  "}

for key,value in d.items():
    if key in range(1,5):
        print(value)
for key,value in reversed(d.items()):
    print(value)

          -          
        -   -        
      -       -      
    -           -    
  -               -  
    -           -    
      -       -      
        -   -        
          -          

```

I hope this helps.

**Comment by kunatastic** [comment]
```
n = 5  # here n is the length of the side.

print(" "*(n-1)+"-")
for i in range(2,n+1):
    print(" "*(n-i)+"-"+" "*(2*i-3)+"-")
for i in range(n-1,1,-1):
    print(" "*(n-i)+"-"+" "*(2*(i)-3)+"-")
if (n>1):
    print(" "*(n-1)+"-")
```
I hope this helps. If you want to draw this figure

```
          -      
        -   -        
      -       -      
    -           -    
  -               -  
    -           -    
      -       -      
        -   -        
          -    
```

**Comment by abdi-tach** [comment]
print=“”””\           “”””

**Comment by xcodz-dot** [comment]
> ```
> facesize=10
> radius=5
> 
> for line in range(facesize):
>     rightshift= ""
>     for shift in range(5):
>         print(" ")
>     print("-")
> ```
> 
> Please help on how I can fix this. I am trying to make something like this:
> 
> ```
>             -
>           -   -
>         -       -
>       -           -
>     -               -  
>       -           -
>         -       -
>           -   -
>             -
> ```

try stackoverflow for that, this is really not a good spot for asking such questions

**Comment by mr-robot-007** [comment]
Run this code it gives the exact answer 
n = 5
for i in range(1,n+1):
    for j in range(1,n+i+1):
        if i+j ==6:
            print("- ",end = "")
        elif j==i+4:
            print("- ",end = "")
        else:
            print("  ",end = "")
    print()


for i in range(n-1,0,-1):
    for j in range(1,n+i+1):
        if i+j ==6:
            print("- ",end = "")
        elif j==i+4:
            print("- ",end = "")
        else:
            print("  ",end = "")
    print()



![image](https://user-images.githubusercontent.com/72905336/105526333-46919680-5d08-11eb-9bf7-1604a0c9e108.png)

**Comment by mr-robot-007** [comment]
> ```
>run this code it gives exact answer 
>n = 5
>for i in range(1,n+1):
>   for j in range(1,n+i+1):
>       if i+j ==6:
>            print("- ",end = "")
>       elif j==i+4:
>            print("- ",end = "")
>        else:
>           print("  ",end = "")
>    print()
>for i in range(n-1,0,-1):
>   for j in range(1,n+i+1):
>        if i+j ==6:
>            print("- ",end = "")
>        elif j==i+4:
>            print("- ",end = "")
>        else:
>            print("  ",end = "")
>    print()
>
>             -
>           -   -
>         -       -
>       -           -
>     -               -  
>       -           -
>         -       -
>           -   -
>             -
>
> ```

**Comment by behzadshomali** [comment]
The thing you should consider is by typing `print('CONTENT')`, it will print the content we passed to it and then goes to a new line, so to avoid this you can do this: `print('CONTENT', end='')`.
Aside that I wrote a simple piece of code that does likely something you need as the result:
`facesize=10

for i in range(facesize): # print top part
    leftshift= " " * (facesize-i)
    centershift = ' ' * (2*i)
    print(leftshift + '-' + centershift + '-')

for i in range(facesize-1, -1, -1): # print bottom part
    leftshift= " " * (facesize-i)
    centershift = ' ' * (2*i)
    print(leftshift + '-' + centershift + '-')`

Note that in Python multiplying a string by a number means to replicate that string. For instance:
'a' * 5 is equal to 'aaaaa'!
