### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by mahendra7801** [TheAlgorithms/Python#4115]
x=4
print x

**Comment by mahendra7801** [comment]
Poor.ptuy

**Comment by xxbadgame** [comment]
>>> 4

**Comment by surbhinahta1211** [comment]
I am also facing the same issue related to [python](https://www.sevenmentor.com/best-python-classes-in-pune.php). thanks for your advice.

**Comment by Anuj-malviya0** [comment]
What you are trying to do?, if you are trying printing x, here is right way to do it
x=4
print(x)

**Comment by xcodz-dot** [comment]
> Poor.ptuy

what are you even trying with that thing?

> I am also facing the same issue related to [python](https://www.sevenmentor.com/best-python-classes-in-pune.php). thanks for your advice.

why do you even advertise. you are very much of a bot.

@dhruvmanila @cclauss

**Comment by xcodz-dot** [comment]
> x=4
> print x

actually this is github.com sir and for what you need help can be asked on [stackoverflow](https://stackoverflow.com)

**Comment by cclauss** [comment]
@xcodz-dot Please do not respond to spamers.

**Comment by Anuj-malviya0** [comment]
What is happening here?

**Comment by xcodz-dot** [comment]
a few spammers advertising on github
