### ISSUE TITLE
Can't install EPANETTOOLS on my Python 3.9 using pip 20.3.3 #1

### ISSUE THREAD

**Issue by miguelguavita** [TheAlgorithms/Python#4138]
I'm learning to match **EPANET** (a hydraulic modelling software) and **PYTHON 3.9**, so I need to install **EPANETTOOLS** module. I use `pip install epanettools` as PyPI says, but I can't get it.

PyPI page: [https://pypi.org/project/EPANETTOOLS/](url)

The first line on my cmd response is: `Building wheel for epanettools (setup.py) ... error`
Then it says: `ERROR: Command errored out with exit status 1`
And it gets a numerous lines of red code.

How can I fix it?

**Comment by xcodz-dot** [comment]
I guess you should raise this issue in [this repository](https://github.com/asselapathirana/epanettools) or maybe on stackoverflow.

**Comment by Naycat** [comment]
I'm having the same issue.

**Comment by cclauss** [comment]
Wrong repo.  Please visit https://github.com/asselapathirana/epanettools
