### ISSUE TITLE
Alexa

### ISSUE THREAD

**Issue by nihardave1316** [TheAlgorithms/Python#4141]
Heyaa

**Comment by Tanj01** [comment]
Can you please elaborate what do we have to program in here

**Comment by Gl0deanR** [comment]
@Tanj01 you should read the [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) file and to summarize, check below:


> We are very happy that you consider implementing algorithms and data structure for others! This repository is referenced and > used by learners from all over the globe. Being one of our contributors, you agree and confirm that:
>
> - You did your work - no plagiarism allowed
>   - Any plagiarized work will not be merged.
> - Your work will be distributed under [MIT License](LICENSE.md) once your pull request is merged
> - You submitted work fulfils or mostly fulfils our styles and standards

**Comment by xcodz-dot** [comment]
cc: @cclauss @dhruvmanila
