### ISSUE TITLE
Phyton tutorial  (3.7.0)

### ISSUE THREAD

**Issue by guaraguhe** [TheAlgorithms/Python#4142]
**An informal introduction to python**

_*some example*_
#this is the first comment
spam = 1 #second comment
         #.. third...
text = "#aww ."

**Comment by Aditya-Ramachandran** [comment]
Hi, I would like to work on this issue, can you suggest me ways get started?

**Comment by xcodz-dot** [comment]
cc: @cclauss @dhruvmanila

**Comment by cclauss** [comment]
Not an algorithm.
