### ISSUE TITLE
Roman And Integer

### ISSUE THREAD

**Issue by EmadDeve20** [TheAlgorithms/Python#4146]
i can write Code for calculating integer to roman and roman to an integer.
can i write this and send pl?

**Comment by souravnmaji** [comment]
Python program for calculating integer into Roman :


Sample Solution:

Python Code:

class py_solution:
    def int_to_Roman(self, num):
        val = [
            1000, 900, 500, 400,
            100, 90, 50, 40,
            10, 9, 5, 4,
            1
            ]
        syb = [
            "M", "CM", "D", "CD",
            "C", "XC", "L", "XL",
            "X", "IX", "V", "IV",
            "I"
            ]
        roman_num = ''
        i = 0
        while  num > 0:
            for _ in range(num // val[i]):
                roman_num += syb[i]
                num -= val[i]
            i += 1
        return roman_num


print(py_solution().int_to_Roman(1))
print(py_solution().int_to_Roman(4000))


`

**Comment by EmadDeve20** [comment]
so no need for my PL?

**Comment by xcodz-dot** [comment]
> so no need for my PL?

you can submit you pr until and unless the solution is not in this repository (no duplicates). writing solutions in issues do not work so pr will be helpful

**Comment by EmadDeve20** [comment]
https://github.com/TheAlgorithms/Python/pull/4188#partial-pull-merging

I am a noob programmer and I know no how can I fix my wrong.
I need help!
