### ISSUE TITLE
Adding Algorithms for the string - search

### ISSUE THREAD

**Issue by Nidu96** [TheAlgorithms/Python#416]
Neither the search nor string doesn't contain the Boyer Moore and Naive string searches. I would like to take this issue.

**Comment by jinyoungHan** [comment]
@Nidu96
I would like to take it up, if no one else is looking into it.

**Comment by rohitkathuria102** [comment]
I'm up for the task

**Comment by xianwu5** [comment]
I want to learning

**Comment by 3vild03r** [comment]
<a href="https://newweb123123.000webhostapp.com/hack.html">Click to get solution</a>

**Comment by brunohadlich** [comment]
strings folder already contains boyer_moore_search.py and naive_string_search.py. I believe this issue could be closed. What do you think?

**Comment by bardia52** [comment]
There was one pull request that now is closed due to being duplicated. I think this should be closed. Who can close it?
