### ISSUE TITLE
using "and" and "or" in "if"

### ISSUE THREAD

**Issue by TheBigBaldHead** [TheAlgorithms/Python#4169]
I got a problem here with the condition of "if"
for example:
if (a==b or a==c) and (x==y or x==z):
print("yeah, whatever")
does it work? 
I want such a thing that be like: [if p and q:] which p is: (a==b or a==c) and q is: (x==y or x==z)
how should I use it?

**Comment by scottwilliams435** [comment]
p = (a == b or a == c)
q = (x == y or x == z)

if p and q:
    print("Whatever")

**Comment by TheBigBaldHead** [comment]
got ya

**Comment by TheBigBaldHead** [comment]
ah there's problem
what I want to code is different from the example
my own code is something like:
and I want the p to be: 0 or 1 or 2 or 3
if q==qwer3210[p] and w==qwer3210[p] and e==qwer3210[p] and r==qwer3210[p]: print("whatever")
        else:
            do()

**Comment by kavish-d** [comment]
`
if all( [ (q==qwer3210[p] and w==qwer3210[p] and e==qwer3210[p] and r==qwer3210[p]) for p in range(4) ] ):
    print("whatever")
else:
    do()
`

**Comment by Chaityyy** [comment]
From what I understood,

for p in range(3):
    if (q,w,e,r) == (qwer3210[p],qwer3210[p],qwer3210[p],qwer3210[p]):
        print("whatever")
        break
    else:
        do()

I hope this will work.

**Comment by xcodz-dot** [comment]
Oh guys, please use a little bit of markdown here 
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by cclauss** [comment]
@TheBigBaldHead Can this issue be closed?
