### ISSUE TITLE
minimum_spanning_tree_kruskal2.py

### ISSUE THREAD

**Issue by Eff4real** [TheAlgorithms/Python#4170]
While comparing the outputs from the "minimum_spanning_tree_kruskal2.py" with the simple "minimum_spanning_tree_kruskal.py" for a big graph, I figured out the bad comportment of the algorithm.

**Comment by xcodz-dot** [comment]
that will be very very great if you could submit the PR for that, thanks 😄.

**Comment by cclauss** [comment]
@Eff4real Can this issue be closed?
