### ISSUE TITLE
Bottom-up-search 

### ISSUE THREAD

**Issue by yitzackRabin** [TheAlgorithms/Python#4178]
It's implementation is rare in many languages

**Comment by Varun270** [comment]
Can someone explain this issue to me , I am not able to understand what this issue is all about.

**Comment by yitzackRabin** [comment]
I'll give a push ion my research after class in 6hours time

**Comment by Jaynemis** [comment]
Thank You

**Comment by dhruvmanila** [comment]
This does not seem like an issue related to TheAlgorithms/Python repository. If you think otherwise, please provide us with more details. Closing this issue.
