### ISSUE TITLE
pre-commit issue ( Validate Filename of env )

### ISSUE THREAD

**Issue by AyushSehrawat** [TheAlgorithms/Python#4182]
I created a pr to emails_from_url.py  , but i failed the pre-commit check . So i passed all the checks except one
```bash
Validate filenames.......................................................[41mFailed[m
[2m- hook id: validate-filenames[m
[2m- duration: 0.16s[m
[2m- exit code: 1052[m
```

```bash
526 files contain uppercase characters:
\env\Lib\site-packages\appdirs.py
\env\Lib\site-packages\cfgv.py
\env\Lib\site-packages\easy_install.py
\env\Lib\site-packages\filelock.py
\env\Lib\site-packages\mccabe.py
\env\Lib\site-packages\nodeenv.py
\env\Lib\site-packages\six.py
# So on....
```

I passed the pre-commit check , but because of this  , i am unable to commit . Can anyone help ?

**Comment by AyushSehrawat** [comment]
OS - Windows 10 x64 
Python version - 3.8.7

**Comment by AyushSehrawat** [comment]
### So guys i solved this issue the problem was solved like this - 

### Create `.env` or `.venv` instead of `env` or `venv`  . It helps exclude virtual environments from pre-commit check and avoid Validate filename error . 

#### I think that it should be included in Contributing.md  , to avoid such errors by others in future

**Comment by AyushSehrawat** [comment]
I reopened the issue , close it once you notice it , and update the contributing.md if possible :)

**Comment by xcodz-dot** [comment]
hello, make sure that you do not accidently commit virtual environment with your code. 😉

**Comment by AyushSehrawat** [comment]
> hello, make sure that you do not accidently commit virtual environment with your code. 😉

I didn't. The git ignore file is there to prevent it. 
still `.env` instead of env fixed it m
