### ISSUE TITLE
qrcode save in path

### ISSUE THREAD

**Issue by traxio-owner** [TheAlgorithms/Python#4187]
How do I save a qrcode image in a path like C:\Users\???\Desktop/folder1
(qrcode module)

**Comment by ashishjayamohan** [comment]
Looking at the docs, it doesn't seem too hard to do so. Check https://pypi.org/project/qrcode/ and scroll down. They have a couple examples on how to do this from command line and from your script as well.

**Comment by traxio-owner** [comment]
Why did you ask mail me.

**Comment by ashishjayamohan** [comment]
What do you mean?

**Comment by traxio-owner** [comment]
Why did you email me
Also I couldn't edit my message

**Comment by ashishjayamohan** [comment]
Uh... I didn't email you. I answered your question directly on GitHub

**Comment by traxio-owner** [comment]
Oh boy nevermind then, I have a question tho is my messages are answers on
GitHub too

**Comment by ashishjayamohan** [comment]
Yes, your messages are regarded as comments on Github

**Comment by traxio-owner** [comment]
Oh boy lmao thanks tho

**Comment by dhruvmanila** [comment]
This does not seem like an issue related to TheAlgorithms/Python repository. Closing this issue.
