### ISSUE TITLE
How can I loop a program for specified period of time

### ISSUE THREAD

**Issue by iamraghav1503** [TheAlgorithms/Python#4200]
pe.moveTo(132,475,1),pe.click(132,475,1),pe.typewrite(superb bro i want this because of camera),pe.click(917,515,1)

i want to loop this program for 2 hours and after the word 'camera' in the sentence i want to add non repeating unique numbers

**Comment by H1Y1B8S1** [comment]
Use time module.

**Comment by iamraghav1503** [comment]
> Use time module.

How can I do that

**Comment by devanshraj3000** [comment]
import time

time_end = time.time() + t
while time.time() < time_end:
       #perform_your_activity_for_t_seconds

**Comment by devanshraj3000** [comment]
`import time

time_end = time.time() + t
while time.time() < time_end:
       #perform_your_activity_for_t_seconds`

**Comment by iamraghav1503** [comment]
thanks @devanshraj3000  now i want to add unique non repeating words after the word "camera" 
so that the output becomes like
best in class luxary want because of triple rear camera 1
best in class luxary want because of triple rear camera 2
best in class luxary want because of triple rear camera 3
and so on....

x=1
>>> time_end=time.time()+30
>>> while time.time()<time_end:
	pe.moveTo(104,279,1),pe.click(104,279,1),pe.typewrite("best in class luxary want because of triple rear camera", x),time.sleep(1),pe.click(925,315,1),time.sleep(4)
	x=x+1
	
	this is the code i'e been using but when i remove the x commands from the program it works perfectely well but when i add the x commands as pasted above the program's  output actually becomes slower and slower instead of adding numbers after the word "camera"

**Comment by iamraghav1503** [comment]
https://user-images.githubusercontent.com/69894986/107762642-53c40300-6d53-11eb-88e9-d8e2943403ab.mp4

this is the output without putting x for adding non repeating numbers
![IDLE Shell 3 9 1 12_02_2021 4_59_59 pm](https://user-images.githubusercontent.com/69894986/107762952-cf25b480-6d53-11eb-9b47-f29ee6ddf549.png)

this is the image of the program
----------------------------------------------------------------------------------------------------------------------------------------------

now
![_IDLE Shell 3 9 1_ 12_02_2021 5_08_08 pm](https://user-images.githubusercontent.com/69894986/107763731-13658480-6d55-11eb-90f9-c86c9bb7d399.png)

this is the program with x


https://user-images.githubusercontent.com/69894986/107764102-a1416f80-6d55-11eb-9e79-bb19d46bb412.mp4

output of program with x

how can i fix that and add unique non repeating numbers after the word "camera".

**Comment by Viridescence** [comment]
Firstly, you would benefit by writing this in a python file instead of a shell. 
<img width="270" alt="image" src="https://user-images.githubusercontent.com/79451920/108739599-16baf600-7535-11eb-9abd-ef459569a99d.png">
Create a new file, save it, and place your code in there first. The shell is not meant for extensive coding, it is meant for tests, function calling, etc. This is likely causing a keyboard interrupt, as your second line is interrupting your first.

**Comment by iamraghav1503** [comment]
I did that but the issue is not resolved I think there is some problem with the code itself

**Comment by xcodz-dot** [comment]
> I did that but the issue is not resolved I think there is some problem with the code itself

and yes that's the problem

**Comment by Williamjacobsen** [comment]
use time module

**Comment by cclauss** [comment]
Can this issue be closed?
