### ISSUE TITLE
[mypy] Packages that are not recognised

### ISSUE THREAD

**Issue by MatthewG25** [TheAlgorithms/Python#4222]
When working on the sorting algorithms for issue #4085, there was one issue that I could not fix so I am raising it here. The issue is that certain packages are not recognised by mypy and can't check for errors as there is no PEP 561 complaint stub package for the installed package. From the mypy errors for the whole repository, the packages that are recognised but dont have stubs are pandas, qiskit, numpy, sklearn, matprolib, statsmodels, skfuzzy, cv2, PIL, mpmath, scipy, bs4, fake_useragent, lxml. For pytest and django it doesnt find any implementation or stubs for these packages. These errors according to mypy docs can be fixed by updating the packages, making our own PEP 561 compliant stub packages to work with or to replace the packages with ones with PEP 561 complaint packages. As only a contributor and with no experience with PEP 561 complaint stub packages and how they work, I didnt know how the other contributors or the owners of this repo want to do with this. Hopefully this will help discussion on what to do now with this information

**Comment by cclauss** [comment]
Run `mypy --ignore-missing-imports` as is done in #4274
