### ISSUE TITLE
Making a table

### ISSUE THREAD

**Issue by Eruannt** [TheAlgorithms/Python#4281]
Hi I got problem I don't have idea to do a table 40x40 when it is fullfiled in 25% each with marks: *, #, @, +. How can I do it? WIth loop maybe def or there is a simple way that I didn't figure out?

**Comment by algobytewise** [comment]
I'm not sure what kind of table you are talking about. If you mean a 2-dimensional list, see [here](https://snakify.org/en/lessons/two_dimensional_lists_arrays/). But this type of question might be better suited for question and answer sites like https://stackoverflow.com unless it pertains to one of the algorithms here.

**Comment by Eruannt** [comment]
Yeah but instead of numbers I need to do marks list and fulfill 40x40 table with marks

**Comment by algobytewise** [comment]
Maybe something like:
```python
table = []
rows = 40
columns = 40
for i in range(rows):
    table.append([])
    for j in range(columns):
        table[i].append('*')
```

**Comment by cclauss** [comment]
```python
from random import shuffle
chars = list("*#@+" * 400)
shuffle(chars)
for row in range(40):
    print("".join(chars[row * 40: (row + 1) * 40]))
```
The last two lines could be a one-liner with a double generator but that might be harder to reason about.
