### ISSUE TITLE
Unable to move the file "other/words"

### ISSUE THREAD

**Issue by algobytewise** [TheAlgorithms/Python#4284]
I wanted to move the files "other/anagrams.py" and "other/words" to the string-folder to make them easier to find. But I can't move the file "other/words" since it has "contains an invalid extension" according to algorithms-keeper. I left the file "other/anagrams.py" in the other-folder for now since it seems to depend on "other/words".

**Comment by dhruvmanila** [comment]
That seems like a `.txt` file and as that file does not contain any extension, the bot will not be able to infer it. If possible, can you please update the file name to include the extension in your open pull request?

**Comment by algobytewise** [comment]
Thanks for the insight, I'll give it a try once I have the time.
