### ISSUE TITLE
Can import or only download?

### ISSUE THREAD

**Issue by X1Z53** [TheAlgorithms/Python#4312]
Can one of these libraries be imported or can only be downloaded and inserted into the project?

**Comment by algobytewise** [comment]
One way to make use of the algorithms here is to download the specific algorithm you are interested in, import it and call the functions defined in it. So if you want to use dynamic_programming/factorial.py: download it, put the file into your project-directory and call the function using

```python
import factorial
print(factorial.factorial(7))
```

But you could also just copy and paste the code of the factorial-function. It's under the MIT-license so you are relatively free concerning how you want to use it.

I think this is an important issue, so it might be a good idea to add something along these lines to "Readme.md" about how the code here can be used. Maybe someone of the members could comment on this.
