### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Amychan-air** [TheAlgorithms/Python#4316]
I am a novice. I don't know what i did wrong.
when i run main.py, IndexError: list index out of range
it is main.py:
data = open('data.txt', 'r')
row = -1
while True:
    row = row + 1
    word = data.readlines()[row]
    print(html_p.find(word))

data.txt:
tommy
amy
bobby
Change
next

**Comment by iamkaushal** [comment]
Hi @Amychan-air  you are increasing the value of the `row ` in an infinite loop. Hence it is getting out of range once the rows in the files reach the end.

**Comment by Amychan-air** [comment]
I have found another solution.But I want to know why this error occurs.
it is my new python:
data = open('data.txt', 'r')
row = -1
while True:
    if row <= 15:
        row = row + 1
        word = data.readlines()[row]
        print(word)
    else:
        break
