### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by Riteshkumar-beep** [TheAlgorithms/Python#4329]
I am a begginer .so is there anyone who would like to help me to learn a little bit about it?

**Comment by QuantumNovice** [comment]
@Riteshkumar-beep  you can find contribution guidlines here [contribution guidlines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
Read the guidelines.
Fork the project. 
Commit your changes and send a PR.

**Comment by LoopGlitch26** [comment]
Hey @Riteshkumar-beep I'm also new here. I started by finding out where I can contribute and what I already know that can help the organization

**Comment by Divyanshusoni860** [comment]
> I am a begginer .so is there anyone who would like to help me to learn a little bit about it?

Me also
