### ISSUE TITLE
why in python select sort , swap element use tuple?

### ISSUE THREAD

**Issue by labike** [TheAlgorithms/Python#4367]
https://github.com/TheAlgorithms/Python/blob/6f21f76696ff6657bff6fc2239315a1650924190/sorts/selection_sort.py#L39

**Comment by Cosmicoppai** [comment]
It doesn't matter, you can remove the parenthesis if you want. They are just for the visual purpose...

**Comment by Rada8732** [comment]
Why did this close

**Comment by labike** [comment]
> Why did this close

reopen
