### ISSUE TITLE
Let’s get rid of “Approve and Run” for first-time contributors

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#4369]
Why do we want to waste time and focus for both contributors and maintainers?

**Comment by dhruvmanila** [comment]
I think it's a default behavior now: 
- https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/
- https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

I don't know whether we can disable that and even if we could it will probably be under the repo settings which can only be accessed by the owner. So, pinging @dynamitechetan @AnupKumarPanwar

**Comment by Rada8732** [comment]
Because, running a good involves both assets

**Comment by dhruvmanila** [comment]
Yes, I understand why GitHub is taking this approach although it would also be beneficial to provide an option to disable that :)
