### ISSUE TITLE
Hello , this is my first time to open source would you please guide me how to get started for this project?

### ISSUE THREAD

**Issue by iCGSE** [TheAlgorithms/Python#4386]
Hello , this is my first time to open source would you please guide me how to get started for this project?

_Originally posted by @vidnyani in https://github.com/TheAlgorithms/Python/issues/4370#issuecomment-829848262_

**Comment by AliHaider20** [comment]
Find the topic which you know very well and add some improvements or else you can find some issues in the project.
Below are the steps you can use to contribute to Github projects using Git.


1.Fork the repository.
2.Create a separate topic branch created from the latest master.
2.1 git branch
2.2 git checkout master
2.3 Git checkout -b "newer-branch"
2.4 git add .
3.Commit and push the topic branch.
4.Make a pull request.

https://guides.github.com/introduction/git-handbook/

Hope this helps.
