### ISSUE TITLE
Create a Median Heap

### ISSUE THREAD

**Issue by anhtumai** [TheAlgorithms/Python#4394]
Create a median heap from Min Heap and Max Heap implementation and write unittest for it. This data structure can help in solving   median in stream of integers problem: https://www.geeksforgeeks.org/median-of-stream-of-integers-running-integers/

**Comment by Priyaraj17** [comment]
May I work on this?

**Comment by anhtumai** [comment]
I think I already have an implementation for that: https://github.com/anhtumai/data-structure-and-algorithms-collection/blob/master/heap/median_heap.py

You can take it as a reference.
