### ISSUE TITLE
Add a license for your repository

### ISSUE THREAD

**Issue by edawine** [TheAlgorithms/Python#44]
Hi!

I would request the owner of this repository to add a license. A license is useful to show if whether a user can use your code freely or not. If you do not have a license, a user may avoid to use your code (see here: http://choosealicense.com/no-license/).

I recommend using MIT license (http://choosealicense.com/licenses/mit/) so the user can tinker with the codes themselves. Also, by using this license, the user can't hold you liable if somehow they broke their computers using your example codes.

**Comment by dynamitechetan** [comment]
Thanks
