### ISSUE TITLE
Adding Threaded Binary Tree and Priority Queue implementations

### ISSUE THREAD

**Issue by Korra15** [TheAlgorithms/Python#4404]
Greetings ma’am/sir,
Going through the list of algorithms, I could not find any implementation of threaded binary tree or priority queues. Could I start working on these algorithms?

**Comment by ak14bbk30** [comment]
yes sure

**Comment by onlinejudge95** [comment]
Make sure to split the implementation into separate PRs

**Comment by Korra15** [comment]
okay
