### ISSUE TITLE
Convert Hexa to Binary

### ISSUE THREAD

**Issue by ktsrivastava29** [TheAlgorithms/Python#4429]
**I want to add a file that converts the hexadecimal value to binary**
**I would be very grateful to do this task if assigned to me**

**Comment by onlinejudge95** [comment]
@ktsrivastava29 this is not how open source contribution works, you can't close the PR's that ask you for a change to be done again. You need to do all your changes in a single PR.

**Comment by ktsrivastava29** [comment]
Sir, I wholeheartedly apologize actually, it is the first time I'm contributing something in open source so, I'm a little unaware of the norms. Sir, I've modified the file now and I request you to look into the code and make me aware of any further modifications that are required.

**Comment by sitanshu422** [comment]
ok
