### ISSUE TITLE
Python compiler error on sw_64 platform

### ISSUE THREAD

**Issue by Ccaomei** [TheAlgorithms/Python#4459]
The error message is as follows:
        /tmp/ccf4b69b.s: Assembler messages:
/tmp/ccf4b69b.s:578: error：unknown opcode `call_pal'
/tmp/ccf4b69b.s: Internal error, aborting at write.c:602 in size_seg
Please report the bug。

Python build finished, but the necessary bits to build these modules were not found:
_tkinter           bsddb185           dl              
imageop            sunaudiodev                        
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

Failed to build these modules:
_ctypes                                               

running build_scripts

The system has been installed libffi.sw_64 and libffi-devel.sw_64

**Comment by shrishti-67** [comment]
Translate in english

**Comment by Prajwalprakash3722** [comment]
Please translate in English.
