### ISSUE TITLE
matrix_operation.py - Function _shape assumes that the input is a rectangular matrix

### ISSUE THREAD

**Issue by pedrolopesc** [TheAlgorithms/Python#4477]
About the file matrix/matrix_operation.py, the shape of the matrix returned could be wrong if its not a rectangular one, since the return column size it is based only in the first row, assuming that the matrix is rectangular.

In case of matrix = [[1, 2], [1, 2, 3]] it would return [2, 2]

Wouldn't this help?
`def _shape(matrix: list[list]) -> tuple[int, int]:`
`if (len(set([len(row) for row in matrix]) == 1):`
`return len(matrix), len(matrix[0])`
`raise TypeError("Matrix is not rectangular")`

_Originally posted by @pedrolopesc in https://github.com/TheAlgorithms/Python/pull/4337#r645872674_

**Comment by Gagan1111** [comment]
> 
> 
> In case of matrix = [[1, 2], [1, 2, 3]] it would return [2, 2]
> 
> Wouldn't this help?
> `def _shape(matrix: list[list]) -> tuple[int, int]:`
> `if (len(set([len(row) for row in matrix]) == 1):`
> `return len(matrix), len(matrix[0])`
> `raise TypeError("Matrix is not rectangular")`
> 
> _Originally posted by @pedrolopesc in [#4337 (comment)](https://github.com/TheAlgorithms/Python/pull/4337#r645872674)_


can you elaborate the issue please.....

**Comment by pedrolopesc** [comment]
> > In case of matrix = [[1, 2], [1, 2, 3]] it would return [2, 2]
> > Wouldn't this help?
> > `def _shape(matrix: list[list]) -> tuple[int, int]:`
> > `if (len(set([len(row) for row in matrix]) == 1):`
> > `return len(matrix), len(matrix[0])`
> > `raise TypeError("Matrix is not rectangular")`
> > _Originally posted by @pedrolopesc in [#4337 (comment)](https://github.com/TheAlgorithms/Python/pull/4337#r645872674)_
> 
> can you elaborate the issue please.....

Sorry about that. I'm starting on github. Hope I'm not disturbing...

**Comment by KholoodS** [comment]
I would like to work on this issue, may I?
