### ISSUE TITLE
New Guy with Python Error

### ISSUE THREAD

**Issue by AVwebcss** [TheAlgorithms/Python#4493]
Please first of all apologise if I'm posting in a wrong place.

I don't understand how this website works.

I'm no coder, this is my first attempt coding something.

I followed some instruction on YouTube to create an automation using Python and InstaPy.

The code of the .py file is the following

`from instapy import InstaPy`

`from instapy import smart_run`

`my_username = 'myuser'`

`my_password = 'mypassword'`

`session = InstaPy(username=my_username,`

`password=my_password,`

`headless_browser=True)`

`with smart_run(session):`

	`session.set_relationship_bounds(enable=True,`

`delimit_by_numbers=True,`

`max_followers=600,`

`min_followers=30,`

`max_following=600)`

	`session.like_by_tags(['tag1', 'tag2', 'tag3', 'tag4'], amount=300)`

	

The `headless_browser=True` because I want to run multiple automatons for different accounts that I have.

At least, based on the tutorials, that's what I think is the correct way.

Using the Terminal, accessing the folder on the desktop where the file is located I run the command `python3` `test.py`

I'm getting a huge error.

I already looked at some post on GtHub that refer to errors on mac and I've already followed the instruction there but I still get this error:

`InstaPy Version: 0.6.13`

 `._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.` 

`Workspace in use: "/Users/av/InstaPy"`

`Error, unable to determine correct filename for 64bit macos`

`Traceback (most recent call last):`

  `File "/Users/av/Desktop/InstaAuto/test.py", line 7, in <module>`

`session = InstaPy(username=my_username,`

  `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 325, in __init__`

`self.browser, err_msg = set_selenium_local_session(`

  `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 122, in set_selenium_local_session`

`driver_path = geckodriver_path or get_geckodriver()`

  `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 38, in get_geckodriver`

`sym_path = gdd.download_and_install()[1]`

  `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install`

`filename_with_path =` [`self.download`](https://self.download)`(version,`

  `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download`

`download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)`

  `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url`

`raise RuntimeError(info_message)`

`RuntimeError: Error, unable to determine correct filename for 64bit macos`

`AVs-MacBook-Pro:InstaAuto av$` 

&#x200B;

Can someone help me understand what should I do?

Thank you so much for you time.

**Comment by abhshkvrm** [comment]
I can work on it I guess

**Comment by Prajwalprakash3722** [comment]
Please check once in stack-overflow, and do post the tutorial link. ✌🏼

**Comment by AVwebcss** [comment]
> Please check once in stack-overflow, and do post the tutorial link. ✌🏼

Hello, 

thank you for your reply!

the post that I followed to solve the issue was this one

https://github.com/timgrossmann/InstaPy/issues/5672

But as you can see in my post I still got the same error.

**Comment by meShubhamJha** [comment]
> Please first of all apologise if I'm posting in a wrong place.
> 
> I don't understand how this website works.
> 
> I'm no coder, this is my first attempt coding something.
> 
> I followed some instruction on YouTube to create an automation using Python and InstaPy.
> 
> The code of the .py file is the following
> 
> `from instapy import InstaPy`
> 
> `from instapy import smart_run`
> 
> `my_username = 'myuser'`
> 
> `my_password = 'mypassword'`
> 
> `session = InstaPy(username=my_username,`
> 
> `password=my_password,`
> 
> `headless_browser=True)`
> 
> `with smart_run(session):`
> 
> ```
> `session.set_relationship_bounds(enable=True,`
> ```
> 
> `delimit_by_numbers=True,`
> 
> `max_followers=600,`
> 
> `min_followers=30,`
> 
> `max_following=600)`
> 
> ```
> `session.like_by_tags(['tag1', 'tag2', 'tag3', 'tag4'], amount=300)`
> ```
> 
> The `headless_browser=True` because I want to run multiple automatons for different accounts that I have.
> 
> At least, based on the tutorials, that's what I think is the correct way.
> 
> Using the Terminal, accessing the folder on the desktop where the file is located I run the command `python3` `test.py`
> 
> I'm getting a huge error.
> 
> I already looked at some post on GtHub that refer to errors on mac and I've already followed the instruction there but I still get this error:
> 
> `InstaPy Version: 0.6.13`
> 
> `._. ._. ._. ._. ._. ._. ._. ._.`
> 
> `Workspace in use: "/Users/av/InstaPy"`
> 
> `Error, unable to determine correct filename for 64bit macos`
> 
> `Traceback (most recent call last):`
> 
> `File "/Users/av/Desktop/InstaAuto/test.py", line 7, in <module>`
> 
> `session = InstaPy(username=my_username,`
> 
> `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 325, in __init__`
> 
> `self.browser, err_msg = set_selenium_local_session(`
> 
> `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 122, in set_selenium_local_session`
> 
> `driver_path = geckodriver_path or get_geckodriver()`
> 
> `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 38, in get_geckodriver`
> 
> `sym_path = gdd.download_and_install()[1]`
> 
> `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install`
> 
> `filename_with_path =` [`self.download`](https://self.download)`(version,`
> 
> `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download`
> 
> `download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)`
> 
> `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url`
> 
> `raise RuntimeError(info_message)`
> 
> `RuntimeError: Error, unable to determine correct filename for 64bit macos`
> 
> `AVs-MacBook-Pro:InstaAuto av$`
> 
> ​
> 
> Can someone help me understand what should I do?
> 
> Thank you so much for you time.

I recently used Instapy in my macbook M1, this issue could arrive if you do not have firefox installed in your computer. You can do one thing, simply clone instapy from Github and install firefox in your mac, then just modify quickstart.py file to automate your insta, it will work like charm.

**Comment by L3str4nge** [comment]
Issue not related to this repository.
