### ISSUE TITLE
recovery of password of protected excel sheet

### ISSUE THREAD

**Issue by emshihab008** [TheAlgorithms/Python#4519]
Hello Everyone,
I have an enquiry regarding recovery of old password which is used to protect excel sheet. Can anyone provides any solution using python? (for my cases, it is highly important to know the old password).

Regards,
Ekram

**Comment by kkanekii** [comment]
can you share code what you have done so far

**Comment by ankithreddy571** [comment]
I'm so sorry. I have installed GitHub recently. I don't know how to access
it. By mistake, I've done something. If possible, guide me through this for
a moment.

**Comment by kkanekii** [comment]
so u want to delete this issue?
