### ISSUE TITLE
Indentation mistake

### ISSUE THREAD

**Issue by bumfuzzle33** [TheAlgorithms/Python#4529]
In sha1.py
=========

On final_hash method ,the "self.hash=..." code line should be tabbed once ,
Else the hash of string more than 64 bytes outputs the wrong result

**Comment by kkanekii** [comment]
Are you making a PR or should I do it

**Comment by bumfuzzle33** [comment]
Just making a PR , thank u tho , ;)

**Comment by kkanekii** [comment]
Yep, if you need help hmu
