### ISSUE TITLE
Python project using GUI Library

### ISSUE THREAD

**Issue by kushshetty** [TheAlgorithms/Python#4538]
I need a project for my university where i need a python project using any GUI Library.

**Comment by KlassiC-Man** [comment]
You can use PyQt5 Library of Python or Tkinter...
Tkinter is verryyyy simple however it doesnt really make stuff look that good on the screen.
PyQt5 is slightly difficult but the things rendered on the screen will surely look good.

docs for Tkinter: https://docs.python.org/3/library/tkinter.html
docs for PyQt5: https://pypi.org/project/PyQt5/

Hope you got it.
If more info needed just comment it and i will be there!

**Comment by KlassiC-Man** [comment]
Hello @kushshetty please close this issue if your problem has been solved if not please comment what else you will need!
