### ISSUE TITLE
Python Game

### ISSUE THREAD

**Issue by PouriaBakrani** [TheAlgorithms/Python#4577]
![image](https://user-images.githubusercontent.com/67164502/127454727-cff33881-3da5-49a8-87ad-b6da4d25bfc8.jpeg)
Hi
I make this code , this is a game then you should make a number between 1-99 then the computer should guess.
I want it to keep all of the last codes of before guesses , at the moment it just get the last one.

**Comment by kkanekii** [comment]
You may need to upload again bro

**Comment by PouriaBakrani** [comment]
> You may need to upload again bro

Is it ok now?

**Comment by kkanekii** [comment]
I can't see it

**Comment by kkanekii** [comment]
Hey bro, you may need to learn python properly first, your code has lots of errors and can be written better and mor error proof, I'll be writing the code and sending it on this issue in a while

**Comment by kkanekii** [comment]
`
import random
guess_number_start = random.randint(0,99)
function guess_number() {
          print('Please think of a number between 1 and 100)
          user_input = input('Is Your Number Bigger or Smaller:')
          if user_input == 'Bigger' or 'bigger':
                     
                     guess_number = random.randint(guess_number_start , 99)
         else if user_input == 'smaller'  or 'Smaller':
                     guess_number = random.randit(guess_number_start , 0)
        
          //finish the rest of the code, try using while and do statements, copy pasting this wont work

}


`

**Comment by vicllo** [comment]
@kkanekii this is still not a working code...
Here is a working version
```python
import random


def ask(guess):
    answer = input("I guess " + str(guess) + ". Is your number smaller, bigger, or equal ? ").lower()
    if answer in ["smaller", "bigger", "equal"]:
        return answer
    else:
        print("I didn't understand your answer.")
        return ask(guess)


def guess_number(minimum, maximum):
    if minimum > maximum:
        print("This is impossible !")
        return -1
    guess = random.randint(minimum, maximum)
    answer = ask(guess)
    if answer == "smaller":
        guess_number(minimum, guess - 1)
    elif answer == "bigger":
        guess_number(guess + 1, maximum)
    else:
        return 0


input("Please think of a number between 1 and 100. Press ENTER when you\'re ready")

if guess_number(0, 100) == 0:
    print("I won !")
```

**Nevertheless**, I don't think this is the kind of program this repository was built for. It is made for algorithm, not for "games".

**Comment by kkanekii** [comment]
That seems good , but I think you've made the game slightly more complex, input should also have a answer.lowercase() if the first letter is uppercase and str(guess) shouldn't work as guess is a Param which hasn't been defined

**Comment by ValleraFTM** [comment]
random.randint already gives an integer

**Comment by PouriaBakrani** [comment]
But it got str then have to make it int

**Comment by vicllo** [comment]
Hello. I'm not sure to understand all of your comments but I'll try my best

To @kkanekii : the input in fact has a `.lower()` which lowercase the input. Furthermore, str(guess) works as guess is the integer given as a parameter.

To @ValleraFTM : yep I agree

To @PouriaBakrani : even though I use `str(guess)`, as I don't assign it to the guess variable, it is only temporary so the guess variable stays an integer. I don't have to put it again to an int

**Comment by PouriaBakrani** [comment]
I will write it down again in the evening and send it back for you .

**Comment by kkanekii** [comment]
Sure! Ill read your code and help

**Comment by Or-C-M** [comment]
@PouriaBakrani
What do you mean by _"keep all of the last codes of before guesses_"? Is it something like displaying all the incorrect guesses along with the final one at the end of the program? If so I'd use a list to store them and print at the end, although  - I just don't really understand this.

And if you mean the computer keeps getting one same answer - I see that you are trying to use two variables (the original _guess_ and the new _hads_) in case the computer doesn't store the new guess number. I personally think it's a good idea, but if you use this, you'll still have to transfer the new guess stored in _hads_ to the _guess_ which still contains the old guess, in order for this to work.
And there's also other issues... below is an altered version of your code (yes I didn't write it my own way):
![image](https://user-images.githubusercontent.com/65101390/128419839-f5fabe05-1c30-434e-98d3-fbe76dc84ace.png)
hope this helps!

ps. I will continue working on a more refined one, allowing a bigger range of user inputs - it was really boring to keep typing "my number is..." XD
but I need to get my laptop charged first

**Comment by Or-C-M** [comment]
New version w/ more answering options and also fixed the situation when the guessing margin goes messed up:

![image](https://user-images.githubusercontent.com/65101390/128423501-20bd132b-68ca-4799-a772-ea00e124c7cd.png)

![image](https://user-images.githubusercontent.com/65101390/128423555-b8e78128-f70b-4f87-b3bf-b02f660f0218.png)

hope this helps!!!

**Comment by kkanekii** [comment]
@Or-C-M Could you please paste the code and enclose it in a ` `` ` so it turns into a copy-able code format? i reckon it would make it easier for @PouriaBakrani to type it as he/she just needs to ctrl+c and ctrl+v , besides, even though i appreciate your response and opinions, with all due respect, not everyone prefers light mode, and it kinda hurts the eye (no offence ) , thank you, kkanekii

**Comment by Or-C-M** [comment]
> @Or-C-M Could you please paste the code and enclose it in a `` `` `` so it turns into a copy-able code format? i reckon it would make it easier for @PouriaBakrani to type it as he/she just needs to ctrl+c and ctrl+v , besides, even though i appreciate your response and opinions, with all due respect, not everyone prefers light mode, and it kinda hurts the eye (no offence ) , thank you, kkanekii

`import random

guess_max = 99
guess_min = 1



### I'm defining a new function here for the user response ###

def check_guess(number):
    while True:
        response = input('My guess is: ' + str(number) + '''\nIs your number bigger, smaller, or the same?
A. My number is bigger
B. My number is smaller
C. My number is the same / Your guess is correct
''')
        if response.lower() == 'a' or 'bigger' in response.lower():
            return 1
        elif response.lower() == 'b' or 'smaller' in response.lower():
            return 2
        elif response.lower() == 'c' or 'same' in response.lower() or 'correct' in response.lower():
            return 0
        else:
            print('Sorry, I couldn\'t identify your response.')

### Definition ends ###



guess = random.randint(1, 99)

while True:

    response = check_guess(guess)
    
    if response == 1:
        guess_min = guess + 1
        try:
            hads = random.randint(guess+1, guess_max)
        except ValueError:
            print('Impossible! You must be kidding me! Where is your gaming morality???')
            break
        print('ok!')
        guess = hads
        print()
        
    if response == 2:
        guess_max = guess - 1
        try:
            hads = random.randint(guess_min, guess-1)
        except ValueError:
            print('Impossible! You must be kidding me! Where is your gaming morality???')
            break
        print('ok!')
        guess = hads
        print()

    if response == 0:
        print()
        print('I win!')
        break`

Does this work? I typed those codes in IDLE on my computer so I took the screenshots, and I don't know if IDLE has a dark mode or smth like that... this is actually my first time posting comments (but I've ran the code myself and it does work)

**Comment by Or-C-M** [comment]
okay wait a second I need to see how to use this `` feature (and I typed my code in IDLE on my computer and I don't know if it has a dark mode or anything like that)

**Comment by Or-C-M** [comment]
```
import random

guess_max = 99
guess_min = 1



### I'm defining a new function here for the user response ###

def check_guess(number):
    while True:
        response = input('My guess is: ' + str(number) + '''\nIs your number bigger, smaller, or the same?
A. My number is bigger
B. My number is smaller
C. My number is the same / Your guess is correct
''')
        if response.lower() == 'a' or 'bigger' in response.lower():
            return 1
        elif response.lower() == 'b' or 'smaller' in response.lower():
            return 2
        elif response.lower() == 'c' or 'same' in response.lower() or 'correct' in response.lower():
            return 0
        else:
            print('Sorry, I couldn\'t identify your response.')

### Definition ends ###



guess = random.randint(1, 99)

while True:

    response = check_guess(guess)
    
    if response == 1:
        guess_min = guess + 1
        try:
            hads = random.randint(guess+1, guess_max)
        except ValueError:
            print('Impossible! You must be kidding me! Where is your gaming morality???')
            break
        print('ok!')
        guess = hads
        print()
        
    if response == 2:
        guess_max = guess - 1
        try:
            hads = random.randint(guess_min, guess-1)
        except ValueError:
            print('Impossible! You must be kidding me! Where is your gaming morality???')
            break
        print('ok!')
        guess = hads
        print()

    if response == 0:
        print()
        print('I win!')
        break


```

okay does this work???

**Comment by vicllo** [comment]
Yes that works
You can do better by typing
\`\`\`python
example = True
`\`\`
```python
example = True
```
Instead of
\`\`\`
example = True
`\`\`
```
example = True
```
To enable syntax highlight

**Comment by Or-C-M** [comment]
> Yes that works
> You can do better by typing
> ```python
> example = True
> `\``
> 
> ```python
> example = True
> ```
> 
> Instead of
> ```
> example = True
> `\``
> 
> ```
> example = True
> ```
> 
> To enable syntax highlight

Okay made the highlight (was just wondering why I don't have it)
Thank you!

**Comment by kkanekii** [comment]
@Or-C-M every ide has a dark Mode, which is hella easy to enable, just open the command pallete or search It up online, for vscode it is ctrl k ctrl t for the themes I think

**Comment by L3str4nge** [comment]
Is this issue related to this repository?

**Comment by kkanekii** [comment]
no but the others arent either
