### ISSUE TITLE
Hi all and thank you in advance for acknowledging my presence!  I have been getting a constant error and I am not certain if this is being caused by old packages!  THE ERROR*********

### ISSUE THREAD

**Issue by lone-wolf07** [TheAlgorithms/Python#4626]
File "C:\Users\hp\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1510, in <module>
    _NON_AUTOPACKABLE_TYPES = set(np.core.numerictypes.ScalarType)

AttributeError: module 'numpy.core' has no attribute 'numerictypes'

WHAT I DID ALREADY:
I tried upgrading all numpy packages according to Stacks Overflow and other python communities!

but this error is constant and its a tad daunting when one cannot see their errors to move forward hence me posting such here for additional guidance and support!

can someone help me to understand the necessary steps that I must take to move forward, please?

**Comment by latamishra** [comment]
Try uninstalling current version in your computer and then install it again.

**Comment by Sourabh-dot** [comment]
pip install -U numpy | if this does not work then find the version of numpy.core that involves "numerictypes" and do a pip install numpy="version". Sometimes things get deprecated during an update.
