### ISSUE TITLE
How did you guys generate gifs on README page?

### ISSUE THREAD

**Issue by rohitkrishna094** [TheAlgorithms/Python#463]
For example, the cocktail shaker gif. Which program did you use or which code did you write to generate those visualizations? 

Thanks

**Comment by pavan097** [comment]
![ ](gif_Name.gif) add this on where you want the GIF to show

**Comment by pavan097** [comment]
![ ](gif_name.gif) add this on where you want the GIF to show in readme.md

**Comment by rohitkrishna094** [comment]
I know that. What I meant was which program did you use to create the gifs in first place? photoshop? or did you program it using say d3js or p5js etc

**Comment by harshildarji** [comment]
You can always find a **gif** for your use from the web!
