### ISSUE TITLE
New algorithm suggestion : Dutch National Flag algorithm

### ISSUE THREAD

**Issue by yatharthmathur** [TheAlgorithms/Python#4636]
Since it is a very popular algorithm, I feel it should be a part of this collection of algorithms and it'll surely be of great help to a lot of programmers.

**Comment by KiranHipparagi** [comment]
Already we have function in python which sorts the array data. it is `list.sort()`

**Comment by yatharthmathur** [comment]
list.sort() is used to sort list with arbitrary range of elements [-inf<a[i]<inf]. Dutch National Flag algorithm is the most optimal sort for 3 unique values (eg. 0,1,2) in an Array. It's a popular algorithm, check https://en.wikipedia.org/wiki/Dutch_national_flag_problem. And isn't the entire point of the repository is to catalogue a list of implementations of popular algorithms in different languages. There's an entire section dedicated to sorting as well.
Dutch National Flag algorithm can sort an array of n size with [0<=a[i]<=2] at guaranteed O(n) complexity in a single pass. It's a common interview problem as well.

**Comment by KiranHipparagi** [comment]
@yatharthmathur thanks for responding!

can I pick this issue as my first contribution?

**Comment by VasanthKumar14** [comment]
@yatharthmathur is this issue still open ?

**Comment by yatharthmathur** [comment]
There are already 2 pull requests trying to resolve this issue. I suggest you take up a new one or create another.

**Comment by ganeshdatta23** [comment]
https://www.geeksforgeeks.org/sort-an-array-of-0s-1s-and-2s/
