### ISSUE TITLE
Added face similarity detection 

### ISSUE THREAD

**Issue by aryasoni98** [TheAlgorithms/Python#4653]
Face similarity detection captures the similarity face image using the Keras model.

**Comment by aryasoni98** [comment]
Can I start working on it !!

**Comment by aishwarya24bhagwat** [comment]
I am interested to make open source contribution on this issue,  face similarity detection, can you please assign me this

**Comment by rishabh-jain14** [comment]
Hey. I am interested in solving this issue for my Microsoft Research technical assessment. Can you please assign it to me today itself? Will strive to deliver by tomorrow. Thanks!

**Comment by sayonnnnnn** [comment]
Hi, I am interested in this issue. Can anyone assign me this?

**Comment by krshnknsr21** [comment]
Hey is this issue still open can I take it up?

**Comment by riddhitech** [comment]
Please assign me this issue.
