### ISSUE TITLE
New functionality suggestion: Adding face, hands, and pose detection for computer vision

### ISSUE THREAD

**Issue by ShaswatPanda** [TheAlgorithms/Python#4668]
Add all three of these functionalities from scratch by using OpenCV and mediapipe.

**Comment by ShaswatPanda** [comment]
Working on optimizations and CUDA support

**Comment by ShaswatPanda** [comment]
Everyone is welcome to add new functionalities like hand-gesture detection, body language detection, facial expression recognition etc.

**Comment by aishwarya24bhagwat** [comment]
I am interested to make open source contribution on pose and body language detection, can you please assign me this issue, I will be using opencv and mediapipe for it

**Comment by mansijain980** [comment]
CAn i work onthis?

**Comment by cclauss** [comment]
Please do not wait to be assigned tasks.  Open pull requests and they will be reviewed.

Make sure that you have read CONTRIBUTING.md because we are not looking for how-to-use OpenCV or how-to-use mediapipe.  We are looking for algorithms as defined in that document.

**Comment by aishwarya24bhagwat** [comment]
Respected Sir,

I am not able to pull request, as it is showing invalid extension for .py
as well as for .zip file, can you please guide me how can I pull request

Thanks and Regards,
Aishwarya Bhagwat
