### ISSUE TITLE
Can we add `flake8`, `mypy` and python `black` to this checklist ?

### ISSUE THREAD

**Issue by QuantumNovice** [TheAlgorithms/Python#4712]
![image](https://user-images.githubusercontent.com/43876848/132121135-a247d39e-3dd4-4e6e-9d73-b3fbd4197db1.png)
**Most pull requests have pre-commit checks failing because the author haven't used it.**

**Comment by poyea** [comment]
Doable. I suggest perhaps we can change some items to `flake8`, `mypy` and `black`. e.g. type hints <-> mypy

**Comment by poyea** [comment]
We already have it in place. Now we need to make it clearer in the list of our PR template.

**Comment by AbhijithGanesh** [comment]
No, my question is, can we implement this through GH Actions which would mandatory enforce pep8 standards or fail the tests.

**Comment by poyea** [comment]
@AbhijithGanesh We've [it](https://github.com/TheAlgorithms/Python/blob/master/.github/workflows/build.yml) here.

**Comment by AbhijithGanesh** [comment]
got it.

**Comment by Joe-Sin7h** [comment]
> Doable. I suggest perhaps we can change some items to `flake8`, `mypy` and `black`. e.g. type hints <-> mypy

do you mean changing type hint to mypy? like this? 
* [ ] All function parameters and return values are annotated with Python [mypy](https://docs.python.org/3/library/typing.html).

I'm confused about how should I add `black` and `flake8`.

**Comment by Joe-Sin7h** [comment]
* [ ] Modified code follows [black](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html) code style.
@poyea could you tell me how can I add `flake8` ?

**Comment by cclauss** [comment]
Not needed as discussed in #4797

The more stuff that we ask contributors to fill out, the less likely that they will do so.

**Comment by Joe-Sin7h** [comment]
point.
