### ISSUE TITLE
Clarify scope of this project

### ISSUE THREAD

**Issue by Dobatymo** [TheAlgorithms/Python#472]
There should be a list of examples of what should be included in this repository and what not.

For example there is the `simple-client-server` code which does not implement any algorithm or data structure and is better suited for a basic `socket` tutorial. Same with `File_Transfer_Protocol` . `linear-algebra-python` includes only very basic linear algebra. Of course there a various great linear algorithms which could be implemented here, but this directory only contains naive implementations and lots of overhead which is not really algorithm related. For example the Strassen algorithm would be a nice addition here.

**Comment by harshildarji** [comment]
@Dobatymo You are right. But the thing is, we merged (*or say allowed*) naive implementations to help newbies in Python. **The scope of this project is and always will be to share opensource implementations of different algorithms.**
