### ISSUE TITLE
invalid syntax in parameter input 

### ISSUE THREAD

**Issue by rizkynat** [TheAlgorithms/Python#4775]
def encode_to_b16(inp: str) -> bytes:
                                    ^

invalid syntaks in parameter input . but i try this is the same result. i use pyhton 3.8*
**sample_string = "Hello World!"
sample_string_bytes = sample_string.encode('ascii')
base64_bytes = base64.b16encode(sample_string_bytes )**

**Comment by poyea** [comment]
Hi there. Please be specific. What the input is here for this function?

**Comment by mrhoseinian** [comment]
Hello. There's no syntax problem with this function. Try print(encode_to_b16("Hello World!")) for testing it.

**Comment by poyea** [comment]
Please let us know if this is closed by mistake.
