### ISSUE TITLE
DSA-Matrix-Python- Minimum Path sum

### ISSUE THREAD

**Issue by jen-sjen** [TheAlgorithms/Python#4796]
Hey there, I'm participating in #hactoberfest2k21, Please assign me the issue. Good day!
Given a m x n grid filled with non-negative numbers, find a path from top left to bottom right, which minimizes the sum of all numbers along its path.You can only move either down or right at any point in time.
Example:
Input: grid = [[1,3,1],[1,5,1],[4,2,1]]
Output: 7

**Comment by ABHIGPT401** [comment]
Please assign me this issue. I am a good programmer and a beginner at open source. I would give it my best!

**Comment by hackto-dev** [comment]
Please assign me this issue. I want to take my first steps towards contributing in open-source.

**Comment by CoderDaicho** [comment]
Hello please assigne me this issue.I am  a beginner at open source and want to hone my skills.

**Comment by ilmiye** [comment]
Hi, I can do this! Can you assign it to me?

**Comment by Eureka-Viraj** [comment]
`I can do this! please assign me this issue`

**Comment by driptanil** [comment]
I can complete this Pythagoras Generator, Please assign this to me
I am new to opensource and I am willing to learn and contribute.
