### ISSUE TITLE
Maximal Square (Square with Max area consisting of all 1's in a binary matrix) | Dynamic Programming

### ISSUE THREAD

**Issue by tejasbirsingh** [TheAlgorithms/Python#4822]
Given an m x n binary matrix filled with 0's and 1's, find the largest square containing only 1's and return its area.
Input: matrix = [["1","0","1","0","0"],
                          ["1","0","1","1","1"],
                          ["1","1","1","1","1"],
                          ["1","0","0","1","0"]]
Output: 4

Input: matrix = [["0","1"],
                          ["1","0"]]
Output: 1

Please Assign this issue to me for adding Maximal Square Dynamic Programming Problem Code.

Points I will take care of:-

- Proper indentation
- Clean and Comment Code
- Time Complexity explanation
- Explained Sample Example

**Comment by abhijitgawai** [comment]
I think you can do this. Then why are you listing this as an issue.

**Comment by tejasbirsingh** [comment]
I raised an issue so this can be assigned to me and I can contribute for this problem. Thanks

**Comment by abhijitgawai** [comment]
Ok. Can this be done by pull request. I am new here. And i dont know difference between this two

**Comment by tejasbirsingh** [comment]
We create the issue first so the maintainers or owner can see them and assign them to us. When we are assigned the work then we make a pull request and attach it to this issue that we raised. 
Steps:-
1. Raise an issue for feature update or a bug 
2. The work will be assigned to you
3. Make the required changes or updates and make a pull request
4. while make pull request link the issue by using #issue number
5. Maintainers/ owner merges your request if it is fine. 
Hope it helps!
