### ISSUE TITLE
Computer Vision - Sliding Window Functions

### ISSUE THREAD

**Issue by khanfarhan10** [TheAlgorithms/Python#4870]
Implement Max/Min Pooling and Other Functions

**Comment by sayonnnnnn** [comment]
Hi, I am too interested in this issue. Can I contribute to this as well?

**Comment by MadJokkerr** [comment]
@khanfarhan10 sir can i countribute a project

**Comment by hd2342-dubey** [comment]
Hello, I want to work over this, please assign it to me.
