### ISSUE TITLE
Add more graph algorithms

### ISSUE THREAD

**Issue by DEBADRIBASAK** [TheAlgorithms/Python#4901]
The graph section of this repository does not contain some well known algorithms like Kruskal's algo, Floyd-Warshall algo etc. Add more number of examples from graphs.

Please assign this issue to me. Algorithms I will add:
1. Kruskal
2. Floyd Warshall

**Comment by ayushjindal23** [comment]
I know these algorithms and worked on python before. Could you assign them to me?

**Comment by ayushjindal23** [comment]
And should I create a branch or directly merge it.??

**Comment by Nivig1310** [comment]
Hello, can I add Brent's algorithm?

**Comment by harshithakolipaka** [comment]
hello, I would like to add the Bellmen Fords algorithm to this repository. Can you please assign this issue to me
