### ISSUE TITLE
Beginner on python

### ISSUE THREAD

**Issue by Empirecaius12345C** [TheAlgorithms/Python#4955]
I'm now starting python and I don't know with what I should start

**Comment by Empirecaius12345C** [comment]
Help me pls 🙏🏾!!!!!

**Comment by abhijitgawai** [comment]
Bro. Explore codes of python. You will see many codes are not optimized.

**Comment by Amankaim555** [comment]
I want learn python lower to peak.

**Comment by Suraj-107** [comment]
learning python is relatively easy than learning other programming languages. So if you're already familiar with cpp or something, python's gonna be a cake walk.

**Comment by Empirecaius12345C** [comment]
> learning python is relatively easy than learning other programming languages. So if you're already familiar with cpp or something, python's gonna be a cake walk.

What is cpp ?

**Comment by Suraj-107** [comment]
> > learning python is relatively easy than learning other programming languages. So if you're already familiar with cpp or something, python's gonna be a cake walk.
> 
> What is cpp ?

C plus plus.

**Comment by jasleen101010** [comment]
Would like to work on this issue if this is Hacktoberfest accepted, thanks!
