### ISSUE TITLE
Project has "Hacktoberfest" label but it is excluded

### ISSUE THREAD

**Issue by RenatoLopes771** [TheAlgorithms/Python#4968]
Due to new event rules, this project can't participate in the hacktoberfest this year (Data Structures and Algorithms). Thus I request the removal of the label

**Comment by poyea** [comment]
@RenatoLopes771 Is there a link to the new rule?

**Comment by RenatoLopes771** [comment]
On the official discord (https://discord.gg/hacktoberfest) you will see this: 

![image](https://user-images.githubusercontent.com/52989307/135845303-0618f560-2bdd-4e21-9087-33a288509387.png)

This repo (and most of those under Algorithms actually) is DSA (Data Structures and Algorithms) therefore it doesn't count as a valid repo for the contest.

Moreover, upon acessing the review page you can see "excluded project" after placing a PR (I think if you access the event page on your github account you will see it if you also have PR's)
![image](https://user-images.githubusercontent.com/52989307/135844238-39aa15bc-3ed3-4234-97a9-26133f21828f.png)

**Comment by poyea** [comment]
Thanks I'm following upon it.

**Comment by poyea** [comment]
The exclusion is lifted according to the Hacktoberfest official. Let's uphold the standard & quality that people are looking for, in not only this repository, but all other repositories.

**Comment by RenatoLopes771** [comment]
> 
> 
> The exclusion is lifted according to the Hacktoberfest official. Let's uphold the standard & quality that people are looking for, in not only this repository, but all other repositories.

This event is so confusing 😂
