### ISSUE TITLE
New Algorithm - A5/1 cipher implementation

### ISSUE THREAD

**Issue by hemil26** [TheAlgorithms/Python#4977]
I would like to implement this cipher in python and would like to contribute to this repository, If you think this would be appropriate addition to this repository can you please assign it to me!
Thank you!

**Comment by nirbhay12345** [comment]
@hemil26 are you working on this issue? If not can I work on this?

**Comment by hemil26** [comment]
@nirbhay12345 you can work on it!

**Comment by nirbhay12345** [comment]
@poyea Please assign this to me

**Comment by nirbhay12345** [comment]
@poyea please assign me this issue
