### ISSUE TITLE
Hacktoberfest 2021 - Implement algorithms or data structures, fix existing ones and more!

### ISSUE THREAD

**Issue by poyea** [TheAlgorithms/Python#4996]
The annual [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is underway! Register on [Hacktoberfest's website](https://hacktoberfest.digitalocean.com/) and open 4 pull requests during October 2021 to plant a tree or receive the swags!

What's more, you can also **fix any existing bugs, improve any documentation** ([open issues in TheAlgorithms/Python](https://github.com/TheAlgorithms/Python/issues?q=is%3Aissue+is%3Aopen)) and **provide better implementations** for [certain algorithms](https://github.com/TheAlgorithms/Python/blob/master/DIRECTORY.md)! Feel free to inform the community by **filling an issue** and start hacking! If you're new to contributing code, please read our [Contribution Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) for an overall understanding and ask questions on the internet - Google, StackOverflow or our Discord/Gitter.

**[TheAlgorithms](https://github.com/TheAlgorithms) has repositories for other programming languages, so find your language and start coding there!**

### What you can do to participate
1. Read our [Contribution Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md)
2. Comment below or open an issue (for big ideas you may want the community to know) on your new implementations, fixes or functionalities
3. Start hacking! 🐱‍💻👩🏾‍💻👩‍💻👨🏻‍💻👨🏽‍💻
4. Open a pull request for your contribution
5. Wait until your pull requests get reviewed or merged! In the meantime, you can review someone else's pull requests too

### Useful links
* Our [Discord](https://discord.gg/c7MnfGFGa6) and [Gitter](https://gitter.im/TheAlgorithms) channels
* The [Contribution Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) of TheAlgorithms/Python
* Our [Code of Conduct](https://github.com/TheAlgorithms/.github/blob/master/CODE_OF_CONDUCT.md)
* The [Directory](https://github.com/TheAlgorithms/Python/blob/master/DIRECTORY.md) of TheAlgorithms/Python

### Remarks
* When in doubt, please refer to any of our Contribution Guidelines. As part of the event, we would like to invite everyone to adhere to [Hacktoberfest's values](https://hacktoberfest.digitalocean.com/resources#values) and general internet etiquette.
* Please observe Hacktoberfest's rules, terms and FAQ. If a pull request is marked `invalid` or `spam` it would not be counted, and the person may be disqualified from the event.
* Hacktoberfest 2021 is an event presented by DigitalOcean, Intel, appwrite and deepsource.

**Comment by marcelozarate** [comment]
Hi! I would like to contribute, this is my first hacktoberfest. I was thinking about a linear motion physical quantities calculator. Providing acceleration, time, velocities, or displacement; each algorithm must calculate the unknown quantity. I believe it should be in the physics folder. I've already read the Contribution Guidelines. Waiting for the answer!

**Comment by priyanshm07** [comment]
Hey, @poyea looking forward for contributing to TheAlgorithms.

**Comment by appledora** [comment]
Hi, I had made several PRs to this repo, but the hacktoberfest page shows that this repo is actually `EXCLUDED` ??

**Comment by vascocbf** [comment]
Hello, this is my first Hacktoberfest. I would like to contribute by making an algorithm which tries to find the Taylor Expansion of a given function, around a given point and to degreen n. I did not find such an algorithm in the repo, please notify me if it already exists.

**Comment by mohammadjalali** [comment]
Hi, this is my first Hacktoberfest. I would like to contribute by developing an cryptography algorithm named "[a symmertic key encryption technique using genetic algorithm](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.588.101&rep=rep1&type=pdf)". I believe it should be in the ciphers folder. I have already read Contribution Guidelines. Please let me know if I can be a participant.

**Comment by Obnoxious-coder** [comment]
I would like to contribute by implementing [Low Order Polylogramathic](https://en.wikipedia.org/wiki/Polylogarithm) series

**Comment by jackrsteiner** [comment]
Hi, I've complete a [quadtree](https://en.wikipedia.org/wiki/Quadtree) implementation. As it's definitely not a binary tree, I'm not sure what directory in the repo it belongs in. @poyea or someone else, could you clarify this? Thanks.

**Comment by keshav5548** [comment]
Would like to contribute circular linkedlist or doubly linkedlist

**Comment by Adri-md-1208** [comment]
Hello, I would like to contribute doing some basic complex numbers operations (add, dot product, abs, exponential...) for the /math folder.

**Comment by mohsinmahmood12** [comment]
Hello, I would like to contribute in basic operation

**Comment by nhimanshujain** [comment]
I would like to contribute to this repo. Could you assign an issue or task to contribute. Thanks!

**Comment by abc516** [comment]
Hey @poyea  I'd like to contribute to this Repo too!

**Comment by Lorenzobattistela** [comment]
Hey, I'd like to contribute to this repo, i thought about a tic-tac-toe machine learning game, can someone help me about where (branch / dir) should i do it? @poyea

**Comment by cheepling** [comment]
This is my first hacktoberfest and i'm not exactly sure what to do, are there any problems that i could solve to contribute?

**Comment by anshu189** [comment]
I really appreciate the productive efforts toward this repo!
Looking forward to contribute more such amazing algos.

**Comment by mohitahlawat2001** [comment]
hi i want to contribute

**Comment by mohitahlawat2001** [comment]
hi @poyea i would like to contribute in repo but dont know how and where

**Comment by jitendrajaria** [comment]
Hi, I want to contribute to this repository, how should I get started?

**Comment by bg2404** [comment]
Hi, I wish to contribute Phong shading to the computer graphics section of the repo.

**Comment by cheepling** [comment]
> This is my first hacktoberfest and i'm not exactly sure what to do, are there any problems that i could solve to contribute?

Doing some updates on the maths folder to clean up and simplify outputs, sorry I haven't done too many things in there yet. If there's anything specific people want done then I can do it, but i don't have too much experience with this stuff so i'll just do the things i can otherwise.

**Comment by vibhuti019** [comment]
I would like to add impossible tic tac toe in the web section. I would love to contribute

**Comment by mohitahlawat2001** [comment]
yes dsa repo marked as spam in hacktober . i ask many senior about this . @poyea

**Comment by akhilmishra365** [comment]
i will like to contribute in project euler

**Comment by 42kkkkkaren** [comment]
Hello, this is my first Hacktoberfest. I would like to contribute by making algorithms or correcting them!

**Comment by spao234** [comment]
Eu gostaria de contribuir para este repositório. Você poderia atribuir um problema ou tarefa para contribuir. Obrigado!

**Comment by augustorsouza** [comment]
Hello, could you please let the Dart guys check my issue and PR please: 

https://github.com/TheAlgorithms/Dart/issues/156

**Comment by franciscoperez2021** [comment]
Hi here, I have made my first PR, can you review it https://github.com/TheAlgorithms/Python/pull/5156?

Thanks,

Cheers,
F.P.

**Comment by franciscoperez2021** [comment]
Hi @cafeco09,

Please, can you review my first PR,  https://github.com/TheAlgorithms/Python/pull/5156?

Thanks

Cheers,
F.P.

**Comment by divyesh1099** [comment]
I did all the necessary changes and now it's completely ready sir @poyea , it'd be great if you have a look in this PR #5474 .
