### ISSUE TITLE
Implement a linear search using recursion

### ISSUE THREAD

**Issue by n1rjal** [TheAlgorithms/Python#5062]
I would live to **implement recursion based linear search**.

**Comment by n1rjal** [comment]
@nhimanshujain  I am planning to do it myself. For Hacktoberfest and I am eagerly waiting for maintainer's response

**Comment by n1rjal** [comment]
I am reserving the PR for myself @Anniee17

**Comment by Rushikesh-Khode** [comment]
I have the implementation for linear_search by recursion. can I create a pull request for it?

**Comment by n1rjal** [comment]
Offcourse @Rushikesh-Khode
Go ahead

**Comment by Rushikesh-Khode** [comment]
> 

done sir

**Comment by saptarshi1996** [comment]
This is really bad. People are here just for the hacktober fest.

**Comment by parth-verma7** [comment]
Hi @n1rjal , I think I can work on this issue, please assign it to me.

**Comment by n1rjal** [comment]
Please go ahead @parth-verma7
