### ISSUE TITLE
Implement optimal merge pattern

### ISSUE THREAD

**Issue by Raj-Pansuriya** [TheAlgorithms/Python#5076]
### Objective
- Merge a set of sorted files of different length into a single sorted file. We need to find an optimal solution, where the resultant file will be generated in minimum time.

### Approach
- If the number of sorted files are given, there are many ways to merge them into a single sorted file. This merge can be performed pair wise.
- To merge a `m-record` file and a `n-record` file requires possibly `m+n` record moves, the optimal choice being, merge the two smallest files together at each step `(greedy approach)`.

Hey, @poyea 
I would like to contribute the mentioned algorithm to the repo.
Also if you feel its worth the contribution, please guide me as where to put this algo in the directory tree as there is no dedicated directory for greedy algorithms.

Waiting for your response...!

**Comment by poyea** [comment]
If @Raj-Pansuriya's on this one, let's wait for a PR first

**Comment by smturro2** [comment]
Ignore the mention above. I mentioned the wrong issue by mistake
