### ISSUE TITLE
Contributing Machine Learning Algorithms

### ISSUE THREAD

**Issue by Candida18** [TheAlgorithms/Python#5081]
Contributing Machine Learning Algorithms with step by step implementation, comments and outputs

**Comment by Darkfile-beka** [comment]
Wee

**Comment by hafiz-max** [comment]
pls let me help!!

**Comment by whoiscris** [comment]
just curious what's the goal of this issue ? Isn't it too broad? or it's meant to track a list of issues that work on different ML algorithms ?

**Comment by rajat-se** [comment]
I can help you with machine learning. assign it to me

**Comment by Kevinsam-Tiny** [comment]
I can work on it. Please assign it to me

**Comment by sparsh44** [comment]
Hello @Candida18 !! I am willing to contribute some searching algorithms.
