### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by thisisanshgupta** [TheAlgorithms/Python#5137]
Hacktoberfest:Implement Algorithms and Data Structures in Python.

**Comment by mhammadsaani** [comment]
Which Data Structure do you want me to implement. I am very interested in participating Hacktoberfest!

**Comment by Kate028** [comment]
Hey can I contribute as well? also, can I use Jupyter Notebook?

**Comment by thisisanshgupta** [comment]
> Hey can I contribute as well? also, can I use Jupyter Notebook?

Yes you can contribute using Jupyter notebook also.

**Comment by thisisanshgupta** [comment]
> @thisisanshgupta CAN I CONTRIBUTE TO YOUR REPO?

What you're looking to implement?

**Comment by thisisanshgupta** [comment]
> > > @thisisanshgupta CAN I CONTRIBUTE TO YOUR REPO?
> > 
> > 
> > What you're looking to implement?
> 
> just adding a adv machine learning project or normal list manupliation

Ok you can.

**Comment by priyaa-rawat** [comment]
@thisisanshgupta can I add implementation of stack and queue in python

**Comment by TheShubham-K** [comment]
okay then can i add implementation of trees

**Comment by TheShubham-K** [comment]
or you can suggest me any topic that i can contribute in this repository

**Comment by thisisanshgupta** [comment]
> Hey, @thisisanshgupta can I implement Sieve of Eratosthenes algorithm...

Yes

**Comment by thisisanshgupta** [comment]
> or you can suggest me any topic that i can contribute in this repository

If you have some knowledge in Qiskit then you can implement something in Quantum Computing part

**Comment by thisisanshgupta** [comment]
> please assign me this issue

Why you want me to do so?
