### ISSUE TITLE
Request to make contributions

### ISSUE THREAD

**Issue by salimcodes** [TheAlgorithms/Python#5268]
Hi! I would like to contribute, this is my first hacktoberfest. I have a couple of Python algorithm ideas in the Mathematical domain. 
Haven already read the Contribution Guidelines, I look forward to hearing from you. Waiting for the answer!

**Comment by poyea** [comment]
@salimcodes Sure! However, please be exact on what your algorithm is. Feel free to file a new issue when you've an idea! Thanks
