### ISSUE TITLE
caesar_cipher.py

### ISSUE THREAD

**Issue by lx1922** [TheAlgorithms/Python#529]
The caesar_cipher.py doesn't work because the index values for position of the alphabet are being considered wrong along with the modulus of the key for if key > 26. (maybe typos in the program)

Also the thing attached here is only for encryption......hence the decryption can be changed easily.
[caesar_cipher.txt](https://github.com/TheAlgorithms/Python/files/2521459/caesar_cipher.txt)

**Comment by harshildarji** [comment]
@lx1922 You are welcomed to improve the code. Just make the PR!
