### ISSUE TITLE
Unnecessary Recursion

### ISSUE THREAD

**Issue by ashwek** [TheAlgorithms/Python#532]
https://github.com/TheAlgorithms/Python/blob/f0d5bc6ece0c1c6f970761dbc348a6f16fdcebd2/ciphers/caesar_cipher.py#L36-L44
https://github.com/TheAlgorithms/Python/blob/f0d5bc6ece0c1c6f970761dbc348a6f16fdcebd2/ciphers/caesar_cipher.py#L51-L53

If you are using a while loop on _line 42_, why are you calling `main()` recursively on line 52, 59 & 63?
Instead you can just add the Menu (`line 37-41`) inside the `while loop`.
As far as i know, recursion usually takes bit more time than it takes to iterate a loop.

**Comment by harshildarji** [comment]
@ashwek You right! Updated the code in commit 4e0184a41dd3e4838da484057d25e17234353da0!
