### ISSUE TITLE
except valuError in python 

### ISSUE THREAD

**Issue by iChouaib** [TheAlgorithms/Python#543]
hey guy im beginning at python, i use pycharm to edit code so i made this game for testing 
see the photo seems all lines is correct but i don’t know why it’s keeping show me that 
indentationerror unindent does not match any outer level in except valueError line 
any idea ?!
![image](https://user-images.githubusercontent.com/37656982/47618528-a7ec4000-dad4-11e8-88c0-4056cf50557d.jpg)

**Comment by iChouaib** [comment]
same error

**Comment by ashwek** [comment]
there is no **try** block / statement.
