### ISSUE TITLE
#5008 Pull request marked as spam

### ISSUE THREAD

**Issue by nathaliaacouto** [TheAlgorithms/Python#5459]
Hello, my pull request has been marked as invalid because it says I didn't use python, but actually I did, how do I fix this? It is already closed and I can't finish my hacktoberfest because of it

**Comment by poyea** [comment]
Please have a look at [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md). We need proper files in Python (ending in `.py`).
