### ISSUE TITLE
 Adding preorder, postorder, inorder, level order traversal

### ISSUE THREAD

**Issue by spartan289** [TheAlgorithms/Python#5554]
I saw tree algorithm but there were no tree traversal algorithm i can add them

**Comment by Kim-AYoung** [comment]
Isn't that the tree traversing algorithm in [data_structures/binary_tree/binary_tree_traversals.py](https://github.com/TheAlgorithms/Python/blob/bf6db32ec2fb04b6477722f0809c5efef0cad813/data_structures/binary_tree/binary_tree_traversals.py) ?

**Comment by cclauss** [comment]
Please do not wait for permission to create the future that you want to live in.

We accept pull requests.
