### ISSUE TITLE
Example for student on contributing on OS project

### ISSUE THREAD

**Issue by patriques82** [TheAlgorithms/Python#5625]
Just a simple thing...

**Comment by Varun270** [comment]
@patriques82 Do you want a doc file containing steps on how to contribute to Open Source?

**Comment by Mihaylov93** [comment]
- Fork the repository.
- Run git clone [your repo url goes here]
- CD into your cloned repo.
- Run git checkout -b [your branch name goes here] to create your new branch.
- Make your edits and save.
- Run git add 
- Run git commit -m 'Commit message goes here'
- git push origin [your branch name goes here]
- Create a new pull request from your forked repository (Click the New Pull Request button located at the top of your repo)
- Wait for your new PR to be reviewed and merged!

**Comment by Varun270** [comment]
> * Fork the repository.
> * Run git clone [your repo url goes here]
> * CD into your cloned repo.
> * Run git checkout -b [your branch name goes here] to create your new branch.
> * Make your edits and save.
> * Run git add
> * Run git commit -m 'Commit message goes here'
> * git push origin [your branch name goes here]
> * Create a new pull request from your forked repository (Click the New Pull Request button located at the top of your repo)
> * Wait for your new PR to be reviewed and merged!

What's this?

**Comment by Mihaylov93** [comment]
@Varun270 Its an example as @patriques82 asked. Small note as first steps for a student that never worked on a repo for example.

**Comment by Varun270** [comment]
> @Varun270 Its an example as @patriques82 asked. Small note as first steps for a student that never worked on a repo for example.

okay got it, so should I include all these steps in a separate doc file or include this in the readme itself.

**Comment by cclauss** [comment]
Closing as the TODO is unclear.
