### ISSUE TITLE
Can't understand how to add label in PR 

### ISSUE THREAD

**Issue by SouvikGhosh05** [TheAlgorithms/Python#5684]
I can't understand how add labels in my pull request. Many labels of this repo are not visible to my forked repo. Can anyone help me for the label of my first PR?

Regards~

**Comment by Varun270** [comment]
@SouvikGhosh05 Hey I also face the same problem can you tell me how did you do it?

**Comment by SouvikGhosh05** [comment]
@Varun270 I also don't know about it.

**Comment by Leoriem-code** [comment]
As far as I know, if you have the permissions to add labels, you will see it.
![image](https://user-images.githubusercontent.com/73761711/140613708-76952143-3c7d-4255-b2bd-95f167ce94fa.png)
You can add labels by clicking on the wheel. But for that you need permissions (I did the screenshot on my fork).

**Comment by SouvikGhosh05** [comment]
@Leoriem-code which permission is needed?

**Comment by Leoriem-code** [comment]
I don't know, as I said, I did the screenshot on my fork of the repository so I have every permission there

**Comment by Varun270** [comment]
@SouvikGhosh05, @Leoriem-code I figured it out bois all you have to do is just click on New Issue add issue name and description, and on the right side as given in the above screenshot just click on the label setting icon, and then you will get the add label option.

**Comment by SouvikGhosh05** [comment]
@Varun270 Those who have the permission to add labels, can only add labels for their issue. Adding labels for the PR is not open to everyone for this repo.
