### ISSUE TITLE
Build fail because of scikit-fuzzy

### ISSUE THREAD

**Issue by Leoriem-code** [TheAlgorithms/Python#5767]
As the name say, and as you can see [here](https://github.com/TheAlgorithms/Python/runs/4106813490?check_suite_focus=true), the build failed because pip couldn't find a matching distribution for scikit-fuzzy.  

Edit: other examples can be found [here](https://github.com/TheAlgorithms/Python/runs/4107438933?check_suite_focus=true) and [here](https://github.com/TheAlgorithms/Python/runs/4102083542?check_suite_focus=true)

**Comment by Leoriem-code** [comment]
Don't know what changed but when pushing an empty commit, it removed the `tests are failing` label
(see #5766 )

**Comment by quant12345** [comment]
I'm trying to run an empty commit, because the status is: tests are failing, all three checks were successful.

Also kept an empty commit.

Helped!
