### ISSUE TITLE
Learn python

### ISSUE THREAD

**Issue by Furbanooo** [TheAlgorithms/Python#5805]
I wanna learn python but I have no idea to how to start

**Comment by VaggelisKoumpagiotis** [comment]
> I wanna learn python but I have no idea to how to start

**Hello Furbanooo! Getting into coding might feel difficult, although its one of the easiest things to do! First of all, there are hundreds of tutorials on Youtube teaching Python for FREE! In addition, there are tons of online books and sites that provide Python exercises, examples, tips, tricks and so much more! Looking forward to seeing your first python program!!!**
