### ISSUE TITLE
 To find roots of quadratic equations

### ISSUE THREAD

**Issue by Idk507** [TheAlgorithms/Python#5896]
# import complex math module
import cmath

# coefficients of a quadratic equation
a = 1
b = 5
c = 6

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
root1 = (-b-cmath.sqrt(d))/(2*a)
root2 = (-b+cmath.sqrt(d))/(2*a)

print('The roots are:')
print(root1)
print(root2)

**Comment by riya8866** [comment]
**THIS SHOULD BE THE REQUIRED CODE:**
import math
a=int(input("enter a:"))
b=int(input("enter b:"))
c=int(input("enter c:"))
#to find discriminant
d=(b**2)-(4*a*c)
#for distinct roots
if d>0:                 
    root1= ((-b)+math.sqrt(d))/(2*a)
    root2= ((-b)-math.sqrt(d))/(2*a)
    print("root1=",root1)
    print("root2=",root2)
#for equal roots
if d==0:
    root1= ((-b)+math.sqrt(d))/(2*a)
    print("root1=",root1)
    print("root2=",root1)
#for imaginary roots
else:
    imgpt=math.sqrt(-d)/2*a
    realpt=-b/2*a
    print("root1=",realpt,"+",imgpt,"i")
    print("root2=",realpt,"-",imgpt,"i")
