### ISSUE TITLE
Find ASCII value of character


### ISSUE THREAD

**Issue by Idk507** [TheAlgorithms/Python#5897]
# Change this value for a different result

c = 'p'

# Uncomment to take character from user
#c = input("Enter a character: ")

print("The ASCII value of '" + c + "' is",ord(c))

**Comment by Idk507** [comment]
def recur_fibo(n):
    """Recursive function to
   print Fibonacci sequence"""
    if n <= 1:
        return n
    else:
        return (recur_fibo(n - 1) + recur_fibo(n - 2))

# Change this value for a different result
nterms = 10

# uncomment to take input from the user
#nterms = int(input("How many terms? "))

# check if the number of terms is valid
if nterms <= 0:
    print("Please enter a positive integer")

else:
    print("Fibonacci sequence:")

    for i in range(nterms):
        print(recur_fibo(i))

**Comment by Manjunadh86** [comment]
assign this for me!!

**Comment by ahmadjubair33** [comment]
can i solve this issue?
