### ISSUE TITLE
def recur_fibo(n):

### ISSUE THREAD

**Issue by Idk507** [TheAlgorithms/Python#5898]
def recur_fibo(n):
    """Recursive function to
   print Fibonacci sequence"""
    if n <= 1:
        return n
    else:
        return (recur_fibo(n - 1) + recur_fibo(n - 2))

# Change this value for a different result
nterms = 10

# uncomment to take input from the user
#nterms = int(input("How many terms? "))

# check if the number of terms is valid
if nterms <= 0:
    print("Please enter a positive integer")

else:
    print("Fibonacci sequence:")

    for i in range(nterms):
        print(recur_fibo(i)) 

_Originally posted by @Idk507 in https://github.com/TheAlgorithms/Python/issues/5897#issuecomment-1003389816_

**Comment by iamhardikat11** [comment]
Can you pls explain what do we what to do with this issue?

**Comment by Prit2341** [comment]
Hi Can you explain the issue
