### ISSUE TITLE
Help needed in Doctest

### ISSUE THREAD

**Issue by karanforprogram1** [TheAlgorithms/Python#5899]
Hey there, I am planning to pr a new algorithm that implements double ended queue through list. However I am having a tough time in adding doctest in it. The algorithm works perfectly. Can someone help?
Here is the code: [https://github.com/karanforprogram1/Python/blob/master/data_structures/queue/double_ended_queue_list.py](url)

**Comment by eightysixth** [comment]
Hi @karanforprogram1, if you need help with the syntax, review the [official documentation for doctest](https://docs.python.org/3/library/doctest.html).

If you're wondering what type of tests to write, take a look some existing code - e.g. [data_structures/queue/linked_queue.py](https://github.com/TheAlgorithms/Python/blob/20e09c3ec2021edf7e6cfd85299544c651012919/data_structures/queue/linked_queue.py). Build test cases to show your algorithm works perfectly. Does it give the correct answer when passing in some expected input? How does it behave when you throw something wacky at it. Hope this helps.
