### ISSUE TITLE
Give user option to retake only incorrect questions or retake the whole test again in python

### ISSUE THREAD

**Issue by 40174456Abrahamwoolley** [TheAlgorithms/Python#5918]
Hello I am creating a quiz game in python and this is supposed to ask the user series of questions and at the end it has to display options to either retry only the wrong questions again or to take the whole quiz again. Now the problem is how to display only the wrong questions. I will appreciate if you can help please. Thank

**Comment by poyea** [comment]
Hi! This doesn't seem to be an algorithmic problem. Please read our Contribution Guidelines, our PRs and the repository for more details.
