### ISSUE TITLE
Frequency of Prime Diffrences

### ISSUE THREAD

**Issue by kunalchhabra37** [TheAlgorithms/Python#5923]
I would like to add the algorithm of finding the difference between consecutive prime numbers between Two given Numbers in maths Repository.

**Comment by Xuewei-Chen** [comment]
Hi, can I be assigned of this?

**Comment by adamsnev1** [comment]
Hello. I forgot to post here earlier. I already started working on this and have made significant progress. I would appreciate it if I could be assigned this. Thanks!

**Comment by SarveshN23** [comment]
Hello @kunalchhabra37, can I be assigned to this?

**Comment by Nisha213-mar** [comment]
Can you Assign this to me

**Comment by imnisi** [comment]
Hello Kunal! Could you assign this issue to me? I would love to solve this issue. 
Thank You
