### ISSUE TITLE
Add successor and predecessor methods for BSTs

### ISSUE THREAD

**Issue by ybrenning** [TheAlgorithms/Python#5943]
I would like to add a method `get_predecessor()` and `get_successor()` to the `BinarySearchTree` class implementation. 
These are common algorithms performed on Binary Search Trees and will return the next lowest/next highest value from the tree based on a given BST and a given value.

**Comment by LucasP78** [comment]
Hello, I am willing to work on this!

**Comment by AdemolaAri** [comment]
Hi, I can work on this
