### ISSUE TITLE
Add ascending and descending mode

### ISSUE THREAD

**Issue by haloapping** [TheAlgorithms/Python#5945]
I suggest to add ascending and descending mode in sort algorithm.

**Comment by Xuewei-Chen** [comment]
I am taking a course on software development methodology and asked to work on a project. Can I be assigned this work?

**Comment by Vandinimodi1595** [comment]
Hey @haloapping, I am new to GitHub contribution. I would like to make my first contribution to this issue. Shall I do it?

**Comment by Vandinimodi1595** [comment]
Hey @haloapping , I have committed a request for selectionSort_ascending_descending algorithm in Python. Please accept my request.

**Comment by nfarhaan** [comment]
Hello,
Can you assign this issue to me?
