### ISSUE TITLE
Convert to excel or csv

### ISSUE THREAD

**Issue by Jatinsharma250** [TheAlgorithms/Python#5954]
# import all required library
   Import xlrd
   Import csv 
   Import pandas csv
 # open workbook by sheet index
 # optional_sheet_by_index()
 
 Sheet=xlrd.open_workbook("Test.xlsx").sheet_by_index(0)
# writen object is created 
 Col= csv.writen(open("Tcsv",'w',newline=" " ))
# writing the data into csv file for row in range(sheet.nrows):
# row by row write 
# operation is perform 
Col.writerow (sheet.row_valued(row))

   # read csv file and convert 
   # into a dataframe object 
df=pd.Data frame(pd.read_csv("Tcsv)))

  # show the data frame df

**Comment by Vandinimodi1595** [comment]
@Jatinsharma250, I would like to contribute to this issue. Could you please assign it to me.

**Comment by dhrubo28** [comment]
Hi, if I am allowed to, I would like to contribute. I would like some guidance as I am a beginner.

**Comment by Doctorshe** [comment]
@Jatinsharma250 hi, please assign me the issue, happy to help 😊
