### ISSUE TITLE
Feature: improve branch coverage

### ISSUE THREAD

**Issue by Dajamante** [TheAlgorithms/Python#6020]
We want to improve branch coverage, starting with the folder data_structures/queue. 
The goal is to write proper tests and documentation as per the contribution guidelines.

For example, inside the folder data_structures/queue, while `circular_queue.py`, `circular_queue_linked_list.py`, `double_ended_queue.py` and `linked_queue.py` pass the tests, there are problems in the other programs.

- normalize all tests with doctests (no print statement as it can be the case today)
- increase branch coverage where it is possible
- fix failing tests where we find them.

Our contribution:
- data_structures/hashing (entire repository)
- data_structures/linked_list  (entire repository)
- strings (min_cost_conversion.py, knutt_morris_pratt.py)
- data_structures/binary_tree/number_of_possible_binary_trees.py
- matrix/count_islands_in_matrix.py
- matrix/matrix_class.py
- divide_and_conquer/convex_hull.py
- divide_and_conquer/closest_pair_of_points.py
- data_structures/binary_tree/red_black_tree.py
- data_structures/binary_tree/treap.py
- data_structures/queue/priority_queue_using_list.py 
- data_structures/queue/queue_on_pseudo_stack.py 
- data_structures/binary_tree/binary_search_tree.py

**Comment by sachin11226** [comment]
can you tell the code for how to test this file please 🙏🙏🙏

**Comment by poyea** [comment]
This sounds great - how do you get the branch coverage report btw?

**Comment by Dajamante** [comment]
https://coverage.readthedocs.io/en/6.3.2/ can show the coverage report.

**Comment by poyea** [comment]
Thsnks I realized we actually have it in the log.
