### ISSUE TITLE
zi

### ISSUE THREAD

**Issue by userzia** [TheAlgorithms/Python#6031]
apt update
$ apt upgrade
$ pkg install git
$ pkg install python
$ pkg install python2
$ pip install vk
$ pip install vk_api
$ git clone https://github.com/XuliGan4eg2006/Vk-Tokenner-.git
$ cd Vk-Tokenner
$ pip3 install -r requirements.txt
$ python3 main.py
$ python2 main.py

**Comment by emelia811** [comment]
Am interested
