### ISSUE TITLE
possible bug in quine_mc_cluskey.py

### ISSUE THREAD

**Issue by ashwek** [TheAlgorithms/Python#604]
https://github.com/TheAlgorithms/Python/blob/91fccecb5688d0a18cf7228ebb6fd7b7f67f4a2f/boolean_algebra/quine_mc_cluskey.py#L3-L8

Shouldn't `Line 8` be `if count > 0:` ?

**Comment by RealOrge** [comment]
I think that no, 
because one "_" is what we want
more than one "_" means that we cannot use this string

**Comment by LogMirzaBaig** [comment]
It should be greater or equal to one. Also, you are going to get an index out of range error if the string don't have the same length. Your range should be len(l1)-1.
