### ISSUE TITLE
Happy birthday my dear brother KHK...

### ISSUE THREAD

**Issue by Idk507** [TheAlgorithms/Python#6049]
n=int(input("enter the date"))
p=str(input("enter the month"))
if n== 18 :
    if p== "03" :
        print("*****happy*****")
        print(" *****bday*****")
        print("*****my brother*****")
        print("*****kishore*****")
        print("*****love u thumbi*****")

    else :
        print("Sry, it's not ur bday")

**Comment by SnowdenSa** [comment]
Nice coding 🎉
في جمعة، 18 مارس، 2022 في 12:20 م، كتب Idk507 ***@***.***>:
