### ISSUE TITLE
The InOrderTraversal in data_structures/binary_search_tree might be wrong

### ISSUE THREAD

**Issue by TillLindemann** [TheAlgorithms/Python#605]
the src is : 
```python
    def __InOrderTraversal(self, curr_node):
        nodeList = []
        if curr_node is not None:
            nodeList.insert(0, curr_node)
            nodeList = nodeList + self.__InOrderTraversal(curr_node.getLeft())
            nodeList = nodeList + self.__InOrderTraversal(curr_node.getRight())
        return nodeList
```

but the [wikipedia](https://en.wikipedia.org/wiki/Tree_traversal#In-order_(LNR)) tells me that in-order-traversal should be  left -- root -- right.
the code above seems to be pre-order-traversal. 
I am now very confused by the definition of traversal.

**Comment by imranjavaid** [comment]
In-order is root--left--right. The above code looks correct. The wikipedia link also says to check current node first, then left, then right.

**Comment by TillLindemann** [comment]
@imranjavaid  no no no, every traversal method should check root first, but it does not mean "display" or "show" the root first. here is the explanation:

1.Check if the current node is empty or null.
2.Traverse the left subtree by recursively calling the in-order function.
3.Display the data part of the root (or current node).
4.Traverse the right subtree by recursively calling the in-order function.

take a look at the 3.
![image](https://user-images.githubusercontent.com/22681439/48531684-384dc180-e8d8-11e8-87ef-8c24d2de66a2.png)
above is the source code example 
and here is the result of the so called "in order traversal":
![image](https://user-images.githubusercontent.com/22681439/48531732-603d2500-e8d8-11e8-9c76-5e1f24edd0a5.png)

DON'T think it's wrong? I mean ,it must be "pre order traversal" ,since the wiki says so, pre-order "disaplay" the root first, then left subtree, then right subtree. 
here is the wiki's pre-order traversal:
![image](https://user-images.githubusercontent.com/22681439/48531779-9c708580-e8d8-11e8-9ca7-9995ca69a1c5.png)

**Comment by adisakshya** [comment]
@TillLindemann you are right,
the code you provided is of **PRE-ORDER** traversal of binary tree.
PRE-ORDER involves:-
1. Visit the root.
2. Traverse the left subtree, i.e., call Preorder(left-subtree)
3. Traverse the right subtree, i.e., call Preorder(right-subtree)

but IN-ORDER involves:-
1. Traverse the left subtree, i.e., call Inorder(left-subtree)
2. Visit the root.
3. Traverse the right subtree, i.e., call Inorder(right-subtree) 

so, code for inorder traversal would be:-
 ```python
     def __InOrderTraversal(self, curr_node):
         nodeList = []
         if curr_node is not None:
             nodeList.insert(0, curr_node)
             nodeList = nodeList + self.__InOrderTraversal(curr_node.getLeft())
             nodeList = nodeList + self.__InOrderTraversal(curr_node.getRight())
         return nodeList
 ```

**Comment by TillLindemann** [comment]
@adisakshya  The code you write is still wrong. here is the result:
![image](https://user-images.githubusercontent.com/22681439/48564524-88a53d80-e931-11e8-8d56-d83ca8818ce2.png)
You can see that nothing changes. You did one right thing, which is the place of the so called "insert" operation, it should be at the second line.but
the real problem is that the "insert" operation is wrong.it should be the "append" operation.here is the result:

![image](https://user-images.githubusercontent.com/22681439/48565298-2ea57780-e933-11e8-8f7b-42cd4767f033.png)

**Comment by adisakshya** [comment]
Good Call, it worked.
