### ISSUE TITLE
How can this code be optimized?

### ISSUE THREAD

**Issue by Dentertvvvv** [TheAlgorithms/Python#6053]
import random
al= "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
al2 ="abcdefghijklmnopqrstuvwxyz"
buk="1234567890"
ele="*/\$€¥¢©®™~¿[]{}<>^¡`;÷\|¦¬×§¶°@#₽&_-()=%*':!?+,."
#moi versia
sum=16
i=0
while i<sum:
    af=random.choice(al+al2+buk+ele)
    print(af,end="")
    i+=1

**Comment by abdullahmortada** [comment]
Can i ask why you are using 4 different strings just to concatenate them? Wouldnt it be much more efficient time and memory wise to use one string?

**Comment by Dentertvvvv** [comment]
> Can i ask why you are using 4 different strings just to concatenate them? Wouldnt it be much more efficient time and memory wise to use one string?

I just don't know any other way.  How can I do this in 1 line?

**Comment by abdullahmortada** [comment]
you can just place all of the characters in one string, and then  in random.choice just pass that string as the argument, saves processing time concatenating

**Comment by Tesipog** [comment]
> > Can i ask why you are using 4 different strings just to concatenate them? Wouldnt it be much more efficient time and memory wise to use one string?
> 
> I just don't know any other way. How can I do this in 1 line?

yeah i know how to write the code in 2 lines But i don't know how to contribute

**Comment by abdullahmortada** [comment]
> 
> yeah i know how to write the code in 2 lines But i don't know how to contribute 
> 
> Because i am new to github
> 

https://youtu.be/GbqSvJs-6W4

This is a good tutorial on it

**Comment by Tesipog** [comment]
Can u provide the file path 


> > yeah i know how to write the code in 2 lines But i don't know how to contribute
> > Because i am new to github
> 
> https://youtu.be/GbqSvJs-6W4
> 
> This is a good tutorial on it

can u provide the file path
