### ISSUE TITLE
New Algorithm: Short Time Fourier Transform (STFT)

### ISSUE THREAD

**Issue by Bobingstern** [TheAlgorithms/Python#6079]
The main idea of this algorithm is to create a spectrogram using the FFT and a window function to run the FFT on. Instead of a pure unchaging signal that the FFT converts to a frequency domain function, the STFT converts a long, changing signal into a time, freqeuncy and power domain. https://en.wikipedia.org/wiki/Short-time_Fourier_transform

**Comment by Akash-Kumar-Sen** [comment]
Hi @Bobingstern I want to contribute to this issue. Will you please assign this to me.
