### ISSUE TITLE
Can I Use A Code that another person has already implemented ?

### ISSUE THREAD

**Issue by dongjji** [TheAlgorithms/Python#6088]
Hello, I'm student for studying to contribute open source software project.
But, I have some questions for doing it.
Can I use a code that another person has already implemented ? 
For example, Implementing some scheduling algorithm using data structures code(already implemented)

I apologize issuing small question. Thank you for reading.

**Comment by dongjji** [comment]
sorry... not using but importing some data structure code in my algorithm code

**Comment by poyea** [comment]
Hi @dongjji Thank you. 1. Please improve existing algorithms, unless there is any strong reason to submit a new version; 2.code submitted should be written by yourself.
