### ISSUE TITLE
Update the QuickSort Algorithm to minimise chance of O(n^2)

### ISSUE THREAD

**Issue by faiqali1** [TheAlgorithms/Python#6095]
According to [this question](https://stackoverflow.com/questions/164163/quicksort-choosing-the-pivot) on StackOverflow it is better to use the median or a random value as a pivot.

Currently the implementation uses the last element as the pivot.

```python
def quick_sort(collection: list) -> list:
    if len(collection) < 2:
        return collection
    pivot = collection.pop()  # <-- Use the last element as the first pivot
    greater: list[int] = []  
    lesser: list[int] = []  
    for element in collection:
        (greater if element > pivot else lesser).append(element)
    return quick_sort(lesser) + [pivot] + quick_sort(greater)
```

**Comment by lt77777** [comment]
I can fix this

**Comment by mahi072** [comment]
Hi @faiqali1, I would like to contribute in this issue. Is it still open?
Please guide me through this.

**Comment by faiqali1** [comment]
Hi @mahi072 And @Ashutosh2613,

Yeah, the issue is still open. Apologies for the late reply. 

The current issue, as stated in the title is that, it is better to choose the pivot at a random point then choosing the last element every time.  

So using the Random module, choose a Random point between 0 & the length of the array and use that as a pivot.

**Comment by Kate-Way** [comment]
HI @faiqali1! I'm new to contribution process. I can't find how fork this question, but here is the code:

`def quick_sort(collection: list) -> list:
    if len(collection) < 2:
        return collection
    pivot = random.choice(collection)  
    greater: list[int] = []
    lesser: list[int] = []
    for element in collection:
        (greater if element > pivot else lesser).append(element)
    return quick_sort(lesser) + quick_sort(greater)`

**Comment by Ashutosh2613** [comment]
@faiqali1 Changes are made, please do review the changes!

**Comment by ruchikayadav1408** [comment]
@faiqali1 heyyy shall i work on this?
