### ISSUE TITLE
Importance of cp36_win_amd64

### ISSUE THREAD

**Issue by sagar1899** [TheAlgorithms/Python#6100]
I have one.pyd file and using python 3.6.2 on 64 bit machine but when i copy that file on another machine the file is not used by python in that machine, but when i renamed that file like one.cp36_win_amd64.pyd that file is used, 

Son
So can you please help me what is the importance of and reason behind it.

**Comment by 31692110737** [comment]
Try upgrading Python

**Comment by 3169210737** [comment]
Try upgrading Python
