### ISSUE TITLE
have a problem about the function of sort()

### ISSUE THREAD

**Issue by wxde** [TheAlgorithms/Python#611]
i want a list sorted by the lenght of str. the environment is python3.6

"strs.sort(lambda x,y:cmp(len(x),len(y)))"

the error : TypeError: must use keyword argument for key function

i don't know where is the error

**Comment by ashwek** [comment]
@wxde 
try: `strs.sort(key = lambda x: len(x))`

**Comment by wxde** [comment]
thanks to ashwek, it work
