### ISSUE TITLE
How about categorizing sorting algorithms?

### ISSUE THREAD

**Issue by hnjang** [TheAlgorithms/Python#614]
How about categorizing sorting algorithms?

I think, they can be categorized like [this page](https://en.wikipedia.org/wiki/Sorting_algorithm#Popular_sorting_algorithms) of wikipedia.

Cat 1. Simple sort
Cat 2. Efficient sort (or advanced sort)
Cat 3. Bubble sort and variants
Cat 4. Distribution sort

Give me any feedback.

**Comment by pandyamarut** [comment]
@hnjang Not Necessary but you can be categorised for understanding.

**Comment by AkashAli506** [comment]
@hnjang Yes, sorting algorithms should be categorized for better understanding.

**Comment by PythonFish98** [comment]
@lisadeoester hello

**Comment by lisadeoester** [comment]
@PythonFish98 yo

**Comment by lisadeoester** [comment]
???

**Comment by PythonFish98** [comment]
neem bestand txt (ELO), maak eerst bestand waar antwoorden in komen. vraag om naam van de ondervraagde en maak met deze naam een bestond voor de antwoorden. hierin komt huidige datum te staan. let op bestandnaam en weergave datum precies kloppen. bijv: hoe heet je? *marcel* ->  txt : dinsdaf 11 juni 2019

**Comment by PythonFish98** [comment]
open in je programma nu t bestand met vragen en vermeld hoeveel vragen er zullen volgen. in voorbeeld bestand vragen.txt gebruikt waarin 3 vragen staan, maar dat kan ook meer of minder zijn: bijv: hoe heet je? *marcel* Hier volgen 3 vragen:

**Comment by PythonFish98** [comment]
Stel de vragen nu 1 voor 1, vragen en antwoorden moeten in antwoordne bestand komen zoals voorbeeld: hoe heet je? *marcel*
hier volgen 3 vragen:
Wat is je leeftijd? *24*
Favoriete gerecht? *pizza*
Favorite taal? *Python*

**Comment by PythonFish98** [comment]
rosa pls haha :'(

**Comment by PythonFish98** [comment]
ik heb nu een 2.5 en ik ga dood

**Comment by lisadeoester** [comment]
heb alleen dit

**Comment by lisadeoester** [comment]
from datetime import date 
import locale
locale.setlocale(locale.LC_ALL,'')
vandaag = date.today()
print(f"het is {vandaag.day} {vandaag.month} {vandaag.year}")


file = open("antwoorden.txt")
inhoud = file.read()

file2 = open("vragen.txt")
inhoud2 = file2.read()

naam =  input("Wat is je naam? ")
print (naam)

count = file2.tell()

print ("Hier volgen", count, "vragen:")
print (inhoud2)

with open ("antwoorden.txt", "a+") as bestand:
	
	bestand.write(naam + "/n") 
	bestand.write(file2.read())

**Comment by lisadeoester** [comment]
from datetime import date 
import locale
locale.setlocale(locale.LC_ALL,'')
vandaag = date.today()
print(f"het is {vandaag.day} {vandaag.month} {vandaag.year}")


file = open("antwoorden.txt")
inhoud = file.read()

file2 = open("vragen.txt")
inhoud2 = file2.read()

naam =  input("Wat is je naam? ")
print (naam)

count = file2.tell()

print ("Hier volgen", count, "vragen:")

for line in open("vragen.txt", "r").readlines():
    print input((line))

with open ("antwoorden.txt", "a+") as bestand:
	
	bestand.write(naam + "/n") 
	bestand.write(inhoud2)

file.close()
file2.close()

**Comment by lisadeoester** [comment]
nieuwe versie
waarom heb je opgave 1 niet gestuurd

**Comment by PythonFish98** [comment]
ja kon niet, lijn 21 error

**Comment by lisadeoester** [comment]
from datetime import date 
import locale
locale.setlocale(locale.LC_ALL,'')
vandaag = date.today()
print(f"het is {vandaag.day} {vandaag.month} {vandaag.year}")


file = open("antwoorden.txt")
inhoud = file.read()

file2 = open("vragen.txt")
inhoud2 = file2.read()

naam =  input("Wat is je naam? ")
print (naam)

count = file2.tell()

print ("Hier volgen", count, "vragen:")

for line in open("vragen.txt", "r").readlines():
    print (line)

with open ("antwoorden.txt", "a+") as bestand:
	
	bestand.write(naam + "/n") 
	bestand.write(inhoud2)

file.close()
file2.close()

**Comment by PythonFish98** [comment]
kan je nog nieuw bestand aanmaken voor marcel?

**Comment by PythonFish98** [comment]
deze heeft geen errors :) top

**Comment by lisadeoester** [comment]
moet jij doen
een antwoorden.txt moet je aanmaken

**Comment by PythonFish98** [comment]
ja

**Comment by PythonFish98** [comment]
nee programma moet bestand maken waar antwoorden dan inkomen

**Comment by PythonFish98** [comment]
na naam vragen, moet je bestand aanmaken met die naam/input

**Comment by lisadeoester** [comment]
bij opgave 3 moet je alleen die api erin zetten en laten controleren, misschien krijg je dan og eenpunt

**Comment by PythonFish98** [comment]
okiedokie, thanks haha

**Comment by lisadeoester** [comment]
dat bestand maken weet ik niet, wist niet dat dat kon

**Comment by PythonFish98** [comment]
me too, nouuuu derde herkansing haha toch bedankt <3

**Comment by lisadeoester** [comment]
hmm jammer, kom app en verwijder dir
\
