### ISSUE TITLE
doctest question

### ISSUE THREAD

**Issue by dongjji** [TheAlgorithms/Python#6150]
I want to ask how to test with docs string in method If the argument is instance object of a class.
Is there any different way to test class method with instance object arguments?

`def some_scheduling_algorithms(processes: list[Process]) -> list[int]:
"""
doctest?
"""
`

**Comment by poyea** [comment]
Yes, I think you can test it with `doctest`. The way you do it is to initiate the objects in the docstrings.

**Comment by dongjji** [comment]
Thank you poyea. I didn't deeply know about python doctest.
I can test my code initiating some objects from your comment.
