### ISSUE TITLE
[suggestion] use relative path in DIRECTORY.md

### ISSUE THREAD

**Issue by 15921483570** [TheAlgorithms/Python#6179]
when openning DIRECTORY.md in local machine, the links in it refers to https://github.com/TheAlgorithms/Python/blob/master/xxx.

it's not convinient for reading locally.

I suggest to make a new file "TOC.md", which removes "https://github.com/TheAlgorithms/Python/blob/master/" in every link.

**Comment by poyea** [comment]
This makes perfect sense! Do you know if the relative path resolution is supported by GitHub?
