### ISSUE TITLE
errors in balanced_parentheses.py

### ISSUE THREAD

**Issue by ashwek** [TheAlgorithms/Python#620]
https://github.com/TheAlgorithms/Python/blob/6a95bf9ad8090a1280abf76752a52ab9ee2420b7/data_structures/stacks/balanced_parentheses.py#L13-L17

`Line 16` returns wrong result due to `not`

`Line 15` can cause error for inputs like **))**. before calling _pop_ it should be checked if stack is empty.

https://github.com/TheAlgorithms/Python/blob/6a95bf9ad8090a1280abf76752a52ab9ee2420b7/data_structures/stacks/balanced_parentheses.py#L3

there is no module named **.Stack**. it should be
 _from **s**tack import Stack_

**Comment by mikaelsouza** [comment]
Oh, I just noticed that you already fixed this issue which makes what I did redundant haha.

I hope the new example can be useful though.
