### ISSUE TITLE
Bisection redundance

### ISSUE THREAD

**Issue by Aarrn33** [TheAlgorithms/Python#6202]
In the [bissection file](https://github.com/TheAlgorithms/Python/blob/master/arithmetic_analysis/bisection.py), on line 34 where mid is defined shouldn't `mid: float = start + (end - start) / 2.0` be replaced by `mid: float = end / 2.0` as it's basically the same but cleaner?
As I am somewhat new to Github please tell me if I do anything wrong.

**Comment by Aarrn33** [comment]
Same problem on line 42 I think

**Comment by Avanonyme** [comment]
Pretty sure your maths are incorrect. This 

`start+(end-start)/2.0`

Can be viewed as 

`start-start/2.0 + end/2.0`

Which simplifies to 

`(start-end)/2.0`

Unless I'm missing something, this is the right answer

**Comment by Aarrn33** [comment]
Yes I am indeed wrong as `start + (end-start)/2.0` isn’t the same as `(start + end - start)/2.0`. My math was off.
