### ISSUE TITLE
Theres is a  problem in "maths/newton_raphson.py"

### ISSUE THREAD

**Issue by SmileOfHeart** [TheAlgorithms/Python#6242]
In file "maths/newton_raphson.py", there is a error in function "newton_raphson()". It likes  that  variables "error" was not refreshed in for-iterator process。So we need to recalculate the "error" in for-loop block, otherwise the iteration will never finish.

**Comment by poyea** [comment]
@SmileOfHeart Sure! Feel free to file a PR to close this issue - https://github.com/TheAlgorithms/Python/blob/master/maths/newton_raphson.py#L25

**Comment by AmilaMadushan** [comment]
https://github.com/TheAlgorithms/Python/pull/6332

**Comment by AmilaMadushan** [comment]
Fixed error https://github.com/TheAlgorithms/Python/pull/6332
