### ISSUE TITLE
Reading XML file Using Python

### ISSUE THREAD

**Issue by bhagyarajan12** [TheAlgorithms/Python#626]

**Comment by loftwah** [comment]
I'd like to help but I am unable to see any XML.

**Comment by bhagyarajan12** [comment]
> I'd like to help but I am unable to see any XML.

I have xml file as shown Below.

<Positions>
 <Pos longsrcid="abv"  empid="rwetrwet">
     <Marketval  Firm="898" portfolio="896">
     <BookPrice firm="989" portfolio="9898">
</Pos>
</Positions>

now that i want to read the empid , Marketval firm and portfolio, BookPrice Firm and Portfolio values 
from xml.etree import ElementTree
import os
Tree=xml.parse("XML Path/XML Filename")
xmlroottag=Tree.findall('Pos')
for c in xmlroottag:
      longsrcid=c.find(longsrcid")
    
can you please help me how to read Marketval Firm and Book price firm values

**Comment by bhagyarajan12** [comment]
<Positions>
 <Pos longsrcid="abv"  empid="rwetrwet">
     <Marketval  Firm="898" portfolio="896">
     <BookPrice firm="989" portfolio="9898">
</Pos>
</Positions>

**Comment by bhagyarajan12** [comment]
> I'd like to help but I am unable to see any XML.

can you please message your email id

**Comment by loftwah** [comment]
I'm not giving you my email, what you are posting doesn't contain any XML.

**Comment by bhagyarajan12** [comment]
<Positions>
 <Pos longsrcid="abv"  empid="rwetrwet">
<Marketval  Firm="898" portfolio="896">
<BookPrice firm="989" portfolio="9898">
</Pos>

<img width="349" alt="capture" src="https://user-images.githubusercontent.com/8483244/49815895-cbbcca00-fd92-11e8-9210-fd97351be177.PNG">

> </Positions>**
Duplicate of #**

**Comment by bhagyarajan12** [comment]
> I'm not giving you my email, what you are posting doesn't contain any XML.

i have posted that xml now, please find it on my above comment

**Comment by Koustubh18** [comment]
import xml.etree.ElementTree as et
tree = et.parse("p.xml").getroot()
for i in tree:
    print(i.tag,i.attrib)



from above code you get all attributes in dictionary form 
you can access easily firm and other stuffs

**Comment by deepakrao92** [comment]
Can you try using BeautifulSoup library

```
from bs4 import BeautifulSoup

with open("test.xml", "r") as myfile:
    data = BeautifulSoup(myfile.read(), features="xml")

    mVal = data.findAll("Marketval")
    for i in mVal:
        print i['Firm']

    bPrice = data.findAll("BookPrice")
    for i in bPrice:
        print i['firm']
```

This returns the value for the specified tags
