### ISSUE TITLE
Sudoko solver

### ISSUE THREAD

**Issue by Nandu8479** [TheAlgorithms/Python#6299]
How to make a sodoko solver that can solve puzzle by giving an input of sudoko in like different sets of list,with unknown value being given some variables

**Comment by Nandu8479** [comment]
Plz help if you can

**Comment by atomicsorcerer** [comment]
Here's a sudoku solver/library I made that should do what you wanted: [https://github.com/atomicsorcerer/sudoku-generator](https://github.com/atomicsorcerer/sudoku-generator). You can also use the helper functions to customize it for your needs.
