### ISSUE TITLE
group_table = []

### ISSUE THREAD

**Issue by AyushSinghWhiteHat** [TheAlgorithms/Python#6364]
group_table = []
def table(number):
    for i in range(1,11):
        if i==4:
            group_table.append(number*i+22)
        else:
            group_table.append(number*i)
number = int(input("ENTER YOUR NUMBER")) 
table(number) 
print(group_table)
def iscorrect():
    num=1
    for item in group_table:
        if item == number*num:
            pass 
        else:
            print(f"WRONG TABLE IS {item} AND CORRECT IS {number*num}")
        num+=1
   
iscorrect()

**Comment by Kim8178184977** [comment]
Can i look at this issue and whats the actual issue
