### ISSUE TITLE
import random

### ISSUE THREAD

**Issue by AyushSinghWhiteHat** [TheAlgorithms/Python#6365]
import random
def Name_Jumbling(no_of_friends,name_list, new_name_list):
    for i in range(no_of_friends):
        a =name_list[i].split(" ")
        new_name_list.append(a)
    for i in range(len(new_name_list)//2):
        l = new_name_list[i][1]
        m = new_name_list[i+1][1]
        new_name_list[i][1]=m
        new_name_list[i+1][1]=l
    return new_name_list
new_name_list=[]
name_list=[]       
no_of_friends=int(input("ENTER YOUR NUMBER OF LIST:\n"))
for i in range(no_of_friends):
    name = input("ENTER YOUR FRIENDS NAME")
    name_list.append(name)
print(Name_Jumbling(no_of_friends,name_list, new_name_list))

**Comment by Kim8178184977** [comment]
Is anyone working on this particular issue?
