### ISSUE TITLE
AssertError

### ISSUE THREAD

**Issue by MaksKamerrer** [TheAlgorithms/Python#6371]
#Task is:
# Write a (pure) ‹sequence› function that calculates the value of member 
# ⟦aₙ⟧ of the sequence described below, where ‹n› is the first parameter of this function. 
# The first term of the sequence, ⟦a₀⟧, is given by the parameter ‹initial›, 
# each other term is then determined by the sum ⟦aⱼ = ∑ᵢ₌₁ᵏ (-1)ⁱ · i · aⱼ₋₁⟧, 
# where ‹k› is second parameter of the ‹sequence› function.

def sequence(n, k, initial):
    for i in range(n+1):
        result = 1**k * (-1)**initial * initial * (n-1)
    print(result)

**Comment by Kim8178184977** [comment]
I want to try

**Comment by Kim8178184977** [comment]
it's working

**Comment by MaksKamerrer** [comment]
> it's working

Can u pls show me ur code?

**Comment by Kim8178184977** [comment]
def sequence(n, k, initial):
    for i in range(n+1):
        result = 1**k * (-1)**initial * initial * (n-1)
        return print(result)
    
if __name__ == '__main__':
    sequence(5,4,1)
