### ISSUE TITLE
Adding Hand contours detection algorithm python file in computer vision

### ISSUE THREAD

**Issue by akshitagupta15june** [TheAlgorithms/Python#6386]
![image](https://user-images.githubusercontent.com/57909583/192320813-12564ae7-59b9-4184-9096-69af0a3f90d1.png)

**Comment by Shubham1193** [comment]
Hi @akshitagupta15june i would to like to work on this file . 
Is this issue still open ?

**Comment by akshitagupta15june** [comment]
@Shubham1193  already given a pr for this waiting for approval #6389

**Comment by cclauss** [comment]
If multiple contributors submit solutions to the same algorithm, it is usually a learning experience for all parties.  Therefore, we review pull requests and do not assign or reserve algorithms.
