### ISSUE TITLE
No Good First Issues

### ISSUE THREAD

**Issue by asim-reza** [TheAlgorithms/Python#6390]
Hey guys! I wanted to start contributing and noticed there was a good first Issue label but there are no issues labeled so... Can someone point out some good issues to start off here?

**Comment by dhruvmanila** [comment]
Thanks for your interest in contributing! There aren't any issues to solve per se in the repository. This is just a collection of algorithms and data structures in the Python language. Start looking at the code for the topic which interests you and, if possible, improve it or if nothing exists for the topic, you can add related algorithms for it.
