### ISSUE TITLE
Improve cnn_classification algorithm

### ISSUE THREAD

**Issue by yash-shimpi** [TheAlgorithms/Python#6391]
The cnn_classification.py in computer vision needs some fixtures in the CNN model, like the number of CNN layers are same, which shouldn't be across the model, there should be at least one dropout layer to prevent overfitting and some more dense layers at the end to improve accuracy.

**Comment by yash-shimpi** [comment]
I would like to work on this issue @horstjens. Please assign me.

**Comment by horstjens** [comment]
@yash-shimpi as far as i understand you just need to send a pull request.

**Comment by yash-shimpi** [comment]
oh ok, sure
