### ISSUE TITLE
Algorithm for Dividing N items into groups such that the distribution yields the minimum sum of a property endemic to the individual items in the group

### ISSUE THREAD

**Issue by sanchayanghosh** [TheAlgorithms/Python#6395]
Say we have N items with a distinct property value of k. We put them in groups such that the sum of the property values of k for all items in each group of P groups is minimum for the group with largest number of elements.

**Comment by R3v3rb3** [comment]
Hi @sanchayanghosh , I like to work on this problem . Please can you assign that issue to me .

**Comment by cclauss** [comment]
If multiple contributors submit solutions to the same algorithm, it is usually a learning experience for all parties.  Therefore, we review pull requests and do not assign or reserve algorithms.

**Comment by sanchayanghosh** [comment]
Hi @R3v3rb3 i have the implementation laid out. If you like, @cclauss we can use this issue  to basically discuss the design and implementation of the algorithm, and for me to effectively help with the implementation details. Or would you like me to directly open a draft PR for this?

I will be posting a draft PR for the same. @R3v3rb3 once I post the link you can take a look at it.
