### ISSUE TITLE
Describe time and space complexity within algorithms such as sort

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#6396]
In the `sort` and `search` algorithms that primarily optimise space and time, the big O notation should be explained.

**Comment by parth-verma7** [comment]
Hi, @CaedenPH I would like to work on this issue, can u please assign it to me?

**Comment by cclauss** [comment]
If multiple contributors submit solutions to the same algorithm, it is usually a learning experience for all parties.  Therefore, we review pull requests and do not assign or reserve algorithms.
