### ISSUE TITLE
Evaluations on the algorithms

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#6397]
Give evaluations on the most efficient algorithms for each category

**Comment by parth-verma7** [comment]
Hi @CaedenPH  I would like to work upon this issue, please assign it to me.

**Comment by iTeraTorr** [comment]
Please list down the required categories.

**Comment by cclauss** [comment]
If multiple contributors submit solutions to the same algorithm, it is usually a learning experience for all parties.  Therefore, we review pull requests and do not assign or reserve algorithms.
