### ISSUE TITLE
bytes int conversion

### ISSUE THREAD

**Issue by decentlearner** [TheAlgorithms/Python#6412]
add python program for bytes int conversion.

**Comment by palaniappan-r** [comment]
Hello, Can I take this?

**Comment by decentlearner** [comment]
yes

**Comment by decentlearner** [comment]
yes, you can take this issue

**Comment by OmAvhad** [comment]
Hey @palaniappan-r ,
is this project for hacktober fest ?
or can you add labels for the issues which you feel are worth for hacktober fest.

**Comment by iTeraTorr** [comment]
What does bytes int conversion mean? Please give some sample input-output test cases.

**Comment by cclauss** [comment]
If multiple contributors submit solutions to the same algorithm, it is usually a learning experience for all parties.  Therefore, we review pull requests and do not assign or reserve algorithms.
