### ISSUE TITLE
Enhancing search bar and page

### ISSUE THREAD

**Issue by keerthanasathya** [TheAlgorithms/Python#6424]
Adding loader while loading for search and making search bar even more engaging
![image](https://user-images.githubusercontent.com/113957926/193394346-67b7e4a8-7753-404b-add0-132fbb26b375.png)

**Comment by dhruvmanila** [comment]
This should be redirected to the https://github.com/TheAlgorithms/website repository.

**Comment by keerthanasathya** [comment]
> This should be redirected to the https://github.com/TheAlgorithms/website repository.

Good morning sir!
Can you explain where I have done mistake, so that I can rectify it?!

**Comment by dhruvmanila** [comment]
Your feature request should be opened in the repository which contains the website code which is https://github.com/TheAlgorithms/website
