### ISSUE TITLE
Swapping 2 numbers using Bit Manipulation

### ISSUE THREAD

**Issue by Mrjoy832** [TheAlgorithms/Python#6425]
Hey , I want to add detailed documentation , code of **Swapping 2 numbers** using Bit Manipulation.<br>
Its an important interview question that **Swap 2 numbers without using 3rd variable,** In that mostly guys answer using some staff like doing some sort of addition , substraction but there if you answer with using Bit-manipulation then it will be eye-catching and also better in case of Time complexity also.

**Comment by Mrjoy832** [comment]
@poyea Hey Sir ...kindly assign this issue to me

**Comment by Tharunkumar001** [comment]
@poyea kindly assign this issue to me

**Comment by cclauss** [comment]
If multiple contributors submit solutions to the same algorithm, it is usually a learning experience for all parties.  Therefore, we review pull requests and do not assign or reserve algorithms.
