### ISSUE TITLE
Finding roots of the equation by Computational Methods

### ISSUE THREAD

**Issue by Anirudh3167** [TheAlgorithms/Python#6431]
Hey, I want to add a topic called computational methods to solve equations.

Computational methods is used to find the roots of an equation in a given interval.
Adding this topic to Algorithms may help others to solve equations easily so that computing will get more easier.

Kindly assign this topic to me

**Comment by cclauss** [comment]
If multiple contributors submit solutions to the same algorithm, it is usually a learning experience for all parties.  Therefore, we review pull requests and do not assign or reserve algorithms.
