### ISSUE TITLE
Implementing Splay Tree

### ISSUE THREAD

**Issue by Kumar-laxmi** [TheAlgorithms/Python#6433]
**This Issue is under Data-Structure in Binary Trees.**

#### Splay tree undergoes 4 operation: Insertion, Deletion, Searching and Splaying.

**Comment by sofezticated-gentleman** [comment]
hey @Kumar-laxmi I would love to work on this issue under hacktoberfest festival can you please assign me

**Comment by cclauss** [comment]
If multiple contributors submit solutions to the same algorithm, it is usually a learning experience for all parties.  Therefore, we review pull requests and do not assign or reserve algorithms.
