### ISSUE TITLE
Adding new algorithm - Pythagorean triplet generator

### ISSUE THREAD

**Issue by keerthanasathya** [TheAlgorithms/Python#6446]
This is one of the important algorithm, I wish to add it in the website in Python language # hactoberfest

**Comment by clueless-bachu** [comment]
Can you please assign it me? I would like to implement it as a part of hacktober festival

**Comment by clueless-bachu** [comment]
Upon searching, this could be the following design:

1) Generate all the triplets with the longest side lesser 'c'
2) Generate all pythagorean triplets which forms a triangle with an area less than 'A'

**Comment by Ayushi96** [comment]
I am interested in contributing to this, could you please provide the expected input and output for the generator?

**Comment by cclauss** [comment]
If multiple contributors submit solutions to the same algorithm, it is usually a learning experience for all parties.  Therefore, we review pull requests and do not assign or reserve algorithms.
