### ISSUE TITLE
Median Search

### ISSUE THREAD

**Issue by WhiteWolf47** [TheAlgorithms/Python#6478]
Implementation of median search in python.

**Comment by WhiteWolf47** [comment]
Can you please assign me this issue (under hacktoberfest)?

**Comment by PaulJWright** [comment]
> Can you please assign me this issue (under hacktoberfest)?

Submit a solution as a PR. Issues aren't assigned

**Comment by naman5825** [comment]
hey I would like to contribute please assign me this issue.

**Comment by AryamanAdivyaSingh47** [comment]
Please assign this issue to me

**Comment by AryamanAdivyaSingh47** [comment]
> > Can you please assign me this issue (under hacktoberfest)?
> 
> Submit a solution as a PR. Issues aren't assigned

Do we directly pull and work on it without waiting for the owner to assign?

**Comment by ShuvamBag** [comment]
hello sir, I want to work on this issue.

**Comment by rakesh-venkata** [comment]
Please assign to me.As it is Binary search related problem,I can solve it easily.

**Comment by Niketdeshmukh** [comment]
I can solve this problem can you assign it to me?
