### ISSUE TITLE
Linear_search.py

### ISSUE THREAD

**Issue by pulkit-999** [TheAlgorithms/Python#6479]
Please assign this issue under hacktoberfest

**Comment by PaulJWright** [comment]
Oh it's that time of the year again...

**Comment by yuvrajthegupta** [comment]
you just want the code for linear search ? or which file to edit?

**Comment by Risavchd24** [comment]
i would like to contribute

**Comment by SumukhaGargeshP** [comment]
I would like to contribute to this. Please assign me to this task. Thanks!

**Comment by SumukhaGargeshP** [comment]
I already see a linear_search.py in the code. is this issue closed?

**Comment by Razafridi** [comment]
i woukd like to cintribute in this issue. Please assign that to me..

**Comment by HuzaifaNaseer02** [comment]
Hi, I would like to contribute to this. Pleas assign me this issue. Thanks

**Comment by Manav39** [comment]
please assign me this issue

**Comment by deepalithakur17** [comment]
I can do it sir . May you please assign it to me.

**Comment by swapnil-23** [comment]
I want to work on this problem. Can you please assign this task to me

**Comment by KajalBhatia24** [comment]
Hello,
I can contribute to my best in this issue. Can you please assign this task to me?

**Comment by Dayanand07** [comment]
Hello, I would like to contribute in this issue. Please assign me this issue.

**Comment by SrijaMarripelli** [comment]
hello please assign this to me

**Comment by hussainiftikhar5242** [comment]
Hi Buddy, plz assign it to me, i want to contribute on it.

**Comment by Swarax007** [comment]
Hey, I would like to contribute, please assign me this issue.

**Comment by naman5825** [comment]
hey I would like to contribute,please assign me this issue.

**Comment by DeepakKabdwal** [comment]
I would love to contribute, can this issue be assigned to me.

**Comment by SiddhiKhade** [comment]
Hi, I would like to contribute to this. I would really appreciate it if you assign this to me, thanks!

**Comment by neelesh08** [comment]
!assign

**Comment by SusavanMondal** [comment]
Hello,
I can contribute to my best in this issue. Can you please assign this task to me?

**Comment by SoumiK-777** [comment]
Hello,
I am interested to solve this issue. Please assign it to me.

**Comment by Abdulwahid7027** [comment]
Hello, I would like to contribute, please assign me this issue.

**Comment by techysubham** [comment]
Hello, I am interested to contribute, please assign me this issue.

**Comment by SohamPashteSSP** [comment]
Hey, I am interested for contibuting to this problem, please assign it to me

**Comment by Himanshi031** [comment]
I would like to contribute for this issue, please assign it to me.

**Comment by AryamanAdivyaSingh47** [comment]
Hello Sir, Please assign this issue to me

**Comment by MasterofDeath0** [comment]
I would like to contribute for this issue, please assign it to me.

**Comment by ShuvamBag** [comment]
Hello sir please assign this work to me. I am a python coder.

**Comment by ShuvamBag** [comment]
hello sir, I want to work on this issue.

**Comment by srajansohani** [comment]
Hi, I want to work please assign this task to me

**Comment by upadhyay8844** [comment]
Please assign this issue to me !!!

**Comment by harshithakolipaka** [comment]
Hello, can you please assign this task to me !!

**Comment by hitensam** [comment]
Can you please assign me this issue?

**Comment by Vishwas1451** [comment]
can I work on this issue
