### ISSUE TITLE
Do not run checklists on draft pull requests

### ISSUE THREAD

**Issue by sanchayanghosh** [TheAlgorithms/Python#6491]
Draft pull requests will often not be refactored and are in progress. So, marking draft pull requests as invalid defeats the purpose of collaborating on what is an unfinished draft.

Once the crux of the draft PR is validated, we can convert it to a proper PR and then do the code quality checks.

**Comment by dhruvmanila** [comment]
I think this belongs to https://github.com/TheAlgorithms/algorithms-keeper. Can you please open this issue there with more description as to what the problem is and which PR are you referring to?
