### ISSUE TITLE
Job Sequencing with Deadlines

### ISSUE THREAD

**Issue by Sneha421** [TheAlgorithms/Python#6510]
**Problem Statement**: Given 3 arrays - Job ID, Job Deadline and Job Profit, find all the non-overlapping jobs that give maximum profit. Only one job can be scheduled at a given time and each job takes one unit of time.

**Input**: Job ID, Job Deadline and Job Profit arrays [can be combined into one array as well]
**Output**: The number of jobs and the maximum profit

<img width="344" alt="image" src="https://user-images.githubusercontent.com/57147597/193437732-9a7191e4-b530-4afe-a66b-c440255c6594.png">

_The above snippet has been taken from GeeksForGeeks_

**Comment by Sneha421** [comment]
This is a problem that involves Greedy Approach. I have previously worked on this approach and would like to submit my work to this repository

**Comment by Subhajit-Roy-O1** [comment]
Hey.. Can you assign this problem to me

**Comment by SusavanMondal** [comment]
Hello, I am interested to solve this issue. Please assign it to me

**Comment by deepakchowdary19** [comment]
it would be great if  i made my first pr by contributing to this, can you assign this to me

**Comment by sushmita-2002** [comment]
Please assign me this issue. I write a very understandable code.
