### ISSUE TITLE
Longest Palindromic Subtring | Dynamic Programming

### ISSUE THREAD

**Issue by ganesh-utla** [TheAlgorithms/Python#6511]
**Problem Statement:** Given a string s, return the longest palindromic substring in s.
A string is called a palindrome string if the reverse of that string is the same as the original string.
Substring is a part of the string that can be achieved by deleting zero or more characters from the beginning and from the ending of the string.

**Input:** "Any String"
**Output:** "palindromic substring with maximum length"

**Eg:** 
**Input:** "abcbabcbade"   
**Output:** "abcbabcba"

**Comment by ganesh-utla** [comment]
Please assign me to this task..

**Comment by deepalithakur17** [comment]
I can do it sir , please assign this task to me.

**Comment by abhijeet-crypto** [comment]
i want to work on this please assign it to me.

**Comment by ratansen** [comment]
I want to work on this sir, please assign it to me.

**Comment by Sounakray2003** [comment]
I would like to contribute

**Comment by RohitSingh107** [comment]
Please assign this to me, I will do not only time complexity optimized but also space optimized dp solution as well.

**Comment by SusavanMondal** [comment]
Hello, I am interested to solve this issue. Please assign it to me

**Comment by Prudhvi26102000** [comment]
Hello, I am ready with this solution and interested to solve this issue. Can you assign this to me?

**Comment by sushmita-2002** [comment]
Can You assign this issue to me. I will try my best to give you the desired code.
