### ISSUE TITLE
Generate Parentheses | Dynamic Programming

### ISSUE THREAD

**Issue by ganesh-utla** [TheAlgorithms/Python#6518]
**Problem Statement:** Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.

**Input:** Any number (N > 0)
**Output:** [List of all combinations of well-formed parenthesis]

**Eg:**
**Input:** `N = 2`
**Output:** `["(())","()()"]`

**Comment by ganesh-utla** [comment]
Please assign me to this task..

**Comment by ratansen** [comment]
I want to write a clean and intuitive algorithm for this. Please assign it to me.

**Comment by Pratham16121** [comment]
Please assign me the task

**Comment by swadhin1237** [comment]
please assign me i already have solution for this

**Comment by Arka-max** [comment]
please assign this task to me
