### ISSUE TITLE
Maximum Subarray | Dynamic Programming

### ISSUE THREAD

**Issue by ganesh-utla** [TheAlgorithms/Python#6519]
**Problem Statement:** Given an integer array `nums`, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.
A subarray is a contiguous part of an array.

**Input:** Any Integer Array
**Output:** Sum of the subarray with maximum sum

**Eg:**
**Input:** `nums = [-2,1,-3,4,-1,2,1,-5,4]`
**Output:** 6
**Explanation:** [4,-1,2,1] has the largest sum = 6.

**Comment by ganesh-utla** [comment]
Please assign me to this task..

**Comment by cclauss** [comment]
We gots lots of em https://github.com/TheAlgorithms/Python/search?q=subarray
