### ISSUE TITLE
Minimum Path Sum | Dynamic Programming

### ISSUE THREAD

**Issue by ganesh-utla** [TheAlgorithms/Python#6520]
**Problem Statement:** Given a M x N `grid` filled with non-negative numbers, find a path from top left to bottom right, which minimizes the sum of all numbers along its path.
_Note: You can only move either down or right at any point in time_

**Input:** M x N grid
**Output:** Path with minimum sum of its numbers

**Eg:**
**Input:** `grid = [[1,8,1],
                    [2,6,9],
                    [4,3,1]]`
**Output:** 11
**Explanation:** Because the path 1 → 2 → 4 → 3 → 1 minimizes the sum.

**Comment by ganesh-utla** [comment]
Please assign me to this task..

**Comment by Rahul664** [comment]
Hi @ganesh-utla,
I believe this program already exists [here](https://github.com/TheAlgorithms/Python/blob/master/dynamic_programming/minimum_cost_path.py) . You can close the issue.
