### ISSUE TITLE
Group Anagrams | String

### ISSUE THREAD

**Issue by shreyasharma6602** [TheAlgorithms/Python#6527]
Problem Statement: Given a list of strings, group all the anagrams together. If there are no anagrams return [].
Input: ['could', 'cloud', 'areas', 'arena', 'artsy', 'grips', 'hello', 'parts', 'prigs', 'strap', 'traps']
Output: [['cloud', 'could'], ['grips', 'prigs'], ['parts', 'strap', 'traps']]

**Comment by Kishore-abhimanyu** [comment]
Can you assign it to me?

**Comment by Kishore-abhimanyu** [comment]
#https://github.com/TheAlgorithms/Python/pull/6530#issue-1393683316
This PR will close this issue

**Comment by anilkumar3313** [comment]
can you assign to me

**Comment by Pymode-Dev** [comment]
Can you assign this to me?

**Comment by anilkumar3313** [comment]
I completed it already

**Comment by imnisi** [comment]
Hello Ma'am! could you assign this issue this to me? I would love to solve this problem.
Thank You
