### ISSUE TITLE
Binary Insertion Sort | Sort

### ISSUE THREAD

**Issue by syedjafer** [TheAlgorithms/Python#6537]
Implementation of binary insertion sort

**Comment by jaygala223** [comment]
I would like to work on this

**Comment by syedjafer** [comment]
I have already created a PR before you :)

**Comment by yogesh-9999** [comment]
!assign

**Comment by mohanty2003** [comment]
may i work on this issue

**Comment by hussainiftikhar5242** [comment]
Please assign this issue to me, i can solve it.

**Comment by SiddhiKhade** [comment]
Hi, I would like to contribute to this. I would really appreciate it if you assign this to me, thanks!

**Comment by syedjafer** [comment]
I have already created the PR #6540 .

**Comment by Anubhav016** [comment]
Hello Sir, can you please assign this assign to me?

**Comment by Abdulwahid7027** [comment]
Hello, I would like to contribute, please assign me this issue.

**Comment by Sunnyvats01** [comment]
I would like to work on this

**Comment by nfarhaan** [comment]
Hello,
Can you assign this issue to me?

**Comment by rydanstar01** [comment]
I have generated a PR to solve this issue #6806. Kindly review it.

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by NIKITApandey01** [comment]
i would like to work on this issue

**Comment by Aakash3081** [comment]
can you assign this issue to me?
