### ISSUE TITLE
Add XGBoost Model

### ISSUE THREAD

**Issue by Chaitanya134** [TheAlgorithms/Python#6551]
### Feature description

There are many commonly used machine learning models already present but there is no implementation of the xgboost model present.

Implement:
1) XGBClassifier - for classification tasks
2) XGBRegressor - for regression tasks

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by yogesh-9999** [comment]
!assign

**Comment by AshwiniDR1802** [comment]
i want to work on this issue

**Comment by Dayanand07** [comment]
Hello, I would like to acknowledge you that I have expertise in this domain . I can contribute to my best in this issue. Can you please assign this task to me?

**Comment by Moddy2024** [comment]
Hi @Chaitanya134  I have created a PR for both of these tasks please review it.  The PR is #6956

**Comment by Moddy2024** [comment]
I have created two separate PR's for both classifier and the regressor. The PR is #7072 for XGBClassifier and  #7074 for XGBRegressor
