### ISSUE TITLE
Script to split bills among a group equally

### ISSUE THREAD

**Issue by yunghog** [TheAlgorithms/Python#6562]
### Feature description

Python program to split bills equally among a group. It should that take induvidual contribution to the bill paid as input and output who owes how much to whom.

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by itsshivamsrivastava** [comment]
Hello, Sir!
I'm interested in solving this issue. Can you please give me a chance to solve this issue?
And, also please explain the issue in detail.

Thank You

**Comment by itsshivamsrivastava** [comment]
Hello, Sir!
I have solved this issue of split bills among a group equally. Please check it out and let me know ASAP. And, if you think it is correct, please merge this PR. And, please help me to increase PR Point in Hacktoberfest by marge this PR request.

Thank You

**Comment by HuzaifaNaseer02** [comment]
Hi, I would like to work on this issue can you assign me this issue? Thanks

**Comment by SoumiK-777** [comment]
Hello @yunghog sir,
I am interested to solve this issue. Please assign it to me.

**Comment by yunghog** [comment]
I have already raised a PR for this issue
