### ISSUE TITLE
SumSet | Maths

### ISSUE THREAD

**Issue by Rhuancpq** [TheAlgorithms/Python#6563]
### Feature description

Add the algorithm for SumSet, also called Minkowski Sum, to sum two subsets, the definition can be read at [WikiPedia](https://en.wikipedia.org/wiki/Sumset)

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by happiestbee** [comment]
I would like to work on this feature

**Comment by OmAvhad** [comment]
I would also love to contribute to it

**Comment by OmAvhad** [comment]
@Rhuancpq can you please add hacktoberfest label to it , it would help us in the fest

**Comment by anshumanbehera27** [comment]
I would also love to contribute to the Minkowski Sum problem I have already created  this so it is more beneficial if you give me the information to add the algorithm  to this project 
@Rhuancpq  can you plz allow me to do this project

**Comment by Sunnyvats01** [comment]
I would like to work on this feature

**Comment by SusavanMondal** [comment]
Hello, I am interested to solve this issue. Please assign it to me

**Comment by Rhuancpq** [comment]
Actually I'll work on this issue...
