### ISSUE TITLE
Lockboxes

### ISSUE THREAD

**Issue by sangwani-coder** [TheAlgorithms/Python#6631]
### Problem
You have `n` number of locked boxes in front of you. Each box is numbered sequentially from `0 to n - 1` and each box may contain keys to the other boxes.

Write a method that determines if all the boxes can be opened.
- A key with the same number as a box opens that box
- You can assume all keys will be positive integers
     - There can be keys that do not have boxes
- The first box is unlocked
- Return True if all boxes can be opened, else return False
- 
input: a list of lists
output: Boolean (True/False)

eg:
input: boxes = [[1], [2], [3], [4], []]
output: True

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by sangwani-coder** [comment]
please assign me to this task.

**Comment by zaki-indra** [comment]
I would like to work on this feature

**Comment by Sounakray2003** [comment]
Yes, I want to work on this feature!
