### ISSUE TITLE
Rotate Linked List

### ISSUE THREAD

**Issue by Kumar-laxmi** [TheAlgorithms/Python#6641]
### Feature description

I would like to work on an algorithm in which a Linked List is given and we have to rotate it by 'x' places to right.

For Example:
![image](https://user-images.githubusercontent.com/76027425/193776081-e48532d3-d998-402d-9002-d915a93ebb4d.png)

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by Kumar-laxmi** [comment]
Kindly assign this issue to me

**Comment by hemantwasthere** [comment]
May i work on this issue

**Comment by Kumar-laxmi** [comment]
> May i work on this issue

Sorry @hemantwasthere, the work has already begun on this issue, kindly look for other issues that are stale for long time

**Comment by AshwiniDR1802** [comment]
i want to work on this issue

**Comment by mohanty2003** [comment]
May i work on this issue ?

**Comment by AbdurRKhalid** [comment]
I think that the work has already been assigned to someone else and it is a easy and not so interesting task, and I also hope that there will be many tasks that will be more interesting than this one.

**Comment by MasterofDeath0** [comment]
Can I work on this I know this code pretty well and can even explain it using comments properly?

**Comment by Arka-max** [comment]
Kindly assign this issue to me

**Comment by gaurbprajapati** [comment]
Hello, I want to work on this issue, Can you please assign this task to me?

**Comment by EpicLulz1509** [comment]
Hey there can i work on this issue?

**Comment by riddhitech** [comment]
Please assign me this issue.
