### ISSUE TITLE
How to a Python program to retrieve info about the following?

### ISSUE THREAD

**Issue by sumonmediu** [TheAlgorithms/Python#668]
1. Write a Python program to retrieve info about the following:
 a. CPU number of system calls
 b. CPU temperature
 c. Context switches
d. Disk and the memory state

**Comment by jithendrabsy** [comment]
I can help you with this

**Comment by jithendrabsy** [comment]
Hi! @sumonmediu  I like to contribute for this!
For knowing the details 
'''
dddd
'''

**Comment by jithendrabsy** [comment]
Hello @sumonmediu  I can help you in this! I just pull requested a .md file about retrieving the information you had questioned!!!

**Comment by jithendrabsy** [comment]
[PC resources](
        Python/PC resources/PC resources.md
      )

**Comment by sumonmediu** [comment]
Can i have for Python 3.x?

But thanks

**Comment by jithendrabsy** [comment]
Yeah it will work for python 3.x and also on windows 
except temperature from psutil module is not supported on windows

**Comment by sumonmediu** [comment]
Ok, I got it for all. But only one problem is here, Temperature of CPU is not working for windows user.
