### ISSUE TITLE
Majority Element

### ISSUE THREAD

**Issue by jaygala223** [TheAlgorithms/Python#6689]
### Feature description

The majority element is the element that appears more than ⌊n / 2⌋ times in an array. One may assume that the majority element always exists in the array.

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by jaygala223** [comment]
Hello Sakshi, appreciate your interest. However, I have already submitted a
Pull request for the same. Feel free to take a look at some other issues.
Thanks.

**Comment by gaurbprajapati** [comment]
Hello, I want to work on this issue, Can you please assign this task to me?

**Comment by EpicLulz1509** [comment]
hello there I would like to work on this issue

**Comment by nidhi-2619** [comment]
I would like to contribute to this issue , I've optimised solution with O(n) time complexity and O(1) space complexity please assign this issue to me
