### ISSUE TITLE
Want to add WildCard Pattern Matching in D.P

### ISSUE THREAD

**Issue by jaisinha** [TheAlgorithms/Python#6692]
### Feature description

This is a leetcode hard problem in dynamic problem.I will give a detail solution with documentation of this code

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by poyea** [comment]
There's an existing [version of it](https://github.com/TheAlgorithms/Python/blob/master/strings/wildcard_pattern_matching.py). Please make sure it's not a duplicate. Otherwise feel free to improve the current version!
