### ISSUE TITLE
I want to add How to text processing step by step in Natural Language Processing(NLP)

### ISSUE THREAD

**Issue by KoolAbhi03** [TheAlgorithms/Python#6727]
### Feature description

In Natural Language Processing, first, we need to convert the text or line in such a way that is meaningful to the model that needs to be trained.
I made a python Notebook to guide everyone through all the steps that needed to be done.

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by AshwiniDR1802** [comment]
I want to contribute

**Comment by KajalBhatia24** [comment]
Hello, I would like to acknowledge you that I have expertise in this domain of NLP . I can contribute to my best in this issue. Can you please assign this task to me?

**Comment by aakash27032001** [comment]
Hello, I would like to tell you that I possess expertise in Natural Language Processing (NLP) and I would like to contribute to this issue. It is my humble request to please assign this task to me.

**Comment by lusifer021** [comment]
Hello I would like to contribute to this.

**Comment by EpicLulz1509** [comment]
Hello I would like to work on this issue.
