### ISSUE TITLE
Want to add min max element in a vector using divide and conquer

### ISSUE THREAD

**Issue by jaisinha** [TheAlgorithms/Python#6728]
### Feature description

I want too add the minimax solution in your repo

### Would you like to work on this feature?

- [ ] Yes, I want to work on this feature!

**Comment by happiestbee** [comment]
I can work on this

**Comment by AryamanAdivyaSingh47** [comment]
Hello Sir/Ma'am, I would like to contribute to this issue. Please assign it to me

**Comment by KshitijKoul26** [comment]
Hi Sir/Ma'am, I want to contribute to this issue.
Can you please assign it to me?
