### ISSUE TITLE
Title of project

### ISSUE THREAD

**Issue by crownedgrouse** [TheAlgorithms/Python#6786]
### Remark

"All algorithms implemented in Python"

Algorithms are algorithms, they are not "implemented" in any Language.

"All" is a bit pretentious, as algorithm is not a finite group of things.

You certainly meant "Python implementation of algorithms"

**Comment by yoBoyio** [comment]
Hello can you assign me this one ?

**Comment by Visha17** [comment]
Hia,Can u assign me this cos i am a newbie in hacktoberfest!!

**Comment by ANANTstudent** [comment]
greeting to manager can you assign this issue to me?

**Comment by karthinivashSR** [comment]
Hello @crownedgrouse , can you assign me with this enhancement ?
