### ISSUE TITLE
Search in 2D matrix

### ISSUE THREAD

**Issue by rissh** [TheAlgorithms/Python#6795]
### Feature description

Wanted to add a solution for Searching for an element in a 2D matrix using Binary search.

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by rissh** [comment]
I want to contribute to this repository, please assign this issue to me.

**Comment by KajalBhatia24** [comment]
Hello, I want to work on this issue, Can you please assign this task to me?

**Comment by RohitShah1706** [comment]
I can solve this issue in the least time complexity.
Please assign this issue to me.

**Comment by anjisnu07** [comment]
Hey buddy assign me for this

**Comment by hussainiftikhar5242** [comment]
Please assign this task to me.

**Comment by saatvik25** [comment]
Hello sir,I want to contribute to this repository, please assign this issue to me.

**Comment by janvi213** [comment]
Please assign this task to me.

**Comment by srusti610** [comment]
Kindly assign me this issue .I would like to contribute.

**Comment by Sumitpathak721** [comment]
Hi @rissh , Its my pleasure if you assign me for this. I'll definitely  give my best approach to solve this is issue.

**Comment by gopal8220** [comment]
I want to solve this issue . Please assign me.

**Comment by Go3452** [comment]
sir , can you plz assign me this issue?

**Comment by imnisi** [comment]
Hello Sir! could you please assign this issue? I would love to solve this issue and give my contribution.
Thank You!

**Comment by rahultalukdargithub** [comment]
Hii @rissh I really want to contribute in this issue . It will be my first pr if you assign me in this issue . please Sir !

**Comment by gaurbprajapati** [comment]
Hello, I want to work on this issue, Can you please assign this task to me?

**Comment by riddhitech** [comment]
Please assign me this issue.
