### ISSUE TITLE
Set Matrix Zeroes

### ISSUE THREAD

**Issue by rissh** [TheAlgorithms/Python#6797]
### Feature description

Wanted to add a solution for Set matrix zeroes.

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by hussainiftikhar5242** [comment]
PLease Assign this task to me.

**Comment by het-dave** [comment]
Please assign this task to me. I know the algorithm for Set Matrix Zeroes.

**Comment by naman5825** [comment]
hey I would like to contribute please assign me this issue.

**Comment by tinshu48** [comment]
Hello Sir, can you assign this issue to me?

**Comment by FrancisBilla** [comment]
Hello, Can you assign this issue to me?

**Comment by Subhajit-Roy-O1** [comment]
Please assign this task to me.

**Comment by Atharva1520** [comment]
Sir,Please Assign this task to me?

**Comment by Madara909** [comment]
lease assign this issue to me.... please

**Comment by rakesh-venkata** [comment]
can you assign this to me

**Comment by Amisha2093** [comment]
Hello @rissh.
Please assign this issue to me.
