### ISSUE TITLE
Undefined name 'on_the_way_back'

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#687]
[flake8](http://flake8.pycqa.org) testing of https://github.com/TheAlgorithms/Python on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./graphs/Directed and Undirected (Weighted) Graph.py:162:100: F821 undefined name 'on_the_way_back'
					if visited.count(__[1]) > 0 and __[1] != parent and indirect_parents.count(__[1]) > 0 and not on_the_way_back:
                                                                                                   ^
./graphs/Directed and Undirected (Weighted) Graph.py:209:100: F821 undefined name 'on_the_way_back'
					if visited.count(__[1]) > 0 and __[1] != parent and indirect_parents.count(__[1]) > 0 and not on_the_way_back:
                                                                                                   ^
./graphs/Directed and Undirected (Weighted) Graph.py:377:100: F821 undefined name 'on_the_way_back'
					if visited.count(__[1]) > 0 and __[1] != parent and indirect_parents.count(__[1]) > 0 and not on_the_way_back:
                                                                                                   ^
./graphs/Directed and Undirected (Weighted) Graph.py:424:100: F821 undefined name 'on_the_way_back'
					if visited.count(__[1]) > 0 and __[1] != parent and indirect_parents.count(__[1]) > 0 and not on_the_way_back:
                                                                                                   ^
4     F821 undefined name 'on_the_way_back'
4
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

@Rizwan-Hasan

**Comment by pradyotd** [comment]
I suspect this failing analysis on all pull requests.

**Comment by cclauss** [comment]
Difficult to say because https://travis-ci.com/TheAlgorithms/Python is not turned on.
