### ISSUE TITLE
Want to contribute some of the Top companies interview Question

### ISSUE THREAD

**Issue by akashagrawalgithub** [TheAlgorithms/Python#6888]
### Feature description

I want to contribute some of the top companies' interview questions so that users can get a glimpse of the question asked in the interview and their possible solutions

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by Harshita781** [comment]
I want to work for this feature.

**Comment by amishachaurasiya** [comment]
I want to work for this feature.

**Comment by Amisha2093** [comment]
I would like to work on this feature.
