### ISSUE TITLE
Stock Price Prediction Algorithms 

### ISSUE THREAD

**Issue by gmmkmtgk** [TheAlgorithms/Python#6889]
### Feature description

Wanted to add Stock Price Prediction Algorithms 

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by Isreal-ogbu** [comment]
Yes, I want to work on this feature!

**Comment by huangderek02** [comment]
Hello @gmmkmtgk I want to work on this issue

**Comment by DeiseCristiane** [comment]
Quero trabalhar nesse recurso!

**Comment by gmmkmtgk** [comment]
Go ahead if any body wants to contribute to this issue

**Comment by NIKITApandey01** [comment]
i would like to work on this issue

**Comment by gmmkmtgk** [comment]
> i would like to work on this issue

go ahead
