### ISSUE TITLE
Missing solution to Median of two Sorted Arrays

### ISSUE THREAD

**Issue by CodeXstalker** [TheAlgorithms/Python#6913]
HI @TheAlgorithms
 I want  to add the missing solution to the problem for `Median of two sorted arrays` in the math file.

### Would you like to work on this feature?

- [x] Yes, I want to work on this feature!

**Comment by CodeXstalker** [comment]
@TheAlgorithms please assign this issue to me.

**Comment by Arko27** [comment]
please assign this task to me.

**Comment by Amisha2093** [comment]
Please assign this issue to me.

**Comment by gaurbprajapati** [comment]
Hello, I want to work on this issue, Can you please assign this task to me?
