### ISSUE TITLE
`maths\jaccard_similarity.py` does not validate input and can divide by zero

### ISSUE THREAD

**Issue by CenTdemeern1** [TheAlgorithms/Python#6916]
### Repository commit

51dba4d743cd2c8d407eea3e9cd4e7b2f69ee34d

### Python version (python --version)

Python 3.10.2

### Dependencies version (pip freeze)

pip==22.2.2
setuptools==60.10.0
wheel==0.37.1

### Expected behavior

According to `CONTRIBUTING.md`, a `ValueError` should be raised in the case of erroneous input.
![image](https://user-images.githubusercontent.com/24682280/194873800-0f430e1c-972c-4b56-b41c-38bd81408379.png)

### Actual behavior

This code makes no effort to check the input, and this can result in a zero division when given empty lists as input:
![image](https://user-images.githubusercontent.com/24682280/194874199-7d8c5153-5fa0-4f7b-a3b9-13e2538a527e.png)

**Comment by CoderRounak** [comment]
what do you want to return from the function when the length of union set is 0 ?
assign me i will add a validating condition

**Comment by CenTdemeern1** [comment]
That commit does not solve the issue!

**Comment by nfarhaan** [comment]
Hello,
Can you assign this issue to me?

**Comment by CenTdemeern1** [comment]
No, go away, spambot.
