### ISSUE TITLE
I want to add an algorithm to find the longest valid parenthesis.

### ISSUE THREAD

**Issue by mohitkumar36** [TheAlgorithms/Python#6917]
### Feature description

I want to add an algorithm to find the longest valid parenthesis, when a string of parenthesis is given to you.

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by AryanMankame** [comment]
can i work on this issue?

**Comment by Atharva1520** [comment]
Sir, Can I Work on It?

**Comment by tejas-veer** [comment]
I would like to contribute

**Comment by tejas-veer** [comment]
Yes u can
It will be mentor choice to choose algorithm 🤗

**Comment by Sumitpathak721** [comment]
Hi @mohitkumar36 , I have efficient approach for this problem and I genuinely want to work on this part. Please assign me for this issue.

**Comment by aakash27032001** [comment]
Hi, I would like to tell you that I have expertise in python and I can propose an efficient solution for this problem. It is my request to please assign this task to me.

**Comment by Riyaksharma** [comment]
Hey can u assign me this issue would love to  contribute my code for the same :)
