### ISSUE TITLE
Some algorithms in this repo are not algorithms rather a whole python script that takes some input and gives an output

### ISSUE THREAD

**Issue by yunghog** [TheAlgorithms/Python#6924]
### Feature description

Some algorithms in this repo are not algorithms rather a whole python script that takes some input and gives an output. Like webscrapping scripts. Cleanup need to be done perhaps

### Would you like to work on this feature?

- [ ] Yes, I want to work on this feature!

**Comment by Devansh-46** [comment]
I would like to work on this feature

**Comment by tianyizheng02** [comment]
Related to #6216, and neither have really been resolved
