### ISSUE TITLE
Include the Sleep Sort

### ISSUE THREAD

**Issue by MatheusMuriel** [TheAlgorithms/Python#6950]
### Feature description

Include the Python implementation of sleep sort

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by MatheusMuriel** [comment]
https://github.com/TheAlgorithms/Python/pull/6951

**Comment by yash509** [comment]
Yes, I want to work on this feature!

**Comment by mohan89en** [comment]
Yes, I want to work on this feature!

**Comment by cclauss** [comment]
#2352
