### ISSUE TITLE
Algo for str

### ISSUE THREAD

**Issue by ameet20** [TheAlgorithms/Python#697]
search and string doesn't contain the Boyer Moore and Naive string searches. someone take it

**Comment by poyea** [comment]
Thanks! I think so.😂 Would you give it a try?

**Comment by Reshad-Hasan** [comment]
did the naive string search

**Comment by ameet20** [comment]
Reshad-Hasan thanks

**Comment by AliasT** [comment]
How about add a `good_suffix_heuristic` implementation ?
