### ISSUE TITLE
I have added the solution for height of Binary tree problem

### ISSUE THREAD

**Issue by kondekarshubham123** [TheAlgorithms/Python#6979]
### Feature description

**Question:**
Given the root of a binary tree, return its maximum depth.
A binary tree's maximum depth is the number of nodes along the longest
path from the root node down to the farthest leaf node.

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by kondekarshubham123** [comment]
PR #6923 raised for same feature.

**Comment by mohan89en** [comment]
Hello Sir, Can you assign me this issue.  I would be grateful to solve it:)

**Comment by mohan89en** [comment]
Yes, I want to work on this feature!

**Comment by CenTdemeern1** [comment]
Plelase see https://github.com/TheAlgorithms/Python/issues/6981#issuecomment-1274490860

**Comment by kondekarshubham123** [comment]
okay
