### ISSUE TITLE
I think that there is better code of heap(data structure).

### ISSUE THREAD

**Issue by elrion018** [TheAlgorithms/Python#698]
Hi!
First of all, thank you for opening your code.
I want to say something useful.

I studied your code(https://github.com/TheAlgorithms/Python/blob/master/sorts/heap_sort.py).
I didn't understand your code until I tested code with many  test cases.
After understanding I wrote new code of heap.
I think this code is better than your code to explain heap data structure.
What do you think?

`class Heap:
    def __init__(self):
        self.h = []
        self.currsize = 0

    def leftChild(self, i): 
        if 2*i+1 < self.currsize:
            return 2*1+1
        return None

    def rightChild(self, i): 
        if 2*i+2 < self.currsize:
            return 2*i+2
        return None

    def maxHeapify(self, node): 
        if node < self.currsize:
            m = node
            lc = self.leftChild(node)
            rc = self.rightChild(node)
            if lc is not None and self.h[lc] > self.h[m]:
                m = lc
            if rc is not None and self.h[rc] > self.h[m]:
                m = rc

            if m!=node:
                temp = self.h[node]
                self.h[node] = self.h[m]
                self.h[m] = temp
                self.maxHeapify(m)

    def buildHeap(self,a):
        self.currsize = len(a)
        self.h = list(a)
        for i in range(self.currsize//2, -1, -1):
            self.maxHeapify(i)
    
    def Maxdelete(self):
        if self.currsize >= 1:
            me = self.h[0]
            temp = self.h[0]
            self.h[0] = self.h[self.currsize-1]
            self.currsize -=1
            self.maxHeapify(0)
            return me
        return None

    def heapsort(self):
        size = self.currsize
        while self.currsize - 1>=0:
            temp = self.h[0]
            self.h[0] = self.h[self.currsize - 1]
            self.h[self.currsize-1] = temp
            self.currsize -=1
            self.maxHeapify(0)
        self.currsize = size

    def insert(self, data):
        self.h.append(data)
        curr = self.currsize
        self.currsize +=1
        while (curr-1)//2 >= 0 and self.h[curr] > self.h[(curr-1)//2]:
            temp = self.h[(curr-1)//2]
            self.h[(curr-1)//2] = self.h[curr]
            self.h[curr] = temp
            curr = (curr-1)//2

    def display(self):
        print(self.h)`

**Comment by poyea** [comment]
Thanks for the advice! Didn't check through two pieces of code (seems that yours is more throughout), but I think it is perfectly fine to open a PR, on a different version of heap sort!😋 - John
