### ISSUE TITLE
[Matrix] I have added the solution for Max area of island problem

### ISSUE THREAD

**Issue by kondekarshubham123** [TheAlgorithms/Python#6981]
### Feature description

**Problem**
Given an m x n binary matrix grid. An island is a group of 1's
(representing land) connected 4-directionally (horizontal or vertical.)
You may assume all four edges of the grid are surrounded by water.
The area of an island is the number of cells with a value 1 in the island.
Return the maximum area of an island in grid.
If there is no island, return 0.

### Would you like to work on this feature?

- [x] Yes, I want to work on this feature!

**Comment by kondekarshubham123** [comment]
Added PR #6918 for same problem

**Comment by bhavya-sharma26** [comment]
Hi , can you assign this task to me?
It will be very thankful from your side

**Comment by CenTdemeern1** [comment]
I don't think this issue is needed.
Also, please ignore assign beggars like @bhavya-sharma26

**Comment by kondekarshubham123** [comment]
Okay sure @CenTdemeern1, in future contribution I will take care of your suggested points.

Thanks for guidance!

**Comment by kondekarshubham123** [comment]
PR https://github.com/TheAlgorithms/Python/pull/6918, merged on 18th oct
