### ISSUE TITLE
Delete broken file

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#7010]
### Feature description

In the [cyphers directory](https://github.com/TheAlgorithms/Python/tree/master/ciphers), there is a weird file called `prehistoric_men.txt`. 
I don't think this is intentional

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by lumi232** [comment]
Please assign me this issue.

**Comment by priti252** [comment]
Yes, I want to work on this feature!

**Comment by AvijeetJain** [comment]
Please assign me this issue
