### ISSUE TITLE
Sum of binary tree nodes

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#7020]
### Feature description

```py
    3
   / \
  9   20
     /  \
    15   7
```
The output would be `3+9+20+15+7`

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by nfarhaan** [comment]
Hello,
Can you assign this issue to me?

**Comment by Akashhpatil** [comment]
I would like to work on this issue!

**Comment by PremSundarB** [comment]
Hey I would love to work on this issue !

**Comment by UTKARSHMOHAN2003** [comment]
SIE ASSIGN ME

**Comment by AbrarAhmed3** [comment]
I would like to work on this issue!
Can you assign this issue to me?

**Comment by aryan-1311** [comment]
Hi, I would like to work on this issue.
Assign it to me.

**Comment by imnisi** [comment]
Hii @CaedenPH! Could you assign this issue to me? I would love to solve this issue. 
Thank You

**Comment by huangderek02** [comment]
Hii @CaedenPH! Could you assign this issue to me? I would love to solve this issue.
Thank You

**Comment by Shubham74500** [comment]
Hii sir could you assign this issue to me.

**Comment by drashan14** [comment]
Hello Sir/Mam,
I would like to do this job could you assign me this task.

**Comment by anuragshuklajec** [comment]
Hii @CaedenPH! Could you assign this issue to me ?

**Comment by SaurabhBudhwani26** [comment]
Hi @CaedenPH , I would love to work on this issue, can you please assign me this?

**Comment by DeiseCristiane** [comment]
Olá, quero contribuir com esse projeto.

**Comment by shyambaral** [comment]
hlo can i do that

**Comment by ashutosh-gupta2111** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by Sanjana20304** [comment]
I would like to work on this. Please assign this to me
