### ISSUE TITLE
Convert snake_case to camelCase or PascalCase

### ISSUE THREAD

**Issue by carlos3dx** [TheAlgorithms/Python#7028]
### Feature description

An algorithm that given a string formatted as snake_case returns it as camelCase or PascalCase depending on Boolean parameter.

Examples:

`def snake_to_camel_case(input: str, use_pascal: bool = False) -> str`
`snake_to_camel_case('some_string_in_snake_case') -> 'someStringInSnakeCase'`
`snake_to_camel_case('some_string_in_snake_case', True) -> 'SomeStringInSnakeCase'`

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by carlos3dx** [comment]
Please assign it to me, I have almost finished it

**Comment by Arko27** [comment]
can you please assign this task to me. I would be glad to contribute in this repo.
