### ISSUE TITLE
Want to add space invader game made from Python

### ISSUE THREAD

**Issue by rahulranjan74** [TheAlgorithms/Python#7035]
### Feature description

made using pygame
important png files will be added

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by sukhmani1303** [comment]
hey @rahulranjan74 !
I would love to contribute to the open-source community, allow me to add to this repository and to my first git PR 😄.
Also, I would request you to label it as Hacktoberfest.

Regards,

**Comment by amananand0001** [comment]
hello @rahulranjan74 
I want to contribute in this project .
so pls allow me to contribute in this project
