### ISSUE TITLE
Add Exponential Search in Search folder

### ISSUE THREAD

**Issue by MohammadRehanPatel** [TheAlgorithms/Python#7042]
### Feature description

assign me with Hacktoberfest tag please

### Would you like to work on this feature?

- [ ] Yes, I want to work on this feature!

**Comment by Isreal-ogbu** [comment]
I would like to work on this

**Comment by UTKARSHMOHAN2003** [comment]
assign me this issue i  want to  work on it

**Comment by Anshika-sona** [comment]
would love to work on this. Please assign me this issue.
