### ISSUE TITLE
Drop Python 2 support?

### ISSUE THREAD

**Issue by slarse** [TheAlgorithms/Python#710]
Also related to #309 

There are a lot of files that try to support both Python 2 and Python 3, with mixed results. Then there are some files using explicit Python 3.6 features (such as f-strings), which makes running _all_ files under both Python 2 and Python 3 a bit yanky.

While we can probably make most of this work using backporting libraries (such as [future-fstrings](https://github.com/asottile/future-fstrings)), we could start going through all of your files and drop Python 2 support entirely. As Python 2 reaches end of life January 1st 2020, this should be done at some point, sooner rather than later. Do you want us to, at least start, to do it while refactoring the test suite? If so, which versions of Python should be supported?

For this whole project to be tested in a unified manner, it must require certain versions of Python. We can do this job for you, when the test suites have been set up.

**Comment by slarse** [comment]
To just be able to keep on working toward #309, we will assume Python 2 should be supported and consider anything that does not work at all in Python 2 to be bugs.

**Comment by slarse** [comment]
After some more digging around in the project, Python 2 support seems to be fairly poor already. There are 256 modules in total, and these are the results for just importing them in Python 2 and 3, respectively:

## Python 2
* 150 succeed
* 106 fail
    - 14 fail because top level code read from stdin
    - 4 timeout (blocking top level code)
    - 81 import errors.

## Python 3
* 176 succeed
* 80 fails
    - 32 fail because they read from stdin in top-evel code
    - 11 timeout (blocking top-level code)
    - 26 import errors

Note that import errors are of 2 types: external dependencies (such as `matplotlib` and `numpy`) and incorrect imports of adjacent modules.

To further #309, we will attempt to not break existing Python 2 compatibility, but we will not backport any Python 3 code, as it is in the majority.

**Comment by cclauss** [comment]
This repo does not support legacy Python.
