### ISSUE TITLE
Evolutionary Algorithms

### ISSUE THREAD

**Issue by VintageDesign** [TheAlgorithms/Python#712]
So I have a whole ton of Evolutionary Algorithm Variants and Simulated Annealing Algorithms from some research for a class. Would you guys want a couple examples of them? (with plenty of documentation and explanation of course)

**Comment by poyea** [comment]
Sure. It seems there's no existing folder for these algorithms, so feel free to create them in folder(s).😄

**Comment by VintageDesign** [comment]
Since I can't push up a new branch on the repo, how does one create a PR?

**Comment by poyea** [comment]
You may [create a pull request from a fork](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork).

**Comment by QuantumNovice** [comment]
Fork the current repository and add the algorithms. Then do a PR.
