### ISSUE TITLE
System of linear equation in 2 variable.

### ISSUE THREAD

**Issue by kituuu** [TheAlgorithms/Python#7122]
### Feature description

I want to implement a new module inside the matrix ... To solve the System of linear equations in 2 variables using Cramer's Rule. 

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by Sritam28** [comment]
Please, assign me this, I want to work on this.

**Comment by kituuu** [comment]
Bro, I want to work on this that's why I CREATED THIS ISSUE 🥲🥲 I m not maintainer ... I m contributor.

**Comment by kituuu** [comment]
Please leave this, try other issues.

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by Sritam28** [comment]
Please assign this to me
