### ISSUE TITLE
Binary tree path sum

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#7135]
### Feature description

https://leetcode.com/problems/path-sum-iii/

Sum of paths in a binary tree

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by shyambaral** [comment]
hey can i do

**Comment by Aniketmishra0** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by shyambaral** [comment]
> Hello Sir, Can You assign this issue to me?

ok solve it

**Comment by Pavan0603** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by ashutosh-gupta2111** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by nfarhaan** [comment]
Hello,
Can you assign this Issue to me?

**Comment by the-amitsingh** [comment]
I would like to do this 
so can you please assign me?

**Comment by apoorvdtu** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by Piyush5madhukar** [comment]
i would like to contribute.

**Comment by ANKUSH531** [comment]
I am interested in contributing

**Comment by Nd1097** [comment]
Interested in Contributing to this.

**Comment by anujwar** [comment]
Hey can you assign me to this issue?
I want to contribute towards this issue !

**Comment by SwaggyRajput** [comment]
Hello sir, can u assign me this issue. I would love to grab this opportunity.

**Comment by siva-balan** [comment]
Hello sir, I would like to contribute for this issue. please assign this issue to me

**Comment by pemo76** [comment]
I would like to contribute to this issu. I am from competitive coding background so I can handle this issu smoothly . So pls assign this to me

**Comment by shivsaranyada** [comment]
HELLO SIR.

Can You assign this issue to me?
I would like to contribute for this issue. please assign this issue to me
