### ISSUE TITLE
Fluid Dynamics (Physics)

### ISSUE THREAD

**Issue by DIvkov575** [TheAlgorithms/Python#7139]
### Feature description

Adding Bernouli's, Torricelli's, + other associated with fluids.

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by aryan9042** [comment]
please assign to me

**Comment by DIvkov575** [comment]
@aryan9042 I already have a pr for this.

**Comment by aryan9042** [comment]
can you plaese suggest me any pr i'm new to this event kindly please help
thank you

**Comment by Sanjana20304** [comment]
Please assign this issue to me

**Comment by DIvkov575** [comment]
@Sanjana20304 I already have a pr for this.
