### ISSUE TITLE
Levinstein distance Dynamic Programming: up -> down approach

### ISSUE THREAD

**Issue by alexpantyukhin** [TheAlgorithms/Python#7172]
### Feature description

Just for demonstration of edit distnace for 2 strings: implement Dynamic Programming: up -> down approach

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by alexpantyukhin** [comment]
The PR: https://github.com/TheAlgorithms/Python/pull/7171

**Comment by theayangupta** [comment]
Hi Sir
I want to work on this feature. Could you please assign this to me?
