### ISSUE TITLE
Dijkstra's Shortest Path Algorithm in Python

### ISSUE THREAD

**Issue by ashutosh-gupta2111** [TheAlgorithms/Python#7173]
### Feature description

To write the code of Dijkstra's Shortest Path Algorithm in python?

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by ashutosh-gupta2111** [comment]
Can you please assign me this issue.

**Comment by AdityaVerma32** [comment]
Hi, I would like to work on this.

**Comment by JainSamyak8840** [comment]
Hi, I wanted to work on this.

**Comment by harshithakolipaka** [comment]
hey , can you please assign this task to me

**Comment by nitingarg2207** [comment]
Hey can you assign this task to me

**Comment by the-amitsingh** [comment]
Heyy !!  I want to work on this, will you please assign me?

**Comment by thunderbolt181** [comment]
Hey , can i work on this issue plz.

**Comment by specdrake** [comment]
I'd like to work on this, can you please assign this issue to me? @ashutosh-gupta2111

**Comment by Ajit-007** [comment]
Hi, I want to work on this issue. Can you please assign me this issue?

**Comment by kisan17** [comment]
hello sir,can you assign me this issue?

**Comment by lakshya0754N** [comment]
I would like to work on this issue. Can u please assign to me

**Comment by aakash27032001** [comment]
I would like to work on this issue. Can u please assign to me

**Comment by aakash27032001** [comment]
I would like to work on this issue. Can u please assign to me

**Comment by RajdeepDey010** [comment]
Hloo, I would like to contribute my learning if you can kindly assign me this issue.

**Comment by Nd1097** [comment]
Hello, I would like to work on this Algorithm. Can you assign the task, thanks!!

**Comment by this-mkhy** [comment]
Hellooooo, I can do it

**Comment by tianyizheng02** [comment]
I believe Dijkstra's algorithm has been already implemented in multiple files:
1. https://github.com/TheAlgorithms/Python/blob/master/graphs/dijkstra.py
2. https://github.com/TheAlgorithms/Python/blob/master/graphs/dijkstra_2.py
3. https://github.com/TheAlgorithms/Python/blob/master/graphs/dijkstra_algorithm.py
4. https://github.com/TheAlgorithms/Python/blob/master/graphs/dijkstra_alternate.py

**Comment by Aakash3081** [comment]
can you assign this issue to me?
