### ISSUE TITLE
Python/arithmetic_analysis/newton_raphson_method.py 

### ISSUE THREAD

**Issue by lmj01** [TheAlgorithms/Python#721]
in this file, NewtonRaphson('sin(x)', 2)), where defined the x ? 
@AlexDvorak

**Comment by AlexDvorak** [comment]
it isn’t, the function takes an argument, a function, for example "y = sin(x)” but without the "y =" part. It's a function to graph, not a numerical input.

**Comment by lmj01** [comment]
i run python newton_raphson_method.py, get the x is not defined,  maybe i don't understand this algorithm how do in graph or show in picture by other library

**Comment by Brykerr78** [comment]
🤔

**Comment by shyamapadamaity** [comment]
I am unable to install healpy in my mac Mojave version though I used pip install  healpy.
