### ISSUE TITLE
Assign each of our pytest warnings to the algorithm authors

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#7211]
### Feature description

Pytest generates a lot of warnings that we should get resolved.  https://github.com/TheAlgorithms/Python/actions/runs/3254565205/jobs/5342967879#step:6:577

Go through each warning and look at the Python file to see who created it or modified it.  Create an issue asking the author(s) to fix the warning.  If they do not respond with a fix within seven days then find someone in the community that is willing to propose a fix.  Let’s get the warnings back down to zero but let’s give the authors the first crack at proposing fixes.

### Would you like to work on this feature?

- [ ] Yes, I want to work on this feature!

**Comment by iSumitBanik** [comment]
So, we would be analyzing the warnings and create the issues manually.
Am I right?

**Comment by CaedenPH** [comment]
@cclauss I believe

**Comment by CaedenPH** [comment]
@cclauss Is this what you meant?

**Comment by PARVASHWANI** [comment]
> 

Yes I would like to work on this feature.

**Comment by mahak-dev** [comment]
hello sir,
I want to solve this problem, I have a little bit of knowledge regarding on this Topic

**Comment by cclauss** [comment]
@PARVASHWANI and @mahak-dev Why are you waiting?  If you see something that you can fix then open a pull request.
