### ISSUE TITLE
3D Grid Dynamic Programming: Memoization

### ISSUE THREAD

**Issue by JainSamyak8840** [TheAlgorithms/Python#7216]
### Feature description

Feature description
To write the code on a 3D Dynamic Programming program on a grid using the memoization approach.

### Would you like to work on this feature?
- [x] Yes, I want to work on this feature!

**Comment by JainSamyak8840** [comment]
I would like to work on this.

**Comment by apoorvdtu** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by SnehalSa** [comment]
Hello Sir,
Can You assign this issue to me?
