### ISSUE TITLE
Add `doctest.testmod` to every file for easier testing

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#7259]
### Feature description

Add this below to every file for easier file testing.
```py
if __name__ == "__main__":
    import doctest

    doctest.testmod()
```
There is already a workflow to automatically check for doctests, however this provides better accessibility when testing specific files.
This issue is questionable so I'm open to conversation

**Comment by dhruvmanila** [comment]
I'm actually against this. I'm more of an opinion that a user would want to actually run the algorithm, so we could provide a minimal CLI for each algorithm using `argparse`. Any thoughts? @cclauss 

The CI already takes care of running the `doctest` and if the user wants to run them, then can easily do so from the module CLI.

_Originally posted by @dhruvmanila in https://github.com/TheAlgorithms/Python/issues/7260#issuecomment-1279896522_

**Comment by dhruvmanila** [comment]
The command to run `doctest` on individual files:
```
python -m doctest -v <filepath>
```

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/.github/workflows/build.yml#L25 runs all doctests so this change is not needed.  Is should continue to be the right of each author to decide if these lines are in their files or not.
