### ISSUE TITLE
New comer

### ISSUE THREAD

**Issue by freesadness** [TheAlgorithms/Python#729]
Hi, good morning.

**Comment by louisparis** [comment]
Hi!

**Comment by wenfangliang** [comment]
hi,good night!

**Comment by xyz2741** [comment]
sign in

**Comment by tongpinmo** [comment]
hahah ,thank you

**Comment by christma** [comment]
You've done a great job. Thank you. I'm from China.


xianliangliu@aliyun.com
 
From: tongpinmo
Date: 2019-04-28 14:37
To: TheAlgorithms/Python
CC: Subscribed
Subject: Re: [TheAlgorithms/Python] New comer (#729)
hahah ,thank you

**Comment by Djpastorss** [comment]
Hi 😊

**Comment by clearwater06** [comment]
thank you for sharing

**Comment by KongQingXin12** [comment]
Hi

**Comment by Liusmaster** [comment]
thanks

**Comment by huiminlatte** [comment]
Hi!

**Comment by AyonzOnTop** [comment]
Hi, I'm Tomiwa from Nigeria. Nice to meet you.

**Comment by 18976080486** [comment]
Hi

**Comment by amid11** [comment]
maybe using a __Discord__ group would be a better idea, I mean submitting *an issue* just for showing gratitude or saying hello doesn't seem to be appropriate. 
### Please don't contribute to this issue anymore, thanks :+1:

**Comment by mo1a1s** [comment]
Hi
