### ISSUE TITLE
[PYTEST WARNING] Machine learning local weighted learning

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#7307]
### Feature description

@venkateshtantravahi Please could you resolve this warning
```
machine_learning/local_weighted_learning/local_weighted_learning.py: 87 warnings
  /opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py:69: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
    return matrix(data, dtype=dtype, copy=False)
```

origin: #7211

**Comment by Jpduker** [comment]
Assign me to this issue

**Comment by Jpduker** [comment]
> ### Feature description
> @venkateshtantravahi Please could you resolve this warning
> 
> ```
> machine_learning/local_weighted_learning/local_weighted_learning.py: 87 warnings
>   /opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py:69: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
>     return matrix(data, dtype=dtype, copy=False)
> ```
> 
> origin: #7211

Can you assign me to this issue ?
