### ISSUE TITLE
How to recieve data's continuously from ethernet connected barcode readers using python?

### ISSUE THREAD

**Issue by Thyagutamizhan** [TheAlgorithms/Python#739]
Hi, Actually I'm a beginner in python. I wanna connect multiple barcode readers via ehernet and recieve data's from those readers continuously for processing those data's. So i wanna know how to recieve the data from ehternet connected barcode readers continuously using python script.

**Comment by cclauss** [comment]
Can we please close this issue?

**Comment by Thyagutamizhan** [comment]
Instead of  closing the issue,  guide me how to recieve data via ethernet barcoe scanners will be helpful
