### ISSUE TITLE
Adding a new algorithm 

### ISSUE THREAD

**Issue by willx75** [TheAlgorithms/Python#744]
Hi I like how you manage your project that's why  i'd like to contribute on it, by adding a new algorithm, 
Best

**Comment by louisparis** [comment]
Go for it! 👍

**Comment by willx75** [comment]
Thanks you!

**Comment by odyszago** [comment]
Hey there!!! I found this repository very interestring. I'd like to contribute on arithmetic_analysis adding new algorithms, such as Lagrange’s Interpolation or least squares polynomial.  Let me know if it's ok ;)

**Comment by QXQJack** [comment]
i want to be an IT player , and i can give up my hair  . hahaha
