### ISSUE TITLE
i want to add inverse factoral method to find nCr in O(1)

### ISSUE THREAD

**Issue by kunjgit** [TheAlgorithms/Python#7440]
### Feature description

the inverse factorial method can find any nCr in just O(1) with some O(n) precomputation so it is really important to find nCr when n is so large 
this is really important to know because as competitive programmer it can help you to make your program faster as well as time efficient

**Comment by sauravkumar8178** [comment]
Hello sir, can you assign this issue to me

**Comment by supreetkaursareen** [comment]
can you assign it to me
