### ISSUE TITLE
Add the Viterbi algorithm

### ISSUE THREAD

**Issue by carlos3dx** [TheAlgorithms/Python#7465]
### Feature description

I want to add to the dynamic programming folder the Viterbi algorithm.

https://en.wikipedia.org/wiki/Viterbi_algorithm

### Would you like to work on this feature?

- [X] Yes, I want to work on this feature!

**Comment by carlos3dx** [comment]
Please, asking it to me, I'm already have half of it.

**Comment by Masoom9587** [comment]
please assign it to me

**Comment by Arghya46** [comment]
Hello sir, Can u assign this issuet to me?
