### ISSUE TITLE
Blum Blum Shub PRNG

### ISSUE THREAD

**Issue by gosueep** [TheAlgorithms/Python#7470]
### Feature description

Blum Blum Shub is a pseudo-random number generator with both an iterative and closed-form solution.
More details on the Wikipedia page: https://en.wikipedia.org/wiki/Blum_Blum_Shub

I would like to add this, but I do not know where it should go - either math or other?

**Comment by syedjafer** [comment]
@gosueep u can place it under math. That would make more sense.
