### ISSUE TITLE
Subset generation shouldn't work entirely by printing

### ISSUE THREAD

**Issue by tianyizheng02** [TheAlgorithms/Python#7502]
### Feature description

The subset generation algorithm in [`dynamic_programming/subset_generation.py`](https://github.com/TheAlgorithms/Python/blob/master/dynamic_programming/subset_generation.py) works entirely by printing all possible subsets to console, which goes against the current contribution guidelines (see #7337 for more details). Ideally the algorithm should generate some data structure containing all of the subsets instead (list, set, generator, whatever), but that would require reworking parts of the algorithm rather than simply removing the print statements.

**Comment by cclauss** [comment]
This looks OK to me.
