### ISSUE TITLE
Code runs in infinite loop to accept Tree elements

### ISSUE THREAD

**Issue by arajb** [TheAlgorithms/Python#76]
This code needs logic fix and libraries.

**Comment by gupta2140** [comment]
Hello. I'm new to python but have a very strong background in c++. I'm a 2nd year CSE student and have always been in competitive field and have good commands on algorithms. I prefer c++ in competitive coding. But for open source contributions, i started python. I want to fix this bug. Further, when i compiled it, it showed the error:  
 File "binary_tree_traversals.py", line 16
    print("Enter the value of the root node: ", end="")
SyntaxError: invalid syntax.

 I would like to fix it it and continue contributing to increase the algorithm files.
Hope to get reply from someone soon!

**Comment by ankit167** [comment]
@gupta2140 I am assuming you are using python2.x to land into this error. This syntax would work with python3.x

**Comment by AnupKumarPanwar** [comment]
@gupta2140  try running it like "python3  binary_tree_traversals.py"

**Comment by gupta2140** [comment]
yupp...that error is removed.

**Comment by gupta2140** [comment]
i would like to fix this "Code runs in infinite loop to accept Tree elements" issue.

**Comment by gupta2140** [comment]
I fixed infinite loop bug.
But pre-order traversal is showing many Invalid inputs.
example:

********* Binary Tree Traversals ************

Enter the value of the root node: 1
Enter the left node of 1: 2
Enter the right node of 1: 3
Enter the left node of 2: 4
Enter the right node of 2: 5
Enter the left node of 3: 6
Enter the right node of 3: 7
Enter the left node of 4: -1

********* Pre Order Traversal ************
1 2 4 Invalid input
Invalid input
5 Invalid input
Invalid input
3 6 Invalid input
Invalid input
7 Invalid input
Invalid input

******************************************


********* In Order Traversal ************
4 2 5 1 6 3 7 
******************************************


********* Post Order Traversal ************
4 5 2 6 7 3 1 
******************************************


********* Level Order Traversal ************
1 2 3 4 5 6 7 
******************************************

**Comment by gupta2140** [comment]
fixed it!

**Comment by 0oo0** [comment]
Thanks.
