### ISSUE TITLE
Vector: Mutable default argument

### ISSUE THREAD

**Issue by areebbeigh** [TheAlgorithms/Python#762]
https://github.com/TheAlgorithms/Python/blob/48bba495ae1007c9e21a0c11d5b95585825f9a9e/linear_algebra_python/src/lib.py#L48-L53

this should be something like

```python
     def __init__(self,components=None): 
         """ 
             input: components or nothing 
             simple constructor for init the vector 
         """ 
         self.__components = [] if not components else list(components) 
```

https://docs.python-guide.org/writing/gotchas/

**Comment by cclauss** [comment]
Fixed at https://github.com/TheAlgorithms/Python/blob/master/linear_algebra/src/lib.py#L49
