### ISSUE TITLE
Newton-Raphson method in math algorithm

### ISSUE THREAD

**Issue by MortazaHassani** [TheAlgorithms/Python#7642]
### Feature description

Newton-Raphson method is not available in math algorithms.

**Comment by ShreyaGupta12** [comment]
Hello sir, Can you assign this issue to me?

**Comment by katderv** [comment]
Hello, I'm interested in this issue, can I be assigned?

**Comment by WilberC1219** [comment]
If no one is assigned this issue I would like to give it a try
