### ISSUE TITLE
Create Testcase for the Algorithm 

### ISSUE THREAD

**Issue by sasankaweera123** [TheAlgorithms/Python#7720]
### Feature description

Add several unit test cases for the algorithms

**Comment by vrinda01go** [comment]
Hey! I am interested in this issue. Could you please assign this issue to me

**Comment by sasankaweera123** [comment]
Go for it

**Comment by patraabinash29** [comment]
Hey! I am interested in this issue. Could you please assign this issue to me?
patraabinash29
