### ISSUE TITLE
Replace `yulewalker` in `audio_filtes/equal_loudness_filter`

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#7724]
### Feature description

https://pypi.org/project/yulewalker/ is no longer maintained it seems, which is logging a warning in the `audio_filters/equal_loudness_filter.py`.

Fixes: #7300

**Comment by Sahil2315** [comment]
what needs to be done?

**Comment by CaedenPH** [comment]
> what needs to be done?

In this file
https://github.com/TheAlgorithms/Python/blob/master/audio_filters/equal_loudness_filter.py#L5
The module `yulewalker` is used. This module uses `np.int` which is deprecataed and raises warnings
Ideally, this module would be swithed out with a later, maintained package, or the code would be refactored in order to not use `yulewalker`
