### ISSUE TITLE
urgently seeking software prototype maker for assessment tool

### ISSUE THREAD

**Issue by alvinlee4858** [TheAlgorithms/Python#775]
Hi there, alvin lee, from singapore here.

i have a startup making Digital Alchemist. it's about recording and curating analogue human experience.

i do not have data nor computer background, i just need some one or small team to make a simple app. alvinlee4858@gmail.com
wwww.castlescanfly.com.
+65 98753550

please contact me.  looking forward,

**Comment by cclauss** [comment]
Can we please close this issue??

**Comment by poyea** [comment]
I'm closing this now. I will also add a few lines to contributing guide.
