### ISSUE TITLE
Create subtraction method in maths folder

### ISSUE THREAD

**Issue by adithyarao121** [TheAlgorithms/Python#7782]
### Feature description

Create subtraction method in maths folder for subtracting 2 numbers

**Comment by rafagarciac** [comment]
Hi @adithyarao121 ! 😄 
Yes, it looks like we already have the `add.py` function to calculate the sum of two numbers.
- https://github.com/TheAlgorithms/Python/blob/master/maths/add.py

So it makes sense to implement the same thing for subtraction.
I'll take the implementation of this problem.
Thanks for your report!

**Comment by ShashankZobb** [comment]
I have created a subtrat.py program. It has passed all the checks

**Comment by rafagarciac** [comment]
Perfect. Could you provide the PR? 🤔 
I think is this the following PR:
- https://github.com/TheAlgorithms/Python/pull/7803
