### ISSUE TITLE
Cramer's Rule for 3x3 matrix.

### ISSUE THREAD

**Issue by kituuu** [TheAlgorithms/Python#7791]
### Feature description

Want to add a script for solving a system of linear equations in three variables using Cramer's rule.

**Comment by Killerraj143** [comment]
# Python3 program to calculate
# solutions of linear equations
# using cramer's rule

# This functions finds the
# determinant of Matrix
def determinantOfMatrix(mat):

	ans = (mat[0][0] * (mat[1][1] * mat[2][2] -
						mat[2][1] * mat[1][2]) -
		mat[0][1] * (mat[1][0] * mat[2][2] -
						mat[1][2] * mat[2][0]) +
		mat[0][2] * (mat[1][0] * mat[2][1] -
						mat[1][1] * mat[2][0]))
	return ans

# This function finds the solution of system of
# linear equations using cramer's rule
def findSolution(coeff):

	# Matrix d using coeff as given in
	# cramer's rule
	d = [[coeff[0][0], coeff[0][1], coeff[0][2]],
		[coeff[1][0], coeff[1][1], coeff[1][2]],
		[coeff[2][0], coeff[2][1], coeff[2][2]]]
	
	# Matrix d1 using coeff as given in
	# cramer's rule
	d1 = [[coeff[0][3], coeff[0][1], coeff[0][2]],
		[coeff[1][3], coeff[1][1], coeff[1][2]],
		[coeff[2][3], coeff[2][1], coeff[2][2]]]
	
	# Matrix d2 using coeff as given in
	# cramer's rule
	d2 = [[coeff[0][0], coeff[0][3], coeff[0][2]],
		[coeff[1][0], coeff[1][3], coeff[1][2]],
		[coeff[2][0], coeff[2][3], coeff[2][2]]]
	
	# Matrix d3 using coeff as given in
	# cramer's rule
	d3 = [[coeff[0][0], coeff[0][1], coeff[0][3]],
		[coeff[1][0], coeff[1][1], coeff[1][3]],
		[coeff[2][0], coeff[2][1], coeff[2][3]]]

	# Calculating Determinant of Matrices
	# d, d1, d2, d3
	D = determinantOfMatrix(d)
	D1 = determinantOfMatrix(d1)
	D2 = determinantOfMatrix(d2)
	D3 = determinantOfMatrix(d3)
	
	print("D is : ", D)
	print("D1 is : ", D1)
	print("D2 is : ", D2)
	print("D3 is : ", D3)

	# Case 1
	if (D != 0):
	
		# Coeff have a unique solution.
		# Apply Cramer's Rule
		x = D1 / D
		y = D2 / D
		
		# calculating z using cramer's rule
		z = D3 / D
		
		print("Value of x is : ", x)
		print("Value of y is : ", y)
		print("Value of z is : ", z)

	# Case 2
	else:
		if (D1 == 0 and D2 == 0 and
			D3 == 0):
			print("Infinite solutions")
		elif (D1 != 0 or D2 != 0 or
			D3 != 0):
			print("No solutions")

# Driver Code
if __name__ == "__main__":

	# storing coefficients of linear
	# equations in coeff matrix
	coeff = [[2, -1, 3, 9],
			[1, 1, 1, 6],
			[1, -1, 1, 2]]

	findSolution(coeff)

**Comment by rafagarciac** [comment]
@kituuu @Killerraj143 
Hi ! Thanks for your report. 👌🏼  
Could you open a new PR? 
Thanks in advance.

**Comment by kituuu** [comment]
> @kituuu @Killerraj143 
> Hi ! Thanks for your report. 👌🏼  
> Could you open a new PR? 
> Thanks in advance. 

Okay I will do today.
