### ISSUE TITLE
Mention the triviality of an algorithm in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#7880]
### Feature description

There are lots of pull requests with trivial algorithms such as `subtract`, `add_three_numbers`, etc.
There should be a section in the `CONTRIBUTING` mentioning the triviality requirements ie this algorithm must meet so and so requirements...

This is hard to enforce due to some trivial files such as
    - https://github.com/TheAlgorithms/Python/blob/master/maths/add.py
    - https://github.com/TheAlgorithms/Python/blob/master/maths/ceil.py (perhaps not so trivial)
Maybe the `add` should be deleted

**Comment by CaedenPH** [comment]
@cclauss Opinion?

**Comment by gillianomenezes** [comment]
hey @CaedenPH what do you mean by the "triviality requirements the algorithm must meet"? I would like to help with this issue.

**Comment by CaedenPH** [comment]
> hey @CaedenPH what do you mean by the "triviality requirements the algorithm must meet"? I would like to help with this issue.

Pull requests are being created with that are basic and unnecessary 
For example
```py
def subtract(a, b):
    return a-b
```
Unfortunately, I'm not entirely sure what the requirements would be or how to phrase them in an approachable manner.

**Comment by gillianomenezes** [comment]
@CaedenPH what do you think about this improvement? https://github.com/TheAlgorithms/Python/pull/7887
