### ISSUE TITLE
GitHub Actions Scheduled builds started in forked repo

### ISSUE THREAD

**Issue by Cjkjvfnby** [TheAlgorithms/Python#7996]
### Repository commit

7f1a5521f4b73d15df409a81f3da48427f9c6cdc

### Python version (python --version)

Python

### Dependencies version (pip freeze)

github.com

### Expected behavior

No scheduled builds after the fork.

### Actual behavior

![изображение](https://user-images.githubusercontent.com/171597/202897375-90a97bcf-cbb9-4b64-b730-90e932c925ee.png)

Build is run each day.   I have to disable the GitHub actions manually.   
https://github.com/orgs/community/discussions/26704

Looks like it could be partially solved by adding a flag.  Action will still run, but will exit fast. 
https://github.com/laravel/framework/issues/34356#issuecomment-692874445

Not sure if actions are enabled by default and how many repos we forked with this scheduled build.

**Comment by beuge8899** [comment]
cool

**Comment by dhruvmanila** [comment]
You can disable the actions from the repository settings: https://github.com/Cjkjvfnby/Python/settings/actions
