### ISSUE TITLE
A tailor-made contribution guide

### ISSUE THREAD

**Issue by poyea** [TheAlgorithms/Python#802]
I think we should write a Contribution Guide from which:
1. New comers know **how they can contribute**
2. Everyone know **what do the community, especially users and readers expect**
3. Most importantly, everyone learns about **the standard of code contribution**, like do we need testing in submission? Is it a strict requirement? Do we need comment description? Are one-liners acceptable? How to deal with "one-liner" alternatives?

I found #432 and #433 relating to this, but the commit concerned is not quite tailor-made to us and thus reading it will not help a newcomer to know points 2 and 3.

**Comment by AnupKumarPanwar** [comment]
@poyea I agree with you. I think we should cover the contribution standards in the README.md file. Check the [README](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/README.md) file of [Algorithms-Explaination](https://github.com/TheAlgorithms/Algorithms-Explanation) for reference.

**Comment by minddetox** [comment]
This would be helpful. i’m so eager to learn and not sure where to begin. thank you
