### ISSUE TITLE
Remove duplicate GCD implementation

### ISSUE THREAD

**Issue by tianyizheng02** [TheAlgorithms/Python#8063]
### Feature description

[`greatest_common_divisor.py`](https://github.com/TheAlgorithms/Python/blob/master/maths/greatest_common_divisor.py) and [`euclidean_gcd.py`](https://github.com/TheAlgorithms/Python/blob/master/maths/euclidean_gcd.py) both have basically the same two implementations of the Euclidean algorithm for calculating the GCD of 2 numbers. Thus, one of them should probably be removed as a duplicate.

**Comment by itsvinayak** [comment]
@cclauss which one we should keep

**Comment by ArhamaQ** [comment]
Hey, I am Arhama . I  am a beginner  in open source contribution. I think I  Can work on this issue. can you assign me this work.

**Comment by cclauss** [comment]
> can you assign me this work.

https://github.com/TheAlgorithms/Python/pull/8871/files

**Comment by HimanshuMahto** [comment]
Hey, is this still an issue to work on if yes can I do it

**Comment by tianyizheng02** [comment]
@HimanshuMahto Read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contribution).
> If you are interested in resolving an open issue, simply make a pull request with your proposed fix. **We do not assign issues in this repo** so please do not ask for permission to work on an issue.

**Comment by aryan1165** [comment]
Hey, I have created a PR #9108. Please review it. Thanks!
