### ISSUE TITLE
LCA (least common ancestor)

### ISSUE THREAD

**Issue by Erfaniaa** [TheAlgorithms/Python#813]
LCA is not present in graph algorithms.

**Comment by Reshad-Hasan** [comment]
It's in datastructure folder

**Comment by Erfaniaa** [comment]
Isn't it better to put it in the graph folder?

**Comment by Reshad-Hasan** [comment]
LCA works on tree and tree is non linear datastructure.

**Comment by constfun** [comment]
Binary tree LCA and dag LCA are different algorithms. Here's an OCaml implementation of the later https://github.com/mirage/irmin/blob/c275f0618e45b66b1d547b62aaa91a3a7d2ad68a/src/irmin/commit.ml#L413
