### ISSUE TITLE
[DOCS] Fix CI badge in the `README.md`

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Python#8132]
### Description

The CI badge on the `README.md` file is not showing up well due to an API change the badge managers did.
This must be fixed immediately. It is an easy fix, which you can contribute to! 🙂

_Steps to contribute_

1. [Fork the repository](https://github.com/TheAlgorithms/Python/fork).
2. Create a new branch named `fix_ci_badge`.
3. Open the `README.md` file.
4. In line 25, replace the **image URL** with the following content:

```markdown
https://img.shields.io/github/actions/workflow/status/TheAlgorithms/Python/build.yml?branch=master&label=CI&logo=github&style=flat-square
```

5. Commit and push your changes.
6. Create a [pull request](https://github.com/TheAlgorithms/Python/compare) to compare your changes.
7. You're done now! 🎉 You just have to wait until the maintainers review your PR.

If you need any help with this, let us know!

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by mehrdadbn9** [comment]
hi 
can you assign me 
i'm eager to do

**Comment by aysuqafarli** [comment]
Hi.I'm sorry. What do you mean?




Kind regards,

Aysu Gafarli.

**Comment by ratneshrt** [comment]
@Panquesito7 I have updated the PR description and created a new pull request.

**Comment by mehrdadbn9** [comment]
@Panquesito7 
hi why didn't you assign me for issue to have two different pull request (#8134 and #8136) and i miss the chance of contribution!?

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python#readme says that CI is failing when it is not.

**Comment by Panquesito7** [comment]
Not for me. 🤔

![image](https://github.com/TheAlgorithms/Python/assets/51391473/c9ab94cd-8116-455e-a1a9-e968fc5ffc54)

Also, this issue was that the CI badge wasn't displayed properly due to an API change.

**Comment by ArhamaQ** [comment]
Hi, can you assign me to this issue?

**Comment by cclauss** [comment]
@ArhamaQ We do not assign issues in this repo.  Instead, we review pull requests.  If you see something that needs fixing then please submit a pull request.  If multiple contributors submit pull requests for the same issue then it is almost always a learning experience.

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python#readme LGTM closing
