### ISSUE TITLE
Divide and Conquer

### ISSUE THREAD

**Issue by Erfaniaa** [TheAlgorithms/Python#817]
May we add a "divide and conquer" folder and add "closest pair of points" and "maximum sub-array" to it?
Also, we can add "meet in the middle" algorithms.

**Comment by siddharthjain1611** [comment]
I think that's a great idea.

**Comment by Dharni0607** [comment]
I would like work on this, if nobody has taken it up.

**Comment by Erfaniaa** [comment]
Please send me an email to discuss and start coding together.
erfan.aa@gmail.com

**Comment by RCtechBosco** [comment]
Together

















========================

Thank u for reading this mail ^_^

========================

Contact me :                                 

Phone : 186 0859 0013               

Wechat : 18608590013               

QQ : 22011136                              

Email : kerong.zhu@163.com

========================

On 07/02/2019 15:50, Erfan Alimohammadi wrote:

Please send me an email to discuss and start coding together.
erfan.aa@gmail.com
