### ISSUE TITLE
Fix broken links to Gitter Community

### ISSUE THREAD

**Issue by ChVeen** [TheAlgorithms/Python#8197]
### What would you like to share?

It seems that the link <https://gitter.im/TheAlgorithms> as used in the `README.md`  and `CONTRIBUTING.md` files is invalid.
I get the error `404 Not Found`.

**Comment by KaixLina** [comment]
it took me a while to find this issue  because ....the loc of the issue is not stated clearly in the above issue request .....i will try to find the sol....

**Comment by ChVeen** [comment]
Hi @KaixLina please note that this issue is already solved, see pull request #8546.
