### ISSUE TITLE
about mean_squared_error method of  machinelearning/Decision_Tree.py 

### ISSUE THREAD

**Issue by siberiafox** [TheAlgorithms/Python#835]
mean_squared_error(X[:i],np.mean(y[:i]))   Is the parameter wrong? 
should be :mean_squared_error(y[:i],np.mean(y[:i]))?
the first arg is true_labels,the second arg is prediction，right？

**Comment by poyea** [comment]
I guess yes. You may correct this by opening up a PR. Providing a small example will speed up the review process! Thanks.
