### ISSUE TITLE
New Algorithms required in Machine Learning

### ISSUE THREAD

**Issue by siddharthjain1611** [TheAlgorithms/Python#840]
Need to add polynomial regression, SVM, SVR, and other important algorithms.

**Comment by StephenGemin** [comment]
There will be multiple updates to follow.  I'd like to pool any regression analysis into a separate module.  It doesn't make sense to put these under machine learning as they are used outside of machine learning too.

**Comment by anand372** [comment]
is this still open i would like to  be assigned for implementing and posting of SVM's?

**Comment by cclauss** [comment]
You do not need to wait for assignment...  Just look though https://github.com/TheAlgorithms/Python/blob/master/DIRECTORY.md and if you see a hole then submit a pull request to fill it.

**Comment by cclauss** [comment]
@siddharthjain1611 What still needs to be done, or can this issue be closed?

**Comment by QuantumNovice** [comment]
#1609

**Comment by siddharthjain1611** [comment]
Yes we can close it.
