### ISSUE TITLE
Add algorithms like Sliding Window, Region Proposal Networks, or Kadane's Algorithm etc.

### ISSUE THREAD

**Issue by harshita130602** [TheAlgorithms/Python#8427]
### Feature description

While going through the repository, I could not find such algorithms. It would be a good idea to add them to the repository.

**Comment by cclauss** [comment]
I think RPN is still open...
- [x] https://github.com/search?q=repo%3ATheAlgorithms%2FPython%20Sliding
- [ ] https://en.wikipedia.org/wiki/Region_Based_Convolutional_Neural_Networks
- [x] https://github.com/search?q=repo%3ATheAlgorithms%2FPython%20Kadane

**Comment by rohan472000** [comment]
> ### Feature description
> While going through the repository, I could not find such algorithms. It would be a good idea to add them to the repository.

can i take this issue?

**Comment by cclauss** [comment]
We do not assign issues.  We review pull requests.

**Comment by rohan472000** [comment]
I'm getting below error while creating pull request.....why?

remote: Permission to TheAlgorithms/Python.git denied to rohan472000.
fatal: unable to access 'https://github.com/TheAlgorithms/Python.git/': The requested URL returned error: 403

**Comment by cclauss** [comment]
Remove the slash on the end and try again.

What command are you running when you get this error?  What is the full error message?

**Comment by rohan472000** [comment]
this i can see after above command

PS C:\pycharm\codes\Python-pull> git branch
  master
* rohan
PS C:\pycharm\codes\Python-pull> git remote -v
origin  https://github.com/TheAlgorithms/Python.git (fetch)
origin  https://github.com/TheAlgorithms/Python.git (push)

**Comment by cclauss** [comment]
This is how I do it...  My fork is `origin` and the main public repo is `upstream`.
% `git remote -v`
```
origin	https://github.com/cclauss/Python (fetch)
origin	https://github.com/cclauss/Python (push)
upstream	https://github.com/TheAlgorithms/Python (fetch)
upstream	https://github.com/TheAlgorithms/Python (push)
```
Like: https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet
Or: https://devguide.python.org/getting-started/git-boot-camp

**Comment by rohan472000** [comment]
PS C:\pycharm\codes\Python-pull> git pull upstream master
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by cclauss** [comment]
Check at least one of the checkboxes in the commit message.

**Comment by mahak-dev** [comment]
Hello 
I can solve this issue, How can I contribute ?

**Comment by rohan472000** [comment]
Is there any algorithm left? If yes then kindly tell, I would try to contribute.
