### ISSUE TITLE
There should be a directory.

### ISSUE THREAD

**Issue by huawenqing** [TheAlgorithms/Python#860]

**Comment by cclauss** [comment]
What does that mean?

**Comment by huawenqing** [comment]
> What does that mean?

An outline or navigation that is easy for the reader to find specific content， like this [https://github.com/scutan90/DeepLearning-500-questions]

**Comment by Ronkiro** [comment]
I think it's a good idea, as we this makes easier to search (CTRL + F) if the content isn't hidden on folders.

I think this Issue should be renamed, and the description should give more information about how it would change. This title doesn't attracts too many people, and it's a good idea.

**Comment by poyea** [comment]
Agree. Do you all have any ideas on how to make it? I mean, any automation tool available to us?

**Comment by poyea** [comment]
https://stackoverflow.com/questions/23989232/is-there-a-way-to-represent-a-directory-tree-in-a-github-readme-md
I've found this maybe helpful to us.

**Comment by NielXu** [comment]
#889 I made a pull request

**Comment by jai-dewani** [comment]
Some new files have been added so I have updated the same in DIRECTORY.md #1161
