### ISSUE TITLE
Refactor code so it's readable

### ISSUE THREAD

**Issue by Starmania** [TheAlgorithms/Python#8622]
### Feature description

I was exploring the git when I was reading this file: https://github.com/TheAlgorithms/Python/blob/f32d611689dc72bda67f1c4636ab1599c60d27a4/ciphers/mixed_keyword_cypher.py

The variable name are really sort, and it make difficulties to read... I think it could be cool if someone take the time to describe a little bit more the code...

**Comment by tianyizheng02** [comment]
The final print statement isn't enclosed in any `__main__` statement either, so that should be done too

**Comment by yanvoi** [comment]
My refactoring could be better but I hope it's gonna cut it.
