### ISSUE TITLE
Adding concepts from AC circuits

### ISSUE THREAD

**Issue by EngineerMarek** [TheAlgorithms/Python#8631]
### Feature description

How about adding algorithms from AC circuit analysis like **calculating apparent power from reactive and real power** in the electronics section? Is this something that is wanted? I would like to work on and add such things!

**Comment by rohan472000** [comment]
Yeah  nice idea...i will try to do that.

**Comment by rohan472000** [comment]
@cclauss , as I'm trying to write codes for AC circuits, where to make PR  for them, do we need to make a separate directory for that?

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/tree/master/electronics ?

**Comment by rohan472000** [comment]
@EngineerMarek I think above issue has been resolved , you can close this issue or anything left then please specify.
