### ISSUE TITLE
Suggestion / opinion needed: Add a line in the boolean_algebra/and_gate.py file

### ISSUE THREAD

**Issue by EngineerMarek** [TheAlgorithms/Python#8632]
### What would you like to share?

I want to suggest adding a line in the boolean_algebra/and_gate.py file and want to see what others think.

```
if __name__ == "__main__":
    print(and_gate(0, 0))
    print(and_gate(0, 1))
    print(and_gate(1, 1))
```
This is an excerpt from lines 45 - 48.

I want to suggest changing it to this:
```
if __name__ == "__main__":
    print(and_gate(0, 0))
    print(and_gate(0, 1))
    print(and_gate(1, 0))
    print(and_gate(1, 1))
```

adding `print(and_gate(1, 0))` completes all examples, and with the others being there, I don't see a reason why we shouldn't have that line also, especially because it is present in the tests. What do you guys think?

**Comment by tianyizheng02** [comment]
@ChrisO345 it should be good to close this now
