### ISSUE TITLE
Suggestion: Add a function call to the boolean_algebra/and_gate.py file.

### ISSUE THREAD

**Issue by code-dev05** [TheAlgorithms/Python#8656]
### What would you like to share?

In the lines 35 - 42, test_and_gate() function is defined.

```python
def test_and_gate() -> None:
    """
    Tests the and_gate function
    """
    assert and_gate(0, 0) == 0
    assert and_gate(0, 1) == 0
    assert and_gate(1, 0) == 0
    assert and_gate(1, 1) == 1
``` 

But it is never called during the entire run time of the program.
Therefore, I would suggest adding a function call ```test_and_gate()``` between lines 45 and 46 to first verify all assertions before any real output.

**Comment by Siddhesh-Agarwal** [comment]
Do you want to make `a and b` as a function?

```python
def and_gate(a: int, b: int) -> int:
    return a and b
```

**Comment by rohan472000** [comment]
@code-dev05 , kindly see PR #8690 .
