### ISSUE TITLE
2**32 being calculated multiple times

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [TheAlgorithms/Python#8686]
### What would you like to share?

In [this file](https://github.com/TheAlgorithms/Python/blob/master/hashes/md5.py) `2**32` is being calculated multiple times.

we can instead use a variable `MOD = 1 << 32` and save lots of compute time.

### Additional information

Bit shift is faster than multiplication in all languages.

**Comment by amirsoroush** [comment]
Not really... take a look at this:
```python
from timeit import timeit

n = 1_000_000
print(timeit("2**32", number=n))  # 0.009813362999921083
print(timeit("1<<32", number=n))  # 0.01045090799971149
```
I got one faster than the other in several runs but the difference is negligible.

**Comment by amirsoroush** [comment]
By the way, Python does something called "constant folding". When the script is complied, both expressions are replaced with `4294967296`.

**Comment by Siddhesh-Agarwal** [comment]
@amirsoroush In C++, the `<<` operator is significantly much faster but that doesn't seem to be the case in (newer versions of) Python. As you said, the error is indeed negligible. Thanks for the clarification.

**Comment by amirsoroush** [comment]
@Siddhesh-Agarwal You're right, It's faster in Python too. Sorry if my first comment was not so informative. I updated it with more details.

**Comment by Siddhesh-Agarwal** [comment]
@amirsoroush Does it mean that I can go ahead and change it?

**Comment by amirsoroush** [comment]
@Siddhesh-Agarwal I'm afraid not. The runtime is going to be the same anyway. In compile time Python will calculate `2**32` and use the result instead. So no matter if that expression is inside a for loop, Python uses the result of that. If the module is being imported, Python creates a `.pyc` file and for further run, it won't even compile that module again. The compilation step is done every time the module is executed as the main module though.

**Comment by amirsoroush** [comment]
@cclauss May I ask your opinion on that?

**Comment by cclauss** [comment]
Given that the operation can be done 5 million times in one second, I think that the most important question should be "Which will be easier for the reader to understand?"

**Comment by Siddhesh-Agarwal** [comment]
Thanks for the clarity on the topic @amirsoroush and @cclauss.
