### ISSUE TITLE
有没有大佬帮我看下我这串代码因为什么原因导致游戏开始,巨型子弹无法消灭精英怪问题

### ISSUE THREAD

**Issue by Xbjzjzjzjzjb** [TheAlgorithms/Python#8713]
### Repository commit

73105145090f0ce972f6fa29cc5d71f012dd8c92

### Python version (python --version)

python 3.11.2

### Dependencies version (pip freeze)

import pygame
import sys
import os
import random
from pygame.locals import *

# 初始化
pygame.init()
# 窗口设置
WIDTH, HEIGHT = 800, 600
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("坦克射击游戏")

# 玩家名字
PLAYER_NAME = "59tank" # 将 Your_Name 替换为您的名字

# 血条设置
HEALTH_BAR_WIDTH = 200
HEALTH_BAR_HEIGHT = 20
HEALTH_BAR_COLOR = (0, 255, 0)
HEALTH_BAR_BACKGROUND_COLOR = (255, 0, 0)
PLAYER_HEALTH = 100

# 颜色
WHITE = (255, 255, 255)
RED = (255, 0, 0)

# 坦克设置
TANK_WIDTH, TANK_HEIGHT = 120, 80
tank_image_path = os.path.join(os.path.dirname(__file__), "tank.png")  # 确保图像文件与代码文件在同一目录下
tank_image = pygame.image.load(tank_image_path)
tank_image = pygame.transform.scale(tank_image, (TANK_WIDTH, TANK_HEIGHT))

# 炮弹设置
BULLET_WIDTH, BULLET_HEIGHT = 5, 10
bullet_surface = pygame.Surface((BULLET_WIDTH, BULLET_HEIGHT))
bullet_surface.fill(RED)

# 巨型炮弹设置
GIANT_BULLET_WIDTH, GIANT_BULLET_HEIGHT = 15, 30
giant_bullet_surface = pygame.Surface((GIANT_BULLET_WIDTH, GIANT_BULLET_HEIGHT))
giant_bullet_surface.fill((255, 0, 255))
# 杀伤范围
ELLIPSE_RADIUS_X = 150
ELLIPSE_RADIUS_Y = 120

# 敌人设置
ENEMY_WIDTH, ENEMY_HEIGHT = 40, 40
ENEMY_COLOR = (255, 0, 0)

# 精英怪设置
ELITE_ENEMY_WIDTH, ELITE_ENEMY_HEIGHT = 250, 260
elite_enemy_image_path = os.path.join(os.path.dirname(__file__), "elite_enemy.png")  # 确保 elite_enemy.png 图像文件与代码文件在同一目录下
elite_enemy_image = pygame.image.load(elite_enemy_image_path)
elite_enemy_image = pygame.transform.scale(elite_enemy_image, (ELITE_ENEMY_WIDTH, ELITE_ENEMY_HEIGHT))

ELITE_ENEMY_BULLET_WIDTH, ELITE_ENEMY_BULLET_HEIGHT = 10, 20
elite_enemy_bullet_surface = pygame.Surface((ELITE_ENEMY_BULLET_WIDTH, ELITE_ENEMY_BULLET_HEIGHT))
elite_enemy_bullet_surface.fill((0, 255, 255))

ELITE_ENEMY_SPAWN_INTERVAL = 180
ELITE_ENEMY_SPEED = 3
ELITE_ENEMY_BULLET_SPEED = 6
ELITE_ENEMY_HEALTH = 1

# 游戏速度
FPS = 60
clock = pygame.time.Clock()

# 坦克位置
tank_x, tank_y = (WIDTH - TANK_WIDTH) // 2, HEIGHT - TANK_HEIGHT

# 背景移动速度
BG_SPEED = 5

# 坦克移动速度
TANK_SPEED = 5

# 炮弹移动速度
BULLET_SPEED = 10
GIANT_BULLET_SPEED = 8

# 敌人移动速度
ENEMY_SPEED = 3

# 活动对象列表
active_bullets = []
active_giant_bullets = []
active_enemies = []
active_elite_enemies = []
active_elite_enemy_bullets = []
active_other_objects = []

# 屏幕震动持续时间
screen_shake_duration = 0

# 敌人生成间隔
ENEMY_SPAWN_INTERVAL = 60

# 精英怪函数
def spawn_elite_enemy():
    elite_enemy_x = random.randint(0, WIDTH - ELITE_ENEMY_WIDTH)
    elite_enemy_y = -ELITE_ENEMY_HEIGHT
    active_elite_enemies.append((elite_enemy_x, elite_enemy_y))

# 巨型炮弹范围判断
def is_inside_ellipse(x, y, ellipse_center_x, ellipse_center_y, radius_x, radius_y):
    return ((x - ellipse_center_x) ** 2) / (radius_x ** 2) + ((y - ellipse_center_y) ** 2) / (radius_y ** 2) <= 1

def draw_health_bar_and_player_name(screen, health, player_name):
    # 绘制血条
    health_percentage = health / PLAYER_HEALTH
    health_bar_width = int(HEALTH_BAR_WIDTH * health_percentage)
    pygame.draw.rect(screen, HEALTH_BAR_BACKGROUND_COLOR, (10, 10, HEALTH_BAR_WIDTH, HEALTH_BAR_HEIGHT))
    pygame.draw.rect(screen, HEALTH_BAR_COLOR, (10, 10, health_bar_width, HEALTH_BAR_HEIGHT))

    # 绘制玩家名字
    font = pygame.font.Font(None, 24)
    player_name_surface = font.render(player_name, True, (0, 0, 0))
    screen.blit(player_name_surface, (10, HEALTH_BAR_HEIGHT + 15))

def rects_intersect(x1, y1, w1, h1, x2, y2, w2, h2):
    return (x1 < x2 + w2 and x1 + w1 > x2 and
            y1 < y2 + h2 and y1 + h1 > y2)

def shake_screen():
    shake_amount = 5  # 震动幅度
    return (random.randint(-shake_amount, shake_amount),
            random.randint(-shake_amount, shake_amount))

def draw_background(y_offset):
    screen.fill(WHITE)
    pygame.draw.rect(screen, (128, 128, 128), (0, y_offset, WIDTH, HEIGHT // 2))
    pygame.draw.rect(screen, (128, 128, 128), (0, y_offset + HEIGHT // 2 + 1, WIDTH, HEIGHT // 2))

def spawn_enemy():
    enemy_x = random.randint(0, WIDTH - ENEMY_WIDTH)
    enemy_y = -ENEMY_HEIGHT
    active_enemies.append((enemy_x, enemy_y))
# 敌人数量
MAX_ENEMIES_ON_SCREEN = 10

def update_enemies():
    global active_enemies, active_elite_enemies, active_elite_enemy_bullets   
    new_enemies = []
    for enemy_x, enemy_y in active_enemies:
        enemy_y += ENEMY_SPEED
        if enemy_y < HEIGHT:  # 保留仍在屏幕范围内的敌人
            new_enemies.append((enemy_x, enemy_y))
    active_enemies = new_enemies

    # 如果当前敌人数量少于最大敌人数量，生成新敌人
    if len(active_enemies) < MAX_ENEMIES_ON_SCREEN:
        spawn_enemy()
    # 精英怪逻辑
    new_elite_enemies = []
    for elite_enemy_x, elite_enemy_y in active_elite_enemies:
        elite_enemy_y += ELITE_ENEMY_SPEED
        if elite_enemy_y < HEIGHT:  # 保留仍在屏幕范围内的精英怪
            new_elite_enemies.append((elite_enemy_x, elite_enemy_y))
            # 精英怪射击逻辑
            if random.random() < 0.01:
                elite_enemy_bullet_x = elite_enemy_x + ELITE_ENEMY_WIDTH // 2 - ELITE_ENEMY_BULLET_WIDTH // 2
                elite_enemy_bullet_y = elite_enemy_y + ELITE_ENEMY_HEIGHT
                active_elite_enemy_bullets.append((elite_enemy_bullet_x, elite_enemy_bullet_y))
    active_elite_enemies = new_elite_enemies

    if len(active_elite_enemies) == 0 and pygame.time.get_ticks() % ELITE_ENEMY_SPAWN_INTERVAL == 0:
        spawn_elite_enemy()
# 精英怪和子弹函数
def draw_elite_enemies(screen):
    for elite_enemy_x, elite_enemy_y in active_elite_enemies:
        screen.blit(elite_enemy_image, (elite_enemy_x, elite_enemy_y))

def draw_elite_enemy_bullets(screen):
    for elite_enemy_bullet_x, elite_enemy_bullet_y in active_elite_enemy_bullets:
        screen.blit(elite_enemy_bullet_surface, (elite_enemy_bullet_x, elite_enemy_bullet_y))
        
def draw_enemies(screen):
    for enemy_x, enemy_y in active_enemies:
        pygame.draw.rect(screen, ENEMY_COLOR, (enemy_x, enemy_y, ENEMY_WIDTH, ENEMY_HEIGHT))

def handle_input():
    global tank_x, tank_y, active_bullets, active_giant_bullets
    keys = pygame.key.get_pressed()
    if keys[K_LEFT]:
        tank_x -= TANK_SPEED
    if keys[K_RIGHT]:
        tank_x += TANK_SPEED
    if keys[K_UP]:
        tank_y -= TANK_SPEED
    if keys[K_DOWN]:
        tank_y += TANK_SPEED
    # 限制坦克在屏幕范围内移动
    tank_x = max(0, min(WIDTH - TANK_WIDTH, tank_x))
    tank_y = max(0, min(HEIGHT - TANK_HEIGHT, tank_y))

def update_bullets():
    global active_bullets, active_giant_bullets, active_elite_enemy_bullets
    new_bullets = []
    new_giant_bullets = []
    for bullet_x, bullet_y in active_bullets:
        bullet_y -= BULLET_SPEED
        if bullet_y > -BULLET_HEIGHT:
            new_bullets.append((bullet_x, bullet_y))
    for giant_bullet_x, giant_bullet_y in active_giant_bullets:
        giant_bullet_y -= GIANT_BULLET_SPEED
        if giant_bullet_y > -GIANT_BULLET_HEIGHT:
            new_giant_bullets.append((giant_bullet_x, giant_bullet_y))
    active_bullets = new_bullets
    active_giant_bullets = new_giant_bullets
    new_elite_enemy_bullets = []
    for elite_enemy_bullet_x, elite_enemy_bullet_y in active_elite_enemy_bullets:
        elite_enemy_bullet_y += ELITE_ENEMY_BULLET_SPEED
        if elite_enemy_bullet_y < HEIGHT:
            new_elite_enemy_bullets.append((elite_enemy_bullet_x, elite_enemy_bullet_y))
    active_elite_enemy_bullets = new_elite_enemy_bullets

def check_collision():
    global active_bullets, active_giant_bullets, active_other_objects, active_enemies, active_elite_enemies, screen_shake_duration, elite_enemy_x, elite_enemy_y, ELITE_ENEMY_HEALTH
    new_enemies = []
    new_bullets = []
    new_giant_bullets = []

    for elite_enemy_x, elite_enemy_y in active_elite_enemies:
        for bullet_x, bullet_y in active_bullets:
            if rects_intersect(bullet_x, bullet_y, BULLET_WIDTH, BULLET_HEIGHT, elite_enemy_x, elite_enemy_y, ELITE_ENEMY_WIDTH, ELITE_ENEMY_HEIGHT):
                ELITE_ENEMY_HEALTH -= 1
                active_bullets.remove((bullet_x, bullet_y))
                if ELITE_ENEMY_HEALTH <= 0:
                    active_elite_enemies.remove((elite_enemy_x, elite_enemy_y))
                    elite_enemy_defeated_x, elite_enemy_defeated_y = elite_enemy_x, elite_enemy_y
    
    # 假设其他对象的宽度和高度
    OTHER_OBJECT_WIDTH = 50
    OTHER_OBJECT_HEIGHT = 50

    # 检测巨型炮弹与精英怪的碰撞
    to_remove_giant_bullets = []
    to_remove_elite_enemies = []
    to_remove_other_objects = []

    for giant_bullet_x, giant_bullet_y in active_giant_bullets:
        giant_bullet_hit = False  # 初始化为未击中状态
        for elite_enemy in active_elite_enemies:
            elite_enemy_x, elite_enemy_y = elite_enemy

            # 如果巨型炮弹与精英怪物发生碰撞
            if rects_intersect(giant_bullet_x, giant_bullet_y, GIANT_BULLET_WIDTH, GIANT_BULLET_HEIGHT, elite_enemy_x, elite_enemy_y, ELITE_ENEMY_WIDTH, ELITE_ENEMY_HEIGHT):
                giant_bullet_hit = True
                to_remove_giant_bullets.append((giant_bullet_x, giant_bullet_y))
                break  # 跳出内层循环，不再检测其他精英怪物

        # 如果巨型炮弹击中了目标，则触发椭圆范围内的爆炸
        if giant_bullet_hit:
            for elite_enemy in active_elite_enemies:
                elite_enemy_x, elite_enemy_y = elite_enemy
                giant_bullet_center_x = giant_bullet_x + GIANT_BULLET_WIDTH / 2
                giant_bullet_center_y = giant_bullet_y + GIANT_BULLET_HEIGHT / 2

                # 检查是否在椭圆范围内
                if is_inside_ellipse(elite_enemy_x, elite_enemy_y, giant_bullet_center_x, giant_bullet_center_y, ELLIPSE_RADIUS_X, ELLIPSE_RADIUS_Y):
                    ELITE_ENEMY_HEALTH -= 1
                if ELITE_ENEMY_HEALTH <= 0:
                    to_remove_elite_enemies.append(elite_enemy)
                    break  # 跳出内层循环，继续检测下一个精英怪物
            # 检测与普通敌人（enemy）的碰撞
            to_remove_enemies = []
            for enemy in active_enemies:
                enemy_x, enemy_y = enemy

            # 检查普通敌人（enemy）是否在椭圆范围内
                if is_inside_ellipse(enemy_x, enemy_y, giant_bullet_center_x, giant_bullet_center_y, ELLIPSE_RADIUS_X, ELLIPSE_RADIUS_Y):
                    to_remove_enemies.append(enemy)

            # 从原列表中移除待移除的普通敌人（enemies）
            for enemy in to_remove_enemies:
                active_enemies.remove(enemy)

            # 检测与其他对象的碰撞
            for other_object in active_other_objects:
                other_object_x, other_object_y = other_object

                # 检查其他对象是否在椭圆范围内
                if is_inside_ellipse(other_object_x, other_object_y, giant_bullet_center_x, giant_bullet_center_y, ELLIPSE_RADIUS_X, ELLIPSE_RADIUS_Y):
                    to_remove_other_objects.append(other_object)

    # 从原列表中移除待移除的巨型炮弹、精英怪和其他对象
    for giant_bullet in to_remove_giant_bullets:
        active_giant_bullets.remove(giant_bullet)  # 确保此行完整
    for elite_enemy in to_remove_elite_enemies:
        active_elite_enemies.remove(elite_enemy)
    for other_object in to_remove_other_objects:
        active_other_objects.remove(other_object)
    
    for enemy_x, enemy_y in active_enemies:
        enemy_hit = False
        for bullet_x, bullet_y in active_bullets:
            if rects_intersect(bullet_x, bullet_y, BULLET_WIDTH, BULLET_HEIGHT, enemy_x, enemy_y, ENEMY_WIDTH, ENEMY_HEIGHT):
                enemy_hit = True
                active_bullets.remove((bullet_x, bullet_y))
        if not enemy_hit:
            new_enemies.append((enemy_x, enemy_y))

        new_bullets = [(bullet_x, bullet_y) for bullet_x, bullet_y in active_bullets
                       if not any(rects_intersect(bullet_x, bullet_y, BULLET_WIDTH, BULLET_HEIGHT, enemy_x, enemy_y, ENEMY_WIDTH, ENEMY_HEIGHT)
                                  for enemy_x, enemy_y in active_enemies)]
    for giant_bullet_x, giant_bullet_y in active_giant_bullets:
        giant_bullet_hit = False
        for enemy_x, enemy_y in new_enemies:
            if rects_intersect(giant_bullet_x, giant_bullet_y, GIANT_BULLET_WIDTH, GIANT_BULLET_HEIGHT, enemy_x, enemy_y, ENEMY_WIDTH, ENEMY_HEIGHT):
                giant_bullet_hit = True
                break
        if giant_bullet_hit:
            active_giant_bullets.remove((giant_bullet_x, giant_bullet_y))
            screen_shake_duration = 10
            new_enemies = [enemy for enemy in new_enemies if not is_inside_ellipse(enemy[0] + ENEMY_WIDTH / 2, enemy[1] + ENEMY_HEIGHT / 2, giant_bullet_x + GIANT_BULLET_WIDTH / 2, giant_bullet_y + GIANT_BULLET_HEIGHT / 2, ELLIPSE_RADIUS_X, ELLIPSE_RADIUS_Y)]
        else:
            new_giant_bullets.append((giant_bullet_x, giant_bullet_y))
    active_enemies = new_enemies
    active_bullets = new_bullets
    active_giant_bullets = new_giant_bullets
#胜利消息
def display_win_message(x, y):
    win_font = pygame.font.Font(None, 36)
    win_text = win_font.render("WIN!", True, (0, 255, 0))
    screen.blit(win_text, (x, y))

def main():
    global tank_x, tank_y, active_bullets, active_giant_bullets, screen_shake_duration
    running = True
    y_offset = 0
    enemy_spawn_time = 0
    elite_enemy_defeated = False
    elite_enemy_defeated_x, elite_enemy_defeated_y = -1, -1
    while running:
        check_collision()
        for event in pygame.event.get():
            if event.type == QUIT:
                running = False
            if elite_enemy_defeated_x != -1 and elite_enemy_defeated_y != -1:
                display_win_message(elite_enemy_defeated_x, elite_enemy_defeated_y)
            if event.type == KEYDOWN:
                if event.key == K_SPACE:
                    bullet_x, bullet_y = tank_x + TANK_WIDTH // 2 - BULLET_WIDTH // 2, tank_y
                    active_bullets.append((bullet_x, bullet_y))
                if event.key == K_RETURN:
                    giant_bullet_x, giant_bullet_y = tank_x + TANK_WIDTH // 2 - GIANT_BULLET_WIDTH // 2, tank_y
                    active_giant_bullets.append((giant_bullet_x, giant_bullet_y))

        handle_input()
        update_bullets()
        update_enemies()
        check_collision()

        draw_background(y_offset)
        screen.blit(tank_image, (tank_x, tank_y))

        draw_enemies(screen)
        draw_elite_enemies(screen)
        draw_elite_enemy_bullets(screen)

        for bullet_x, bullet_y in active_bullets:
            screen.blit(bullet_surface, (bullet_x, bullet_y))
        for giant_bullet_x, giant_bullet_y in active_giant_bullets:
            screen.blit(giant_bullet_surface, (giant_bullet_x, giant_bullet_y))
        if elite_enemy_defeated:
            display_win_message(elite_enemy_rect.x, elite_enemy_rect.y)

        y_offset += BG_SPEED
        if y_offset >= HEIGHT // 2:
            y_offset = 0

        if screen_shake_duration > 0:
            screen_shake_duration -= 1
            screen_shake_offset = shake_screen()
            screen.scroll(screen_shake_offset[0], screen_shake_offset[1])
            
        draw_health_bar_and_player_name(screen, PLAYER_HEALTH, PLAYER_NAME)
       
        pygame.display.update()
        clock.tick(FPS)
        
    pygame.quit()
    sys.exit()

if __name__ == "__main__":
    main()

### Expected behavior

解决游戏开始,巨型子弹无法消灭精英怪问题.还有消灭精英怪后原地不显示win问题.
很简单的需求,很简单的代码.

### Actual behavior

代码在游戏开始,巨型子弹无法消灭精英怪问题.还有消灭精英怪后原地不显示win问题.

**Comment by Xbjzjzjzjzjb** [comment]
这么简单的问题都没人会吗?

**Comment by tianyizheng02** [comment]
> 有没有大佬帮我看下我这串代码因为什么原因导致游戏开始,巨型子弹无法消灭精英怪问题
> Is there anyone who can help me see why my code is causing the game to start and why the giant bullets can't kill the elite enemies

> 这么简单的问题都没人会吗?
> Nobody can answer such a simple question?

What does this code have to do with this repository? Also, if this question is so simple, then why not figure it out yourself?
