### ISSUE TITLE
Ruff fails my pull request despite the issue not being my code

### ISSUE THREAD

**Issue by imengus** [TheAlgorithms/Python#8723]
### What would you like to share?

https://github.com/TheAlgorithms/Python/actions/runs/4960833192/jobs/8876852733?pr=8722

"maths/euclidean_distance.py:9:13: UP007 Use `X | Y` for type annotations"

**Comment by cclauss** [comment]
@dhruvmanila Can you please suggest fixes?

**Comment by ValentinKlinger** [comment]
I've got the same problem and when I solve it, the others test get errors

**Comment by dhruvmanila** [comment]
I don't see any problem here. `ruff` is suggesting some autofixes which should be applied.

> I've got the same problem and when I solve it, the others test get errors

What errors? Please provide details in the issue.
