### ISSUE TITLE
Duplicate solutions for postfix notation evaluation.

### ISSUE THREAD

**Issue by amirsoroush** [TheAlgorithms/Python#8724]
### Feature description

Hi,
I noticed there are two files for evaluating postfix notation which are:

1. [...stacks/evaluate_postfix_notations.py](https://github.com/TheAlgorithms/Python/blob/master/data_structures/stacks/evaluate_postfix_notations.py)
2. [...stacks/postfix_evaluation.py](https://github.com/TheAlgorithms/Python/blob/master/data_structures/stacks/postfix_evaluation.py)

The latter has bunch of print statements explaining the steps which is pretty useful for educational purposes but not in production. (It can be changed to have a `verbose=True` parameter for prints for example.)

Is having these two files intentional or we should combine them?

**Comment by tianyizheng02** [comment]
I highly doubt that having two files was intentional, especially since their algorithms appear to be basically identical. My guess is that a duplicate implementation was unknowingly approved and merged. Personally, I'm in favor of merging the two implementations into a single file.

**Comment by arijitde92** [comment]
Hi @amirsoroush @tianyizheng02 ,

I rectified this issue and #8754 in PR #8787.

Could you please review the PR and let me know if there is anything else that needs to be done?

Thanks
