### ISSUE TITLE
Making binary tree traversals lazy.

### ISSUE THREAD

**Issue by amirsoroush** [TheAlgorithms/Python#8725]
### Feature description

Hi,
In [binary_tree_traversals.py](https://github.com/TheAlgorithms/Python/blob/master/data_structures/binary_tree/binary_tree_traversals.py) file, there are different kinds of traversals such as `preorder`, `inorder`, `postorder` and etc.

Although the implementations are pretty clean one-liner like:
```python
# preorder
return [root.data, *preorder(root.left), *preorder(root.right)] if root else []
```
It isn't memory friendly. We can use generators instead not to load all the nodes into the memory:

```python
# preorder
    if not root:
        return []
    yield root.data
    yield from preorder(root.left)
    yield from preorder(root.right)
```
Shall we go ahead and change them?

**Comment by spam-1008** [comment]
+1

**Comment by rohan472000** [comment]
Absolutely, it's a great idea to switch from list-based traversals to generator-based traversals in the `binary_tree_traversals.py` file. Using generators instead of lists will indeed make the traversals more memory-friendly, especially for large trees.

**Comment by digital-dev-07** [comment]
@amirsoroush  Please assign this task to me.

**Comment by tianyizheng02** [comment]
@digital-dev-07 Read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contribution).
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
