### ISSUE TITLE
Put issue numbers in PR description, not in PR title

### ISSUE THREAD

**Issue by tianyizheng02** [TheAlgorithms/Python#8735]
### Feature description

Currently the PR template includes the following checklist item:

> If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

I think it's better to ask contributors to put issue numbers in the PR description rather than the commit message for the following reasons:

1. The vast majority of contributors to this repo (myself included) don't put closing keywords in commit messages. In my experience, the norm on GitHub is to put them in the PR description.
2. Since contributors typically make their commits in their local git repos and not directly on GitHub, it's less convenient to include the issue number because git can't autocomplete GitHub issue numbers.
3. A PR that resolves an issue often includes multiple commits, so no single commit single-handedly resolves the issue. Thus, putting the issue number in the PR description makes more sense IMO.
4. From the [GitHub docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue):

    > You can also use closing keywords in a commit message. The issue will be closed when you merge the commit into the default branch, but the pull request that contains the commit will not be listed as a linked pull request.

    Therefore, even if one puts the issue number with a closing keyword in a commit, GitHub won't automatically link the PR that it's a part of, which makes it slightly harder to refer back to the original issue.

We can also link to the GitHub docs (see above) in the checklist item to help contributors use the closing keywords correctly.

**Comment by tianyizheng02** [comment]
@dhruvmanila @cclauss What do you think?

**Comment by cclauss** [comment]
I agree.  I find is difficult to read pull request titles like:
* https://github.com/TheAlgorithms/Python/pull/8752
* https://github.com/TheAlgorithms/Python/pull/8758
* https://github.com/TheAlgorithms/Python/pull/8738
* https://github.com/TheAlgorithms/Python/pull/8730
* https://github.com/TheAlgorithms/Python/pull/8674
* https://github.com/TheAlgorithms/Python/pull/8137

**Comment by dhruvmanila** [comment]
Yeah I agree. Although I'm not sure how to enforce it. We could add it in Contributing Guidelines but vast majority of contributors won't be reading it. There's a check in the PR description to add any closing keywords if the PR is addressing an issue. Any suggestions?

**Comment by tianyizheng02** [comment]
@dhruvmanila I think it's still best to add it to the contributing guidelines for the few contributors who do read it (and those who don't read it won't be able to feign ignorance). As for the PR check, I think we could clarify the wording to emphasize where to put the issue number:

- [ ] If this pull request resolves one or more open issues then ~~the commit message contains Fixes: `#{$ISSUE_NO}`.~~ **I have included the issue number with a [closing keyword ](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) in the description: "Fixes #ISSUE-NUMBER"**

or something like this.

To address what @cclauss brought up, we might want to emphasize (both in the contributing docs and the PR checklist) that PRs should have descriptive titles.

**Comment by tianyizheng02** [comment]
As for enforcement, maybe we could have the algorithms-keeper bot check the PR description for an issue number and closing keyword if the contributor checked the "resolves an issue" checkbox? I'm not sure how exactly that'd be implemented. Other than that, I think it'd have to be enforced on a case-by-case basis.

**Comment by cclauss** [comment]
I changed the title of this issue because a `commit message` can be multiple lines.  In this case, the first line is the pull request title and the remaining lines are the pull request's body (or description).  We want the issue #number in the body, not in the title so that it is clickable.
