### ISSUE TITLE
mypy syntax error in maths/gcd_of_n_numbers

### ISSUE THREAD

**Issue by JadeKim042386** [TheAlgorithms/Python#8795]
### Repository commit

3a9e5fa5

### Python version (python --version)

Python 3.10.9

### Dependencies version (pip freeze)

<details close>
<summary> Dependencies </summary>
appnope @ file:///home/conda/feedstock_root/build_artifacts/appnope_1649077682618/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
boltons @ file:///home/conda/feedstock_root/build_artifacts/boltons_1677499911949/work
Bottleneck @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_07078715-3ab7-4562-8d3d-d56b0eaa0f7dp504n_ny/croots/recipe/bottleneck_1657175566567/work
brotlipy==0.7.0
certifi @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_5c4sjwommo/croot/certifi_1683875376620/work/certifi
cffi @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_ab19r4bji3/croot/cffi_1670423206034/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
conda==23.3.1
conda-content-trust @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_11146a2b-93c2-444c-a378-ad4fac363e991s0r1hnp/croots/recipe/conda-content-trust_1658126383571/work
conda-package-handling @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_5f3f459f9v/croot/conda-package-handling_1672865025324/work
conda_package_streaming @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_58gpsa_6af/croot/conda-package-streaming_1670508144037/work
cryptography @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_8c_qoky_1b/croot/cryptography_1673298759921/work
debugpy @ file:///Users/ktietz/ci_310/debugpy_1643965577625/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
idna @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_771olrhiqw/croot/idna_1666125579282/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1682176699712/work
ipykernel @ file:///Users/runner/miniforge3/conda-bld/ipykernel_1655369698656/work
ipython @ file:///Users/runner/miniforge3/conda-bld/ipython_1683226209954/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
jsonpatch @ file:///home/conda/feedstock_root/build_artifacts/jsonpatch_1632759296524/work
jsonpointer==2.0
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1681432441054/work
jupyter_core @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_d1sy1hlz9t/croot/jupyter_core_1679906585151/work
lxml @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_bbjv2ox7t8/croot/lxml_1679646469466/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mypy==1.3.0
mypy-extensions==1.0.0
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
numexpr @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_76yyu1p9jk/croot/numexpr_1683221830860/work
numpy @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_f9f5xs2fx0/croot/numpy_and_numpy_base_1682520577456/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas==1.5.3
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1667297516076/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
pip==22.3.1
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1683850015520/work
pluggy @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_croot-w6jyveby/pluggy_1648109277227/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1677600924538/work
psutil @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_1310b568-21f4-4cb0-b0e3-2f3d31e39728k9coaga5/croots/recipe/psutil_1656431280844/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pycosat @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_e9xhel3kyj/croot/pycosat_1666805516297/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1681904169130/work
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
PySocks @ file:///Users/ktietz/ci_310/pysocks_1643961536721/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_c56ru3yml9/croot/pytz_1671697451306/work
pyzmq @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_a7d9jpero7/croot/pyzmq_1682697648735/work
requests @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_b15e28ca-768e-4951-b4c6-8a7476e43183hrjpnkg9/croots/recipe/requests_1657734638595/work
ruamel.yaml @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_aeh5mqcw49/croot/ruamel.yaml_1666304555976/work
ruamel.yaml.clib @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_f64xdg2rww/croot/ruamel.yaml.clib_1666302244208/work
ruff==0.0.270
setuptools==65.6.3
six @ file:///tmp/build/80754af9/six_1644875935023/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
tomli==2.0.1
toolz @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_362wyqvvgy/croot/toolz_1667464079070/work
tornado @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_a61b4xoie9/croots/recipe/tornado_1662061692951/work
tqdm @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_637jfu39ar/croots/recipe/tqdm_1664392693982/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1678559861143/work
urllib3 @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_8fvc4z_gis/croot/urllib3_1673575619550/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
wheel==0.37.1
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1677313463193/work
zstandard @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_99wz2rcox4/croots/recipe/zstandard_1663827384884/work
</details>

### Expected behavior

i need to solve mypy error.

### Actual behavior

i tried `pre-commit run --all-files --show-diff-on-failure` and result is below

```
check that executables have shebangs.....................................Passed
check toml...............................................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
fix requirements.txt.....................................................Passed
auto-walrus..............................................................Passed
ruff.....................................................................Passed
black....................................................................Passed
codespell................................................................Passed
pyproject-fmt............................................................Passed
Validate filenames.......................................................Passed
Validate pyproject.toml..................................................Passed
mypy.....................................................................Passed
❯ pre-commit run --all-files --show-diff-on-failure
check that executables have shebangs.....................................Passed
check toml...............................................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
fix requirements.txt.....................................................Passed
auto-walrus..............................................................Passed
ruff.....................................................................Passed
black....................................................................Passed
codespell................................................................Passed
pyproject-fmt............................................................Passed
Validate filenames.......................................................Passed
Validate pyproject.toml..................................................Passed
mypy.....................................................................Passed
❯ git reset --hard 3a9e5fa5
HEAD is now at 3a9e5fa5 Create a Simultaneous Equation Solver Algorithm (#8773)
❯ pre-commit run --all-files --show-diff-on-failure
check that executables have shebangs.....................................Passed
check toml...............................................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
fix requirements.txt.....................................................Passed
auto-walrus..............................................................Passed
ruff.....................................................................Passed
black....................................................................Passed
codespell................................................................Passed
pyproject-fmt............................................................Passed
Validate filenames.......................................................Passed
Validate pyproject.toml..................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 2

maths/gcd_of_n_numbers.py:38: error: invalid syntax  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```

`maths/gcd_of_n_numbers.py:38` is `match-case` statement.

**Comment by JadeKim042386** [comment]
i modified type hint of get_factors but got the ruff error
```python
from typing import Optional
def get_factors(
    number: int, factors: Optional[Counter] = None, factor: int = 2
) -> Counter:
```
maths/gcd_of_n_numbers.py:11:27: UP007 [*] Use `X | Y` for type annotations
   |
11 | def get_factors(
12 |     number: int, factors: Optional[Counter] = None, factor: int = 2
   |                           ^^^^^^^^^^^^^^^^^ UP007
13 | ) -> Counter:
14 |     """
   |
   = help: Convert to `X | Y`

Found 1 error.
```

**Comment by JadeKim042386** [comment]
```
project_euler/problem_074/sol1.py:74: error: X | Y syntax for unions requires Python 3.10  [syntax]
maths/gcd_of_n_numbers.py:10: error: X | Y syntax for unions requires Python 3.10  [syntax]
maths/decimal_to_fraction.py:1: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/hashing/hash_map.py:18: error: No overload variant of "dataclass" matches argument types "bool", "bool"  [call-overload]
data_structures/hashing/hash_map.py:18: note: Possible overload variants:
data_structures/hashing/hash_map.py:18: note:     def dataclass(None, /) -> Callable[[Type[_T]], Type[_T]]
data_structures/hashing/hash_map.py:18: note:     def [_T] dataclass(Type[_T], /) -> Type[_T]
data_structures/hashing/hash_map.py:18: note:     def dataclass(*, init: bool = ..., repr: bool = ..., eq: bool = ..., order: bool = ..., unsafe_hash: bool = ..., frozen: bool = ...) -> Callable[[Type[_T]], Type[_T]]
data_structures/hashing/hash_map.py:44: error: X | Y syntax for unions requires Python 3.10  [syntax]
project_euler/problem_101/sol1.py:48: error: Type expected within [...]  [misc]
project_euler/problem_101/sol1.py:48: error: Invalid type alias: expression is not a valid type  [valid-type]
project_euler/problem_101/sol1.py:48: error: Value of type "Type[List[Any]]" is not indexable  [index]
project_euler/problem_101/sol1.py:48: error: Unsupported left operand type for | ("Type[float]")  [operator]
project_euler/problem_101/sol1.py:51: error: Variable "project_euler.problem_101.sol1.Matrix" is not valid as a type  [valid-type]
project_euler/problem_101/sol1.py:51: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
project_euler/problem_101/sol1.py:63: error: Variable "project_euler.problem_101.sol1.Matrix" is not valid as a type  [valid-type]
project_euler/problem_101/sol1.py:63: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
project_euler/problem_101/sol1.py:73: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:75: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:81: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:84: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:88: error: Unsupported target for indexed assignment (Matrix?)  [index]
project_euler/problem_101/sol1.py:88: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:91: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:92: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:94: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:102: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:104: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:108: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:130: error: Variable "project_euler.problem_101.sol1.Matrix" is not valid as a type  [valid-type]
project_euler/problem_101/sol1.py:130: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
project_euler/problem_101/sol1.py:131: error: Variable "project_euler.problem_101.sol1.Matrix" is not valid as a type  [valid-type]
project_euler/problem_101/sol1.py:131: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
project_euler/problem_101/sol1.py:132: error: Variable "project_euler.problem_101.sol1.Matrix" is not valid as a type  [valid-type]
project_euler/problem_101/sol1.py:132: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
project_euler/problem_101/sol1.py:139: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:140: error: Value of type Matrix? is not indexable  [index]
project_euler/problem_101/sol1.py:156: error: Value of type Matrix? is not indexable  [index]
physics/grahams_law.py:42: error: X | Y syntax for unions requires Python 3.10  [syntax]
physics/grahams_law.py:69: error: X | Y syntax for unions requires Python 3.10  [syntax]
physics/grahams_law.py:105: error: X | Y syntax for unions requires Python 3.10  [syntax]
physics/grahams_law.py:141: error: X | Y syntax for unions requires Python 3.10  [syntax]
physics/grahams_law.py:177: error: X | Y syntax for unions requires Python 3.10  [syntax]
machine_learning/self_organizing_map.py:24: error: X | Y syntax for unions requires Python 3.10  [syntax]
machine_learning/self_organizing_map.py:25: error: X | Y syntax for unions requires Python 3.10  [syntax]
sorts/strand_sort.py:4: error: X | Y syntax for unions requires Python 3.10  [syntax]
fractals/julia_sets.py:92: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/hashing/hash_table.py:13: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/hashing/hash_table.py:14: error: X | Y syntax for unions requires Python 3.10  [syntax]
quantum/bb84.py:53: error: X | Y syntax for unions requires Python 3.10  [syntax]
project_euler/problem_092/sol1.py:49: error: X | Y syntax for unions requires Python 3.10  [syntax]
physics/lorentz_transformation_four_vector.py:137: error: X | Y syntax for unions requires Python 3.10  [syntax]
other/maximum_subsequence.py:4: error: X | Y syntax for unions requires Python 3.10  [syntax]
linear_algebra/src/schur_complement.py:10: error: X | Y syntax for unions requires Python 3.10  [syntax]
linear_algebra/src/rank_of_matrix.py:8: error: X | Y syntax for unions requires Python 3.10  [syntax]
graphs/bi_directional_dijkstra.py:29: error: X | Y syntax for unions requires Python 3.10  [syntax]
graphs/bi_directional_dijkstra.py:30: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/queue/queue_by_two_stacks.py:10: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/heap/heap_generic.py:10: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/heap/heap_generic.py:21: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/heap/heap_generic.py:25: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/heap/heap_generic.py:30: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/heap/heap_generic.py:116: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/heap/heap_generic.py:120: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/inorder_tree_traversal_2022.py:13: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/inorder_tree_traversal_2022.py:14: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/inorder_tree_traversal_2022.py:17: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/inorder_tree_traversal_2022.py:46: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/inorder_tree_traversal_2022.py:60: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/fenwick_tree.py:11: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:10: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:12: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:13: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:14: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:25: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:34: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:83: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:93: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:107: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:139: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:155: error: X | Y syntax for unions requires Python 3.10  [syntax]
data_structures/binary_tree/binary_search_tree.py:170: error: X | Y syntax for unions requires Python 3.10  [syntax]
computer_vision/horn_schunck.py:65: error: X | Y syntax for unions requires Python 3.10  [syntax]
machine_learning/linear_discriminant_analysis.py:259: error: X | Y syntax for unions requires Python 3.10  [syntax]
web_programming/fetch_well_rx_price.py:16: error: X | Y syntax for unions requires Python 3.10  [syntax]
web_programming/fetch_well_rx_price.py:84: error: X | Y syntax for unions requires Python 3.10  [syntax]
Found 77 errors in 25 files (checked 1189 source files)
```

**Comment by JadeKim042386** [comment]
### Solution for error: X | Y syntax for unions requires Python 3.10  [syntax]

- add `from __future__ import annotaions`

**Comment by Ifeanyi222** [comment]
from collections import Counter

def count_occurrences(number):
    if isinstance(number, int) and number > 0:
        return Counter({number: 1})
    else:
        raise TypeError("number must be an integer and greater than zero")

**Comment by JadeKim042386** [comment]
@Ifeanyi222 

- match-case syntax

https://github.com/TheAlgorithms/Python/blob/80d95fccc390d366a9f617d8628a546a7be7b2a3/maths/gcd_of_n_numbers.py#L38-L44

**Comment by RamDanny** [comment]
I'm new to open source. This issue seems to be a good first issue. How can I help?

**Comment by Sagarkumar7** [comment]
assign me this

**Comment by mhsuhail00** [comment]
please share video, if available

**Comment by cclauss** [comment]
This repo ONLY supported the very latest version of Python which is currently v3.12 which has support for the `match` statement.
