### ISSUE TITLE
Heap's Algorithm for generating all Permutations

### ISSUE THREAD

**Issue by nidhi-2619** [TheAlgorithms/Python#8814]
### Feature description

It is an decrease and conquer algorithm which is used to generate all the permutations of a given sequence.

**Comment by tianyizheng02** [comment]
We already have implementations of Heap's algorithm in [`heaps_algorithm.py`](https://github.com/TheAlgorithms/Python/blob/daa0c8f3d340485ce295570e6d76b38891e371bd/divide_and_conquer/heaps_algorithm.py) and [`heaps_algorithm_iterative.py`](https://github.com/TheAlgorithms/Python/blob/daa0c8f3d340485ce295570e6d76b38891e371bd/divide_and_conquer/heaps_algorithm_iterative.py)

**Comment by tianyizheng02** [comment]
Closing this issue, if you have an implementation that's different from the existing ones or if you want to improve upon the existing ones, you're welcome to open a PR.
