### ISSUE TITLE
project_euler/problem_010/sol1.py

### ISSUE THREAD

**Issue by MatthiasHeinz** [TheAlgorithms/Python#8821]
### Repository commit

2104fa7aebe8d76b2b2b2c47fe7e2ee615a05df6

### Python version (python --version)

Python 3.10.4

### Dependencies version (pip freeze)

Does not matter.

### Expected behavior

> solution(2)

 should yield 2.

### Actual behavior

The result of 

> solution(2)

is 0.

[In this line](https://github.com/TheAlgorithms/Python/blob/46379861257d43bb7140d261094bf17dc414950f/project_euler/problem_010/sol1.py#L65) the condition 

> if n > 2

should read 

> if n >= 2

 instead.

**Comment by Pooja-Lohar25** [comment]
"""
    Returns the sum of all the primes below n.

    >>> solution(1000)
    76127
    >>> solution(5000)
    1548136
    >>> solution(10000)
    5736396
    >>> solution(7)
    10
    """

The program is to find the sum of primes below n therefore solution(2) yields 0 which is correct.

**Comment by MatthiasHeinz** [comment]
My bad; should've read the task more carefully.
