### ISSUE TITLE
Linear Regression

### ISSUE THREAD

**Issue by Madhav-2808** [TheAlgorithms/Python#8844]
### Feature description

I wanted to add some Python codes related to linear regression which is used to predict one dependent variable from another independent variable

**Comment by tianyizheng02** [comment]
The repo already has an implementation of linear regression in [`machine_learning/linear_regression.py`](https://github.com/TheAlgorithms/Python/blob/master/machine_learning/linear_regression.py), but you're still welcome to add your own implementation as long as it's significantly different

**Comment by tianyizheng02** [comment]
Closing this issue, but again you're welcome to add your own implementation (related: #8847)
