### ISSUE TITLE
Additional Features for Binary Tree Implementation

### ISSUE THREAD

**Issue by di-was** [TheAlgorithms/Python#8865]
### Feature description

I would like to modify the basic_binary_tree.py file under **datastructures/binary_tree section**. I propse adding a new BinaryTree class which will serve as a main interface for creating and manipulating binary trees. Additionally i want all the utilities function of the present file to be the methods of the new class.

**Comment by rohan472000** [comment]
Propose your thought through PR, so that it can be reviewed and merged if useful.

**Comment by paragnimkar** [comment]
I would like to contribute in this feature. So, can u assign this task to me.

**Comment by tianyizheng02** [comment]
@paragnimkar Read the contributing guidelines:
> If you are interested in resolving an open issue, simply make a pull request with your proposed fix. **We do not assign issues in this repo** so please do not ask for permission to work on an issue.

**Comment by dasdebanna** [comment]
@tianyizheng02 
Please see the PR that I have submitted  and close this issue https://github.com/TheAlgorithms/Python/issues/8865

**Comment by UjjwalPardeshi** [comment]
can you assigned this task to me .

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.
