### ISSUE TITLE
MinMax Scaler

### ISSUE THREAD

**Issue by KYKong97** [TheAlgorithms/Python#8873]
### Feature description

I would like to add MinMax scaler implementation which is used in preprocessing step

**Comment by tianyizheng02** [comment]
The `normalization` function machine_learning/data_transformations.py](https://github.com/TheAlgorithms/Python/blob/master/machine_learning/data_transformations.py) already implements min-max normalization. If you wish, you're welcome to open a PR to enhance its functionality.

**Comment by cclauss** [comment]
Closing.  If a pull request is created then it can be reviewed.
