### ISSUE TITLE
`web_programming/convert_number_to_words.py` is not web programming

### ISSUE THREAD

**Issue by tianyizheng02** [TheAlgorithms/Python#8881]
### What would you like to share?

[`web_programming/convert_number_to_words.py`](https://github.com/TheAlgorithms/Python/blob/5aefc00f0f1c692ce772ddbc616d7cd91233236b/web_programming/convert_number_to_words.py) has no web programming whatsoever. It should be moved to a different directory.

### Additional information

#8877 shows that this file is among those which broke ruff following the most recent pre-commit update. With how heavily nested the code is (among other questionable coding choices), perhaps it should be rewritten as well.

**Comment by ARUSHI-2004** [comment]
similar results, such as the inflect library in Python

**Comment by ARUSHI-2004** [comment]
similar result can be achieved using inflect library in python

**Comment by tianyizheng02** [comment]
> similar result can be achieved using inflect library in python

@ARUSHI-2004 No, you misunderstand. The entire point of this repo is to implement algorithms _from scratch_ for educational purposes. Using an existing Python library that implements the entire algorithm for us would defeat the whole point.

**Comment by cclauss** [comment]
If `weeb_programming` is the wrong category, what is the right category?

@ARUSHI-2004 idea might be quite instructional for 1. testing and 2. benchmarks.

**Comment by tianyizheng02** [comment]
> If `weeb_programming` is the wrong category, what is the right category?

@cclauss [`conversions`](https://github.com/TheAlgorithms/Python/tree/master/conversions), it's in the name: `convert_number_to_words.py`

**Comment by jaxparrow07** [comment]
> > If `web_programming` is the wrong category, what is the right category?
> 
> @cclauss [`conversions`](https://github.com/TheAlgorithms/Python/tree/master/conversions), it's in the name: `convert_number_to_words.py`

how ironic
