### ISSUE TITLE
python grading system

### ISSUE THREAD

**Issue by fawwazwasique** [TheAlgorithms/Python#8896]
### What would you like to share?

def calculate_grade(score):
    if score >= 90:
        return 'A+'
    elif score >= 80:
        return 'A'
    elif score >= 70:
        return 'B'
    elif score >= 60:
        return 'C'
     elif score>=50:
      return 'D'
    else:
        return 'Fail'

# Test the grading system
try:
    score = float(input("Enter the numeric score: "))
    if 0 <= score <= 100:
        grade = calculate_grade(score)
        print(f"The letter grade for the score {score} is: {grade}")
    else:
        print("Invalid score. Please enter a number between 0 and 100.")
except ValueError:
    print("Invalid input. Please enter a valid numeric score.")

**Comment by akoalp** [comment]
def calculate_grade(score):
if score >= 50:
return 'D'
elif score >= 60:
return 'C'
elif score >= 70:
return 'B'
elif score >= 80:
return 'A'
elif score>=90:
return 'A+'
else:
return 'Fail'

**Comment by akoalp** [comment]
I think try like this

**Comment by tianyizheng02** [comment]
Duplicate of #8894, and I don't see how this is relevant to the repo anyway
