### ISSUE TITLE
[DOCS] Update Discord links to the newest one

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Python#8910]
### What would you like to share?

The current Discord invitation link is the default Discord link that looks unclean.
It should be updated to the latest one we're using, which is <https://the-algorithms.com/discord>.

_Steps to contribute_

1. Fork the repository [here](https://github.com/TheAlgorithms/Python/fork).
2. Create a new branch named `update_invitation_link`.
3. Open the `README.md` file.
4. Replace all `discord.gg/` instances with `https://the-algorithms.com/discord`, which is the new link we're using for invitations to our community.
5. Commit and push your changes.
6. Create a [pull requst](https://github.com/TheAlgorithms/Python/compare) to compare your changes.
7. You're done now! 🎉 You just have to wait until the maintainers review and check your PR.

If you need any help with this, let us know! 🙂

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by tianyizheng02** [comment]
I guess this isn't really relevant anymore now that I merged your PR #8696...
