### ISSUE TITLE
Feat:Octal To Binary Converter 

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Python#8921]
### Feature description

Octal To Binary Converter is missing in conversion section.
So want to add octal to binary converter

**Comment by rohan472000** [comment]
Don't wait for anyone to respond or assign, make necessary PR so that it get reviewed.

**Comment by BamaCharanChhandogi** [comment]
Hey, @rohan472000 Can you check this #8949 ?
