### ISSUE TITLE
Why am i facing ruff failed on other files?

### ISSUE THREAD

**Issue by Miltonbhowmick** [TheAlgorithms/Python#8935]
### What would you like to share?

I am trying to add a new algorithm for first time. While i submitting my file and bot is checking for `ruff` test, its failed on files except my file. 
If anyone can help me out of this, i will glad.

PR: [https://github.com/TheAlgorithms/Python/actions/runs/5805449154/job/15736567968?pr=8931](url)

Thanks in Advance.

**Comment by tianyizheng02** [comment]
@Miltonbhowmick The ruff errors have been fixed. To fix the extraneous ruff errors in your PR, you just need to update your PR's branch on your fork of the repo.
