### ISSUE TITLE
`web_programming/current_stock_price.py` no longer works

### ISSUE THREAD

**Issue by jbrowning** [TheAlgorithms/Python#8950]
### Repository commit

ae0fc85401efd9816193a06e554a66600cc09a97

### Python version (python --version)

N/A

### Dependencies version (pip freeze)

N/A

### Expected behavior

To print the current stock price for the given symbol.

### Actual behavior

No stock price is printed because the `https://in.finance.yahoo.com/quote/` endpoint used by this script is no longer operational.

**Comment by NextThread** [comment]
hey, can I work on this

**Comment by tianyizheng02** [comment]
> hey, can I work on this

@NextThread As stated in our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/ae0fc85401efd9816193a06e554a66600cc09a97/CONTRIBUTING.md), we don't assign issues. If you want to work on something, just do it. Also, please note that there's already an open PR addressing this issue.
