### ISSUE TITLE
File in python

### ISSUE THREAD

**Issue by nazanintalebi** [TheAlgorithms/Python#8953]
### What would you like to share?

Hello there, I find out a problem with my codes
I would be grateful if anyone could solve it.
**Here is my data table:**
Date/	Active ingredient/	Drug name	/Company
7/25/2023/	Lotilaner/	lotilaner/	Tarsus Pharmaceuticals
7/21/2023/	Cantharidin/	Ycanth/	Verrica Pharmaceuticals
7/20/2023/	Quizartinib dihydrochloride/	Vanflyta/	Daiichi Sankyo
7/17/2023/	Nirsevimab/	Beyfortus	/AstraZeneca
6/27/2023/	Somatrogon/	Ngenla/	Pfizer Inc
6/26/2023/	Rozanolixizumab/	Rystiggo/	UCB Inc

**And here is my code:**
```
with open(r'C:\Users\Rayaneh PouYa\Desktop\AI\file\drugsinf1.txt','r') as drugsName:
    drugsN=drugsName.readlines()
    print(*drugsN)
    drugDate=[]
    drugActiveI=[]
    drugName=[]
    drugCompany=[]

    for i in range(len(drugsN)):
        dsplit=drugsN[i].split()
        drugDate.append(dsplit[0])
        drugActiveI.append(dsplit[1])
        drugName.append(dsplit[2])
        drugCompany.append(dsplit[3])
        
print(*drugDate,sep='\n')
print('the drug Active ingredient is:')
print(*drugActiveI,sep='\n')
print('the drugsname is:')
print(*drugName,sep='\n')
print('the drugs company  name is:')
print(*drugCompany,sep='\n')    
with open(r'C:\Users\Rayaneh PouYa\Desktop\AI\file\class\drugsDate.txt','a') as drugsDatelist:
    for j in range(len(drugDate)):
        drugsDatelist.write(drugDate[j])
        drugsDatelist.write('\n')
with open(r'C:\Users\Rayaneh PouYa\Desktop\AI\file\class\drugsActiveI.txt','a') as drugsActiveingredientlist:
    for b in range(len(drugActiveI)):
        drugsActiveingredientlist.write(drugActiveI[b])
        drugsActiveingredientlist.write('\n')
with open(r'C:\Users\Rayaneh PouYa\Desktop\AI\file\class\drugsName.txt','a') as drugsNamelist:
    for z in range(len(drugName)):
        drugsNamelist.write(drugName[z])
        drugsNamelist.write('\n')
with open(r'C:\Users\Rayaneh PouYa\Desktop\AI\file\class\drugsCompany.txt','a') as drugsCompanylist:
    for c in range(len(drugCompany)):
        drugsCompanylist.write(drugCompany[c])
        drugsCompanylist.write('\n')

```
As the table couldn't appear in the .txt format so the result wasn't accurate, I consider that happened due to wrong indexing, but I can't find the proper one.
My teacher told me I should solve it without using pandas

**Comment by karthxk07** [comment]
So, here is what I could infer from the issue.

If you'd look closely in the Data table that you provided , you can see that you have a _whitespace characters_ at few places in your table.

> Date/ **Active ingredient**/ **Drug name** /Company
> 7/25/2023/ Lotilaner/ lotilaner/ **Tarsus Pharmaceuticals**
> 7/21/2023/ Cantharidin/ Ycanth/ **Verrica Pharmaceuticals**
> 7/20/2023/ **Quizartinib dihydrochloride**/ Vanflyta/ **Daiichi Sankyo**
> 7/17/2023/ Nirsevimab/ Beyfortus /AstraZeneca
> 6/27/2023/ Somatrogon/ Ngenla/ **Pfizer Inc**
> 6/26/2023/ Rozanolixizumab/ Rystiggo/ **UCB Inc**

and when you split this data using `.split()` , it includes all the whitespace characters there are in the the data, and hence your table wasn't accurate

**To Solve this**, you could use `.split("/")` which would split your data everywhere where it encounters a '/' character. However you would also have to edit your data accordingly, by changing the data format from dd/mm/yyyy to dd-mm-yyyy

> Date/ Active ingredient/ Drug name /Company
> 7-25-2023/ Lotilaner/ lotilaner/ Tarsus Pharmaceuticals
> 7-21-2023/ Cantharidin/ Ycanth/ Verrica Pharmaceuticals
> 7-20-2023/ Quizartinib dihydrochloride/ Vanflyta/ Daiichi Sankyo
> 7-17-2023/ Nirsevimab/ Beyfortus /AstraZeneca
> 6-27-2023/ Somatrogon/ Ngenla/ Pfizer Inc
> 6-26-2023/ Rozanolixizumab/ Rystiggo/ UCB Inc

Another error you would face then would be the new line characters after every company name. For that you could simply add
`drugCompany.append(dsplit[3]**.strip('\n'))**` to strip the string of any newline characters.

This you probably should solve your issue.

**Comment by nazanintalebi** [comment]
thanks for replying me.
you solved the issue.
