### ISSUE TITLE
'ArtistList' object has no attribute 'remove'

### ISSUE THREAD

**Issue by prathmeshpalande** [TheAlgorithms/Python#9015]
### Repository commit

0a9438071ee08121f069c77a5cb662206a4d348f

### Python version (python --version)

Python 3.10.9

### Dependencies version (pip freeze)

brotlipy @ file:///Users/runner/miniforge3/conda-bld/brotlipy_1666764759924/work
certifi==2022.12.7
cffi @ file:///Users/runner/miniforge3/conda-bld/cffi_1671179893800/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1661170624537/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
conda==22.11.1
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1669907009957/work
conda_package_streaming @ file:///home/conda/feedstock_root/build_artifacts/conda-package-streaming_1669733752472/work
cryptography @ file:///Users/runner/miniforge3/conda-bld/cryptography-split_1675828699498/work
docutils==0.20.1
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
pip==23.0
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1667232663820/work
pycosat @ file:///Users/runner/miniforge3/conda-bld/pycosat_1666836623787/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1672659226110/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1673863902341/work
ruamel.yaml @ file:///Users/runner/miniforge3/conda-bld/ruamel.yaml_1666827372049/work
ruamel.yaml.clib @ file:///Users/runner/miniforge3/conda-bld/ruamel.yaml.clib_1670412881259/work
setuptools==65.6.3
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1662214488106/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1673452138552/work
wheel==0.38.4
zstandard==0.19.0

### Expected behavior

In Matplotlib, when you plot something on an axis, it returns a list of artists/lines. If you want to remove a specific line from the axis, you can directly use the remove method of that specific line object. The key difference is that the remove method is called on the specific line (self.ax_loss.lines[0]) instead of trying to call it on the entire list of lines (self.ax_loss.lines).

### Actual behavior

The error AttributeError: 'ArtistList' object has no attribute 'remove' suggests that self.ax_loss.lines is an ArtistList object and doesn't have the remove method.

**Comment by Anianonymous** [comment]
Hey, I am interested to solve this issue

**Comment by Rai-Sahil** [comment]
Hi can I get assigned to this bug?

**Comment by SamarFatimaJaffri** [comment]
> Hi can I get assigned to this bug?

You can simply assign this to yourself and start working.

PS: I was gonna do the same, but I saw your comment..

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.
