### ISSUE TITLE
Adding MFCC Audio Signal Feature Extraction Algorithm

### ISSUE THREAD

**Issue by AmirLavasani** [TheAlgorithms/Python#9026]
### Feature description

**Issue Title:** 
Adding MFCC Audio Signal Feature Extraction Algorithm

**Issue Description:**
I am planning to contribute to this repository by implementing the MFCC (Mel Frequency Cepstral Coefficients) audio signal feature extraction algorithm. MFCC is widely used in various applications, including speech recognition and audio analysis.

**Proposed Location:**
I would like to propose adding a new category or subcategory for signal processing or feature extraction. Specifically, I suggest:
- Creating a "Signal Processing" category if one does not exist, and placing the MFCC algorithm under it.
OR
- Creating a "Feature Extraction" subcategory under the "Machine Learning" section and placing MFCC under it.

**Contributor Request:**
I am opening this issue to let the community know about my intention to work on this algorithm. I also welcome suggestions and feedback from other contributors regarding the best location for this feature extraction algorithm and any considerations related to its implementation.

Looking forward to collaborating with the community to enhance this repository with the addition of the MFCC feature extraction algorithm.

**Comment by rohan472000** [comment]
check [audio_filters](https://github.com/TheAlgorithms/Python/tree/master/audio_filters).

**Comment by AmirLavasani** [comment]
Thanks for your response. @rohan472000  

I also checked the audio filter folder, but I didn't find an MFCC implementation there, so I will open a PR to add the MFCC Algorithm. MFCC is commonly categorized as a feature extraction algorithm in machine learning, rather than an audio filter. I'm open to community feedback, and if most agree, I'll add it to the audio filter category.

**Comment by rohan472000** [comment]
Yep.. it would be better to put this into machine_learning folder.

**Comment by AmirLavasani** [comment]
The automatic build keeps failing for other algorithm tests. Hey Rohan, What do you suggest I do? @rohan472000 

Here is the error message:

=========================== short test summary info ============================
FAILED machine_learning/xgboost_regressor.py::machine_learning.xgboost_regressor.main
FAILED machine_learning/xgboost_regressor.py::machine_learning.xgboost_regressor.xgboost
============ 2 failed, 1473 passed, 16 warnings in 66.14s (0:01:06) ============
Error: Process completed with exit code 1.

**Comment by rohan472000** [comment]
I'm working to fix that issue...will raise PR for it...after getting merged your PR's build will be successful.
