### ISSUE TITLE
sigmoid, tanh and relu should be moved to neural_network/activation_functions from maths/

### ISSUE THREAD

**Issue by AdarshAcharya5** [TheAlgorithms/Python#9048]
### Feature description

`sigmoid.py`, `tanh.py`, `sigmoid_linear_unit.py` and `relu.py` should be moved to neural_network/activation_functions.

**Comment by rohan472000** [comment]
@AdarshAcharya5 , why you want to move those .py files?

**Comment by anchor54** [comment]
is this still a requirement and open for contribution?

**Comment by aayushi-0407** [comment]
Hey
I have been working with neural net for quite a while now (check my GitHub). would love to work on this issue.
Am new to open source and would love any help whatsoever.

**Comment by UjjwalPardeshi** [comment]
can you assign me this task please.

**Comment by tianyizheng02** [comment]
@rohan472000 Functions such as sigmoid, tanh, and ReLU are nowadays commonly used as activation functions for neural networks. Sigmoid (or more specifically the logistic function) and tanh are still well-known mathematical functions outside of ML, so I think those should stay in the `maths/` directory. However, ReLU is pretty much only known as an activation function as far as I know, so I think it's appropriate to move that algorithm to `neural_network/activation_functions`.

**Comment by piyush-poddar** [comment]
Hi I have raised a [PR](https://github.com/TheAlgorithms/Python/pull/9753), please review it.
