### ISSUE TITLE
Add QuadTree

### ISSUE THREAD

**Issue by SaurabhGoyal** [TheAlgorithms/Python#905]
Added [quadtree](https://en.wikipedia.org/wiki/Quadtree) with basic functionality of adding and searching points in a 2D map. I will add functionality for finding nearest points in next PR.
PR: https://github.com/TheAlgorithms/Python/pull/904

**Comment by anand372** [comment]
would like to work on this if still open...:)

**Comment by SaurabhGoyal** [comment]
Sure, you can continue work on my pr.
