### ISSUE TITLE
blockchain section doesn't contain blockchain-related algorithms

### ISSUE THREAD

**Issue by ar406** [TheAlgorithms/Python#9051]
### What would you like to share?

The blockchain section contains a README which starts talking about blockchains, DLTs and cryptography, as expected, but then includes links to the Chinese Remainder Theorem and modular division.  

While certainly interesting topics, they are not strictly related to blockchains. 

The Chinese Remainder Theorem is used in many RSA implementations, but RSA is not used in blockchains like Bitcoin and Ethereum.

 Hashes such as SHA256 are by far more related to blockchains, but they are implemented in the hash/ directory.

I believe the blockchain section, in its current version, is confusing.

Some possible solutions:
- amend the documentation
- move CRTs, modular division to a new directory (maybe number theory? Linear algebra already exists and looks like a nice precedent)
- rename the blockchain directory

**Comment by jaysaadana** [comment]
@quest-bot embark

**Comment by tianyizheng02** [comment]
I completely agree. I personally don't think that any of the algorithms in the blockchain directory are _directly_ related to blockchains, and they'd belong better under another directory such as maths. I'd be in favor of removing the blockchain directory entirely and relocating the algorithms. @cclauss, thoughts?

**Comment by cclauss** [comment]
# amend the documentation
