### ISSUE TITLE
Returning index instead of boolean when knuth_morris_pratt matches.

### ISSUE THREAD

**Issue by amirsoroush** [TheAlgorithms/Python#9077]
In [knuth morris pratt algorithm](https://github.com/TheAlgorithms/Python/blob/master/strings/knuth_morris_pratt.py), I think it's better to return the "index" of the matched substring in case of success, and `-1` in case of failure, so that it would be consistent with the `str.find()` in Python. `True` and `False` aren't that helpful.

**Comment by ArhamaQ** [comment]
Hey, My name is Arhama. I am a beginner in open source contribution. After exploring a couple of hours, this is the first project I have found  for myself. and I think i can work on this please assign me this work
