### ISSUE TITLE
Feat: Add Three sum in Math Section

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Python#9153]
### Feature description

I think Two sum is available but the Three sum is not available. 
I want to add three sum Problem. 
### **Examples:**
 **Input:** array = [-1,0,1,2,-1,-4]
**Output:** [[-1,-1,2],[-1,0,1]]

**Comment by BamaCharanChhandogi** [comment]
@tianyizheng02 Could we work on this issue?

**Comment by tianyizheng02** [comment]
# @BamaCharanChhandogi, read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contribution).

> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
