### ISSUE TITLE
[Add] : Project Euler - 95 solution 

### ISSUE THREAD

**Issue by kosuri-indu** [TheAlgorithms/Python#9166]
### Feature description

**Addition of Project Euler - 95 solution**

**Problem statement - Amicable Chains**

![image](https://github.com/TheAlgorithms/Python/assets/118645569/863546a0-c723-437a-9475-3017e3218d55)

**Comment by Pr0-C0der** [comment]
Hey! I can take up this issue. In which folder should I add the code?

**Comment by amitaryansingh** [comment]
hlo would you please assign this to me

**Comment by tianyizheng02** [comment]
@amitaryansingh Read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contribution).
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.

**Comment by haxkd** [comment]
@tianyizheng02 it's not an issue.
It's just to contribute an algorithm. so I think have to submit a pull request instead of creating an issue.

**Comment by tianyizheng02** [comment]
> @tianyizheng02 it's not an issue. It's just to contribute an algorithm. so I think have to submit a pull request instead of creating an issue.

@haxkd Yes, exactly, people shouldn't be creating issues to contribute a new algorithm. From our contributing guidelines:
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
