### ISSUE TITLE
Hyperparameters tunning in machine learning

### ISSUE THREAD

**Issue by Mridul-2003** [TheAlgorithms/Python#9188]
### Feature description

Adding hyperparameters tuning like grid search cv and random search cv in  machine learning folder.

**Comment by anchor54** [comment]
Hi, would like to work on this, can you assign me this issue?

**Comment by tianyizheng02** [comment]
Please read our contributing guidelines.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
