### ISSUE TITLE
Feature: Bogosort Algorithm

### ISSUE THREAD

**Issue by sharansukesh1003** [TheAlgorithms/Python#9242]
### Feature description

Bogo Sort, a quirky and impractical sorting algorithm, epitomizes randomness in sorting. It shuffles an array randomly until, by sheer luck, it arrives at a sorted permutation. Known for its abysmal time complexity, Bogo Sort serves as a humorous illustration of how not to sort, making it more of a novelty than a practical choice for sorting large datasets.

**Comment by tianyizheng02** [comment]
We already have an implementation of [bogo sort](https://github.com/TheAlgorithms/Python/blob/eaa87bd791cdc18d210d775f3258767751f9d3fe/sorts/bogo_sort.py). Please check to make sure that an algorithm isn't already implemented before opening an issue or contributing.
