### ISSUE TITLE
Enhancement of the knapsack algorithm

### ISSUE THREAD

**Issue by Jiang15** [TheAlgorithms/Python#9266]
### Feature description

There is a recursive implementation of 0-1 knapsack problem. The idea is to enhance it with code optimization and feature extension.

- Optimize the recursion with memorization (DP) which reduces the complexity to O(KN).
- Implement knapsack algorithm which gives the option to allow the items been repetitively picked multiple times, i.e, either 0-1 or 0-N knapsack problem.

**Comment by balkishan69** [comment]
hey @Jiang15 can i get assigned this issue...

**Comment by abhishek09827** [comment]
hey @Jiang15 I have already solved the issue pls assign this to me

**Comment by Jiang15** [comment]
I already created a PR here https://github.com/TheAlgorithms/Python/pull/9295

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.
