### ISSUE TITLE
Required: ANN Implementation for Classification and Regression tasks

### ISSUE THREAD

**Issue by ravin-d-27** [TheAlgorithms/Python#9269]
### Feature description

Require a file which contains ANN implementation for both classification and regression tasks. It should have both the classes in the same file and each should be for classification and regression respectively

**Comment by abhishek09827** [comment]
Hello @ravin-d-27 pls assign thsi task to me

**Comment by Sahana-Math** [comment]
Hey 
I've just learnt ANN. Can you please assign this to me?

**Comment by aayushi-0407** [comment]
Hey 
I have been working with neural net for quite a while now (check my GitHub). would love to work on this issue.
Am new to open source and would love any help whatsoever.

**Comment by tianyizheng02** [comment]
@abhishek09827 @Sahana-Math @aayushi-0407 Read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contribution).
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.

**Comment by tianyizheng02** [comment]
@ravin-d-27 You too, read the contributing guidelines. If you want to add NN implementations for classification and regression, then open a PR. Why open an issue? Also, why do you say that we're _required_ to have it?

**Comment by ravin-d-27** [comment]
> @ravin-d-27 You too, read the contributing guidelines. If you want to add NN implementations for classification and regression, then open a PR. Why open an issue? Also, why do you say that we're _required_ to have it?

Sure, will go thru the guidelines. I thought the PR also requires an issue to be closed also. Thank you for the information and sorry for the inconvenience caused..

**Comment by UjjwalPardeshi** [comment]
Can i be assigned this task please.

**Comment by tianyizheng02** [comment]
@UjjwalPardeshi I already said this in a previous comment: **read the contributing guidelines, and we don't assign issues. If you want to contribute, just open a PR.**

**Comment by tianyizheng02** [comment]
Closing all issues that propose/ask permission to work on a new algorithm. Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues). We don't assign issues in this repo.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
