### ISSUE TITLE
I like to work in AVL, PArtially ordered tree and A* is it anyone doing this actually?

### ISSUE THREAD

**Issue by rafaelleru** [TheAlgorithms/Python#93]

**Comment by dynamitechetan** [comment]
Please go ahead.

**Comment by 0oo0** [comment]
Any Updates @rafaelleru ?

**Comment by rafaelleru** [comment]
Yes, in a week or less I will pull request the master, sorry I was on my holidays after school exams.

**Comment by sachinarora707** [comment]
@rafaelleru Any updates?

**Comment by rafaelleru** [comment]
I already PR with AVL

**Comment by harshildarji** [comment]
@rafaelleru Looking forward to receive more contributions from your side.
