### ISSUE TITLE
ADD Metropolis-Hastings Algorithm in python

### ISSUE THREAD

**Issue by Kalivarapubindusree** [TheAlgorithms/Python#9307]
### What would you like to share?

The Metropolis-Hastings algorithm is a Markov chain Monte Carlo (MCMC) algorithm used for sampling from complex probability distributions. It's commonly used in Bayesian statistics for posterior inference when direct sampling is not feasible.

### Additional information

can you please assign me this task under hacktoberfest contribution

**Comment by tianyizheng02** [comment]
> can you please assign me this task under hacktoberfest contribution

@Kalivarapubindusree No. We do not assign issues in this repo. Anyone who wants to add an algorithm is free to open a PR. Read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contribution):
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.

**Comment by mhsuhail00** [comment]
Where the file of this algorithm should be placed in the Python directory.

**Comment by tianyizheng02** [comment]
Closing all issues that propose/ask permission to work on a new algorithm. Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues). We don't assign issues in this repo.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
