### ISSUE TITLE
ADDED NEW ELECTRIC FIELD AROUND RING IN PHYSICS

### ISSUE THREAD

**Issue by wountv** [TheAlgorithms/Python#9322]
### Feature description

SO, This is my first contribution to open source by writing few lines of code and to make life easier for physics geeks like me. Thanks seeing forward to see my code in this repo.

**Comment by tianyizheng02** [comment]
Closing all issues that propose/ask permission to work on a new algorithm. Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues). We don't assign issues in this repo.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
