### ISSUE TITLE
Add Sum of Two Integers using Bit Manipulation

### ISSUE THREAD

**Issue by crocmons** [TheAlgorithms/Python#9329]
### Feature description
I want to add a new DSA Problem Solution, which is a sum of two integers using Bit manipulation.. 

Problem -
**Given two integers a and b, return the sum of the two integers without using the operators + and -.**

Example 1:
Input: a = 1, b = 2
Output: 3

Example 2:
Input: a = 2, b = 3
Output: 5

**Comment by subhashree9898** [comment]
Hey @crocmons Please assign me this issue.

**Comment by crocmons** [comment]
> Hey @crocmons Please assign me this issue.
Actually, I have already started working on it. @subhashree9898

**Comment by PiKa919** [comment]
Hey @crocmons, Can you assign this issue to me, I have a rough idea ready for this solution which is (using XOR and AND operators)

**Comment by tianyizheng02** [comment]
@crocmons If you're already working on this algorithm, then why did you open an issue? We don't assign issues here, aand anyone who wants to contribute can just open a PR. Did you read the contributing guidelines?

**Comment by tianyizheng02** [comment]
Also, we already have an implementation of integer addition using bit manipulation in [bit_manipulation/bitwise_addition_recursive.py](https://github.com/TheAlgorithms/Python/blob/e798e5acdee69416d61c8ab65cea4da8a5c16355/bit_manipulation/bitwise_addition_recursive.py). Did you check to make sure that we didn't already have it before you opened this issue?

**Comment by crocmons** [comment]
yeah now I checked, thanks for informing me of this! @tianyizheng02
