### ISSUE TITLE
Want to Add Power of Four logic using Logarithm

### ISSUE THREAD

**Issue by crocmons** [TheAlgorithms/Python#9331]
### Feature description
Want to Add DSA Solution of this problem - Power of Four - using Logarithm

**Problem Statement - 
Given an integer n, return true if it is a power of four. Otherwise, return false.
An integer n is a power of four, if there exists an integer x such that n == 4x.**

Example 1:
Input: n = 16
Output: true

**Comment by DevAgrawal04** [comment]
Could you assign this issue to me? Thanks

**Comment by tianyizheng02** [comment]
If you want to add an algorithm, just open a PR. We don't assign issues and there's no need to open an issue for a new algorithm. Please read the contributing guidelines.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.

**Comment by tianyizheng02** [comment]
@cclauss Would you say this is even a valuable algorithm to include? Every PR opened for this issue has simply used a built-in logarithm function like `math.log()`.

**Comment by debnath003** [comment]
#9369 
I have done this PR, but looks like no reviewer is there to approve and merge this PR. Anybody help me! @dhruvmanila @tianyizheng02

**Comment by cclauss** [comment]
@tianyizheng02 I agree that all the implementations are too trivial if `math.log()` is used.
