### ISSUE TITLE
Add largest power of 2 less than or equal to a given number

### ISSUE THREAD

**Issue by siddwarr** [TheAlgorithms/Python#9347]
### Feature description

This can be done by left-shifting the given number and stopping when you reach the first set bit. And then you can find the largest power of two by finding the difference between the length of the given number when converting it to binary form and the no of times you had to shift to find the first set bit.

**Comment by coolyashas** [comment]
take

**Comment by tusharsharma5347** [comment]
Hello Sir,
I want to work on this. Can you please assign me this issue.
