### ISSUE TITLE
Optimization of Minimum Waiting time algorithm

### ISSUE THREAD

**Issue by atmikshetty** [TheAlgorithms/Python#9353]
### Feature description

We just avoid sorting the list which imrpoves the overall time complexity.

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.
