### ISSUE TITLE
Issue first or PR first?

### ISSUE THREAD

**Issue by sidharthshah** [TheAlgorithms/Python#937]
I've read the contributing guideline, its great for understanding kinds of acceptable contribution and overall style dos and don't. 

But I has a question: From contributing guideline it is not clear if one needs to get feedback on Issue first or PR can directly be submitted.

Would make sense to explicitly mention the recommended way of claiming the issue to work on. E.g. I'd like to contribute code for [RLE](https://en.wikipedia.org/wiki/Run-length_encoding) in compression section.

**Comment by poyea** [comment]
That's not a big deal - but if you believe your thoughts require more attention before working on them, kindly open an issue for discussion. For a bulky change(that, say, involves >20 files), it's recommended to refer to an issue, but for a tiny or trivial change or a file addition, you can either open an issue first or directly open a PR. It's up to you. It's even perfectly fine if you open a draft PR.

**Comment by poyea** [comment]
It's really up to you. How would you organize your flow/ideas?

**Comment by sidharthshah** [comment]
@poyea appreciate your inputs. I think I get the idea -- will open draft PR get some feedback until its good for merging. Mostly I was thinking about doing minor additions to existing categories. 👍 Thank you.
