### ISSUE TITLE
conversions: infix to prefix

### ISSUE THREAD

**Issue by AvinashReddy19** [TheAlgorithms/Python#9399]
### Feature description

conversion of infix to prefix is missing in this repo

**Comment by kbadal19** [comment]
Hey, can I do this?

**Comment by dhruvsaxena11** [comment]
@AvinashReddy19 
Hi,
Please kindly assign this issue to me under the hacktoberfest 2023.
I have my prior experience in data structures and Python.
I am a Data Science enthusiast.

Thank You
Dhruv Saxena

**Comment by tianyizheng02** [comment]
> conversion of infix to prefix is missing in this repo

We actually do have an infix-to-prefix algorithm: [data_structures/stacks/infix_to_prefix_conversion.py](https://github.com/TheAlgorithms/Python/blob/0a84b8f842c4c72f400d96313d992b608d621d07/data_structures/stacks/infix_to_prefix_conversion.py)
