### ISSUE TITLE
Knapsack problem dynamic programming approach missing

### ISSUE THREAD

**Issue by kbadal19** [TheAlgorithms/Python#9402]
### What would you like to share?

The knapsack problem using the dynamic programming approach is not solved. Instead, only naive recursive methodology and greedy methods are used. I would like to implement the Dynamic Programming approach which is faster and more efficient.

**Comment by palak-chaturvedi** [comment]
Hey,
I would like to work on this.

**Comment by Jiang15** [comment]
Hi, I have implemented with dp and the PR is here: https://github.com/TheAlgorithms/Python/pull/9295

**Comment by tianyizheng02** [comment]
> The knapsack problem using the dynamic programming approach is not solved.

... Did you check the `dynamic_programming/` directory? [dynamic_programming/knapsack.py](https://github.com/TheAlgorithms/Python/blob/f8fe8fe41f74c8ecc5c8555ca43d65bd12b4f073/dynamic_programming/knapsack.py)
