### ISSUE TITLE
Fractional Knapsack Problem

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [TheAlgorithms/Python#9408]
### Feature description

The KnapSack problem defined is 0-1 Knapsack. Fractional Knapsack problem is missing.

**Comment by kbadal19** [comment]
Hey, Can I solve it?

**Comment by debnath003** [comment]
Can I solve this problem? I want to contribute

**Comment by OMKAR-KALEPU** [comment]
Please do look for other issues. I want to contribute, hence i raised an issue.

**Comment by imSanko** [comment]
Kindly review my PR for the Fractional Knapsack Problem in DP #9444 @tianyizheng02

**Comment by imSanko** [comment]
Have you viewed my PR #9444 @tianyizheng02  ?

**Comment by ChrisO345** [comment]
We already have implementations of fractional knapsacks at [greedy_methods/fractional_knapsack.py](https://github.com/TheAlgorithms/Python/blob/master/greedy_methods/fractional_knapsack.py) and [greedy_methods/fractional_knapsack_2.py](https://github.com/TheAlgorithms/Python/blob/master/greedy_methods/fractional_knapsack_2.py)

**Comment by imSanko** [comment]
Can you view my Pr #9444

**Comment by Shantanusharnagat** [comment]
I would like to work on this issue, could you please assign it to me

**Comment by ChrisO345** [comment]
As mentioned before we already have implementations of this algorithm.
