### ISSUE TITLE
Polynomial Manipulation

### ISSUE THREAD

**Issue by debnath003** [TheAlgorithms/Python#9423]
### Feature description

I propose to add a python code which can manipulate the polynomials, taking the test cases using doctest module. Since it is not given, I thought to add it to help the students!

**Comment by codetechie-abhay** [comment]
# Polynomial Manipulation Library

📚 This Python library allows you to manipulate and work with polynomials easily.

## Features

✨ Key features of this library include:

- Create polynomials with given coefficients.
- Display polynomials in a user-friendly format.
- Evaluate polynomials for specific values of x.

## Usage

### Installation

To use this library, you can simply import the `Polynomial` class from `polynomial_manipulation.py`:

```python
from polynomial import Polynomial

# Create a polynomial
p = Polynomial([3, 2, 1])  # 3x^2 + 2x + 1
#fix:9423

**Comment by debnath003** [comment]
Thanks for the advice, but I still wanna try without using any kind of Polynomial library import! Thanks btw @codetechie-abhay
