### ISSUE TITLE
[QUESTION] The Eligibility of Algorithm to check validity of Sri Lankan phone number

### ISSUE THREAD

**Issue by SpiderMath** [TheAlgorithms/Python#9435]
### What would you like to share?

The algorithm in question: https://the-algorithms.com/algorithm/is-srilankan-phone-number

The repositories under the organisation The Algorithms are said to contain non-trivial algorithms of various sorts. However, the algorithm I present does not seem to have any major significance, and does not facilitate any learning for the user, for it has just a RegEx which you could use to detect whether a phone number is Sri Lankan or not. It is highly specific and I do not think it is a valid algorithm to be included in the repositories by what is stated in the documentation, yet why is it listed and added as an algorithm?

I'm opening this issue here because there is only a Python implementation for this, and none other, hence I felt this is a more appropriate place to open the issue.

(I sincerely apologise if my language sounds rude, English is not my first language, I do not mean any disrespect to anyone, it is simply an honest question which I had)

**Comment by Sarthakkul2311** [comment]
I would like to contribute in this project

**Comment by SpiderMath** [comment]
> I want to contribute to this.

> I would like to contribute in this project

My sincere apologies but this issue was not meant to ask people to check if a phone number was Sri Lankan using RegEx. There's already an entry for that, which I feel does not belong here, and hence I asked the maintainers to see whether the it should still be there. There's nothing to be making pull requests for yet!

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.

**Comment by SpiderMath** [comment]
> [`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> 
> > **Do not** create an issue to contribute an algorithm. Please submit a pull request instead.

Excuse me, sorry to bother you again but this isn't about **contributing** an algorithm, it's regarding the removal of one. I hope you read what I'd written in my issue!
