### ISSUE TITLE
Longest Consecutive sequence leetcode problem

### ISSUE THREAD

**Issue by Mridul-2003** [TheAlgorithms/Python#9436]
### Feature description

Longest consecutive sequence problem solved using hash set.

**Comment by KiranBabu007** [comment]
Hey I have been solving coding problems on various platforms lately... i can contribute the solution for this using python.. can you assign it to me if noone alse has taken it?

**Comment by KiranBabu007** [comment]
In which folder should i add the program file or should i create a new one?

**Comment by jayant-01** [comment]
can i work on this under hacktoberfest 2023

**Comment by Kaushik2201** [comment]
I have made a PR #9451 please have a look

**Comment by Sarthak950** [comment]
I have added a well-documented solution for Leet Code Problem Longest consecutive Sequence
#9686

**Comment by tianyizheng02** [comment]
Closing all issues that propose/ask permission to work on a new algorithm. Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues). We don't assign issues in this repo.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
