### ISSUE TITLE
Longest Palindromic subsequence problem

### ISSUE THREAD

**Issue by sanketkittad** [TheAlgorithms/Python#9445]
### Feature description

Add longest palindromic subsequence problem algorithm in python.

**Comment by jayant-01** [comment]
can i get to work on this

**Comment by sanketkittad** [comment]
i have already added a PR, its pending reviews

**Comment by Chirag13222** [comment]
I will work on this !

**Comment by sanketkittad** [comment]
> I will work on this !

i have already added a PR, its pending reviews
