### ISSUE TITLE
Backtracking Algorithms

### ISSUE THREAD

**Issue by hetzz** [TheAlgorithms/Python#945]
I would want to add a new directory/folder for problems that can be solved using the backtracking algorithmic-approach. The three problems I would work on are nQueens, Sum of Subsets, m-coloring(Graph).

**Comment by Erfaniaa** [comment]
Does anyone agree?
Personally, I agree with n-queens and m-coloring.
@poyea @AnupKumarPanwar @himangSharatun @dynamitechetan @nikit19 @jogendra

**Comment by hetzz** [comment]
PR: #953

**Comment by poyea** [comment]
I'm okay with this. I've approved #953 and will let it be there for a moment. I'll merge it very soon.

**Comment by poyea** [comment]
I've heard previously that these problems should not be included, but I think it's fine as long as files are not duplicate/redundant. They could be classical or modern or "interview" type algorithms, but if that's a problem, this should be stated in README, etc.

**Comment by jai-dewani** [comment]
What about "Crossword problem", it is also a Backtracking problem?
