### ISSUE TITLE
Library Sort Algorithm

### ISSUE THREAD

**Issue by MihirRajeshPanchal** [TheAlgorithms/Python#9506]
### Feature description

Library sort or gapped insertion sort is a sorting algorithm that uses an insertion sort, but with gaps in the array to accelerate subsequent insertions.

![image](https://github.com/TheAlgorithms/Python/assets/78205431/067b8769-8466-466a-be10-e3a48c6d6d02)

**Comment by draksham** [comment]
I will work on this issue can you please assign it to me

**Comment by tianyizheng02** [comment]
@draksham Do not ask to be assigned to issues. Read the contributing guidelines.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. **We do not assign issues in this repo** so please do not ask for permission to work on an issue.

**Comment by tianyizheng02** [comment]
Closing all issues that propose/ask permission to work on a new algorithm. Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues). We don't assign issues in this repo.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
