### ISSUE TITLE
ADD counting sort

### ISSUE THREAD

**Issue by Sakhi29** [TheAlgorithms/Python#9508]
### Feature description

Addition of another sorting algorithm called counting sort in the sorts folder on this repository. I would request to assign this task to me.

**Comment by tianyizheng02** [comment]
**Read the contributing guidelines.**

1. We don't assign issues in this repo. Just submit a PR if you want to contribute.
2. We already have an implementation of counting sort: [sorts/counting_sort.py](https://github.com/TheAlgorithms/Python/blob/95345f6f5b0e6ae10f54a33850298634e05766ee/sorts/counting_sort.py). You must check to make sure that an algorithm isn't already in the repo before you contribute. If you choose to contribute this algorithm anyway, make sure that it's a different approach and not the same implementation.
