### ISSUE TITLE
Segment Tree: range maximum query

### ISSUE THREAD

**Issue by Erfaniaa** [TheAlgorithms/Python#951]
https://github.com/TheAlgorithms/Python/blob/master/data_structures/binary_tree/segment_tree.py

This code comments and docstrings are not enough. This specific segment tree solves the "range maximum problem" but this term is not mentioned anywhere.

**Comment by andreicioban** [comment]
I'm calling myself out since i'm not familiar with `Python`.

**Comment by fty48jj19** [comment]
e   ok obrigado so quero que fique bem claro nao costumo enplanta nada de
codigo asim nao  so quando faço pedidos  ok

Em qui, 4 de jul de 2019 às 04:24, Andrei Cioban <notifications@github.com>
escreveu:

**Comment by Erfaniaa** [comment]
@fty48jj19 Please write in English.

**Comment by ksangeet9ap** [comment]
Can we add the iterative implementation of segment trees from http://codeforces.com/blog/entry/18051 instead?
