### ISSUE TITLE
Improved Heap sorting technique

### ISSUE THREAD

**Issue by Soyvor** [TheAlgorithms/Python#9528]
### Feature description

code you provided is a clear and concise implementation of the heap sort algorithm in Python. However, if you want to make it slightly more concise while preserving readability, you can make a few adjustments.

sign me up for hacktober fest

**Comment by abhaygzb15** [comment]
@Soyvor  It would be grateful if you could assign this issue to me under hactoberfest.

**Comment by cclauss** [comment]
* [ ] Keep the doctests and add more.
* [ ] Keep the self-documenting parameter names and add more
* [ ] Add type hints for all function parameters and return types.

**Comment by Richards-Richie** [comment]
sign me up for  this issue
