### ISSUE TITLE
Maximum sum submatrix

### ISSUE THREAD

**Issue by vgnshiyer** [TheAlgorithms/Python#9555]
### Algorithm

- I would like to add an implementation for maximum sum submatrix in the dynamic programming section.
- I noticed that there is a Kadane's algorithm implementation for the 2-D array in the repository. However, there is no implementation for a 3-D array. 
- I would like to add a PR for the same under Hacktoberfest. 

Waiting for the approval from the repository maintainer.

**Comment by rohan472000** [comment]
Don't wait to get assigned, raise PR, here no one assigns , just discuss and raise.

**Comment by shivamk23** [comment]
let me do PR for this issue.

**Comment by vgnshiyer** [comment]
> let me do PR for this issue.

PR is already up for it.

**Comment by tianyizheng02** [comment]
Closing all issues that propose/ask permission to work on a new algorithm. Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues). We don't assign issues in this repo.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
