### ISSUE TITLE
Ohm's Law Calculator

### ISSUE THREAD

**Issue by Arpit1033** [TheAlgorithms/Python#9564]
### Feature description

Feature Description:

Overview:
This feature aims to enhance the 'physics' repository by adding an Ohm's Law calculator. Ohm's Law is a fundamental principle in electrical engineering and physics, describing the relationship between voltage (V), current (I), and resistance (R) in an electrical circuit. Adding this calculator will provide users with a valuable tool for solving electrical problems and understanding basic principles of electronics.

Feature Components:
1) User Interface:
Integrate a user-friendly interface into the 'physics' repository, accessible via a command-line interface or a web application, depending on the platform's requirements.
Create a dedicated section or menu for the Ohm's Law calculator to ensure easy access.

2) Input Fields:
Voltage (V): Allow users to input the voltage value (in volts) in the circuit.
Current (I): Provide an input field for users to enter the current value (in amperes).
Resistance (R): Include a field for entering the resistance value (in ohms).

3) Calculation Functionality:
Implement the calculation of Ohm's Law using the formula: V = I * R, where V represents voltage, I represents current, and R represents resistance.
Ensure that the calculator can solve for any of the three variables (V, I, or R) based on user input for the other two variables.
Incorporate error handling to validate user inputs, ensuring that they are numerical and within reasonable ranges.

4) Results Display:
Display the calculated result (V, I, or R) clearly to the user.
Provide meaningful labels for the result to ensure user comprehension.

5) Units and Conversions:
Support the display of units (volts, amperes, ohms) with the calculated results for clarity.
Allow users to choose different units if needed and handle unit conversions accordingly.

6) Additional Information:
Include a brief explanation of Ohm's Law to help users understand its significance.
Offer relevant examples and use cases for applying Ohm's Law in practical scenarios.

7) User-Friendly Feedback:
Implement informative error messages and prompts to guide users in case of incorrect inputs or other issues.

I would like to work on this issue. Could it be assigned to me ?

**Comment by tianyizheng02** [comment]
> I would like to work on this issue. Could it be assigned to me ?

@Arpit1033 Did you read the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contribution)? We don't assign issues.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.

We also already have a file for Ohm's law: [electronics/ohms_law.py](https://github.com/TheAlgorithms/Python/blob/e60779c202880275e786f0f857f4261b90a41d51/electronics/ohms_law.py). Did you check the codebase beforehand to make sure that we didn't already have it?
