### ISSUE TITLE
about closest_pair_of_points 

### ISSUE THREAD

**Issue by 1171000322** [TheAlgorithms/Python#957]
https://github.com/TheAlgorithms/Python/blob/master/divide_and_conquer/closest_pair_of_points.py
the closest_pair_of_points problem might have a better solution which Time complexity is O(n * logn)

**Comment by fty48jj19** [comment]
e  pode deixar asim que vou fazer pedidos de pull  mas que vc possa
meciclar

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em sex, 5 de jul de 2019 às 04:30, 1171000322 <notifications@github.com>
escreveu:

**Comment by Erfaniaa** [comment]
@1171000322, of course, you're right. We will update it soon.
