### ISSUE TITLE
AES algorithm in CBC v1 mode

### ISSUE THREAD

**Issue by ojasva** [TheAlgorithms/Python#9571]
### Feature description

Description: 
The AES algorithm operates in multiple modes, CBC (Cypher Block-Chaining) is one of the most popular and well-known modes. An implementation of CBC v1 mode of AES algorithm would be really good in this repository.

**Comment by abhaygzb15** [comment]
@ojasva Hey!! It would be grateful for me if you could assign this issue to me under hactoberfest.

**Comment by ojasva** [comment]
> @ojasva Hey!! It would be grateful for me if you could assign this issue to me under hactoberfest.

Hey, I have already raised a PR for the issue. If it is rejected, I will assign the issue to you. 
Thank You :)

**Comment by abhaygzb15** [comment]
@ojasva sure.👍

**Comment by tianyizheng02** [comment]
Closing all issues that propose/ask permission to work on a new algorithm. Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues). We don't assign issues in this repo anyway.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
