### ISSUE TITLE
Suggestion for creating a new GRAPHS section under the DSA Section 

### ISSUE THREAD

**Issue by Pikachu-345** [TheAlgorithms/Python#9587]
### Feature description

I was going through the code and observed that Graph Data Structure was not there. So, I have a suggestion for DSA section of the GitHub repo: I think it would be helpful to add "GRAPHS".

Graphs are a non-linear data structure that can be used to model many real-world problems. I think it would be helpful to add a section on graphs to the DSA section of the GitHub repo, as this would give learners a better understanding of this important data structure and its applications.

**Comment by Pikachu-345** [comment]
If permission granted.I would like to solve this issue

**Comment by tianyizheng02** [comment]
... We literally have an entire directory called [graphs/](https://github.com/graphs)
