### ISSUE TITLE
Convert to Base -2

### ISSUE THREAD

**Issue by tanishkunigiri** [TheAlgorithms/Python#9588]
### Feature description

Found a solution to this problem.

I would like to solve this issue.

**Comment by RamDanny** [comment]
Hi, I want to contribute to this issue. However I couldn't find the code file in the repo. Can you help me out on where to begin? (I'm a beginner and would really appreciate some help)

**Comment by tanishkunigiri** [comment]
Hey, I am a beginner as well. Just contributed to one project before, but
never contributed to such a big project. I am still figuring out how to
contribute to such big repo.

I would be very happy to collab with u, regarding this.

**Comment by haxkd** [comment]
Created PR #9748
