### ISSUE TITLE
multilayer perceptron

### ISSUE THREAD

**Issue by chaitu789** [TheAlgorithms/Python#9598]
### Feature description

I have seen the code for the simple perception I would like to add an algo for multilayer perceptron

**Comment by tianyizheng02** [comment]
We already have [machine_learning/multilayer_perceptron_classifier.py](https://github.com/TheAlgorithms/Python/blob/b60a94b5b305487ca5f5755ab6de2bf0adeb3d78/machine_learning/multilayer_perceptron_classifier.py). However, this file is a how-to that simply uses the scikit-learn built-in multilayer perceptron model (see #6216), so it must be replaced. We welcome you (or any other contributor) to propose a replacement that implements the perceptron model. If you want to contribute, simply open a PR—we don't assign issues.

**Comment by acf-patrick** [comment]
I have seen that 
> Projects asking contributors to submit assorted data structures and algorithms

are excluded from **Hacktoberfest**
Is this repo still valid for Hacktoberfest ?

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.
