### ISSUE TITLE
Serialize and Deserialize

### ISSUE THREAD

**Issue by Arunsiva003** [TheAlgorithms/Python#9611]
### Feature description

Design an algorithm to serialize and deserialize a binary tree. You just need to ensure that a binary tree can be serialized to a string and this string can be deserialized to the original tree structure.

**Comment by MK-75** [comment]
@Arunsiva003 I would like to work on this enhancement

**Comment by Arunsiva003** [comment]
> @Arunsiva003 I would like to work on this enhancement. Can you assign this to me?

You don't have to wait for any approval. make a pull request and proceed!

**Comment by AVAniketh0905** [comment]
i started working on this

**Comment by AVAniketh0905** [comment]
@Arunsiva003 hey i have pushed my pr. Can you check?

**Comment by tianyizheng02** [comment]
Closing all issues that propose/ask permission to work on a new algorithm. Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues). We don't assign issues in this repo anyway.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
