### ISSUE TITLE
Gravity sort in python

### ISSUE THREAD

**Issue by mahammadhussain98** [TheAlgorithms/Python#9635]
### Feature description

The "Gravity Sort" algorithm, also known as "Bead Sort" or "Gravity-Bead Sort," is a playful and inefficient sorting method. It models sorting as a physical phenomenon, where each number in a list is represented by beads in columns. In each pass, beads "fall" down through the columns under gravity until they settle at the bottom, representing sorted values. This process repeats until all columns are sorted. While Gravity Sort is a fun concept, it's highly impractical for real-world use due to its inefficiency and non-standard nature.

**Comment by mahammadhussain98** [comment]
hello !@darkstar ,please assign this issue for me

**Comment by tianyizheng02** [comment]
1. We do not assign issues. Simply open a PR if you wish to contribute.
2. We already have an implementation of bead sort here: [sorts/bead_sort.py](https://github.com/TheAlgorithms/Python/blob/0a84b8f842c4c72f400d96313d992b608d621d07/sorts/bead_sort.py). Unless you have an implementation that works in a significantly different way, please consider contributing something else. If you do have such an implementation, just open a PR.
