### ISSUE TITLE
Wiki sort algorithm in python 

### ISSUE THREAD

**Issue by mahammadhussain98** [TheAlgorithms/Python#9637]
### Feature description

WikiSort is an advanced sorting algorithm that improves upon traditional merge sort by reducing memory usage and enhancing performance. It efficiently divides the input into blocks, sorts them using insertion sort, and then merges them with a unique merging strategy. This approach minimizes memory overhead and yields competitive sorting performance, making it suitable for various applications. The provided Python implementation demonstrates WikiSort's practical usage by sorting a list of user-provided numbers.

**Comment by mahammadhussain98** [comment]
"Could someone please assign this issue to me?"

**Comment by tianyizheng02** [comment]
> "Could someone please assign this issue to me?"

Please read the contributing guidelines. We don't assign issues in this repo. If you want to contribute an algorithm, just open a PR. There is no need to open an issue.

> WikiSort is an advanced sorting algorithm that improves upon traditional merge sort by reducing memory usage and enhancing performance.

Can you provide a source that explains this algorithm? From what I see online, Wikisort appears to be an implementation of block merge sort.
