### ISSUE TITLE
Chatgpt Response Generator is "Web_programming"

### ISSUE THREAD

**Issue by kingpin-ay** [TheAlgorithms/Python#9669]
### A new feature "Chatgpt Response Generator" is Web_programming
I have checked most of the codes and thinking of implementing this feature where the person have to give there **Chatgpt api key** and they can generate response based on there **input on the console** if it's accepted, I can contribute for this .

**Comment by nrhitik** [comment]
I would like to work on this issue. Could you assign me this issue.

**Comment by tianyizheng02** [comment]
Closing all issues that propose/ask permission to work on a new algorithm. Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues). We don't assign issues in this repo anyway.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
