### ISSUE TITLE
Adding the fractionated morse cipher

### ISSUE THREAD

**Issue by Om-Alve** [TheAlgorithms/Python#9691]
### Feature description

The implementation of the fractionated morse cipher has not yet been added to the ciphers directory. The Fractionated Morse cipher first converts the plaintext to morse code, then enciphers fixed size blocks of morse code back to letters. I have already implemented it in python and sent a pull request which has passed all the tests and just needs to be reviewed. 

Pull request - #9442

This would be a good addition to the repository and I hope you take a look at it! Thank you!

**Comment by ChrisO345** [comment]
For new algorithms, please do not create a new issue.
See: [Contributing Guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues)
