### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by jasper256** [TheAlgorithms/Python#970]
I just found this repository and decided that I wanted to contribute, so I created a decimal to hexadecimal converter.  I am very new to GitHub and this is my first time contributing to anything open source.  I thought that the proper way to do this would be to add a new branch, so that's what I did and I put the file in it.  However, GitHub will not let me publish the branch.  I assume therefore that I am supposed to submit work another way, but there were no specific instructions in the contributing guidelines.  Like I said, this is my first open source contribution so sorry if it seems like a stupid question.

**Comment by Izzy90** [comment]
Hey there,
You should probably read these first:
https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md
Make sure you did everything according to the standards, then submit a Pull-request.

**Comment by jasper256** [comment]
> 
> 
> Hey there,
> You should probably read these first:
> https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md
> Make sure you did everything according to the standards, then submit a Pull-request.

I thought that to create a pull request I needed a separate branch.  Like I said, I'm new to this, so I'm probably missing something very simple.

**Comment by Izzy90** [comment]
I'm pretty new to it myself too, but I think that in order to create a pull request, you need to Fork the repo.

**Comment by jasper256** [comment]
I understand now.  Thank you.
