### ISSUE TITLE
Add camelCase to snake_case conversion algorithm

### ISSUE THREAD

**Issue by Mrk-Mzj** [TheAlgorithms/Python#9726]
### Feature description

In the 'strings' folder there is an algorithm that converts snake_case to camelCase. 
But what's missing is camel to snake algorithm that handles numbers. It should be added.

**Comment by Mrk-Mzj** [comment]
I've created PR #9727

**Comment by Richards-Richie** [comment]
i would like to work on this issue

**Comment by sahithi79** [comment]
Hey could you please assign this issue to me

**Comment by sahithi79** [comment]
I have raised a PR [https://github.com/TheAlgorithms/Python/pull/9774](url)

**Comment by Groot-2001** [comment]
Hey @Mrk-Mzj is this issue is still open , could you please confirm that!

**Comment by Richards-Richie** [comment]
No the pull request is closed
