### ISSUE TITLE
Adding Flake8 F4 Tests to find Import Errors

### ISSUE THREAD

**Issue by PatOnTheBack** [TheAlgorithms/Python#973]
@PatOnTheBack if you add [__F4__](https://flake8.pycqa.org/en/latest/user/error-codes.html) to the flake8 tests in __.travis.yml__, you will find other import-related issues to fix.  Thanks for your attention to these details.

_Originally posted by @cclauss in https://github.com/TheAlgorithms/Python/pull/920#issuecomment-509011067_

Like cclauss said, adding Flake8 F4 to the Travis file can help us find import errors that reduce code qulaity.

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/.travis.yml#L8
