### ISSUE TITLE
Update ~script.py

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/Python#978]
The ` ~script.py ` needs to be updated. Currently, it is generating broken links. For example, try opening LCA under Data Structures in [DIRECTORY.md](https://github.com/TheAlgorithms/Python/blob/master/DIRECTORY.md). It will show a 404 error.

1. The script should list only ` .py ` and ` .ipynb ` files.
2. List the files in such a way that every word is capitalised in the parsed file name. For example, `binary_search_tree.py` should be listed as [Binary Search Tree](https://github.com/TheAlgorithms/Python/blob/master/data_structures/binary_tree/binary_search_tree.py)

**Comment by cclauss** [comment]
Can we give it a better name?  Like __scripts/build_directory_md.py__?

**Comment by poyea** [comment]
Maybe SCRIPT_GEN. py. I think the script should be in the root.

**Comment by AnupKumarPanwar** [comment]
Keeping in `scripts` directory seems more appropriate to me. If in future we plan to automate other things, we can put that in the `scripts` folder.

**Comment by qckzr** [comment]
I have sent pull request #1013 with the changes
