### ISSUE TITLE
Adding a Losses Directory in Machine Learning

### ISSUE THREAD

**Issue by THEGAMECHANGER416** [TheAlgorithms/Python#9789]
### Feature description

Adding a losses directory in MachineLearning Directory that will contain common loss functions used in Machine Learning like BinaryCrossEntropy, Sparse_Categorical_CrossEntropy and MeanSquaredError, MeanAbsoluteError etc.

I would like to work on this issue

**Comment by THEGAMECHANGER416** [comment]
I would like to work on this issue

**Comment by cclauss** [comment]
Please work on it.
