### ISSUE TITLE
Move `maths/sigmoid_linear_unit.py` to `neural_network/activation_functions`

### ISSUE THREAD

**Issue by tianyizheng02** [TheAlgorithms/Python#9793]
Follow-up from [this comment](https://github.com/TheAlgorithms/Python/issues/9692#issuecomment-1748662811)

The sigmoid linear unit function is primarily known as a NN activation function, so it should be moved from the `maths` directory to the `neural_network/activation_functions` directory.

Hacktoberfest contributors: if you want to work on this, read the contributing guidelines first and just open a PR. We don't assign issues in this repo.

**Comment by Asif-Sheriff** [comment]
Hey I am new to open source
I have fixed this issue but when I create a pull request my previous commits are being included
How can I fix this, apologizes for the inconvenience.

**Comment by AasheeshLikePanner** [comment]
Hi, I opened a [PR](https://github.com/TheAlgorithms/Python/pull/9824) Can you please Check it.

**Comment by Asif-Sheriff** [comment]
@tianyizheng02 
Ahh thanks for the clarification mate
