### ISSUE TITLE
Add code for all sorting algorithms in Python

### ISSUE THREAD

**Issue by AkankshaNarula** [TheAlgorithms/Python#9809]
### Feature description

I would like to add codes for Selection Sort, Insertion Sort, Selection Sort, Merge Sort, Quick Sort and Heap Sort in Python

**Comment by tianyizheng02** [comment]
@AkankshaNarula We already have selection sort, insertion sort, merge sort, quick sort, and heap sort in this repo. Please check the codebase to make sure that an algorithm isn't already implemented before you open an issue for it. Furthermore, do not open an issue to propose a new algorithm. _Please read our contributing guidelines._
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.

@Aksshay88 Do not ask to be assigned to an issue. We don't assign issues in this repo.
