### ISSUE TITLE
pytest --doctest-modules graphs fails

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#984]
Missing __if \_\_name\_\_ == "\_\_main\_\_":__ ?

**Comment by fty48jj19** [comment]
e ja expliquei a situaçao nao vou sede nada  a codigo malicioso na sei qual
sao bons  desculpa  agurde eu entra nas configuraçes

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em ter, 9 de jul de 2019 às 10:02, cclauss <notifications@github.com>
escreveu:
