### ISSUE TITLE
pytest --doctest-modules data_structures fails

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#989]
Missing __if \_\_name\_\_ == "\_\_main\_\_":__ ?

**Comment by cclauss** [comment]
pytest --doctest-modules data_structures
============================================================================== test session starts ==============================================================================
platform darwin -- Python 3.7.4, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /Users/cclauss/Python/itinerant_futurizer/Python
collected 0 items / 5 errors

==================================================================================== ERRORS =====================================================================================
____________________________________________________________ ERROR collecting data_structures/hashing/double_hash.py ____________________________________________________________
data_structures/hashing/double_hash.py:3: in <module>
    from .hash_table import HashTable
E   ImportError: attempted relative import with no known parent package
____________________________________________________ ERROR collecting data_structures/hashing/hash_table_with_linked_list.py ____________________________________________________
data_structures/hashing/hash_table_with_linked_list.py:1: in <module>
    from .hash_table import HashTable
E   ImportError: attempted relative import with no known parent package
_________________________________________________________ ERROR collecting data_structures/hashing/quadratic_probing.py _________________________________________________________
data_structures/hashing/quadratic_probing.py:3: in <module>
    from .hash_table import HashTable
E   ImportError: attempted relative import with no known parent package
________________________________________________________ ERROR collecting data_structures/stacks/balanced_parentheses.py ________________________________________________________
data_structures/stacks/balanced_parentheses.py:3: in <module>
    from stack import Stack
E   ModuleNotFoundError: No module named 'stack'
____________________________________________________ ERROR collecting data_structures/stacks/infix_to_postfix_conversion.py _____________________________________________________
data_structures/stacks/infix_to_postfix_conversion.py:5: in <module>
    from .Stack import Stack
E   ModuleNotFoundError: No module named 'stacks.Stack'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 5 error in 0.43 seconds ============================================================================

**Comment by QuantumNovice** [comment]
I was going through the issue and I saw this. I didn't get any notification about this. I'm working on it.

**Comment by cclauss** [comment]
Thi
