### ISSUE TITLE
[Add] : Project Euler - 60 solution

### ISSUE THREAD

**Issue by haxkd** [TheAlgorithms/Python#9895]
### Feature description

Feature description
Addition of Project Euler - 60 solution

Problem statement - Prime Pair Sets
![Screenshot (51)](https://github.com/TheAlgorithms/Python/assets/33129246/ff072455-b92f-4dcb-b731-4511b760517e)

**Comment by tianyizheng02** [comment]
Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues).
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
