### ISSUE TITLE
[Add] : Generate Parentheses program by using Backtracking

### ISSUE THREAD

**Issue by kosuri-indu** [TheAlgorithms/Python#9920]
### Feature description

**FEATURE DESCRIPTION**

Generate Parentheses program - Under **BACKTRACKING**

![image](https://github.com/TheAlgorithms/Python/assets/118645569/e8b62184-6f68-4be4-adcc-f841cf8e9e33)
![image](https://github.com/TheAlgorithms/Python/assets/118645569/8edbeb6f-21f9-40db-b3a5-4ee32ed04669)

**Comment by NotTheRightGuy** [comment]
Hey, I think I can help with this issue. Can you assign this to me?

**Comment by anshul-132002** [comment]
hey ! @kosuri-indu  I want to contribute to this issue

**Comment by Jibesh10101011** [comment]
I want to contribute with this issue , can you please assign it to me ?

**Comment by anushkp1107** [comment]
@kosuri-indu I want to contribute to this issue . Can you please assign it to me?

**Comment by haxkd** [comment]
@anshul-132002 @anushkp1107 @Jibesh10101011 start contributing to issue, because no one assignees.

**Comment by RaunakMishr** [comment]
I want to contribute, could you please assign me this ? Please ?

**Comment by haxkd** [comment]
@RaunakMishr you should start contributing

**Comment by Sandhya-Rani05** [comment]
I want to contribute to this. Please assign me this

**Comment by haxkd** [comment]
@Sandhya-Rani05 no assignees here so... You should start contributing

**Comment by Icarus-05** [comment]
hey. Newbie here. How do i contribute to this project ?

**Comment by haxkd** [comment]
@Icarus-05 go through the [https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md](this)

**Comment by tianyizheng02** [comment]
Closing all issues that propose/ask permission to work on a new algorithm. Please read our [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues). We don't assign issues in this repo anyway.
> If you are interested in resolving an [open issue](https://github.com/TheAlgorithms/Python/issues), simply make a pull request with your proposed fix. We do not assign issues in this repo so please do not ask for permission to work on an issue.
>
> Do not create an issue to contribute an algorithm. Please submit a pull request instead.
