### ISSUE TITLE
Adding Tower of Hanoi

### ISSUE THREAD

**Issue by Aloneking789** [TheAlgorithms/Python#9936]
### What would you like to share?

The **Tower of Hanoi** is a classic problem in computer science and mathematics that involves moving a tower of disks from one peg to another, subject to certain constraints.

**Comment by tianyizheng02** [comment]
1. Do not open an issue for new algorithms. Please read our contributing guidelines.
2. We already have an implementation of the Tower of Hanoi in [other/tower_of_hanoi.py](https://github.com/TheAlgorithms/Python/blob/795e97e87f6760a693769097613ace56a6addc8d/other/tower_of_hanoi.py).
