### ISSUE TITLE
Minimization of while loop in Armstrong Numbers

### ISSUE THREAD

**Issue by lohith-lalam** [TheAlgorithms/Python#9968]
### Feature description

We can use math.log() to find the number of digits in a number instead of while loop.

c = log(n) + 1

**Comment by dwarka-9504** [comment]
My change in this code has fixed the problem you were facing, it has minimized loops and in simple way

**Comment by ambiguousphoton** [comment]
Please check the pull request -> https://github.com/TheAlgorithms/Python/pull/10127

**Comment by himanchal08** [comment]
i would like to work on this issue it seems doable
i will try my best to implement it

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.
