### ISSUE TITLE
[ADD]:Stack using two Queues

### ISSUE THREAD

**Issue by IndranjanaChatterjee** [TheAlgorithms/Python#9987]
### What would you like to share?

Implementation of a program which performs stack operations like push, pop, peek using two queues

### Additional information

Perform the PUSH ,POP and PEEK operations of a STACK using two Queues following the LIFO process.

**Comment by anamithrak15** [comment]
Can you please assign me this issue under hacktoberfest

**Comment by haxkd** [comment]
@anamithrak15 just start contribution.
